### ISSUE TITLE
Add Sematext Cloud to documentation 

### ISSUE THREAD

**Issue by megastef** [timberio/vector#1000]
Hi, 

could you please help me to add documentation for [Sematext](https://sematext.com) in Vector docs? 

It turned out it is difficult to add a separate documentation section in sinks. Do you plan a section for vendor integrations without dependencies on the .meta files and scripts?   

We need just a few provider-specific settings and would like to describe it in vector docs. To make it easy to discover, the Sematext configuration should be visible in the TOC.   

First I've started to create a separate .md file in the docs directory, then I've seen the documentation is generated via scripts. The scripts use .meta files for the sinks. 
And here is my problem: How can we add simple documentation sections without creating a special sink for Sematext? It makes no sense to create a separate sink, .meta files and such when we can tell users, how to configure elasticsearch sink for Sematext. 

To ship logs to Sematext you can use [elasticearch sink](https://docs.vector.dev/usage/configuration/sinks/elasticsearch). 

## 1. Set the host for North America or Europe region: 

NA: 

```
	# Sematext Cloud / North America  
	host = "https://logsene-receiver.sematext.com:443"
```  

Europe: 

```
  # Sematext Cloud / Europe 
  host = "https://logsene-receiver.eu.sematext.com:443"
```

## 2. The index name is the Sematext Logs Token

```
index = YOUR_SEMATEXT_LOGS_TOKEN_HERE
```

## 3. Disable gzip compression

The elasticsearch sink uses compression by default, currently, we have to disable compression. 

```
compression = "none"
```

## 4. Sematext Cloud Example
[Sematext Cloud](https://www.sematext.com/cloud) supports the Elasticsearch API for log ingestion. Therefore logs can be shipped to Sematext using the [elasticsearch sink](https://docs.vector.dev/usage/configuration/sinks/elasticsearch). 

### Config File 

```toml

[sinks.sematext-logs]
  type = "elasticsearch" # must be: "elasticsearch"
  inputs = ["my-source-id"]
  # Sematext Cloud / North America  
  host = "https://logsene-receiver.sematext.com:443"
  # Sematext Cloud / Europe 
  # host = "https://logsene-receiver.eu.sematext.com:443"
  index = "YOUR_SEMATEXT_LOGS_TOKEN_HERE"
  doc_type = "logs"
  compression = "none"

```
