### ISSUE TITLE
Cloudwatch identifying a dynamic group name when it is static

### ISSUE THREAD

**Issue by LucioFranco** [timberio/vector#1002]
Config:

```toml
    [sinks.cloudwatch]
    type = "aws_cloudwatch_logs"
    encoding = "json"
    inputs = ["kubernetes"]
    group_name = "/kube-demo/echo"
    stream_name = "{{ pod_uid }}"
    region = "us-east-1"
```

Output logs:
```
Oct 09 20:18:37.159 INFO vector::sinks::aws_cloudwatch_logs: cloudwatch group_name is dynamic; skipping healthcheck.
```

I will need to dig deeper to figure out why this is happening but opening this to track this potential bug.
