### ISSUE TITLE
[Help] How to connect source TCP

### ISSUE THREAD

**Issue by romvarac** [timberio/vector#1007]
Hi team,
I use timberio/vector:latest-debian (0.4-dev)
1. vector.yml
```
[sources.in]
  # REQUIRED - General
  type = "tcp" # must be: tcp

  # OPTIONAL - General
  address = "0.0.0.0:9000" # no default
  max_length = 102400 # default, bytes
  shutdown_timeout_secs = 30 # default, seconds

  # OPTIONAL - Context
  host_key = "host" # default

[sinks.out]
  inputs = ["in"]
  type = "console"
```
2. docker-compose.yml
```
version: "3.7"

services:
  vector:
    image: timberio/vector:latest-debian
    ports: 
      - 9000:9000
    volumes: 
      - ${PWD}/vector.toml:/root/vector.toml:ro
```
3. golang code file
```
package main

import (
	"bufio"
	"fmt"
	"net"
)

func main() {

	// connect to this socket
	conn, err := net.Dial("tcp", "127.0.0.1:9000")
	defer conn.Close()
	if err != nil {
		fmt.Printf("Connection error: %v", err)
		return
	}
	text := "2019-02-13T19:48:34+00:00 [info] Started GET for 127.0.0.1"
	// send to socket
	fmt.Fprintf(conn, text)
	// listen for reply
	message, _ := bufio.NewReader(conn).ReadString('\n')
	fmt.Print("Message from server: " + message)
}
```
Log vector not show anything, so, how I can connect source TCP. Thanks.

**Comment by lukesteensen** [comment]
Your dial address is fine, `0.0.0.0` is a special address that means "listen on all interfaces".

I believe the issue is that you're not sending a newline at the end of your log message. The tcp source uses newlines as the delimiter between messages, so if it never receives a newline it will also there could be more data coming as part of the same message.

**Comment by romvarac** [comment]
@lukesteensen, you have a demo for connecting to source TCP, any language code. Thanks

**Comment by binarylogic** [comment]
I've added this to the setup & debugging milestone because it probably could be resolved with a simple demo. This is something I want to explore as part of improving the setup experience.

**Comment by lukesteensen** [comment]
@romvarac Here's a quick example I've tested locally:

1. `vector.toml` (same as yours)

```toml
[sources.in]
  # REQUIRED - General
  type = "tcp" # must be: tcp

  # OPTIONAL - General
  address = "0.0.0.0:9000" # no default
  max_length = 102400 # default, bytes
  shutdown_timeout_secs = 30 # default, seconds

  # OPTIONAL - Context
  host_key = "host" # default

[sinks.out]
  inputs = ["in"]
  type = "console"
```

2. `docker-compose.yml` (different volume config than yours)

```yaml
version: "3.7"

services:
  vector:
    image: timberio/vector:latest-debian
    ports:
      - 9000:9000
    volumes:
      - ./vector.toml:/etc/vector/vector.toml:ro
```

3. `src/main.rs` (Rust program instead of Go, but same idea)

```rust
use std::{io::Write, net::TcpStream};

fn main() {
    let mut conn = TcpStream::connect("127.0.0.1:9000").unwrap();
    let text = "2019-02-13T19:48:34+00:00 [info] Started GET for 127.0.0.1\n";
    conn.write_all(text.as_bytes()).unwrap();
}
```

You don't actually need the `\n` at the end of the text in this case since Vector will automatically terminate the message when the connection is closed at the end of the run of the program, but for other cases you would.
