### ISSUE TITLE
Nest request_* options under request.*

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1022]
This is low priority. Currently, the `request_*` options are represented as top-level options:

```toml
[sinks.my_sink]
  type = "http"
  request_in_flight_limit = 3
  request_rate_limit_duration_secs = 10
  request_rate_limit_num = 3
  request_retry_attempts = 3
  request_retry_backoff_secs = 2
  request_timeout_secs = 30
```

My guess is that we'll want to add more options to adjust the response codes to retry on, etc. To keep things consistent with `buffers.*`, `tls.*`, etc. I propose that we move these to a `request` table:

```toml
[sinks.my_sink]
  type = "http"

[sinks.my_sink.request]
  in_flight_limit = 3
  rate_limit_duration_secs = 10
  rate_limit_num = 3
  retry_attempts = 3
  retry_backoff_secs = 2
  timeout_secs = 30
```
