### ISSUE TITLE
Nest batch_* options under batch.*

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1023]
Similar to #1022, I think we can group `batch_*` options under a `batch` table:

```toml
[sinks.my_sink]
  type = "http"
  batch.size = 1049000
  batch.timeout_secs = 30
```

Again, this is low priority, but would help to make our options style more consistent which would make documenting and scanning options easier.

Ex: https://docs.vector.dev/v/master/usage/configuration/sinks/http
