### ISSUE TITLE
Nest rate_limit_* options under rate_limit.*

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1024]
Similar to #1022, I think we can group `rate_limit_*` options under a `rate_limit` table:

```toml
[sinks.my_sink]
  type = "http"
  rate_limit.duration = 30
  rate_limit.num = 5
```

Again, this is low priority, but would help to make our options style more consistent which would make documenting and scanning options easier.

Ex: https://docs.vector.dev/v/master/usage/configuration/sinks/http
