### ISSUE TITLE
Subcommand to generate boilerplate configuration files

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1058]
As a follow up to https://github.com/timberio/vector/issues/931#issuecomment-542703022 we should offer a subcommand to generate boilerplate configs. As @Jeffail pointed out, this is helpful for operators that generating a lot of configurations for different services. Ex:

```bash
$ vector generate stdin|json_parser|console
```

Would output (STDOUT) the following:

```toml
[sources.stdin]
  type = "stdin"

[transforms.json_parser]
  type = "json_parser"
  inputs = ["stdin"]

[sinks.console]
  type = "console"
  inputs = ["json_parser"]
```

The above is just an example. We can change the interface to whatever we think is best.
