### ISSUE TITLE
New `kubernetes_pod_metadata` transform

### ISSUE THREAD

**Issue by LucioFranco** [timberio/vector#1072]
We should provide a `kubernetes_pod_metadata` transform that is able to fetch a list of pods and enrich events. This should work based off of the kube openapi spec using the [`k8-openapi`] crate.

# Configuration

```toml
[transforms.my_transform_id]
  type = "kubernetes_pod_metadata"
  fields = ["instance-id", "local-hostname", "local-ipv4", "public-hostname", "public-ipv4"] # default
  namespace = ["your-namespace"] # optional, default is to list ALL pods in all namespaces
```

## Options

- `fields` contains the list of fields to include in each event.
- ~~`namespace` contains a list of namespaces that we should watch for a list of pods and their metadata.~~ See global schema for this field.

## Fields

We should provide this set of fields by default and they are overridable via the `fields` option.

- `pod_name`
- `pod_namespace`
- `pod_uid`
- `labels` (not sure if we should provide a way to include the label name in the key or have them as a tuple?)
- `annotations`
- `node_name`

Most of these data points should come from a combination of [`PodSpec`] and [`ObjectMeta`] using the [`Pod::list_namespaced_pod`].

[`k8-openapi`]: https://docs.rs/k8s-openapi
[`PodSpec`]: https://docs.rs/k8s-openapi/0.6.0/k8s_openapi/api/core/v1/struct.PodSpec.html
[`ObjectMeta`]: https://docs.rs/k8s-openapi/0.6.0/k8s_openapi/apimachinery/pkg/apis/meta/v1/struct.ObjectMeta.html
[`Pod::list_namespaced_pod`]: https://docs.rs/k8s-openapi/0.6.0/k8s_openapi/api/core/v1/struct.Pod.html#method.list_namespaced_pod

## Global Schema

`log_schema` should add a `kubernetes_namespace` field to correlate where nested fields should be added to events. This should replace the `namespace` transform option.

## Implementation

This should use the [`k8-openapi`] crate, plus the [`kube`] crate, though I would prefer we stick with just hyper and vendor the config loading. This implementation should follow the proposed method for implementing a stream table join transforms as seen in #1069.

[`kube`]: https://docs.rs/kube/0.16.1/kube/

## Questions

- How should we nest these? Should they live under a `kubernetes` key?
- How can we correlate pod events coming from the `kubernetes` source with the ones on the list? @ktff 

## Todo

- [x] `WatchClient`

- [ ] `kubernetes_pod_metadata`
