### ISSUE TITLE
Rename `basic_auth` namespace to `auth`

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1084]
## Overview

Certain sinks will require different authentication strategies. For example, the `elasticsearch` sink offers [AWS authentication](https://docs.vector.dev/usage/configuration/sinks/aws_s3#authentication) and HTTP basic auth. Similar to how we accept a `strategy` option for the `sources.file.fingerprint` namespace we should do the same for `auth`. This will require transitioning all sinks that implement `basic_auth`.

## Example

```toml
[sinks.es]
  type = "elasticsearch"

[sinks.es.auth]
  strategy = "aws"
```

And for basic auth:

```toml
[sinks.es]
  type = "elasticsearch"

[sinks.es.auth]
  strategy = "basic"
  username = "username"
  password = "password"
```

## Requirements

- [ ] Support the `auth.strategy = "basic_auth"` for the `clickhouse` sink
- [ ] Support the `auth.strategy = "basic_auth"` for the `elasticsearch` sink
- [ ] Support the `auth.strategy = "aws"` for the `elasticsearch` sink
- [ ] Support the `auth.strategy = "basic_auth"` for the `http` sink
