### ISSUE TITLE
ElasticSearch sink fails to get EC2 instance credentials

### ISSUE THREAD

**Issue by phyber** [timberio/vector#1093]
## Software Version

Vector: 0.5.0, RPM

## Issue

Vector doesn't seem to be able to obtain the EC2 instance profile role credentials

## Expected

Vector would get the credentials and be able to push logs to ElasticSearch

## Observations

The EC2 instance definitely has enough permissions to perform actions in the AWS ElasticSearch Service, this was confirmed by using [`aws-es-curl`](https://github.com/joona/aws-es-curl) on the instance to perform some basic operations such as looking at the cluster health and creating a new index.

When running Vector in dry-run mode with an ES sink configuration of 
```toml
[sinks.elasticsearch]
 host = "https://logging.endpoint.example.org/"
 index = "ec2-%Y-%m-%d"
 inputs = ["var_log"]
 type = "elasticsearch"
 provider = "aws"

# The region has to be provided like this, the documentation appears to be incorrect
 [sinks.elasticsearch.region]
 region = "eu-west-1"
```

Vector will eventually error out with
```
 ERROR vector::topology: Configuration error: Sink "elasticsearch": Could not
 generate AWS credentials: CredentialsError { message: "Couldn\'t find AWS
 credentials in environment, credentials file, or IAM role." }
```

However, we already verified that the instance profile role was able to perform actions within the ES cluster.

If we perform a `tcpdump` from the instance with `tcpdump -X -s 0 'tcp port 80'`, it appears that Vector (probably the Rusoto crate), never sends the `GET` request to the `169.254.169.154` meta-data endpoint. It appears to connect and disconnect, never sending the `GET`.

I am currently attempting to upgrade to Rusoto 1.38.0 and Credentials 0.17.0 to see if this has any effect, however, due to the `RusotoError` changes this is not a quick process.
