### ISSUE TITLE
Make the `http` sink `uri` option templateable

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1155]
Currently, the `http` sink's `uri` option is static. It would be nice to make it templateable, allowing users to partition data across different `uri`s. Ex:

```toml
[sinks.my_http_sink]
  type = "http"
  uri = 'https://localhost/{{application_id}}
```
