### ISSUE TITLE
A json input with "message" field

### ISSUE THREAD

**Issue by m1keil** [timberio/vector#1166]
I'm evaluating Vector and have a very simple config:

```toml
[sources.in]
  type = "udp"
  address = "0.0.0.0:9000"

[transforms.json]
  type = "json_parser"
  inputs = ["in"]

  drop_invalid = true
  field = "message"

[sinks.stdout]
  type = "console"
  inputs = ["json"]
```

sending the message:

     $ echo '{"message":"hello", "key":"value"}' | nc -u 127.0.0.1 9000

and inspecting the processed output:

    {"key":"value","timestamp":"2019-11-10T13:18:16.140912611Z","host":"127.0.0.1:38985"}

Incoming `message` field got dropped.

If I understand correctly, my incoming log is stored as the internal Vector log format where the `message` field contains the entire incoming content. Then the `message` field gets parsed and the "new" `message` is no longer a JSON so it gets dropped (silently). 
(I'm not sure if what I said even makes sense. My mental model can be totally wrong here)

Question is - how can I have a JSON input with `message` field which is not colliding with the internal `message` field? Docs specifying that I should have a rename field transformer, but I couldn't find one. Given how common the term `message` is, I wonder if the internal message field should be `_message` or something similar.

**Comment by binarylogic** [comment]
Hey @m1keil, thanks for letting us know. Can you try setting `drop_field` to `false`? Ex:

```toml
[transforms.json]
  type = "json_parser"
  inputs = ["in"]

  drop_invalid = true
  drop_field = false
  field = "message"
```

I'm realizing this is confusing. To resolve this I'd like to do the following:

- [ ] `drop_field` should _only_ drop the field if it does not exist in the post-processed data. For example.

Ref https://github.com/timberio/vector/issues/897
