### ISSUE TITLE
New `concat` transform

### ISSUE THREAD

**Issue by foosinn** [timberio/vector#1173]
Hey,

we would love to see an option to concat multiple labels, to parse them in combination.

We have logs that contain only day, month and time in the logline. The date is in the filename. With concat the grok parse would be able to parse a date from multiple labels after concating.

**Comment by foosinn** [comment]
example lua transform implementation:

```toml
[transforms.add_time_field]
  type = "lua"
  inputs = ["my_input"]
  source = """
    event["log_timestamp"] = string.sub(event["file"], -10, -7) .. " " .. string.sub(event["message"], 1, 15)
"""
```
