### ISSUE TITLE
Transform the event's timestamp format

### ISSUE THREAD

**Issue by gtie** [timberio/vector#1177]
I tried using the .types options for both the regexp and the coercer transforms, but looks like neither is capable of changing the event's internal timestamp format.

E.g.
```
# Reformat date for Athena
[transforms.tinydns-anycast-reformat]
  type = "coercer"
  inputs = ["tinydns-regex"]
[transforms.tinydns-reformat.types]
  timestamp = "timestamp|%Y-%m-%d %H:%M:%S.%f"
```

Results in the `timestamp` field being dropped out completely from the event that goes to the sink. If I try the same in my `tinydns-regex` transform, then instead the logs complain that there is no `timestamp` field (which is indeed not part of the regex caputres). 

Is there anything short of Lua that would enable the transformation of the timestamp?

**Comment by a-rodin** [comment]
The timestamp format in `coercer` transform is used to parse timestamp strings that have this format, but not to enforce output format for timestamps.

Because currently Vector can output timestamps only in RFC 3339 format (see [this discussion](https://github.com/timberio/vector/pull/693#discussion_r311397256)), the easiest way to output timestamp in the desired format is to output  them as strings with desired format.

It can be done with `lua` transform by replacing your `transforms.tinydns-anycast-reformat` to

```toml
# Reformat date for Athena
[transforms.tinydns-anycast-reformat]
  type = "lua"
  inputs = ["in"]
  source = """
    event["timestamp"] = string.sub(string.gsub(event["timestamp"], "T", " "), 1, -2)
  """
```
