### ISSUE TITLE
New `new_relic_logs` sink

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1261]
@Jeffail has more insight into what's required here, but from the sound of it, it appears this will simply wrap the `http` sink. If that's the case, I'd like to think a little more about how these types of sinks are created, because we'll be creating quite a few more (ex: #1000).

@Jeffail if there are any pending issues or questions feel free to add them here and we can weigh in.

**Comment by Jeffail** [comment]
According to the [docs](https://docs.newrelic.com/docs/logs/new-relic-logs/log-api/introduction-log-api) there are two formats for sending data to New Relic over HTTP, the first is a simple JSON object:

```json
POST /log/v1 HTTP/1.1
Host: log-api.newrelic.com
Content-Type: application/json
X-Insert-Key: <YOUR_INSIGHTS_INSERT_KEY>
Accept: */*
Content-Length: 133
{
     "timestamp": <TIMESTAMP-OF-EVENT>,
     "message": "User 'xyz' logged in",
     "service": "login-service",
     "hostname": "login.example.com"
}
```

The second is array based, with the ability to send >1 logs in a single request and the ability to set common fields:

```json
POST /log/v1 HTTP/1.1
Host: log-api.newrelic.com
Content-Type: application/json
X-Insert-Key: <YOUR_INSIGHTS_INSERT_KEY>
Accept: */*
Content-Length: 319
[{
   "common": {
     "attributes": {
       "service": "login-service",
       "hostname": "login.example.com"
     }
   },
   "logs": [{
       "timestamp": <TIMESTAMP-OF-EVENT>,
       "message": "User 'xyz' logged in"
     },{
       "timestamp": <TIMESTAMP-OF-EVENT>,
       "message": "User 'xyz' logged out",
       "attributes": {
         "auditId": 123
       }
     }]
}]
```

The first version doesn't support newline delimited JSON, the second version would require a custom sink implementation to build that format.

However, it looks as though the simplified API also allows you to post JSON arrays e.g. `[{"message":"foo"},{"message":"foo2"}]`, so now that the `http` sink supports the `json` encoding option that means we can support New Relic with this config:

```toml
[sinks.nr]
inputs = ['foo']
type = 'http'
uri = 'https://log-api.newrelic.com/log/v1'
encoding = 'json'

[sinks.nr.headers]
Content-Type = "application/json"
X-License-Key = "xxxxx"
```

So I think the logical next step is to implement a `type = "new_relic"` sink with a config format like:

```toml
[sinks.nr]
inputs = ['foo']
type = 'new_relic'
license_key = 'xxxxx' # optional
insert_key = 'xxxxx' # optional
region = 'us' # enum, options are 'us' or 'eu', default 'us'
```

Which under the hood simply creates the equivalent `http` config and spawns it.

## THINGS LEFT TO CONSIDER / DECISIONS TO BE MADE

- We're currently working on exposing metrics for components within Vector, if we're opaquely creating an `http` sink internally then might this cause confusion for the user?
