### ISSUE TITLE
Improve topology debugging

### ISSUE THREAD

**Issue by Jeffail** [timberio/vector#1300]
It would be cool to make it quicker and easier to debug a topology while it's being written. The baseline that we're trying to beat is something like this:

```toml
[sources.my_src]
  type = "stdin"

[transforms.foo]
  type = "grok_parser"
  inputs = ["over_tcp"]
  pattern = "%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:level} %{GREEDYDATA:message}"

[transforms.bar]
  type = "add_fields"
  inputs = ["foo"]
  [transforms.bar.fields]
    new_field = "this is a static value"

[transforms.baz]
  type = "remove_fields"
  inputs = ["bar"]
  fields = ["level"]

[sinks.from_foo]
  type = "console"
  inputs = ["foo"]
  encoding = "json"
  target = "stdout"

[sinks.from_bar]
  type = "console"
  inputs = ["bar"]
  encoding = "json"
  target = "stdout"

[sinks.from_baz]
  type = "console"
  inputs = ["baz"]
  encoding = "json"
  target = "stdout"
```

Where a user wanting to see how an event transforms as it passes through a topology has been forced to change their config to read test events over stdin and add a bunch of sinks, one per transform.

Proposals here need to improve the user experience but they should also ideally be simple enough to discover and understand without needing to dig deep into documentation.

**Comment by loony-bean** [comment]
I'm not sure how this applies here, but I'm a long time fan of Prismatic and their [Graph](http://plumatic.github.io/prismatics-graph-at-strange-loop) library.

Basically, the idea is that once you have a declarative DAG, you can apply a high-order function to add thing like evaluation strategy (lazy/eager), jitter, logging, monitoring, etc on top of it.

**Comment by Jeffail** [comment]
Looks interesting @loony-bean, I think for starters we're looking for a simple mechanism for injecting a test message and seeing the result as it passes through.

Going to start adding proposals. Everyone is welcome to comment, please feel free to add more, and don't be shy to propose something radically different. I'll probably add a few more proposals over the next few days.

## Proposal 1

Add a flag `--debug` to regular Vector use that causes it to spit out a log of its resulting event for every single transform. This would be simple to document but possibly a little hacky to implement. Ideally we want to enable a sampling parameter and also whitelisting of transforms to debug, in which case we could expect a string argument of the form '<wildcard_targets>:<sample_rate>', for example:

- `--debug *:1` would print all events from all transforms
- `--debug foo` would print all events from a transform called `foo`
- `--debug *_foo:0.5` would print half of events from transforms that end in `_foo`
- `--debug bar_*:0.12` would print 12% of events from transforms that start with `bar_`

### Printing Events

When logging events it needs to be clear where the event comes from (which transform) and the format needs to be easy to work with. I would suggest we print all events in JSON format as it's easy to work with (`jq`, etc).

### Strengths

It would be possible to expand this functionality so that the debug logs can instead be captured with a custom source. This would allow production deployments to send samples of events to a special destination for QA. Obviously it would also be possible to instead consume a logged feed with another vector.

### Weaknesses

During execution this flag won't alter the sources or sinks of the topology. Therefore it'll still be up to the user to inject messages themselves if they want to see how they change throughout the pipeline. It'll also be up to the user to remove (or comment out) any sinks that they do not want active during these tests. This means the process retains some friction.

## Proposal 2

Add a subcommand `debug` which expands on proposal 1 by reducing the target config into just the transforms, and using stdin for pushing events through the topology. Using the command might look like this:

```sh
$ echo 'this is a test input message' | vector debug ./test.toml
<timestamp> DEBUG vector::topology: Event from transform 'foo': {"message":"this is a modified test input message"}
<timestamp> DEBUG vector::topology: Event from transform 'bar': {"okay":"adding some more fields now","message":"this is a modified test input message"}
<timestamp> DEBUG vector::topology: Event from transform 'baz': {"message":"huh, we deleted the other fields now, seems redundant"}
```

If nothing is piped directly into the vector command then it would become interactive, each line written would print back the results of each transform.

Sampling would be possible with a flag `--sample 0.5`, and it would be possible whitelist transforms to be sampled `--target foo_*`.

When a config contains >1 sources we would also need users to specify at which source we should be injecting test messages (allowing them to test different topologies), for that we can have a flag `--inject-at` (which also allows transform names), this flag would be mandatory only when the number of sources is >1.

### Strengths

This command removes the need for any manual editing of the config, making it almost entirely frictionless.

### Weaknesses

This proposal isn't as useful for production use. However, production configs can always sample and export data manually so I think we should focus users in the process of writing their configs.

This functionality has more buttons, if we aren't able to document its behavior adequately from the cli then we will likely fail to capture many users.

**Comment by Jeffail** [comment]
## Proposal 3

The behavior we're describing here can already be achieved with the `test` subcommand if we append the following to our config:

```toml
[[tests]]
  name = "generated_test"
  [tests.input]
    insert_at = "foo"
    type = "raw"
    value = "Generated test message"

  [[tests.outputs]]
    extract_from = "foo"
    [[tests.outputs.conditions]]
      type = "check_fields"
      "message.equals" = "A changed message"

  [[tests.outputs]]
    extract_from = "bar"
    [[tests.outputs.conditions]]
      type = "check_fields"
      "message.equals" = "A changed message"

  [[tests.outputs]]
    extract_from = "baz"
    [[tests.outputs.conditions]]
      type = "check_fields"
      "message.equals" = "A changed message"
```

Then each time we run `vector test ./config.toml` we will get an output showing us the resulting event of each transform:

```sh
$ vector test ./config.toml
Running ./config.toml tests
Test ./config.toml: generated_test ... failed

failures:

--- ./config.toml ---

Test 'generated_test':
check transform 'foo' failed conditions: [ 0 ], payloads (encoded in JSON format):
  {"message":"Generated test message","timestamp":"2019-12-05T15:55:10.563508360Z"}
check transform 'bar' failed conditions: [ 0 ], payloads (encoded in JSON format):
  {"new_field":"this is a static value","timestamp":"2019-12-05T15:55:10.563508360Z","message":"Generated test message"}
check transform 'baz' failed conditions: [ 0 ], payloads (encoded in JSON format):
  {"new_field":"this is a static value","timestamp":"2019-12-05T15:55:10.563508360Z","message":"Generated test message"}
```

If a user then adapts the tests to properly check for the output they're aiming for then it serves a purpose beyond the initial development of the config (regression tests).

However, adding unit tests is currently a manual effort, and for a new user that wants to simply play around with configs they aren't likely to want to dive into this more advanced feature initially.

We could reduce this friction by adding a new flag to the `generate` subcommand:

`vector generate --test 'foo|foo,bar,baz'`

The flag `--test <expr>`  generates unit tests following an expression. The expression above indicates we want to inject test data into transform `foo` and check the outputs of `foo`, `bar` and `baz`. In the above command we've also omitted an expression for topology components, which means none are generated, the output would be the same as the TOML snippet above.

We can then advise users to append tests to their config with `vector generate --test 'foo|foo,bar,baz' >> ./config.toml`.

**Comment by binarylogic** [comment]
I'm very much in favor of Proposal 3. It's a familiar workflow (dev/test) and the user is left with something of value that can control regression. But I think we can make this even simpler. What if we allowed users to run the `test` subcommand against a Vector config that did not have tests declared? The default behavior could be similar to what you described above.

For example, given the configuration you supplied above:

```toml
[sources.my_src]
  type = "stdin"

[transforms.foo]
  type = "grok_parser"
  inputs = ["over_tcp"]
  pattern = "%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:level} %{GREEDYDATA:message}"

[transforms.bar]
  type = "add_fields"
  inputs = ["foo"]
  [transforms.bar.fields]
    new_field = "this is a static value"

[transforms.baz]
  type = "remove_fields"
  inputs = ["bar"]
  fields = ["level"]

[sinks.from_foo]
  type = "console"
  inputs = ["foo"]
  encoding = "json"
  target = "stdout"
```

Executing `vector test` could result in the following:

```bash
$ vector test vector.toml
No tests found! Try the following command to inspect your pipeline:

    vector test vector.toml --input.foo="Hello world"
```

Then the user could run that command and get the following output:

```bash
$ vector test vector.toml --input.foo="Hello world"

Insert data into `transforms.foo'
Transform `foo` failed:
  WARN: No fields captured from grok pattern.
  Input: {"message": "Hello world"}
```

And if they supplied valid input:

```bash
$ vector test vector.toml --input.foo="2019-12-2T00:00:00Z info Hello world"

Insert data into `transforms.foo'
Transform `foo` passed:
  Input:    {"message": "2019-12-2T00:00:00Z info Hello world"}
  Output: {"timestamp": "2019-12-2T00:00:00Z", "level": "info", "message": "Hello world"}

Transform `bar` passed:
  Input: {"timestamp": "2019-12-2T00:00:00Z", "level": "info", "message": "Hello world"}
  Output: {"timestamp": "2019-12-2T00:00:00Z", "level": "info", "message": "Hello world", "new_field": "this is a static field"}

Transform `baz` passed:
  Input: {"timestamp": "2019-12-2T00:00:00Z", "level": "info", "message": "Hello world", "new_field": "this is a static field"}
  Output: {"timestamp": "2019-12-2T00:00:00Z", "message": "Hello world", "new_field": "this is a static field"}

Sink `from_foo` passed:
  Input: {"timestamp": "2019-12-2T00:00:00Z", "message": "Hello world", "new_field": "this is a static field"}
```

Obviously the details here can change, but the `test` subcommand progressively walks the user through building out a working pipeline. I'm curious about what you think.

**Comment by Jeffail** [comment]
I like that, it'd be possible to infer basic test conditions for a transform but it'd be a lot of work for us. However, adding a flag to inject an event somewhere and trace the events out seems reasonable. Ideally I'd like the behavior it generates to have an equivalent test config as it'd help with documentation.

For example, we could say something like:

```sh
vector test --inspect 'foo|foo,bar,baz|2019-12-2T00:00:00Z info Hello world' ./vector.toml
```

Runs the tests in `./vector.toml` (if there are any) and also executes a meta test at the end which is the equivalent of:

```toml
[[tests]]
  name = "flag_test_1"
  [tests.input]
    insert_at = "foo"
    type = "raw"
    value = "2019-12-2T00:00:00Z info Hello world"

  [[tests.outputs]]
    extract_from = "foo"

  [[tests.outputs]]
    extract_from = "bar"

  [[tests.outputs]]
    extract_from = "baz"
```

And we can slightly expand the unit test spec where if you define a test output without any conditions then it triggers an 'inspection' (and therefore prints out the event), which would give you something like this:

```sh
$ vector test --inspect 'foo|foo,bar,baz|2019-12-2T00:00:00Z info Hello world' ./vector.toml
Running ./config.toml tests
Test ./config.toml: flag_test_1 ... inspected

inspections:

--- ./config.toml ---

Test 'flag_test_1':
inspect transform 'foo': payloads (encoded in JSON format):
  {"message":"2019-12-2T00:00:00Z info Hello world"}
inspect transform 'bar': payloads (encoded in JSON format):
  {"new_field":"this is a static value","timestamp":"2019-12-05T15:55:10.563508360Z","message":"2019-12-2T00:00:00Z info Hello world"}
inspect transform 'baz': payloads (encoded in JSON format):
  {"new_field":"this is a static value","timestamp":"2019-12-05T15:55:10.563508360Z","message":"2019-12-2T00:00:00Z info Hello world"}
```

It'd be easy to set this up so you can have any number of `--inspect` flags in one run:

```sh
vector test \
  --inspect 'foo|foo,bar,baz|2019-12-2T00:00:00Z info Hello world' \
  --inspect 'foo|foo,bar,baz|oops this doesnt fit the expected pattern' \
  --inspect 'foo|foo,bar,baz|{"text":"and this is json! what is the world coming to??"}' \
  ./vector.toml
```

Needs a little more thought around the syntax and naming, I don't want to overwhelm new users with weird terminology and magic commands, there's maybe a nicer syntax than `<input>|<output(s)>|<message>`.
