### ISSUE TITLE
New `fixed` source

### ISSUE THREAD

**Issue by a-rodin** [timberio/vector#1317]
A new source generating pre-defined messages at given interval could greatly help in configuration testing and debugging.

Example config:

```toml
[sources.fixed]
type = "fixed"
fields.message = "hello"
repeat = 100 # ms
```

This would produce log events looking like

```json
{
  "message": "hello",
  "timestamp": "2019-12-05T08:24:12.957302185Z",
  "host": "localhost"
}
```

each 100 milliseconds.

If the `repeat` parameter is not specified, just a single message should be generated and then this source should be closed.

**Comment by binarylogic** [comment]
I like this. I'm going to close https://github.com/timberio/vector/issues/980 in favor since you're supports structured data.

**Comment by Jeffail** [comment]
This would be awesome for testing pipelines and benchmarking a config. It'd be extra useful if we could add some sort of increment capability for fields so that generated events can have unique identifiers. Maybe using some custom field interpolation value like:

```toml
[sources.fixed]
type = "fixed"
fields.message = "hello"
fields.id = "{{ fixed_counter }}"
repeat = 100 # ms
```

Or a specific field type:

```toml
[sources.fixed]
type = "fixed"
fields.message = "hello"
incremented_fields = [ "id" ]
repeat = 100 # ms
```
