### ISSUE TITLE
remove_fields not working 

### ISSUE THREAD

**Issue by Nitin5acc** [timberio/vector#1319]
HI,
I have below configuration - 
```

[sources.synapse_log]
 type = "tcp"
 address = "10.208.11.71:9001"
 #Transform
 [transforms.synapse_ssn] 
   inputs = ["synapse_log"] 
   type="remove_fields"
   fields = ["timestamp""]
# Output data
[sinks.out]
  inputs   = ["synapse_ssn"]
  type     = "file"
  path = "vector-%Y-%m-%d.log"
  encoding = "text"
```

But even then file Sink has "Timestamp"  -

{"timestamp":"2019-12-05T16:16:25.9052597-06:00","level":"Information","message":"The WhiteWalker ......}

P.S:- I am using a .NET core agent(serilog) to send log events to TCP address.  

Please help

**Comment by LucioFranco** [comment]
Does changing `fields = ["timestamp""]` to `fields = ["timestamp"]` work?

**Comment by Nitin5acc** [comment]
Hello,
No it does not , I tried hiding the "level" as well but same issue.

```
# Input data.
[sources.synapse_log]
 type = "tcp"
 address = "10.208.11.71:9001"
 #Transform
 [transforms.synapse_ssn] 
   type="remove_fields"
   inputs = ["synapse_log"]  
   fields = ["level"]
# Output data
[sinks.out]
  inputs   = ["synapse_ssn"]
  type     = "file"
  path = "vector-%Y-%m-%d.log"
  encoding = "text"
```

And I get this -
{"timestamp":"2019-12-05T16:38:28.8056063-06:00","**level**":"Information","message":"The WhiteWalker { WhiteWalkerId: 1, WhiteWalkerName: \"Night King\", WhiteWalkerSocialSecurityNumber: 724512333, WhiteWalkerStrength: [Darkness, Darkness, Ice, IceDragon], IsWhiteWalker: False } has just died:","nightKing":{"WhiteWalkerId":1,"WhiteWalkerName":"Night King","WhiteWalkerSocialSecurityNumber":724512333,"WhiteWalkerStrength":["Darkness","Darkness","Ice","IceDragon"],"IsWhiteWalker":false,"_typeTag":"WhiteWalker"}}

**Comment by LucioFranco** [comment]
Ah this is because of the `tcp` source does not parse your log events into a structured format but instead stores your json under the `message` field without decoding it. I would suggest adding the `json_parser` infront of remove field and after `synapse_log`.

**Comment by Nitin5acc** [comment]
Are you asking me not to use `remove_fields` ?  I am not able to follow. We need to drop "level" field 
it would be great if you Can you please edit the above-shared config file?

**Comment by LucioFranco** [comment]
This should work
```toml
# Input data.
[sources.synapse_log]
 type = "tcp"
 address = "10.208.11.71:9001"
[transforms.json]
type = "json_parser"
inputs = ["synapse_log"]
drop_invalid = true
 #Transform
 [transforms.synapse_ssn] 
   type="remove_fields"
   inputs = ["json"]  
   fields = ["level"]
# Output data
[sinks.out]
  inputs   = ["synapse_ssn"]
  type     = "file"
  path = "vector-%Y-%m-%d.log"
  encoding = "text"
```
