### ISSUE TITLE
Support GeoIP ASN in `geoip` transform

### ISSUE THREAD

**Issue by mhf-ir** [timberio/vector#1372]
Support for ASN ?
https://dev.maxmind.com/geoip/geoip2/geolite2-asn-csv-database/
Get isp and Network of ip.

**Comment by Jeffail** [comment]
Hey @mhf-ir, is there an advantage to using the CSV database rather than the binary city database that the `geoip` transform (https://vector.dev/docs/reference/transforms/geoip) currently targets?

**Comment by mhf-ir** [comment]
@Jeffail sorry my bad, for sharing link. my Point is DB of [ASN](https://en.wikipedia.org/wiki/Autonomous_system_(Internet)).
For get data of ISP and network of ip:
https://geolite.maxmind.com/download/geoip/database/GeoLite2-ASN.tar.gz

**Comment by Jeffail** [comment]
Understood, we can possibly add support for the ASN DB as an additional extra. So with a config like:

```toml
[transforms.my_transform_id]
  type = "geoip"
  inputs = ["my-source-id"]
  database = "/path/to/GeoLite2-City.mmdb"
  asn_database = "/path/to/GeoLite2-ASN.csv"
  source = "ip_address"
  target = "geoip"
```

And with the `asn_database` field present the DB would be parsed and data enriched with the extra information. If this functionality is being added to `geoip` then it would be necessary to also make the field `database` optional, where the absence of either `database` or `asn_database` is accepted, but both would cause an error (the transform would be a no-op).
