### ISSUE TITLE
Global options for schema field names (message, host, timestamp, etc)

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1446]
This is a simple change that allows a user to change the defaults for the common field names, such as a `host`, `timestamp`, and `message`.

## Example

In the `vector.toml` file a user could specify these as top-level options:

```toml
[log_schema]
host_key = "instance" # default "host"
message_key = "info" # default "message"
timestamp_key = "datetime" # default "timestamp"
```

## Requirements

- [ ] All sources should use the settitngs.
- [ ] All transforms that implicitly operate on the `message` field should use the `message_key` setting.
- [ ] All sinks that implicity use the `timestamp` key for partittioning or other means s hould use the `timestamp_key` variable.
