### ISSUE TITLE
Support a new reusable `pipelines` directive when configuring Vector

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1447]
Following up on https://github.com/timberio/vector/issues/1327#issuecomment-569018428, I'd like to consider a new `pipelines` directive in Vector's configuration files that would make a component's `inputs` key optional.

## Examples

Below are a few examples to show how this would work in practice:

### Simple

```toml
[pipelines]
  nginx_logs = ["nginx_logs", "parse_json", "print"]

[sources.nginx_logs]
  type = "file"
  include = "/var/log/nginx/*.log"

[transforms.parse_json]
  type = "json_parser"

[transforms.print]
  type = "console"
```

### Default components

Taking the above example, a user could simply specify the component type if they do not want to customize it further.

```toml
[pipelines]
  nginx_logs = ["nginx_logs", "json_parser", "console"] # notice the use of direct component names

[sources.nginx_logs]
  type = "file"
  include = "/var/log/nginx/*.log"
```

This is very close to @lukesteensen's bash syntax idea 😄 .

### Chaining pipelines

It should also be possible to chain pipelines together. This is very similar to https://github.com/timberio/vector/issues/1061, and is probably the solution to that.

`/etc/vector/scrub_sensitive_data.toml`:

```toml
[pipelines]
  scrub_sensitive_data = ["drop_sensitive_fields", "scrub_message"]

[transforms.drop_sensitive_fields]
  type = "remove_fields"
  fields = ["user_name", "user_email", "last_4"]

[transforms.scrub_message]
  type = "lua"
  source = """
  // special code to scrube sensitive info from the message field
  ""
```

`/etc/vector/vector.toml`:

```toml
[pipelines]
  main = ["app_logs", "scrub_sensitive_data", "archive"]

[sources.app_logs]
  type = "file"
  include = "/var/log/my_app/*.log"

[sinks.archive]
  type = "aws_s3"
  bucket = "my-bucket"
```

**Comment by a-rodin** [comment]
I was recently thinking that our components can be seen as functions (even though some of them, such as sources or sinks, are impure). This pipeline approach fits nicely in this mental framework, as a pipeline can be seen as a composition of these functions.

**Comment by Jeffail** [comment]
Yeah I like this. Would be interesting to gather some large configs used in the wild and reproduce them as pipelines. A diamond shaped filter config might look like this (omitting the actual transforms):

```toml
[pipelines]
  process_common = [
    "this_common_thing",
    "another_common_thing",
    "console",
  ]
  process_foos = [
    "nginx_logs",
    "filter_just_foos",
    "do_thing",
    "do_another_thing",
    "process_common",
  ]
  process_bars = [
    "nginx_logs",
    "filter_just_bars",
    "do_something_else",
    "and_then_this",
    "process_common",
  ]
```

I'm also in favor of a transpiling, I think at least internally we should only ever have one config format, and one way of defining a topology.

However, another thing to consider is whether this is a syntax for advanced users or beginners. If it's intended for beginners then we ought to emphasize it within the first few pages of our docs, it may well be the first syntax that new users experiment with and therefore it's more likely to become the (adopted) standard config format for Vector configs.

This might become an issue if the underlying "canonical" config differs. For example, which format do we expose with https://github.com/timberio/vector/issues/1039, the canonical form, or the one the user provided?

**Comment by binarylogic** [comment]
> I think at least internally we should only ever have one config format, and one way of defining a topology.

👍 

> However, another thing to consider is whether this is a syntax for advanced users or beginners.

I'm leaning towards making this the single/only way to define a topology and deprecating the `inputs` field, but I want to see how this comes together first.

> emphasize it within the first few pages of our docs

We'll update all of the docs

> For example, which format do we expose with #1039, the canonical form, or the one the user provided?

I think we expose our internal normalized format. In other words, the topology map encoded as JSON. Happy to hear reasons to not do this.

**Comment by a-rodin** [comment]
> I'm leaning towards making this the single/only way to define a topology and deprecating the inputs field, but I want to see how this comes together first.

Note that the pipelines syntax as discussed here allows to define only subset of currently possible topologies because it doesn't seem possible to define multiple inputs for a single transform or sink with it.

**Comment by Jeffail** [comment]
Depends on how it's implemented, my initial assumption with the syntax was that:

```toml
[pipelines]
  first = [
    "foo",
    "common_proc",
    "baz",
  ]
  second = [
    "bar",
    "common_proc",
    "baz",
  ]
```

Would translate to:

```toml
[sources.foo]
  type = "todo"

[sources.bar]
  type = "todo"

[transforms.common_proc]
  inputs = [ "foo", "bar" ]
  type = "todo"

[sinks.baz]
  inputs = [ "common_proc" ]
  type = "todo"
```

That assumption is a stretch as it requires the knowledge that Vector would create one single instance of `common_proc` and hook it up within two separate pipelines. It's not intuitive behavior based on the pipeline syntax itself, where we might assume we have two isolated event feeds, but with the already established understanding of how Vector components work (with `inputs`) we might make the leap.

In that sense we're relying on the fact that transforms (currently) in practice aren't pure functions as they're wrapped with our message routing mechanisms (consuming events from a list of input components) and therefore have managed state.

However, if we were to rely on this pipeline syntax as the _exclusive_ way to define topologies then there's no longer any reason to assume a transform would be shared across pipelines. In which case I would assume the pipeline config above to translate to:

```toml
[sources.foo]
  type = "todo"

[sources.bar]
  type = "todo"

[transforms.common_proc_1]
  inputs = [ "foo" ]
  type = "todo"

[transforms.common_proc_2]
  inputs = [ "bar" ]
  type = "todo"

[sinks.baz_1]
  inputs = [ "common_proc_1" ]
  type = "todo"

[sinks.baz_2]
  inputs = [ "common_proc_2" ]
  type = "todo"
```

For stateless transformations this difference is inconsequential as the composition is the same. However, we're already starting to propose transforms that carry state (https://github.com/timberio/vector/issues/1200) so it's entirely possible that this becomes a very confusing issue. It's also a problem with naming collisions as if these are isolated components then their metrics and logging should also be separate.

I personally think if we were to lean fully into a hierarchical config format (instead of our current flattened syntax) then there's a lot more to consider. We're trading off some strengths that Vector has in making it very clean to structure complex topologies in favor of making it more concise to express the much more simple serial pipelines.

Interestingly, I've gone through the process of taking Benthos from the opposite direction. I started from a hierarchical config structure where my equivalent of a transform (a processor) is a pure function and you can simply list them:

```yaml
pipeline:
  processors:
    - jmespath:
        query: '{ nested: @, links: len(urls) }'
    - if:
        operator: im_bored
        then:
          - text:
              operator: to_upper
```

Then gradually added support for flattening the structure with named global processors that you compose:

```yaml
pipeline:
  processors:
    - resource: foo
    - if:
        operator: im_bored
        then:
          - resource: bar

resources:
  processors:
    foo:
      jmespath:
        query: '{ nested: @, links: len(urls) }'
    bar:
      text:
        operator: to_upper
```

The former is better for simplified pipelines, where the structure is simple enough to express as a list of steps. The latter is better for large and heavily structured pipelines where it's preferential to break out certain functions and configure them outside of the structure definition.

**Comment by a-rodin** [comment]
> However, if we were to rely on this pipeline syntax as the exclusive way to define topologies then there's no longer any reason to assume a transform would be shared across pipelines.

Yeah, that's how I understood it initially! I assumed that that reusing a named component without the `inputs` field between different pipelines would create isolated copies of that component for each pipeline.

I think if the opposite approach is used, so that there is only one instance of each named component shared between pipelines, it could lead to some unexpected behavior.

For example, this pipeline config

```toml
[pipelines]
nginx_logs = ["nginx_file_source", "generic_http_logs_parser", "s3_sink_1"]
apache_logs = ["apache_file_source", "generic_http_logs_parser", "s3_sink_2"]
```

would write _both_ NGINX and Apache logs to each of the sinks, which is probably not what the user expects.

> The former is better for simplified pipelines, where the structure is simple enough to express as a list of steps. The latter is better for large and heavily structured pipelines where it's preferential to break out certain functions and configure them outside of the structure definition.

I support the idea of having two different syntaxes, "common" which is easy to use and works for most of simple topologies and "advanced" which might be harder to user, but works for all possible to topologies. However, it might be useful to have some kind of evidence that "common" syntax is actually easier to grasp for new users than "advanced", but I'm not sure how to collect it.
