### ISSUE TITLE
AWS authentication for the kafka source and sink

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1516]
I did some light reading regarding Amazon's MSK service authentication strategy:

https://docs.aws.amazon.com/msk/latest/developerguide/security_iam_service-with-iam.html

It appears we'll need to support the basic AWS authentication strategy for both the `kafka` source and sink. We accomplished this in the `elasticsearch` sink by adding an auth strategy:

```toml
[sinks.es]
  type = "elasticsearch"
  auth.strategy = "aws"
```

I would like to do the same here.
