### ISSUE TITLE
Automaic timestamp coercion

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1543]
Currently [all parser transforms](https://vector.dev/components/?functions%5B%5D=parse) accept a `types` table for field value coercion. The `timestamp` type is unique in that it requires an explicit strptime format to be specified:

```toml
[transforms.coerce]
  type = "coercer"

  [transforms.coerce.types]
    timestamp_field = "timestamp|%s"
```

I propose that we offer a best-effort timestamp parsing option that does not require a strptime format:

```toml
[transforms.coerce]
  type = "coercer"

  [transforms.coerce.types]
    timestamp_field = "timestamp"
```

The formats would include:

- [ ] IS08601
- [ ] RFC3339
- [ ] A generic time only format: `HH:MM[:SS][.SSS][SSS][Z]`, where `[...]` represents an optional successive fragment. The date is assumed to be the local date.

I'm open to other formats I might be missing here.
