### ISSUE TITLE
Document `docker` source installation

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1557]
We need better documentation on how to setup the `docker` source. This was a conversation in our chat:

> Hi there,
> I'm once more considering Vector to replace my current "log ingestion process".
> All the app that we want to monitor run on a docker container. So currently, we use fluentbit as the "log driver" to parse / transform the logs.
> I've looked at vector's docker source module and it seems to work quite differently than fluentbit.
> In our case fluentbit itself run in a container, from what I understood, the plugin was installed directly inside of docker, docker then route the logs to a port... inside a container.
> If I wanted to use vector I would have to install on the server itself, bare metal ?
> Would it be possible to run a container with both vector and docker installed in it so that I don't require to install docker to the server ? I'm far from a docker expert, but that seems like it could potentially cause some sort of problems (to run a docker inside a container) ?
> Maybe you have some experience with a similar flow ?
> Cheers.

And @a-rodin responded with:

> Hi, it is possible to pass the Docker socket from the host inside the Vector container to allow Vector communicate with the Docker engine. It can be done by mounting /var/run/docker.sock. For example if you run Vector as docker run vector, an additional option -v/var/run/docker.sock:/var/run/docker.sock can be added to the list of command line arguments to do this. For docker-compose.yml it is possible to mount it like this:

```
version: '3'                                                                                                            

services:                                                                                                               
  vector:                                                                                                               
    image: timberio/vector:nightly-alpine                                                                               
    volumes:                                                                                                            
      - ./vector.toml:/etc/vector/vector.toml                                                                           
      - /var/run/docker.sock:/var/run/docker.sock
```

> Note that if you use console sink, you might want to not include the Vector's container to the list of containers it watches for.
