### ISSUE TITLE
Make `vector generate` output documentation

### ISSUE THREAD

**Issue by Hoverbear** [timberio/vector#1687]
Right now `vector generate` outputs quite minimal configurations.

```bash
❯ vector generate "stdin"
data_dir = '/var/lib/vector/'
dns_servers = []
[sources.source0]
max_length = 102400
type = 'stdin'
```

This issue proposes the output be something like the following:

```toml
#                                    __   __  __
#                                    \ \ / / / /
#                                     \ V / / /
#                                      \_/  \/
#
#                                    V E C T O R
#                                   Configuration
#
# ------------------------------------------------------------------------------
# Website: https://vector.dev
# Docs: https://vector.dev/docs/
# ------------------------------------------------------------------------------

# The location of data storage
data_dir = '/var/lib/vector/'
# Custom DNS servers to use (if any)
dns_servers = []

[sources.source0]
# https://vector.dev/docs/reference/sources/stdin/
type = 'stdin'
# The maxiumum bytes size of a message before it is discarded.
max_length = 102400
```

We may want to opt for a smaller logo, or none at all. We also may want to output commented versions of fields that are using defaults.
