### ISSUE TITLE
Add a `swimlanes` transform

### ISSUE THREAD

**Issue by Jeffail** [timberio/vector#1724]
Our flattened inputs format makes it possible, but awkward, to create logical forks within a topology:

```toml
[transforms.filter_things]
  inputs = [ "somewhere" ]
  type = "field_filter"

[transforms.filter_not_things]
  inputs = [ "somewhere" ]
  type = "field_filter"

[sinks.things]
  type = "foo"
  inputs = [ "filter_things" ]

[sinks.not_things]
  type = "bar"
  inputs = [ "filter_not_things" ]
```

This forces us to create two transforms that contain basically the same logic (`foo` and `NOT foo`) and hook up four components for a relatively simple and common use case. We can immediately reduce this significantly by implementing a conditional transform, where we can specify one logical condition:

```toml
[transforms.contains_foo]
  inputs = [ "somewhere" ]
  type = "conditional"
  where = "message contains 'foo'" # Don't worry about this syntax for now

[sinks.things]
  type = "foo"
  inputs = [ "contains_foo.if" ]

[sinks.not_things]
  type = "bar"
  inputs = [ "contains_foo.else" ]
```

This new transform would create two pseudo transforms `<name>.if` and `<name>.else`, which are delivered events that pass the condition or fail it respectively, these transforms are a direct pass-through and only serve as an input target for other components.

## Inline Transforms

The above is still somewhat awkward and clunky for the simplest use case which is "if X do Y otherwise Z", so we can also allow inline transforms (or id's) similar to the compose transform spec (https://github.com/timberio/vector/issues/1653):

```toml
[transforms.contains_foo]
  inputs = [ "somewhere" ]
  type = "conditional"
  where = "message contains 'foo'" # Don't worry about this syntax for now
  if = [ "foo" ]
  else = [ "bar" ]

[sinks.things]
  inputs = [ "contains_foo" ]
  type = "foo"
```

This would create a diamond shape of transforms, where the outputs from the `if` and `else` transforms are merged and can be consumed directly from `contains_foo`.

**Comment by Jeffail** [comment]
## Switch

This would be a transform that behaves similarly to the above, except with an arbitrary number of cases:

```toml
[transforms.contains_foo]
  inputs = [ "somewhere" ]
  type = "switch"
  [[transforms.contains_foo.cases]]
    name = "case1"
	condition = "message contains 'foo'" # Again, don't worry about this syntax for now.
	passthrough = false

  [[transforms.contains_foo.cases]]
    name = "case2"
	condition = "message contains 'bar'"
	passthrough = true

  [[transforms.contains_foo.cases]]
    name = "case3"
	condition = "message contains 'baz'"

[sinks.things]
  inputs = [ "contains_foo.case1" ]
  type = "foo"

[sinks.not_things]
  inputs = [ "contains_foo.case2" ]
  type = "bar"
```

And with the ability to inline case transforms:

```toml
[transforms.contains_foo]
  inputs = [ "somewhere" ]
  type = "switch"
  [[transforms.contains_foo.cases]]
    name = "case1"
	condition = "message contains 'foo'" # Again, don't worry about this syntax for now.
	do = [ "foo" ]
	passthrough = false

  [[transforms.contains_foo.cases]]
    name = "case2"
	condition = "message contains 'bar'"
	do = [ "bar" ]
	passthrough = true

  [[transforms.contains_foo.cases]]
    name = "case3"
	condition = "message contains 'baz'"
	do = [ "baz" ]

[sinks.things]
  inputs = [ "contains_foo" ]
  type = "foo"
```

**Comment by binarylogic** [comment]
I love this. Thank you for opening. Some feedback:

### Initial Proposal

```toml
[transforms.contains_foo]
  inputs = [ "somewhere" ]
  type = "conditional"
  where = "message contains 'foo'" # Don't worry about this syntax for now

[sinks.things]
  type = "foo"
  inputs = [ "contains_foo.if" ]

[sinks.not_things]
  type = "bar"
  inputs = [ "contains_foo.else" ]
```

Big 👍 on this from me.

### Inline Proposal

```toml
[transforms.contains_foo]
  inputs = [ "somewhere" ]
  type = "conditional"
  where = "message contains 'foo'" # Don't worry about this syntax for now
  if = [ "foo" ]
  else = [ "bar" ]

[sinks.things]
  inputs = [ "contains_foo" ]
  type = "foo"
```

I dislike this. It seems like it's conflating control flow with what you were trying to accomplish with the `compose` transform. It's also weird because this is the first time we allowing topology definitions in a "has many" form instead of a "belongs to" form. This makes groking the topology even more difficult.

### Switch Proposal

I like it! I think we can simplify things by doing:

```toml
[transforms.contains_foo]
  inputs = [ "somewhere" ]
  type = "switch"
  [transforms.contains_foo.cases.case1]
    condition = "message contains 'foo'" # Again, don't worry about this syntax for now.

  [transforms.contains_foo.cases.case2]
    condition = "message contains 'bar'"

  [transforms.contains_foo.cases.case3]
    condition = "message contains 'baz'"

[sinks.things]
  inputs = [ "contains_foo.case1" ]
  type = "foo"

[sinks.not_things]
  inputs = [ "contains_foo.case2" ]
  type = "bar"
```

1. Adding the case ID into the name seems simpler to me and its consistent with how we're defining IDs throughout the rest of the topology.
2. I don't know if we need the `passthrough` option? What's the downside of not referencing a case ID? IMO, they can use it or not.

To further simplify this, one could do:

```toml
[transforms.contains_foo]
  inputs = [ "somewhere" ]
  type = "switch"
  cases.case1.condition "message contains 'foo'"
  cases.case2.condition = "message contains 'bar'"
  cases.case3.condition = "message contains 'baz'"
```

The simplicity of that is 🥇 .

**Comment by Jeffail** [comment]
Agreed, let's get the simplest use case solved first with the narrower syntax. If we decide we want the inline stuff it can be added later. Same for `fallthrough`, it'd allow for more specialized matching without receiving duplicates or exhaustive conditions, but there's such a strong case for a smaller config that if we wanted to solve that we could do it separately.

**Comment by binarylogic** [comment]
Cool. I'm also realizing that my changes to the "case" example do not account for ordering :/, so it's likely that syntax is not feasible unless we were able to preserve the order cases were defined.

**Comment by Jeffail** [comment]
It would work as a general swimlanes type of transform (called `swimlanes`?), where any case that resolve true gets a message routed. That would be a very fast and easy way of creating a range of conditional pipelines, and would likely be enough for most use cases, especially so when the conditions are mutually exclusive (`foo == 'bar'`, `foo == `baz`).

Then in use case where conditions aren't necessarily exclusive and a user needs more control over flow we can offer the more verbose `switch`.

**Comment by LucioFranco** [comment]
I would like to note this `switch` transform would be extremely useful for sinks like `loki` that don't internally route logs. In the context of loki they support multi-tenancy and it routes logs to different loki distributors via a tenant id. Using this transform one could then setup this type of routing easily.

Reference https://github.com/grafana/loki/tree/master/cmd/fluent-bit#running-multiple-plugin-instances

**Comment by Jeffail** [comment]
The simplest transform to implement here is a `swimlanes` format factor, where each case that passes for an event has it routed to it. In terms of implementation this is basically just a macro for N filter transforms.

It also covers all the use cases of and if/else `conditional` and a `switch`, although there's still justification for eventually adding these as they assist users in creating exclusive branches.

I therefore think `swimlanes` is a good place to start here. I can crank out a proof of concept and then we can evaluate whether we're happy with the implementation and user experience.

In terms of implementation I can see two potential candidates:

## 1. Configuration Expansion

Allow transform configurations to expand into N configurations, essentially making them a macro. This is most likely the simplest to manage on a technical level as we can expand the configs out before building and validating the whole topology, so there's no special cases to insert into our topology builder.

The main disadvantage here is that the resulting transforms are isolated. This is fine for `swimlanes` as the branches are isolated anyway. However, when implementing if/else and switch it would be advantageous to consume an event only once, test it only once, and branch it out across pseudo outputs accordingly.

## 2. Multiple Outputs

Currently all sources and transforms within Vector have one single output. We could potentially open this up to accomodate multiple named outputs so that a call to `transform_into` results in a map of named outputs to events.

Relevant part of the topology builder: https://github.com/timberio/vector/blob/master/src/topology/builder.rs#L161

For this to work we would need to allow transform configs to list their named outputs, use that for topology validation, and then in our builder we would construct a fan out stream per named output and stream the resulting events according.

The advantage here is that it's much more flexible than the config expansion approach and can be reused, but at the cost of adding some complexity for our topology builder.

**Comment by binarylogic** [comment]
I'm in favor of that, do you mind sharing an example config for this transform to make sure we're on the same page?

**Comment by Jeffail** [comment]
It'll look something like this

```toml
[transforms.foo]
  inputs = [ "somewhere" ]
  type = "swimlanes"

  [transforms.foo.lanes.case1]
    type = "check_fields"
    "message.eq" = "foo bar"

  [transforms.foo.lanes.case2]
    type = "check_fields"
    "message.eq" = "bar baz"

[sinks.the_foobars]
  inputs = [ "foo.case1"]
  type = "something"

[sinks.the_barbazs]
  inputs = [ "foo.case2"]
  type = "something_else"
```

The structure of a lane here is the same as a unit test output condition (a `condition` component), the `type` `check_fields` is currently the only condition type. More on conditions as a concept here: https://github.com/timberio/vector/issues/1281

**Comment by binarylogic** [comment]
Yeah, I like the shared conditions concept. It's almost like you've built something like this before 😄 . To clarify, an event could be true for multiple "lanes" and theresfore show up in both?

**Comment by Jeffail** [comment]
Yep. To avoid that you'd need to make sure your logical conditions are exclusive which can be a bit awkward for certain scenarios, so that's the justification for a separate `switch` transform.

**Comment by binarylogic** [comment]
Cool, I like that 👍 . I agree this is a better first step over an `if` transform.

**Comment by binarylogic** [comment]
Another thought, what if `check_fields` was our default condition type? Then we could remove the repetitive `type` calling and you could achieve:

```toml
[transforms.foo]
  inputs = [ "somewhere" ]
  type = "swimlanes"
  lanes.case1.message.eq = "foo bar"
  lanes.case2.message.eq = "baz bar"
```

Has your experience with Benthos shown this to be the most common?
