### ISSUE TITLE
Expose unavailable Kafka source broker

### ISSUE THREAD

**Issue by Jeffail** [timberio/vector#1752]
Currently, you can start Vector with an unavailable Kafka broker as the source and see no errors:

```toml
[sources.kafka]
    type = "kafka"
    bootstrap_servers = "this-doesnt-exist-fam"
    group_id = "foo"
    topics = ["bar"]

[sinks.out]
    inputs   = ["kafka"]
    type     = "console"
    encoding = "text"
```

The service starts up and you get no feedback that the connection is failing at all. We should be at the very least intermittently logging errors to indicate the connection is not open.

We should also consider adding healthchecks to sources, eventually we'll want to add endpoints (https://github.com/timberio/vector/issues/1073) for checking the health of the service, and we should offer a probe for whether our components (all of them) are successfully connected.
