### ISSUE TITLE
Investigate Vector thread usage for `stdin` source

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1762]
This was reported by a Vector user:

> I did notice the agent is using 30+ threads which seems a bit excessive to me. Curious if you guys have ever thought of providing a config variable to limit thread count in Tokio’s pool? It’s not an issue at all I’m just hyper sensitive to resources being used by [company] cause we get lots of requests from our users to reduce CPU/Mem footprint.

Example config is:

```toml
[sources.app]
    type = "stdin"
    host_key = "host"

[transforms.json_parsed]
  type = "json_parser" 
  inputs = ["app"]

[transforms.unauth_user]
  type = "lua"
  inputs = ["json_parsed"]
  source = """
if event["user_id"] == nil then
  event["user_id"] = "unauthenticated"
end
"""

[sinks.console]
  inputs = ["unauth_user"]
  type = "console"
  encoding = "json"

[sinks.cloud]
  inputs = ["unauth_user"]
  type = "aws_cloudwatch_logs"
  region = "us-east-1"
  group_name = "app-prod"
  stream_name = "user-{{ user_id }}"
  encoding = "json"
```
