### ISSUE TITLE
Change `add_fields` to support string templating

### ISSUE THREAD

**Issue by Hoverbear** [timberio/vector#1766]
Update the `add_fields` transform to support templates like the `log_to_metric` transform.

https://vector.dev/docs/reference/transforms/log_to_metric/

Use cases:

* Adding 'summary' fields for downstream consumption.
  ```toml
  [transforms.sms_summary]
    type = "add_fields"
    inputs = ["sudo_reports"]
    [transforms.sms_summary.fields]
      notice = "EXEC({{host}}) {{user}}:{{binary}} - {{sentry_url}}"
  ```
* Simple data enrichment.
  ```toml
  [transforms.target_idc]
    type = "add_fields"
    inputs = ["geoip_located"]
    [transforms.target_idc.fields]
      idc = "{{geoip.country_code}}-1"
  ```
