### ISSUE TITLE
Configuration unit tests pass even when the event is dropped

### ISSUE THREAD

**Issue by a-rodin** [timberio/vector#1810]
Let's say that there is the following configuration file:

```toml
[transforms.field_filter_simple]
  inputs = []
  type = "field_filter"
  field = "file"
  value = "a"
[[tests]]
  name = "field_filter_simple"
  [tests.input]
    insert_at = "field_filter_simple"
    type = "log"
    [tests.input.log_fields]
      file = "b"
  [[tests.outputs]]
    extract_from = "field_filter_simple"
    [[tests.outputs.conditions]]
      type = "check_fields"
      "file.exists" = true
```

The `field_filter` transform drops the event which it gets as the input, however the test passes.
