### ISSUE TITLE
Support config unit testing for transforms which change the number of output events

### ISSUE THREAD

**Issue by a-rodin** [timberio/vector#1813]
Currently the config unit tests, as far as I understand, support only a single output event coming from a transform. However, hypothetically some transforms can either produce multiple events from a single event or drop the event.

It might make sense to support assertions for such cases to allow the users to test for them explicitly.

Related to #1810.

**Comment by Jeffail** [comment]
We already support this to an extent. When we receive >1 events from a transform each condition must pass for one or more of the extracted events in order for the test to pass. Right now that means if you want to test for the structure of each individual event your `check_fields` condition must also be exclusive to an event:

```toml
    [[tests.outputs.conditions]]
      type = "check_fields"
      "id.equals" = "foo_event"
      "message.equals" = "what we expect from the foo event"

    [[tests.outputs.conditions]]
      type = "check_fields"
      "id.equals" = "bar_event"
      "message.equals" = "what we expect from the bar event"
```

This is mentioned in the unit test guide but I haven't fleshed it out with examples, I imagine testing >1 events is going to be rare for most users. If that's not the case then it might be worth adding an "Advanced Testing" section to the end of the guide to cover this with examples.

However, we can't currently test for "transform X recevied zero events", which I think is worth having. We could do that pretty easily with something like a `no_outputs_from = [ "foo", "bar" ]` field.
