### ISSUE TITLE
Allow passing advanced `librdkafka` options to the `kafka` source and sink

### ISSUE THREAD

**Issue by a-rodin** [timberio/vector#1821]
`librdkafka` which underlies `kafka` source and sink supports [many advanced configuration options](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md).

Some users might have a reason to tune some of them. I propose to add a new advanced configuration option called `librdkafka_options` to the configuration of both of them.

Its usage could look like this:

```toml
[sinks.my_sink_id]
  # REQUIRED - General
  type = "kafka" # must be: "kafka"
  inputs = ["my-source-id"] # example
  bootstrap_servers = "10.14.22.123:9092,10.14.23.332:9092" # example
  key_field = "user_id" # example
  topic = "topic-1234" # example
  # REQUIRED - requests
  encoding = "json" # example, enum
  # OPTIONAL - General
  healthcheck = true # default
  [sinks.my_sink_id.librdkafka_options]
    "max.in.flight.requests.per.connection" = "1000000"
    "max.poll.interval.ms" = "300000"
    "socket.timeout.ms" = "60000"
```

For example, ClickHouse, which uses `librdkafka` as the base of its `Kafka` engine too, [allows to pass arbitrary options to it](https://clickhouse.tech/docs/en/operations/table_engines/kafka/#configuration).

Related to https://github.com/timberio/vector/issues/1818.
