### ISSUE TITLE
New `flatten` transform

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1880]
This transform would recursively flatten all nested keys into the root document. For example

## Example 1: Default root key

```toml
[transforms.flatten_all]
  type = "flatten"
```

Input:

```json
{
  "parent": {
    "child": {
      "grandchild": "value"
    }
  }
}
```

Output:

```json
{
  "grandchild": "value"
}
```

## Example 2: Configurable root key

```toml
[transforms.flatten_all]
  type = "flatten"
  root = "parent"
```

Input:

```json
{
  "parent": {
    "child": {
      "grandchild": "value"
    }
  }
}
```

Output:

```json
{
  "parent": {
    "grandchild": "value"
  }
}
```
