### ISSUE TITLE
Ability to control flow from programmable transforms

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1942]
Something that would be very powerful would be the ability to dynamic define channels from programmable transforms. This would unblock complex control flow logic. For example:

```toml
[transforms.control_flow]
  type = "lua"
  source = """
if ... then
  emit(event, 'lane1')
else
  emit(event, 'lane2')
end
```

This would produce named outputs, similar to the `swimlanes` transform that could then be connected downstream:

```toml
[sinks.first]
  inputs = ["control_flow.lane1"]

[sinks.second]
  inputs = ["control_flow.lane2"]
```
