### ISSUE TITLE
New `loggly` sink

### ISSUE THREAD

**Issue by afoninsky** [timberio/vector#1982]
Couldn't find information if Vector supports log output to Loggly SaaS. Creating issue as a feature request. Please mark as duplicate if already exists.

**Comment by binarylogic** [comment]
Thanks @afoninsky. I think we an wrap our `http` sink fairly easily and send the data via https://www.loggly.com/docs/http-endpoint/.

**Comment by afoninsky** [comment]
@binarylogic please specify what do you mean by "wrap our http". Is it a feature in roadmap to implement, or "you can easily do it using existing http sync"? Thank you for the information :)

**Comment by binarylogic** [comment]
I mean as an official `loggly` sink. We've been wrapping the `http` sink for other providers. Ex: https://github.com/timberio/vector/pull/1847/files. And from the looks of their documentation, you should be able to configure the `http` to work as well:

```toml
[sinks.loggly]
  type = "http"
  uri = "https://logs-01.loggly.com/bulk/${LOGGLY_TOKEN}/tag/bulk/"
  encoding = "json"

[sinks.loggly.batch]
  max_size = 5000000 # 5mb, loggly's max
```
