### ISSUE TITLE
Add option to remove blank leftover objects

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#2047]
Both the `rename_fields` and `remove_fields` transform should have a `drop_blank_objects` settings (defaults to `true`) that removes blank parent objects after the operation succeeds.

For example:

```json
{
  "parent": {
    "child": "value"
  }
}
```

Renaming the `parent.child` field to `root` results in this object:

```json
{
  "root": "value",
  "parent": {}
}
```

The new `drop_blank_objects` option would result in:

```json
{
  "root": "value"
}
```

**Comment by binarylogic** [comment]
After some manual testing I think this might already be done. At the very least we should add tests for this to ensure the behavior does not regress.

**Comment by bruceg** [comment]
My testing using a behavioral test indicates this does not already happen, so I'll add an option for it.

**Comment by binarylogic** [comment]
@bruceg, so my tests show that this is working, at least from a user's perspective:

```toml
[sources.in]
type = "stdin"

[transforms.parse]
type = "json_parser"
inputs = ["in"]

[transforms.rename]
type = "rename_fields"
inputs = ["parse"]
fields."metadata.first" = "metadata_first"
fields."metadata.second" = "metadata_second"

[sinks.out]
type = "console"
inputs = ["rename"]
encoding = "json"
```

This input:

```json
{"metadata": {"first": "value1", "second": "value2"}}
```

Produces this output

```json
{"host":"Bens-MacBook-Pro.local","metadata_first":"value1","metadata_second":"value2","timestamp":"2020-03-18T12:43:32.684155Z"}
```

Notice that the `metadata` root key is not included.

**Comment by bruceg** [comment]
Odd. I can't reproduce with a behavior test. Am I testing the wrong thing?

``` TOML
[transforms.rename_fields_empty_objects]
  inputs = []
  type = "rename_fields"
  [transforms.rename_fields_empty_objects.fields]
      "b.d" = "renamed_d"
      b.e = "renamed_e"
[[tests]]
  name = "rename_fields_empty_objects"
  [tests.input]
    insert_at = "rename_fields_empty_objects"
    type = "log"
    [tests.input.log_fields]
      "b.d" = "d"
      "b.e" = "e"
  [[tests.outputs]]
    extract_from = "rename_fields_empty_objects"
    [[tests.outputs.conditions]]
      "renamed_d.equals" = "d"
      "b.d.exists" = false
      "renamed_e.equals" = "e"
      "b.e.exists" = false
      "b.exists" = false
```

The output from this shows:
`output: {"b":{},"message":"","renamed_d":"d","renamed_e":"e","timestamp":"2020-03-18T15:53:51.761362213Z"}`
