### ISSUE TITLE
New `filter` transform

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#2065]
This transform should supersede the `field_filter` transform and use the new conditions sytanx that is used in tests, `swimlanes`, and `transaction`. Ex:

```toml
[transforms.filter]
  type = "filter"
  conditions."app_id.eq" = 2
```
