### ISSUE TITLE
Improve error when a table is passed for a single key

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#2066]
I attempted to use a Vector config that included the new `encoding` table but it was on an older version of Vector. It produced the following configuration error:

```toml
[sinks.company_api_http]
type = "http"
inputs = ["company_api_rename"]
uri = "http://{{ consumer_instance.ec2_private_ip_address }}:{{ consumer_port }}"

[sinks.company_api_http.encoding]
except_fields = ["metadata.shard[0]", "metadata.shard[1]"]
```

The valid config is:

```toml
[sinks.company_api_http]
type = "http"
inputs = ["company_api_rename"]
uri = "http://{{ consumer_instance.ec2_private_ip_address }}:{{ consumer_port }}"
encoding.format = "json"
```

```
Mar 14 17:39:21 ip-10-0-131-11 vector[11926]: Mar 14 17:39:21.233 ERROR vector: Configuration error: "/etc/vector/vector.toml": invalid value: map, expected map with a single key for key `sinks.company_api_http`
```

This is not very descriptive of the error. It should probably be something like:

```
Mar 14 17:39:21 ip-10-0-131-11 vector[11926]: Mar 14 17:39:21.233 ERROR vector: Configuration error: "/etc/vector/vector.toml": invalid value: map, expected map with a single key for encoding `sinks.company_api_http`
```
