### ISSUE TITLE
Non-working Splunk HEC sink example from the documentation

### ISSUE THREAD

**Issue by MadsRC** [timberio/vector#2114]
The [documentation](https://vector.dev/docs/reference/sinks/splunk_hec/) mentions the following configuration for a Splunk HEC sink:

```
[sinks.my_sink_id]
  # General
  type = "splunk_hec" # required
  inputs = ["my-source-id"] # required
  host = "http://my-splunk-host.com" # required
  token = "${TOKEN_ENV_VAR}" # required
  healthcheck = true # optional, default
  host_key = "hostname" # optional, no default
  indexed_fields = ["field1", "field2"] # optional, no default, relevant when encoding = "json"

  # Encoding
  encoding.codec = "json" # required
```

Which, when passed to Vector yields the following error:

```
Mar 22 15:38:38.107  INFO vector: Log level "info" is enabled.
Mar 22 15:38:38.107  INFO vector: Loading configs. path=["/etc/vector/vector.toml"]
Mar 22 15:38:38.111 ERROR vector: Configuration error: "/etc/vector/vector.toml": unknown field `host_key`, expected one of `token`, `host`, `host_field`, `indexed_fields`, `encoding`, `compression`, `batch`, `request`, `tls` for key `sinks.my_sink_id`
```

### My config

```
[sources.my_source_id]
  type = "stdin" # required

[sinks.my_sink_id]
  # General
  type = "splunk_hec" # required
  inputs = ["my-source-id"] # required
  host = "http://my-splunk-host.com" # required
  token = "${TOKEN_ENV_VAR}" # required
  healthcheck = true # optional, default
  host_key = "hostname" # optional, no default
  indexed_fields = ["field1", "field2"] # optional, no default, relevant when encoding = "json"

  # Encoding
  encoding.codec = "json" # required
```

### How I run vector
`vector-test % docker run -v $PWD/vector.toml:/etc/vector/vector.toml:ro -e TOKEN_ENV_VAR=empty timberio/vector:0.8.2-alpine`

### Further info
The error output from Vector mentions `host_field`, which if I change `host_key` to `host_field` I get the following error:

```
Mar 22 15:46:21.235  INFO vector: Log level "info" is enabled.
Mar 22 15:46:21.235  INFO vector: Loading configs. path=["/etc/vector/vector.toml"]
Mar 22 15:46:21.239 ERROR vector: Configuration error: "/etc/vector/vector.toml": unknown variant `codec`, expected `text` or `json` for key `sinks.my_sink_id`
```

**Comment by binarylogic** [comment]
Hi @MadsRC, sorry for the trouble here. We're hoping to get versioned documentation up by tomorrow. If you're on the latest version `0.8.2` this config will work:

```toml
[sources.my_source_id]
  type = "stdin" # required

[sinks.my_sink_id]
  # General
  type = "splunk_hec" # required
  inputs = ["my-source-id"] # required
  host = "http://my-splunk-host.com" # required
  token = "${TOKEN_ENV_VAR}" # required
  healthcheck = true # optional, default
  host_field = "hostname" # optional, no default
  indexed_fields = ["field1", "field2"] # optional, no default, relevant when encoding = "json"

  # Encoding
  encoding = "json" # required
```

Sorry again about the misdirection! We'll get it fixed this week.
