### ISSUE TITLE
Support sending log events to a specific Splunk index

### ISSUE THREAD

**Issue by Alexx-G** [timberio/vector#2116]
I've checked splunk-related issues and documentation and couldn't find any example of dispatching events to a different splunk index.
This feature is quite important when it's necessary to sends logs to an index depending on log type (e.g. a field).

IIRC index (or sourcetype) is just a field of of the raw entry (at the same level as "event").
Here's how it's set in fluentd - https://github.com/splunk/fluent-plugin-splunk-hec#example-3-overwrite-hec-defaults
And in fluent-bit it's necessary to enable sending "raw" events into splunk and structure event data accordingly (group all fields under "event" field, adding the index field etc)
```
    [FILTER]
        Name                   modify
        Match                  {{ .match }}
        Add                    index {{ .index }}
```

Looking at https://github.com/timberio/vector/blob/master/src/sinks/splunk_hec.rs , I believe currently there's no way of adding the index field at the same level as "event" key.

**Comment by Alexx-G** [comment]
@binarylogic @LucioFranco In case there's anything I can help with, providing more info or testing something with splunk, please let me know. My Rust skill are insufficient to contribute with code, so if there's something I can contribute with, will be glad to help.
I have to say that so far our tests with Vector as replacement for fluent* look promising.

**Comment by LucioFranco** [comment]
@Alexx-G looks like #2127 should solve this issue! Should be merged today. Thanks!

**Comment by Alexx-G** [comment]
Thank you so much @LucioFranco @a-rodin 
So it would work like this:
```toml
    [sources.kubernetes]
      type = "kubernetes"

    [transforms.longterm_filter]
      type = "field_filter"
      inputs = ["kubernetes"]
      field = "x"
      value = "y"

    [transforms.default_filter]
      type = "field_filter"
      inputs = ["kubernetes"]
      field = "x"
      value = "bar"

    [sink.splunk]
      type = "splunk_hec"
      inputs = ["longterm_filter"]
      index = "long"

    [sink.splunk]
      type = "splunk_hec"
      inputs = ["default_filter"]
      index = "short"
```

I believe this approach would work great and it's quite declarative (I can totally live with duplicating some data for the splunk sink).
How would be possible to add `sourcetype` support? Usually it's a bit more dynamic than index.
