### ISSUE TITLE
lua multiplying calculation error

### ISSUE THREAD

**Issue by mikhno-s** [timberio/vector#2189]
Hello, again!
Problem is during multiplying floats to 1000 I get odd numbers. For example:

nginx_request_time = 4.081
nginx_request_time = nginx_request_time*1000

and then nginx_request_time will be 4081.0000000000005

Example config:

```toml
...
[sources.nginx_in]
  type = "file"
  include = ["./nginx.log"]
  glob_minimum_cooldown = 1000
  ignore_older = 86400
  max_read_bytes = 4096

[sources.nginx_in.fingerprinting]
    strategy = "device_and_inode"
    fingerprint_bytes = 256
    ignored_header_bytes = 0

[transforms.json]
    type = "json_parser"
    inputs = ["nginx_in"]
    drop_invalid = true

[transforms.transform_ms]
    type = "lua"
    inputs = ["json"]
    source = """
        event["nginx_request_time"] = event["nginx_request_time"]*1000
      """

[transforms.field_transform]
    type = "coercer"
    inputs = ["transform_ms"]

    [transforms.field_transform.types]
            nginx_request_time = "int"
...
```

input:
```json
{ "timestamp": 1585646290.169, "nginx_time_local": "31/Mar/2020:09:18:10 +0000", "nginx_remote_addr": "127.0.0.1", "nginx_http_host": "www.google.com", "nginx_http_referer": "", "nginx_http_user_agent": "some user agent", "nginx_request_uri": "/blabla", "nginx_request_length": 527, "nginx_request_time": 4.081, "nginx_status": 200, "nginx_request_method": "GET", "nginx_content_type": "", "nginx_upstream_content_type": "text/html;charset=utf-8", "nginx_body_bytes_sent": 87713, "nginx_upstream_addr": "10.10.10.27:80", "nginx_response_time": [4.081], "upstream_status": [200], "nginx_country_code": "", "nginx_bytes_sent": 90102 }
```

error log during processing this line:
```
Mar 29 12:44:31.605  WARN transform{name=field_transform type=coercer}: vector::transforms::coercer: Could not convert types. field="nginx_request_time" error
=Invalid integer "4081.0000000000005": invalid digit found in string rate_limit_secs=10
```

same example from poor lua:
<img width="696" alt="Screenshot 2020-03-31 at 14 01 35" src="https://user-images.githubusercontent.com/13031076/78019340-31eaa900-7358-11ea-8953-a532c7ee18a5.png">

---------
I have fixed this already with `math.floor` func, but you should know that.
Also question - why `nginx_request_time` is still string after `event["nginx_request_time"] = event["nginx_request_time"]*1000`. I suppose, that that field shout be float, after multiplying, not a string, as it has been written in logs.

Muchas gracias!
