### ISSUE TITLE
Add "duration" parsing type

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#2250]
Sometimes values within logs will be suffixed by their time unit. For exmaple, the [Heroku router logs](https://devcenter.heroku.com/articles/http-routing#heroku-router-log-format):

```
... service=18ms ...
```

When parsing this with the `logfmt` parser it makes it impossible to parse this into a numeric time unit. I'd like to propose something like:

```toml
[transform.logfmt]
type = "logfmt"

types.service = "duration|ms"
```

That would result in the following:

```js
{
  // ...
  "service": 18
  // ...
}
```

They could also specify other time units to normalize the values:

```toml
[transform.logfmt]
type = "logfmt"

types.service = "duration|s"
```

That would result in the following:

```js
{
  // ...
  "service": 0.018  // ...
}
```
