### ISSUE TITLE
Benchmark glibc

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#2313]
Based on @a-rodin's comments, we should benchmark glibc to see what kind of performance difference this makes over our current approach, which I believe is MUSL right now?

**Comment by a-rodin** [comment]
Yes, currently most of our installation methods use MUSL, although some, such as `nix`, use GLibc.

**Comment by a-rodin** [comment]
I tried to measure performance of Vector for `tokenizer` transform when compiled with musl or glibc, and also with and without additional optimization options.

I tested it using the following configuration file:

`vector.toml`
```toml
[sources.stdin]
  type = "stdin"

[transforms.tokenizer]
  type = "tokenizer"
  inputs = ["stdin"]
  field_names = ["a.b.c", "d.e.f"]

[sinks.console]
  type = "console"
  inputs = ["stdin"]
  encoding = "json"
```

and the measurement was performed by running the following command

```sh
cat /dev/urandom | base64 | ./target/release/vector --config vector.toml  | pv -l > /dev/null
```

for 30 seconds.

Results for this test are below, columns related to both musl and glibc display the total number of processed events.

| `lto`,`codegen-units=1` | **musl** | **glibc** |
| :---: | --- | --- |
| ✖ | 1.05M | 1.00M |
| ✔️| 1.10M | 1.30M |
