### ISSUE TITLE
Lua os.date table is not parsed as Vector timestamp if missing wday, yday, or isdst

### ISSUE THREAD

**Issue by jschaf** [timberio/vector#2331]
The docs say https://vector.dev/docs/reference/transforms/lua/

> If such a table is passed from Lua to Vector, the fields yday, wday, and isdst can be omitted.

However the code requires that `yday`, `wday`, and `isdst` must be present.

https://github.com/timberio/vector/blob/ff4a6dccefc16f56910d49b996f797ef75de1759/src/transforms/lua/v2/interop/util.rs#L22

### Repro

```toml
[transforms.my_transform_id]
  type = "lua"
  inputs = ["my-source-id"]
  version = "2"

  # Hooks
  hooks.process = """
  function (event, emit)
    event.log.timestamp = {year = 2020, month = 1, day = 1, hour = 1, min = 1, sec = 1}
    event.log.message = "<msg>"
    emit(event)
  end
  """

[[tests]]
  name = "test my_transform_id"
  [[tests.inputs]]
    type = "raw"
    insert_at = "my_transform_id"
    value = "<ignore>"
  [[tests.outputs]]
    extract_from = "my_transform_id"
    [[tests.outputs.conditions]]
      type = "check_fields"
      "timestamp.eq" = "2020-01-01T01:01:01Z"
      "message.eq" = "<msg>"
```
