### ISSUE TITLE
Improve the UX for multiple parsing strategies

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#2418]
This is something that I've heard from a number of users:

> Hi. :-) In your docs, you say "A config can have any number of transforms and it's entirely up to you how they are chained together." But there's no real example of how to do that. I have a pretty specific regex transform, but I'd like to match on more than one case, which would include another specific regex. But when running the tests fail because I have more than one.

The best way to solve that currently is to use the `swimlanes` transform and hook up each lane with a specific parser, creating a diamond shape topology. Ex:

```toml
[transform.route]
type = "swimlanes"

[transforms.route.lanes.service_a]
  type = "check_fields" 
  "message.contains" = "service_a"

[transforms.route.lanes.service_b]
  type = "check_fields" 
  "message.contains" = "service_b"

[transforms.parse_service_a]
type = "regex_parser"
inputs = ["service_a"]
regex = "..."

[transforms.parse_service_b]
type = "regex_parser"
inputs = ["service_b"]
regex = "..."

[sinks.print]
type = "console"
inputs = ["parse_service_a", "parse_service_b"]
```

I would like to explore ways to make this simpler. One option is to simply provide "fallback" patterns in all of our parsing transforms. For example, allow users to provide an array of regular expressions in the `regex_parser` transform. Each one is tried until one succeeds.
