### ISSUE TITLE
Does ElasticSearch sink support an ApiKey authentication?

### ISSUE THREAD

**Issue by DmitryRusakovKodiak** [timberio/vector#2433]
Does ElasticSearch sink support an ApiKey authentication? 
At least, I haven't found it in the docs.

**Comment by binarylogic** [comment]
Hi @DmitryRusakovKodiak, you could use the [`headers`](https://vector.dev/docs/reference/sinks/elasticsearch/#headers) option and set the `Authorization` header directly:

```toml
[sinks.es]
type = "elasticsearch"
headers.Authorization = "my-token"
```
