### ISSUE TITLE
New `azure_event_hubs` sink

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#2434]
[Azure Event Hubs](https://azure.microsoft.com/en-us/services/event-hubs/) is like a managed Kafka service:

> Allow existing Apache Kafka clients and applications to talk to Event Hubs without any code changes—you get a managed Kafka experience without having to manage your own clusters.

This suggests that we could wrap the existing `kafka` sink or just document that the `kafka` sink should be used for this.

**Comment by bigredmachine** [comment]
I'm interested in Azure Event Hubs Sink Support.

More specifically from an end to end perspective, looking to scrape an applications prometheus metrics endpoint, convert it into Application Insights JSON metrics format (something like this http://apmtips.com/blog/2017/10/27/send-metric-to-application-insights/), and then send them in compressed batches to an Azure Event hub (preferred, or to Application Insights direct)

Appears the first part is supported.

Let me know if I can help, e.g. QA this out.

**Comment by martinohansen** [comment]
I can't get it working, so just to be sure: is it possible to use the Kafka sink for Azure Event Hub? And if so, is there any caveats i need to be aware of?

**Comment by jamtur01** [comment]
@martinohansen when we say wrap the kafka sink we mean add a sink that reuses the kafka code customized for event hub. The straight kafka source will not directly work I suspect.

**Comment by mdtro** [comment]
For those that are also super excited to get vectordev to send into Azure Event Hub as a sink. I was able to get this working this morning by following @joshmue's source configuration (see #4261) and the Microsoft documentation as inspiration. :)

```yaml
sinks:
  event_hub:
    type: kafka
    inputs: ["kubernetes_logs"]
    bootstrap_servers: "<EVENT_HUB_NAMESPACE>.servicebus.windows.net:9093"
    group_id: '$$Default'
    topic: "<EVENT_HUB_NAME>"
    encoding:
      codec: "json"
    healthcheck:
      enabled: true
    sasl:
      enabled: true
      mechanism: PLAIN
      username: "$$ConnectionString"
      password: "<YOUR_SAS_CONNECTION_STRING>"
    librdkafka_options:
      "security.protocol": sasl_ssl
```

The key part that got it working for me are those last two lines. Make sure the _key_ is surrounding with quotes as it is expecting a string, not a map.

```yaml
    librdkafka_options:
      "security.protocol": sasl_ssl
```
