### ISSUE TITLE
splunk_hec sink doesn't set indexed fields when text encoding is used

### ISSUE THREAD

**Issue by Alexx-G** [timberio/vector#2439]
Currently `indexed_fields` are set only when `json` encoding is used.

The use case is quite simple - some logs must be sent to splunk as plain text (thus setting log message as splunk's `event` field), however it's necessary to set some specific fields that are gonna be indexed and used to filter data later.
It works perfectly fine for `json` codec, since it extracts `indexed_fields` from event and sets them as `fields` property. However, `text` codec only extracts the message from event and sets it as `event` property, without setting `fields` (using `indexed_fields` config).

It seems that `indexed_fields` should work regardless of the used `encoding.coded` since indexed fields just go into a different field.

Here's a sample vector config used to reproduce the issue
```toml
# tested with vector 0.9
[sources.files]
    type = "file"
    include = ["/var/log/*.log"] # required

[transforms.cluster_tagging]
    type = "add_fields"
    inputs = ["files"]

    fields.cluster = "us-east"

[transforms.json_parser]
    type = "json_parser"
    inputs = ["cluster_tagging"]
    field = "message"
    drop_field = true
    drop_invalid = false

[sinks.splunk]
    type = "splunk_hec"
    inputs = ["json_parser"]
    host = "https://splunk.net"
    token = "${SPLUNK_TOKEN}"

    encoding.codec = "text" # replacing it with `json` allows filtering using `cluster` field

    healthcheck = true
    indexed_fields = ["cluster"]
```
