### ISSUE TITLE
The `package-*` Docker compose services do not need `builder-*` Dockerfile's

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#2467]
While cleaning up our Makefile (#2368) I split out build process into 4 steps:

1. Build Vector binary (`build-*` -> `scripts/build.sh`)
2. Package archive (`package-archive-*` -> `scripts/package-archive.sh`)
3. Package deb (`package-deb-*` -> `scripts/package-deb.sh`)
4. Package rpm (`package-rpm-*` -> `scripts/package-rpm.sh`)

Steps 2 - 4 are fairly simple. They just package the Vector binary created in step 1, but they still use the `builder-*` Docker images. For example:

```
package-archive-x86_64-unknown-linux-musl:
    build:
      context: .
      dockerfile: scripts/ci-docker-images/builder-x86_64-unknown-linux-musl/Dockerfile
    environment:
      TARGET: x86_64-unknown-linux-musl
      FEATURES: default-musl
      CARGO_TERM_COLOR: always
    volumes:
      - $PWD:$PWD
      - ./target/x86_64-unknown-linux-musl/cargo/registry:/opt/rust/cargo/registry
      - ./target/x86_64-unknown-linux-musl/cargo/git:/opt/rust/cargo/git
      - ./target/x86_64-unknown-linux-musl/rustup/tmp:/opt/rust/rustup/tmp
    working_dir: $PWD
    command: ./scripts/package-archive.sh
```

These steps should be switched to simpler Docker images that are simpler and faster for the task at hand. We have a `scripts/ci-docker-images/packager-rpm/Dockerfile` and it's probably worth introducing one for creating archives and debs.
