### ISSUE TITLE
Add RegexSet support to regex

### ISSUE THREAD

**Issue by Hoverbear** [timberio/vector#2469]
This is a more specific form of #1477. (and thus related to #2418)

Add `RegexSet` support to the `regex_parser` transform.

The docs for RegexSet are: https://docs.rs/regex/1.3.7/regex/struct.RegexSet.html

This would allow users to match over multiple regexes efficiently and save them some configuration woes.

```toml
[transforms.<transform-id>]
  type = "regex_parser"
  field = "message"
  regexes = [
     '^(?P<host>[\w\.]+) - (?P<user>[\w]+) (?P<bytes_in>[\d]+) \[(?P<timestamp>.*)\] "(?P<method>[\w]+) (?P<path>.*)" (?P<status>[\d]+) (?P<bytes_out>[\d]+)$',
     '^(?P<host>[\w\.]+) - (?P<user>[\w]+) (?P<bytes_in>[\d]+) \[(?P<timestamp>.*)\] "(?P<method>[\w]+) (?P<path>.*)" (?P<status>[\d]+) (?P<bytes_out>[\d]+)$',
     '^(?P<host>[\w\.]+) - (?P<user>[\w]+) (?P<bytes_in>[\d]+) \[(?P<timestamp>.*)\] "(?P<method>[\w]+) (?P<path>.*)" (?P<status>[\d]+) (?P<bytes_out>[\d]+)$',
  ]

[transforms.<transform-id>.types]
  bytes_in = "int"
  timestamp = "timestamp|%d/%m/%Y:%H:%M:%S %z"
  status = "int"
  bytes_out = "int"
```
