### ISSUE TITLE
Wildcards for input list ?

### ISSUE THREAD

**Issue by filippog** [timberio/vector#2550]
Hello, I'm trying out Vector and I'm wondering how to handle configurations with multiple transforms all needing to converge into a single sink.

In other words, my use case is being able to add a transform and have the sink pick it up e.g. based on its name, without changing the sink's input list. Something like being able to say to the sink "use all transforms starting with 'blah' as inputs" without listing all input names explicitly.

Is this possible and/or planned? Thank you!

**Comment by lukesteensen** [comment]
Hi @filippog! We don't currently have any wildcard-like mechanism for `inputs`, but we are definitely interested in finding ways to make our configs work better for users.

If I'm understanding correctly, a glob-like syntax for selecting from all available inputs would meet your needs? For example:

```toml
[sources.src_a]
type = "foo"

[sources.src_b]
type = "bar"

[transforms.tx_c]
type = "baz"
inputs = ["src_*"] # all sources

[transforms.tx_d]
type = "quux"
inputs = ["tx_c"]

[sinks.s]
type = "quuux"
inputs = ["tx_*"] # all transforms
```
