### ISSUE TITLE
sources.socket tcp cpu 100%

### ISSUE THREAD

**Issue by panpan-wu** [timberio/vector#2564]
vector vesrion: 0.9.1-alpine

vectoc.toml

```
[sources.tcp]
  type = "socket"
  mode = "tcp"
  address = "0.0.0.0:7000"
  max_length = 1024000 # 1M
```

When I send a msg that is larger than 1M, vector reports an error:

```
May 08 03:03:08.874  WARN source{name=tcp type=socket}:connection{peer_addr=172.19.0.1}: codec: discarding frame larger than max_length buf_len=1048576 max_len=1024000 rate_limit_secs=30
```

This behavior is right, what I don't known is why the CPU usage reaches 100%.

**Comment by panpan-wu** [comment]
![Uploading 截屏2020-05-08上午11.49.18.png…]()

**Comment by bruceg** [comment]
I can confirm this degenerate behavior for large messages. This behavior appears to be worse if `max_length` is smaller too. I am investigating.

**Comment by bruceg** [comment]
For the record, here is my reproducer. My config:
```toml
[sources.tcp]
  type         = "socket"
  mode         = "tcp"
  address      = "`127.0.0.1:9000"
[sinks.stdout]
  inputs       = [ "tcp" ]
  type         = "console"
  encoding     = "text"
```
On a command line, run:
```
printf '%01000000d\n' 0 | nc localhost 9000
```
After five minutes, Vector still shows 100% CPU. Worse yet, it spawns a new thread per connection, so this is 100% CPU per connection.
