### ISSUE TITLE
Bearer authentication strategy support?

### ISSUE THREAD

**Issue by fanatid** [timberio/vector#2599]
Currently only `basic` authentication strategy supported through config options.

There also a question, which value should be used if config have valid `auth` and `Authorization` header? Should be validation error be thrown if two options set at one time and have different values?

cc @grantisdale

**Comment by binarylogic** [comment]
Hi @fanatid which component is this related to? If it's the `http` sink users can set custom headers via the `headers` option:

```toml
[sinks.http]
  type = "http"
  headers.Authorization = "Bearer <token>"
```
