### ISSUE TITLE
TLS PEM cert chain is not correctly being used

### ISSUE THREAD

**Issue by suvl** [timberio/vector#2612]
Hi! I have this `ca.pem` file that has 6 CA certs belonging to two chains (so there's a chain with a root CA and an intermediate CA, then a second chain with a root CA and two intermediate CAs) and when I try validating my client cert with it I get:

```
❯ openssl verify -CAfile cas/foo-certs.pem certs/cert.pem
certs/cert.pem: OK
```

but then when I set this at the config:

```toml
    [sources.tls]
      type = "socket"
      address = "0.0.0.0:6514"
      mode = "tcp"
      tls.enabled = true
      tls.crt_path = "/workdir/cert.pfx"
      tls.ca_path = "/crt/ca.pem"
      tls.verify_certificate = true
```

I keep getting `"remote error: tls: unknown certificate authority"` but these are the same files. 'Tis a bug, perhaps? Ofc setting `verify_certificate = false` works.
