### ISSUE TITLE
Loki + Kubernetes labels question

### ISSUE THREAD

**Issue by uhthomas** [timberio/vector#2710]
Hey! I've been trying to setup Vector on my cluster, but am struggling with the config as it seems various resources are outdated, or unclear as to how to approach Loki and Kubernetes.

Loki config:
```
data_dir = "/var/lib/vector"
[sources.kubernetes]
  type = "kubernetes"
[sinks.loki]
  type = "loki"
  inputs = ["kubernetes"]
  endpoint = "http://loki:3100"
  encoding.codec = "json"
```

The output of running this is:
```
➜  ~ kubectl -n vector logs vector-4d5np vector
May 29 18:27:28.838  INFO vector: Log level "info" is enabled.
May 29 18:27:28.838  INFO vector: Loading configs. path=["/etc/vector/vector.toml"]
May 29 18:27:28.841 ERROR vector: Configuration error: "/etc/vector/vector.toml": missing field `labels` for key `sinks.loki`
```

What sort of labels should I be putting the config? 

How do I extract k8s labels and ship them to Loki?

See Loki's [`fluent-bit`](https://github.com/grafana/loki/blob/master/production/helm/fluent-bit/values.yaml#L22) config for what sorts of labels (I assume) should be added.

**Comment by pySilver** [comment]
this is confusing, im also having troubles running loki integration with grafana cloud

**Comment by MOZGIII** [comment]
From the `loki` [docs](https://github.com/grafana/loki/blob/master/docs/overview/README.md#overview-of-loki):

> Unlike other logging systems, Loki is built around the idea of only indexing labels for logs and leaving the original log message unindexed. This means that Loki is cheaper to operate and can be orders of magnitude more efficient.

We're currently working on a new integration with Kubernetes! Please take a look #2653 - it will be shipping soon.

If you can't wait, you can try a development build, for instance from here: https://github.com/timberio/vector/pull/2653#issuecomment-643525091.

With our new implementation, you'll be able to configure Vector like this:

```toml
data_dir = "/var/lib/vector"

[sources.kubernetes_logs]
  type = "kubernetes_logs"

[sinks.loki]
  type = "loki"
  inputs = ["kubernetes_logs"]
  endpoint = "http://loki:3100"
  encoding.codec = "json"
  [values]
    kubernetes_pod_name = "{{ kubernetes.pod_name }}"
    kubernetes_pod_namespace = "{{ kubernetes.pod_namespace }}"
    kubernetes_pod_uid = "{{ kubernetes.pod_uid }}"
```
