### ISSUE TITLE
Parsing with lua

### ISSUE THREAD

**Issue by Teosof** [timberio/vector#2730]
I would like your help with vector.dev. I could not convert my log file test.log containing:
```
<i key = "key1"
    host = "127.0.0.1"
    >
<request date="13.01.2020">
</request>
</i>
```
As a result, I would like to get json:
`{key: key1, host: 127.0.0.1, date="13.01.2020" ...}`

I used lua for these tasks, but the examples from the site are only for csv files, which do not help. 
Could you please help me and explain what hooks.process will look like? Please advise a module on lua that would solve this problem.
Sorry to distract you, but you are really making a cool product that I just can't figure out :)

**Comment by Teosof** [comment]
Hi, @bruceg. Could you help me?

**Comment by Hoverbear** [comment]
Hey @Teosof , this looks like XML! I'm guessing you can use https://github.com/manoelcampos/xml2lua for this. I suggest using a strategy like https://vector.dev/guides/advanced/custom-aggregations-with-lua/#keep-all-code-together

**Comment by Teosof** [comment]
@Hoverbear, thanks for the tip! I used xml2lua and the article, but unfortunately did not get the results. My log file is disguised as an xml file: I do not have a global tag.
I would like to receive:
`<lua><i key = "key1" host = "127.0.0.1"><request date="13.01.2020"></request></i></lua>`
An important aspect. The classic xml file looks like this:
`<i><key>key1</key><host>127.0.0.1</host><request><date>13.01.2020</date></request></i>`
But my log file has fields inside the tag itself. What should I do?

**Comment by Hoverbear** [comment]
@Teosof Could you share the LUA code you tried to use?

**Comment by Teosof** [comment]
@Hoverbear, here is my code below. Sorry for not sending earlier:
```
source = """
    xml2lua = require("xml2lua")
    handler = require("xmlhandler.tree")
    column_names = {
        "key",
        "host",
        "date"
    }
"""
hooks.process = """
    function(event, emit)
        parser = xml2lua.parser(handler)
        l = "<lua>".. event.log.message.. "</lua>"
        parser:parse(l)
        event.log.message = nil

        for column, value in ipairs(handler.root.parser.i) do
            event.log["key"] = value._attr.key
            event.log["host"] = value._attr.host
            event.log["date"] = value._attr.date
        end

        emit(event)
    end
"""
```
Here is the error I received: 

> ERROR transform{name=inside type=lua}: vector::transforms::lua::v2: error=Runtime error in "hooks.process" function: runtime error: /etc/vector/xml2lua/xml2lua.lua:92: Unbalanced Tag (/lua) [char=16]

**Comment by Hoverbear** [comment]
This works for me!

![image](https://user-images.githubusercontent.com/130903/84807286-df667380-afbb-11ea-88ea-21914853f621.png)


```toml
[sources.in]
  type = "stdin" # required

[transforms.trans]
  # General
  type = "lua" # required
  inputs = ["in"] # required
  version = "2" # required
  # Hooks
  search_dirs = [
    "xml2lua/"
  ]
  source = """
    local xml2lua = require("xml2lua")

    local column_names = {
        "key",
        "host",
        "date"
    }

    function process(event, emit)
        local handler = require("xmlhandler.tree")
        local parser = xml2lua.parser(handler)

        parser:parse(event.log.message)

        event.log.date = handler.root.i.request.date
        event.log.key = handler.root.i._attr.key
        event.log.key = handler.root.i._attr.host

        emit(event)
    end
  """
  hooks.process = "process"

[sinks.sinkc]
  # General
  type = "console" # required
  inputs = ["trans"] # required
  target = "stdout" # optional, default

  # Encoding
  encoding.codec = "json" # required
```
