### ISSUE TITLE
Inconsistent handling of dots in field names by json_parser

### ISSUE THREAD

**Issue by tyrken** [timberio/vector#2814]
When the `json_parser` transform unpacks JSON with dots in a key name, then it handles field names containing dots inconsistently, e.g. see the below config/setup/output.  I'm working around this for now but hope it can be fixed & isn't a designed-in ambiguity...

```toml
# Convenience
data_dir = "/tmp"

[sources.in]
  type = "file"
  include = ["./input.log"]
  start_at_beginning = true
  # Make vector read the small input file
  fingerprinting.strategy = "device_and_inode"

[transforms.t1]
  inputs = ["in"]
  type = "json_parser"
  drop_field = true
  drop_invalid = false
  field = "message"
  # Uncomment the target_field to see "correct" behaviour when inserting always under a key
  # target_field = "json"

[sinks.out]
    type = "console"
    inputs = ["t1"]
    target = "stdout"
    encoding = "json"
```

When you run v0.9.2 vector (on Linux FWIW) with the below input file.

``` bash
echo '{"field.with.dots": true, "sub_field": {"another.one": false}}' >input.log
```

... you get the below result (pretty printed for clarity), noting "field.with.dots" is now a three-level hierarchy not a string:

```json
{
    "field": {
        "with": {
            "dots": true
        }
    },
    "file": "input.log",
    "host": "my-host-name",
    "source_type": "file",
    "sub_field": {
        "another.one": false
    },
    "timestamp": "2020-06-15T08:14:00.312871271Z"
}
```

If you uncomment the target_field to make sure it's always not-inserting-at-root then the problem disappears.
