### ISSUE TITLE
GCP PubSub Sink: Allow specifying max messages

### ISSUE THREAD

**Issue by joscha-alisch** [timberio/vector#2826]
GCP PubSub has a limit on how many messages can be included in one publication batch. At the moment this limit is set at 1000 messages. 

It doesn't seem to be documented on their main PubSub docs but we encountered this and it's also written down here for the python client: https://googleapis.dev/python/pubsub/latest/publisher/index.html#:~:text=Pub%2FSub%20accepts%20a%20maximum,can%20not%20exceed%2010%20megabytes.

The GCP PubSub sink allows specifying the max batch size in bytes, but not the max number of messages in a batch as far as I can tell. 

Would it be possible to introduce this as a new parameter to batch? Something like:
```toml
[sinks.my_pubsub_sink]
  type = "gcp_pubsub" # required
  batch.max_events = 1000 # optional, default
```

Our workaround at the moment is to use max_size and calculate with our average message size when the batch should reach around 1000 events. But that is sometimes error-prone, so we are either losing events or sending very small batches.
