### ISSUE TITLE
Lua transform timers are not correctly documented

### ISSUE THREAD

**Issue by PrivateRookie** [timberio/vector#2991]
when setting timer for lua transform, I got following error

> data did not match any variant of untagged enum LuaConfig for key `transforms.remove_peak`

version: 0.9.2
platform: ubuntu

I have tried timer example in [doc](https://vector.dev/docs/reference/transforms/lua/), and got the same error.
How to fix this error ?

**Comment by Hoverbear** [comment]
Unfortunately, those docs are wrong! :(

Can you try this? 

```toml
data_dir = "/var/lib/vector/"

[sources.source0]
max_length = 102400
type = "stdin"



[transforms.transform0]
  type = "lua"
  inputs = ["source0"]
  version = "2"

  hooks.process = """
  function (event, emit)
    emit(event)
  end
  """

  [[transforms.transform0.timers]]
  handler = """
  function (emit)
    print "Hello!"
  end
  """
  interval_seconds = 1 # required, seconds

[sinks.sink0]
healthcheck = true
inputs = ["transform0"]
type = "console"
encoding = "json"

[sinks.sink0.buffer]
type = "memory"
max_events = 500
when_full = "block"
```
