### ISSUE TITLE
Kubernetes: Windows nodes support

### ISSUE THREAD

**Issue by MOZGIII** [timberio/vector#2997]
See [RFC](https://github.com/timberio/vector/blob/master/rfcs/2020-04-04-2221-kubernetes-integration.md) for the context.

Kubernetes has support for `Node`s running Windows and Windows Containers. It's an actual Windows OS running `kubelet`, not the Kubernetes running in the Linux VM under "Docker for Windows" (that should already work fine).

The main problem with supporting Windows is not the implementation - it's just a few changes that are very easy to grasp - but the ability to test the quality continuously after we claim we support it.
So, pretty much, we need a way to run E2E tests on a Windows cluster within our CI system.

The easiest way to get such a cluster is to use a managed cloud on Azure. The good thing is it's probably what our users would use in the first place.

However, it's not obvious if this is a highly demanded feature.

> If you're reading this and you need Vector for Windows nodes - add your :+1: to this issue!

**Comment by Hoverbear** [comment]
(Side note, if you're using Vector with windows, do please let us know and let us know if we can improve support! See also #2719 )

**Comment by gattytto** [comment]
yes it is demanded, it would also be nice to have a headless shim-only windows node for the runhcs so to have less complexity on the windows node.

**Comment by protoz** [comment]
I am currently running EKS with linux nodes but our users have a need for Windows containers.  Our current work around is to use fluentbit on Windows to ship to a Vector aggregator then on to our long term storage but, it would be ideal to keep it all under one system

**Comment by djboris9** [comment]
FYI. We are currently rolling out Vector on Windows kubelets to collect Pod logs, no windows event log. So far there were no issues seen on around 25 nodes running a couple of weeks now.

We've built the image `djboris/vector-windows:0.46.1` from https://github.com/djboris9/vector-windows, if it's ok and our tests are successful, I can try to make a PR for building Windows docker images in this repository. But I don't see a way for E2E testing this in CI. 

This is the basic configuration we're using:
```yaml
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vector-agent-win
  labels:
    app: vector-agent-win
spec:
  selector:
    matchLabels:
      app: vector-agent-win
  template:
    metadata:
      labels:
        app: vector-agent-win
    spec:
      serviceAccountName: vector-agent
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - windows
                  - key: node.kubernetes.io/windows-build
                    operator: In
                    values:
                      - '10.0.20348'
      tolerations:
      - effect: NoSchedule
        key: os
        operator: Equal
        value: "windows"
      containers:
      - name: vector
        image: djboris/vector-windows:0.46.1
        args: ["--watch-config", "--config-dir", "/etc/vector/"]
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: VECTOR_SELF_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        livenessProbe:
          httpGet:
            path: /health
            port: 8686
          initialDelaySeconds: 10
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8686
          initialDelaySeconds: 10
          periodSeconds: 3
        resources:
          requests:
            memory: 4Mi
            cpu: 5m
          limits:
            memory: 256Mi
            cpu: 500m
        volumeMounts:
        - name: config
          mountPath: /etc/vector
        - name: var-log
          mountPath: /var/log
        - name: var-lib-vector
          mountPath: /var/lib/vector/
      volumes:
      - name: config
        configMap:
          name: vector-agent
      - name: var-log
        hostPath:
          path: /var/log
      - name: var-lib-vector
        hostPath:
          path: /var/lib/vector
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-agent
data:
  vector.yaml: |
    # This is persisted for the agent on the host
    data_dir: /var/lib/vector
    api:
      enabled: true
      address: "0.0.0.0:8686"

    sources:
      k8s:
        type: kubernetes_logs
        fingerprint_lines: 10
        ignore_older_secs: 600
        timezone: Europe/Zurich
      k8s_host:
        type: file
        include:
          - /var/log/kubernetes/*
#.....
```
