### ISSUE TITLE
Should vector shutdown if the stdin source is exhausted/exited with an error?

### ISSUE THREAD

**Issue by LukeMathWalker** [timberio/vector#3031]
Facing some interesting behaviour when using the `stdin` source with `vector`.
Consider this dummy setup:
```bash
sleep 5 | vector --config vector.toml
```
where
```toml
data_dir = "/var/lib/vector/"
dns_servers = []

[log_schema]
message_key = "message"
timestamp_key = "timestamp"
host_key = "host"

[sources.source0]
max_length = 102400
type = "stdin"

[sinks.sink0]
healthcheck = true
inputs = ["source0"]
type = "console"

[sinks.sink0.buffer]
type = "memory"
max_events = 500
when_full = "block"
```
(output of `vector generate stdin//console`).

I would expect `vector` to exit once the piped command exits (roughly after the 5 seconds sleep time), but it does not seem to be the case: `vector` will keep running indefinitely.

The same happens if the piped command exits with a non-zero exit code, e.g.:
```bash
exit 1 | vector --config vector.toml
```
Even using a proper bash script with `pipefail` does not cause `vector` to exit when the piped command fails, e.g.
```bash
#!/bin/bash
set -euxo pipefail

exit 1 | vector --config vector.toml
```

This can be fairly problematic when piping the output of an application inside `vector` to ship logs: we'd like to let the application crash to have it restarted by our orchestrator (e.g. Kubernetes) but `vector` is going to be keep the container running.
Any solution to this dilemma?
