### ISSUE TITLE
Feature request: Add support for grouping parsed JSON fields under a specific field

### ISSUE THREAD

**Issue by AlexGustafsson** [timberio/vector#3054]
---
name: Feature Request
about: Suggest a new feature or other enhancement.
labels: Type: Enhancement
---

### Current Vector Version

```
Docker, 0.9.1-alpine
```

### Use-cases

1. To mitigate the potential merge collisions mentioned here: https://vector.dev/docs/reference/transforms/json_parser/#merge-conflicts.
2. To help structure the result of logs for services such as Traefik and Kibana which provide many values with names such as `type`, `req`, `tags` etc.

### Attempted Solutions

Not attempted, but the runtime transform could be used with a third-party JSON library. 

### Proposal

JSON Parser Transform:
```toml
[transforms.parse-json]
  type = "json_parser"
  inputs = ["in"]
  drop_field = true
  drop_invalid = true
  field = "message"
  # New optional value
  namespace = "my.log.namespace"
```

JSON log:
```
{"id": "1", "foo": "2"}
```

JSON output:
```
{
  "timestamp": "2020-07-13T14:32:13+0000",
  "my": {
    "log": {
      "namespace": {
          "id": "1",
          "foo": "2",
       }
    }
  }
}
```
