### ISSUE TITLE
Move field to root of json

### ISSUE THREAD

**Issue by defusevenue** [timberio/vector#3061]
We're just getting started with Vector and it's been fantastic so far. One problem we ran into is that we only need the contents of `message` to be sent to our sink. We tried to using the rename_fields transform but can't the contents of `message` to move to the root of the json. Is this possible with the rename_fields transform? 

We did see that a Lua transform is available. It would be easy to implement in Lua but we wanted to know if it's possible without it, since the transform is in beta and considered not production ready.

Example:

From this:
```
{
    "message: {
	"foo": "bar"
    }
}
```
To this:
```
{
   "foo": "bar"
}
```

**Comment by defusevenue** [comment]
I found out that the json transform does this for you. 

For those who stumble onto the same issue in the future, here is the solution:
```toml
[transforms.json]
  type = "json_parser"
  inputs = ["source"]
  drop_field = true
  drop_invalid = true
  field = "message"
```
