### ISSUE TITLE
Coercer not recognizing timestamp format

### ISSUE THREAD

**Issue by defusevenue** [timberio/vector#3071]
The Coercer transform doesn't seem to recognize the timestamp format `%F %T` which corresponds to `YYYY-MM-DD HH:MM:SS`. I was able to recreate this issue on a new Vector instance. I've posted the configuration and results below.

As you can see below, in the first console output the original value of the field `date` is `2020-07-15 02:03:08` which satisfies the timestamp format, but in the second console output the value is converted to `2020-07-15T02:03:08Z`.

Is my configuration or understanding of the timestamp format incorrect? 

Thank You!

Config:
```toml
[sources.http]
  # General
  type = "http"
  address = "0.0.0.0:80"
  encoding = "json"

[transforms.coercer]
  # General
  type = "coercer"
  inputs = ["http"]
  drop_unspecified = true

  # Types
  types.date = "timestamp|%F %T"

[sinks.console]
  # General
  type = "console"
  inputs = ["http"]
  target = "stdout"

  # Encoding
  encoding.codec = "json"

[sinks.console2]
  # General
  type = "console"
  inputs = ["coercer"]
  target = "stdout"

  # Encoding
  encoding.codec = "json"
```

Console Output
> vector-agent      | {**"date":"2020-07-15 02:03:08"**,"source_type":"http","timestamp":"2020-07-15T10:36:48.358015400Z"}
> vector-agent      | {**"date":"2020-07-15T02:03:08Z"**}
