### ISSUE TITLE
New `remap` transform v1

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#3119]
The first version is mostly focused on laying a solid foundation that:

* Integrates properly with our event model
* Produces user-friendly error messages

**Comment by Jeffail** [comment]
There are two major remaining features that ought to be added to the remap transform which in my view would otherwise block it from replacing all the current mapping transforms. Those two features are type coercion and error handling.

Type coercion is straight forward and in order to fit this in nicely with our existing syntaxes I would suggest we start small and add query functions (one for each type) that take a path parameter, it would look like this:

```toml
mapping = """
  .id = string(.id)
  .bytes_in = int(.bytes_in)
  .bytes_out = int(.bytes_in)
  .timestamp = timestamp(.timestamp, "%d/%m/%Y:%H:%M:%S %z")
  .status = int(.status)
"""
```

However, we're now introducing more ways in which our mappings might fail, and therefore it would be nice to be able to specify per-field how (and whether) to recover in the event where these type coercions cannot be performed. I suggest we allow an optional second parameter for these functions that defines the default value to use if for any reason the coercion is going to fail (the field doesn't exist, its value cannot be converted, etc). It would look like this:

```toml
mapping = """
  .id = string(.id)
  .bytes_in = int(.bytes_in, 0)
  .bytes_out = int(.bytes_in, 0)
  .timestamp = timestamp(.timestamp, "%d/%m/%Y:%H:%M:%S %z")
  .status = int(.status, 200)
"""
```

Note that in this example we don't specify a default for the field `.id` because we want the mapping to fail entirely if the id cannot be parsed. We also won't have defaults for `timestamp` initially as timestamp literals are probably worthy of their own RFC in order to agree on the syntax. However, you could do something like this as a short-term work around:

```txt
  .timestamp = timestamp(string(.timestamp, "11/10/1946:12:00:00 -0400"), "%d/%m/%Y:%H:%M:%S %z")
```

This syntax would also solve general purpose error handling as it would allow users to specify type assertions and also fallback values in the case where the target paths don't exist.
