### ISSUE TITLE
Add explicit configuration for HEC sourcetype field

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#3250]
https://github.com/timberio/vector/pull/2318 added automatic setting and propagation of a `sourcetype` field in the Splunk HEC sink based on its source; however, this caused issues with the humio sink (which uses the Splunk HEC compatible endpoint) (https://github.com/timberio/vector/issues/3082#issuecomment-665148156) as humio attempts to parse the message differently based on the sourcetype. For example, a `sourcetype` of `syslog` causes humio to attempt to parse the incoming message as a syslog message whereas we are sending a JSON payload.

Splunk takes the same approach for `sourcetype`; attempting to handle the incoming message format differently depending on the type (https://docs.splunk.com/Documentation/Splunk/8.0.5/Data/Listofpretrainedsourcetypes).

In Splunk parlance, I think our `sourcetype` would typically be `_json`.

To allow users to set their own `sourcetype` for routing and parsing purposes I propose we:

* Drop the automatic setting of `sourcetype` as this is unlikely to be set to a value that would work out-of-the-box with Splunk or Humio
* Add a `sourcetype` field to the `humio` and `splunk` sink types that can be use to set a type

The configuration would then look like:

```toml
[sinks.my_sink_id]
  # General
  type = "splunk_hec" # required
  inputs = ["my-source-or-transform-id"] # required
  healthcheck = true # optional, default
  host = "http://my-splunk-host.com" # required
  host_key = "hostname" # optional, no default
  indexed_fields = ["field1", "field2"] # optional, no default, relevant when encoding = "json"
  token = "${SPLUNK_HEC_TOKEN}" # required
  sourcetype = "_json" # optional, no default, will be automatically be set by the provider
```

By default, we will not send a `sourcetype` and allow the HEC provider set it.

**Comment by binarylogic** [comment]
I'm curious if it would be simpler, and more flexible, to make `sourcetype` templateable?

```toml
sourcetype = "_json"
sourcetype = "{sourcetype}"
```
