### ISSUE TITLE
Add configuration for HEC source field

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#3251]
In Splunk parlance, I think our `sourcetype` would typically be `_json`.

To allow users to set their own `sourcetype` for routing and parsing purposes I propose we:

* Add a `source` field to the `humio` and `splunk` sink types that can be use to set the source

The configuration would then look like:

```toml
[sinks.my_sink_id]
  # General
  type = "splunk_hec" # required
  inputs = ["my-source-or-transform-id"] # required
  healthcheck = true # optional, default
  host = "http://my-splunk-host.com" # required
  host_key = "hostname" # optional, no default
  indexed_fields = ["field1", "field2"] # optional, no default, relevant when encoding = "json"
  token = "${SPLUNK_HEC_TOKEN}" # required
  source = "/var/log/syslog" # optional, no default, will be automatically be set by the provider
```

By default, we will not send a `source` and allow the HEC provider set it.
