### ISSUE TITLE
GCP Cloud Storage Sink Ignores batch.max_bytes Setting

### ISSUE THREAD

**Issue by gteshome** [timberio/vector#3263]
Regardless of what I set `batch.max_bytes`, Vector writes the default 10 MB sized file to the GCP Cloud Storage (GCS) bucket. Currently I have `batch.max_bytes = 104857600`, which should be 100 MB. But, when I send a 45 MB file to Vector via the syslog source, 5 files are written to GCS bucket: four 10 MB files and one 5 MB file. What's more confusing is that `batch.timeout_secs` is honored by Vector.

My vector.toml is below:

```toml
[sources.my_source_id]
  type = "syslog" # required
  address = "0.0.0.0:514" # required, required when mode = "tcp" or mode = "udp"
  mode = "tcp" # required
[sinks.gcs_id]
  type = "gcp_cloud_storage" # required
  inputs = ["my_source_id"] # required
  bucket = "my-bucket" # required
  compression = "none" # optional, default
  credentials_path = "/full/path/to/creds.json" # optional, no default
  healthcheck = true # optional, default
  encoding.codec = "text" # required
  key_prefix = "my-bucket/date=%F/" # optional, default
  batch.max_bytes = 104857600 # batch  
  batch.timeout_secs = 60 # max age of batch before flush
```
