### ISSUE TITLE
New `journald` source

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#327]
This is a new source that makes it easy to ingest journald entries. The [Rust `systemd` library](https://docs.rs/systemd/0.4.0/systemd/journal/struct.Journal.html) should make this easier.

### Specification

The first order of business for this source is to spec it out. I would like to start with an investigative process filling in the blanks in my comment below. The questions I have (I'm sure I'm missing some):

1. How do we filter by service? Does the `JournalRecord` type include the service source? And would this be a post ingestion filter?
2. What else can we filter by?
3. How does checkpointing / cursor position work? Ex: If we restart Vector how do we resume where we left off?

## Prior art

* Journalbeat: https://github.com/elastic/beats/issues/8323 & https://github.com/elastic/beats/tree/master/journalbeat
* Fluentbit: https://docs.fluentbit.io/manual/input/systemd

**Comment by binarylogic** [comment]
@bruceg I'd like for you to start by finishing off the following spec. Please many any adjustments you feel are necessary. There are a number of behavior questions we have (as noted in the original issue) that I would like to solidify before we begin work:

---

## Specification

### Config Example

```toml
[sources.journald]
  type = "journald"
  paths = ["/path/to/journal/dir"]
  include_matches: [] # ex: ["systemd.unit=nginx"]
  exclude_matches = [] # # ex: ["systemd.unit=bad_service"]
  current_runtime_only = true # default
  local_only = true # default
```

### Requirements

- [ ] `paths` - `[string]` - A list of directories or journal files to monitor.
- [ ] `include_matches` - `[string]` - A whitelist of filters/matches to include. If blank all entries are accepted.
- [ ] `exclude_matches` - `[string]` - A blacklist of filters/matches to exclude. Defaults to none. Note: this takes precedence over `include_matches`.
- [ ] `current_runtime_only` - `boolean` - if `true`, include only journal entries from the current boot. If `false`, include all entries.
- [ ] `local_only` - `boolean` - if `true`, include only journal entries originating from localhost. If `false`, include all entries.
