### ISSUE TITLE
Better error message when topology components don't match supported types

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#3273]
I recently helped a user fix a topology error, where they had a `prometheus` source (metrics) connected to a `rename_fields` transform (logs). They received the following error:

```
Jul 30 19:44:26.948 ERROR vector::topology: Configuration error: Data type mismatch between aws_meta (Log) and aws_env (Metric)
Jul 30 19:44:26.948 ERROR vector::topology: Configuration error: Data type mismatch between mystique (Metric) and aws_meta (Log)
```

I think we can improve this error message and also link to our docs explaining what it is (ref #978).

**Comment by LinTechSo** [comment]
HI, same issue, any updates?

**Comment by jszwedko** [comment]
> HI, same issue, any updates?

Can you share your configuration? Seemingly you have two incompatible components connected.

**Comment by omers** [comment]
Same Issue here.

```
---
sources:
  data_in:
    type: http_server
    address: 0.0.0.0:8686
    encoding: json
    method: POST
    path: /influx
    path_key: influx
transforms:
  sanity:
    type: remap
    inputs:
      - data_in
    source: |
      .timestamp = to_unix_timestamp(now())
sinks:
  to_influx:
    type: influxdb_metrics
    inputs: 
      - data_in
    bucket: sls
    endpoint: http://**:8086
    token: "***"
    org: ***
    batch:
      timeout_secs: 1
```

```
curl localhost:8686/influx -XPOST -d '{
  "metric": {
    "counter": {
      "value": 1.5
    },
    "kind": "incremental",
    "name": "logins",
    "tags": {
      "host": "my-host.local"
    }
  }
}'
```

Error:
```
2023-08-13T13:38:23.632958Z ERROR vector::cli: Configuration error. error=Data type mismatch between data_in (Log) and to_influx (Metric)
```
