### ISSUE TITLE
The `statsd` sink should allow a  FQDN

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#3277]
It's likely this issue will overlap with the solution proposed in #3269 (wrapping the `socket` sink).

Currently, the `statsd` sink's `address` option takes an IP address. It should also support [fully qualified domain names](https://en.wikipedia.org/wiki/Fully_qualified_domain_name). Ex:

```toml
[sinks.my-statsd-sink]
type = "statsd"
address = "my.host.example:1234"
```
