### ISSUE TITLE
Inspect events as they are processed

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#342]
We need a way to inspect events as they flow through the pipeline. This is useful for debugging. Ideas to accomplish this:

1. Adding a shared `print` option to every source, transformer, and sink. This would print the record _after_processing it.
2. A global `print` option that will print records throughout the entire pipeline.
3. A `print` transformer that can be manually added to the pipeline.

Requirements:

- [ ] There should be a way to sample records. Ex: only printing every 1,000th record. This should be a required option given that this could take down a production pipeline if not specified.
- [ ] The records should be printed in JSON encoded format.

**Comment by Jeffail** [comment]
Whatever we choose to add should beat this for convenience and performance:

```toml
[transforms.foo]
  type = "coercer"
  inputs = ["something"]
  # Do some complex stuff that we'd like to expose

[transforms.sample_foo]
  type = "sampler"
  inputs = ["foo"]
  rate = 10

[sinks.print_sampled_foo]
  type = "console"
  inputs = ["sample_foo"]
  target = "stdout"
```

^ Disclaimer: I haven't actually tried that.
