### ISSUE TITLE
Sending `internal_metrics` to `statsd` sink results in only namespace being sent

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#3488]
From gitter: https://gitter.im/timberio-vector/community?at=5f3b9c2478f4a801800fe861

### Vector Version

```
vector 0.11.0 (g0d0ce76 x86_64-unknown-linux-gnu 2020-08-18)
```

### Vector Configuration File

```toml
[sources.generator]
  type = "generator"
  lines = ["Line 1", "Line 2"]
  batch_interval = 1

[transforms.transform]
  type = "add_fields"
  inputs = ["generator"]
  overwrite = true
  fields.string_field = "string value"

[sources.internal_metrics]
  type = "internal_metrics"

[sinks.statsd]
  type = "statsd"
  inputs = ["internal_metrics"]
  namespace = "test"
  address = "127.0.0.1:8125"

[sinks.stdout]
  type = "console"
  inputs = ["internal_metrics", "transform"]
  target = "stdout"
  encoding = "json"
```

### Debug Output

https://gist.github.com/jszwedko/5bda09378d913d1d4eb22c9c3afc6f3e

### Expected Behavior

Metrics are sent to statsd sink.

### Actual Behavior

Only the namespace is sent to the statds sink.

### Example Data

Output of `nc -l -u -p 8125`:

```
test.test.
```
