### ISSUE TITLE
"timestamp too new" when using vector for Syslog forwarding to loki (like "https://vector.dev/guides/integrate/sources/syslog/loki/")

### ISSUE THREAD

**Issue by markus7811** [timberio/vector#3522]
### Vector Version
```
vector 0.10.0 (g0f0311a x86_64-unknown-linux-musl 2020-07-22)
```

### Vector Configuration File
```toml
[sources.syslog_tcp]
  address = "0.0.0.0:1514" # required, required when mode = "tcp" or mode = "udp"
  mode = "tcp" # required
  type = "syslog" # required
[sources.syslog_udp]
  address = "0.0.0.0:514" # required, required when mode = "tcp" or mode = "udp"
  mode = "udp" # required
  type = "syslog" # required

[sinks.out]
  # General
  endpoint = "http://loki-stack.monitoring-and-logging.svc.cluster.local:3100" # required
  inputs = ["syslog_tcp", "syslog_udp"] # required
  type = "loki" # required

  # Labels
  labels.key = "value" # example
  labels.key = "{{ event_field }}" # example
```

### Debug Output
I don't think we don't need further output ... i think the problem is obvious
```
 Aug 21 22:47:28.654  WARN sink{name=out type=loki}:request{request_id=261}: vector::sinks::util::retries2: request is not retryable; dropping the request. reason=response status: 400 Bad Request                                                                                                                                                                                                                                      ││ Aug 21 22:47:28.654 ERROR sink{name=out type=loki}:request{request_id=261}: vector::sinks::util::sink: Response wasn't successful. response=Response { status: 400, version: HTTP/1.1, headers: {"content-type": "text/plain; charset=utf-8", "x-content-type-options": "nosniff", "date": "Fri, 21 Aug 2020 22:47:28 GMT", "content-length": "89"}, body: b"entry for stream '{agent=\"vector\"}' has timestamp too new: 2020-08-22 00
```

### Expected Behavior
Logs should be accepted by loki

### Actual Behavior
So, it is  2020-08-22 00:47 (here in germany) and loki refuses my messagees, that were send from vector with timestamp Fri, 21 Aug 2020 22:47:28 GMT. But i think vector should

### Example Data
i m curious to see the log lines ... i tried vector to see what unifi and vigor/draytek are logging - so sorry, no idea.

### Additional Context
Running vector and loki-stack inside microk8s with metallb bgp service over my unifi router.
