### ISSUE TITLE
Socket sinks fail to parse IPv6 address `[host]:<port>`

### ISSUE THREAD

**Issue by juchiast** [timberio/vector#3573]
`http::Uri::host` returns `[host]` which creates an error when passing to `ToSocketAddrs`.

```toml
[sinks.out]
mode = "udp"
type = "socket"
address = "[::1]:5000"
inputs = ["in"]
encoding.codec = "json"
```

Solution: trim left and right brackets.
