### ISSUE TITLE
UDP socket sink does not work for IPv6

### ISSUE THREAD

**Issue by juchiast** [timberio/vector#3574]
As documented in [send_to](https://doc.rust-lang.org/std/net/struct.UdpSocket.html#method.send_to),

> This will return an error when the IP version of the local socket does not match that returned from ToSocketAddrs.

UDP sinks bind to IPv4 by default, therefore sending to an IPv6 will fail.

Reproducible:

```toml
[sinks.out]
mode = "udp"
type = "socket"
address = "test.host:5000"
inputs = ["in"]
encoding.codec = "json"
```

/etc/hosts:
```text
::1 test.host
```

Output:
```
ERROR connection{host=test.host port=5000}: vector::sinks::util::udp: send failed error=Address family not supported by protocol (os error 97)
```
