### ISSUE TITLE
Vector buffer never get cleaned on SUSE 42.2 with Vector sink

### ISSUE THREAD

**Issue by alpi-ua** [timberio/vector#3594]
```
vector 0.10.0 (g0f0311a x86_64-unknown-linux-gnu 2020-07-22)
```

```toml
[sources.in]
  type = "journald" 

[sinks.vector]
  type = "vector"
  inputs = ["in"]
  address = "1.2.3.4:5000"
  healthcheck = true

  buffer.max_size = 504900000
  buffer.type = "disk"
  buffer.when_full = "block"
```

### Debug Output
```
https://gist.github.com/alpi-ua/dc498aa6a67ac73ff7f34cdddab7f37e
```

### Expected Behavior

ls /var/lib/vector/vector_buffer/ | wc -l
9
this output is from ubuntu

vector deleting files correctly on SUSE.

### Actual Behavior

Vector is not deleting buffer files and is holding them opened while running and have stable connection to the server.
Vector start consuming CPU due to a massive io blocking.

### Additional Context
cat /etc/osrelease
ID=opensuse
VERSION_ID="42.2"

uname -r
4.4.27-2-default

uname -m
x86_64
