### ISSUE TITLE
kubernetes_logs corrupts K8s labels with dots in their names

### ISSUE THREAD

**Issue by tyrken** [timberio/vector#3595]
### Vector Version
Nightly build from 2020-08-27 as you haven't fully released the new K8s source yet...
```
vector 0.11.0 (gb2f9a09 x86_64-unknown-linux-gnu 2020-08-27)
```

### Vector Configuration File
```toml
data_dir = "/var/tmp/vector"

[sources.kubernetes_logs]
  type = "kubernetes_logs"
  auto_partial_merge = true
  self_node_name = "${VECTOR_SELF_NODE_NAME}"
  [sources.kubernetes_logs.annotation_fields]
    pod_labels = "labels"
    pod_name = "pod"
    pod_namespace = "namespace"
    pod_uid = "pod_uid"

[sinks.debug]
  inputs = ["kubernetes_logs"]
  type = "console"
  target = "stdout"
  encoding = "json"
```

### Debug Output
skipped for now - not needed, relevant snippet with prettifying:
```json
{
    "file": "/var/log/pods/kube-system_ebs-csi-node-wtxnw_105dcb2d-b14f-4869-80da-ecae53d4f4cf/liveness-probe/0.log",
    "labels": {
        "app": {
            "kubernetes": {
                "io/instance": "aws-ebs-csi",
                "io/name": "aws-ebs-csi-driver"
            }
        },
        "controller-revision-hash": "6dc48fdb7f",
        "pod-template-generation": "2"
    },
    "message": "I0827 06:37:10.003083       1 main.go:53] Sending probe request to CSI driver \"ebs.csi.aws.com\"",
    "namespace": "kube-system",
    "pod": "ebs-csi-node-wtxnw",
    "pod_uid": "105dcb2d-b14f-4869-80da-ecae53d4f4cf",
    "source_type": "kubernetes_logs",
    "stream": "stderr",
    "timestamp": "2020-08-24T06:37:10.004636713Z"
}
```

### Expected Behavior
The labels should have been:

```json
{
    "file": "/var/log/pods/kube-system_ebs-csi-node-wtxnw_105dcb2d-b14f-4869-80da-ecae53d4f4cf/liveness-probe/0.log",
    "labels": {
        "app": "ebs-csi-node",
        "app.kubernetes.io/instance": "aws-ebs-csi",
        "app.kubernetes.io/name": "aws-ebs-csi-driver",
        "controller-revision-hash": "6dc48fdb7f",
        "pod-template-generation": "2"
    },
    ...
}
```

### Actual Behavior
Dots in labels confused Vector, leading to missing one label & incorrect sub-objects.

### Example Data
Original K8s yaml:
```yaml
# kubectl get pod ebs-csi-node-wtxnw -o yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: eks.privileged
  creationTimestamp: "2020-07-09T09:23:18Z"
  generateName: ebs-csi-node-
  labels:
    app: ebs-csi-node
    app.kubernetes.io/instance: aws-ebs-csi
    app.kubernetes.io/name: aws-ebs-csi-driver
    controller-revision-hash: 6dc48fdb7f
    pod-template-generation: "2"
  name: ebs-csi-node-wtxnw
  namespace: kube-system
...
```

### Additional Context
Note that I run vector with suitable env-vars/tokens-in-files to enable K8s access outside a pod to allow me to debug this at a console.

### References
This sounds similar to my earlier report about similar behaviour from the JSON parser, see #2814
