### ISSUE TITLE
Allow a headers option table for the elasticsearch sink

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#361]
This allow users to specify custom headers when writing to Elasticsearch. This should function [the same way that the `http` sink headers function](https://docs.vector.dev/usage/configuration/sinks/http):

```toml
[sinks.my_sink_id]
  type = "elasticsearch"
  
  [sinks.my_sink_id.headers]
    Authorization = "Basic QWxhZGRpbjpPcGVuU2VzYW1l"
    X-Custom-Header = "value"
```
