### ISSUE TITLE
new source: Remote Connections

### ISSUE THREAD

**Issue by Hoverbear** [timberio/vector#3679]
Inspired by the output of https://github.com/imsnif/bandwhich, we noted that a source which creates new metrics each time a new connection is established or dropped with the host.

```toml
[sources.remotes]
type = "remote_connections"
adapters = ["eth0"] # Default `*`
exclude_addresses = [] # Default, none
include_addresses = [] # Default, all
```

The source would draw from the [dependencies](https://github.com/imsnif/bandwhich/blob/b275ee61e11c3404c84868e85b1a52b8dd231d03/Cargo.toml#L22-L35) of bandwhich like [`pnet`](https://docs.rs/pnet/0.26.0/pnet/) to create the following metrics:

```json
# A new host has connected.
{
  "name": "remote_connections.connected",
  "timestamp": "2019-11-01T21:15:47+00:00",
  "kind": "absolute",
  "tags": {
    "remote": "${THE_REMOTE_IP}"
  },
  "counter": {
    "value": 24
  }
}
```

```json
# A host has disconnected.
{
  "name": "remote_connections.disconnected",
  "timestamp": "2019-11-01T21:15:47+00:00",
  "kind": "absolute",
  "tags": {
    "remote": "${THE_REMOTE_IP}"
  },
  "counter": {
    "value": 24
  }
}
```

Note that this feature request does not request connection bandwidth.
