### ISSUE TITLE
new source: dmesg

### ISSUE THREAD

**Issue by Hoverbear** [timberio/vector#3680]
Inspired by the output of https://github.com/polyverse/rmesg, we noted that a source which creates new events from  kernel dmesg logs.

It should turn each dmesg event into a Vector event.

```toml
[sources.kernel_dmesg]
type = "dmesg"
```

**Comment by MOZGIII** [comment]
Would be useful at https://github.com/timberio/vector/issues/5362

**Comment by binarylogic** [comment]
@MOZGIII in what way? I'm curious how critical this is. I'd like to see if we get more user demand for this feature.

**Comment by gvalkov** [comment]
This would be useful and if it was available, we would use it process nftables/iptables log messages from the kernel log.

Instead of providing a separate source, you could also extend the capabilities of the `journald` source (i.e. `journalctl SYSLOG_IDENTIFIER=kernel` or `journalctl -k`).

**Comment by phyber** [comment]
A quick solution to this which worked for me was to define an `exec` `source`.

```yaml
sources:
  dmesg:
    mode: "streaming"
    type: "exec"
    command:
      - "/usr/bin/dmesg"
      - "--ctime"
      - "--follow"
```

Depending on your system/vector configuration, you may also need to ensure that `kernel.dmesg_restrict = 0` in `sysctl`.
