### ISSUE TITLE
Parsing JSON in dotted notation can silently overwrite existing key values

### ISSUE THREAD

**Issue by awangc** [timberio/vector#3697]
### Vector Version

```
vector 0.10.0 (g0f0311a x86_64-apple-darwin 2020-07-22)
```

### Vector Configuration File

```toml
[sources.app_log]
  type = "http"
  address = "0.0.0.0:9091"
  encoding = "json"

[sinks.to_file]
  type = "file"
  inputs = ["app_log"]
  path = "/tmp/vector.log"
  encoding.codec = "ndjson"
```

### Debug Output

https://gist.github.com/awangc/c09cd11f75a3ed17bcf201e2bad580e0

### Expected Behavior

A warning/log line that `test` and `test2.child` fields have been overwritten (see the gist above)

### Actual Behavior

The fields `test` and `test2.child` were silently overwritten

### Example Data

See the `curl` command from the gist above
