### ISSUE TITLE
Cloudwatch: Value '[]' at 'logEvents' failed to satisfy constraint

### ISSUE THREAD

**Issue by gtie** [timberio/vector#3707]
### Vector Version
```
vector 0.10.0 (g0f0311a x86_64-unknown-linux-gnu 2020-07-22)
```

### Vector Configuration File

```toml
[sources.journald]
  type = "journald" # required
  current_boot_only = false
  exclude_units = ["vector.service"]


[sinks.cloudwatch-logs]
  # General
  type = "aws_cloudwatch_logs"
  inputs = ["journald"]
  compression = "gzip"
  create_missing_group = false
  create_missing_stream = true
  group_name = "journald"
  healthcheck = true
  region = "us-west-2"
  stream_name = "{{ host }}"

  # Encoding
  encoding.codec = "json"
```

### Debug Output
https://gist.github.com/gtie/70b40f08fad59444d3052bffd9d02d94

### Expected Behavior
After starting vector with a new Journald source -> CloudWatch Logs sync the journald log lines to start appearing in Cloudwatch Logs without errors

### Actual Behavior
For 2-3 minutes after startup, vector is generating error messages without successfully submitting anything to CloudWatch logs. A very short excerpt is at https://gist.github.com/gtie/70b40f08fad59444d3052bffd9d02d94

After the initial period of a few minutes have passed, vector starts successfully submitting the logs to Cloudwatch without complaining. It keeps on successfully sending data even after it is restarted.

It is only the initial bulk processing of new journald data that is triggering the errors.

### Example Data
E.g. 2.5G of journald data 

### Additional Context
Vector running on 32CPU bare metal server. Vector is started through systemd with no CPU/Memory restrictions for this experiment. Up-to-date Debian 10.5.

### References
N/A
