### ISSUE TITLE
User having issue with basic auth and Loki sink

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#3710]
Opening this as I didn't get a chance to completely follow up with the user [on gitter](https://gitter.im/timberio-vector/community?at=5f4cde6436e6f709fd145f82) and am hoping someone else can dig in.

They are having some issues using HTTP basic auth (via an nginx proxy as [Loki doesn't support auth directly](https://grafana.com/docs/loki/latest/operations/authentication/)) with the Loki sink. They are able to use the same credentials to access Loki directly (via nginx) in the browser.

I verified that Vector seems to be setting the Basic Auth headers as expected with the `loki` sink, but I didn't get a chance to try to fully reproduce this with a running nginx and Loki instance.

Config snippet

```toml
[sinks.loki-nginx]
  inputs   = ["nginx_dev"]
  type     = "loki"
  endpoint = "https://a-endpoint"
  auth.strategy = "basic"
  auth.user = "username"
  auth.password = "some_password"
  labels.key = "dev_nginx"
```

Nginx snippet:

```
              auth_basic "Adiministrador Login";
              auth_basic_user_file /etc/nginx/.htpasswd;

              proxy_pass http://127.0.0.1:3100;
```
