### ISSUE TITLE
Elasticsearch sink: 'except_fields' evaluated prior to setting index field

### ISSUE THREAD

**Issue by spencergilbert** [timberio/vector#3715]
### Vector Version

```
root@vector-59bf4dc996-d75fp:/# vector --version
vector 0.10.0 (g0f0311a x86_64-unknown-linux-gnu 2020-07-22)
```

### Vector Configuration File

```toml
[transforms.add_index]
        type = "add_fields"
        inputs = ["in"]
        fields.index = "example"

# Output data
[sinks.elasticsearch_out]
        type = "elasticsearch"
        inputs = ["add_index"]
        compression = "none"
        healthcheck = true
        host = "http://logging-es-http.logging.svc.cluster.local:9200"
        index = "logstash-{{ index }}-writealias"

        auth.strategy = "basic"
        auth.password = "${ELASTICSEARCH_PASSWORD}"
        auth.user = "${ELASTICSEARCH_USERNAME}"

        encoding.except_fields = ["index"]
```

### Expected Behavior
Set target index, and drop unneeded field used for routing

### Actual Behavior
'index' field removed before setting the target index in Elasticsearch causing the index request to fail
```
Sep 04 20:25:25.571  WARN sink{name=elasticsearch_out type=elasticsearch}: vector::internal_events::elasticsearch: keys do not exist on the event; dropping event. missing_keys=[Atom('index' type=inline)] rate_limit_secs=30
Sep 04 20:25:25.572  WARN sink{name=elasticsearch_out type=elasticsearch}: vector::internal_events::elasticsearch: "keys do not exist on the event; dropping event." is being rate limited. rate_limit_secs=5
```
