### ISSUE TITLE
syslog log event ignores message timestamp

### ISSUE THREAD

**Issue by calvin** [timberio/vector#3723]
### Vector Version

```
vector 0.10.0 (g0f0311a x86_64-unknown-linux-gnu 2020-07-22)
```

### Vector Configuration File

```toml

[sources.remote_syslog]
  type = "syslog"
  address = "0.0.0.0:6514"
  mode = "tcp" 

[sinks.joyntonave_logs]
  type = "gcp_stackdriver_logs"
  inputs = ["remote_syslog"]
  credentials_path = "..."
  healthcheck = true
  project_id = "..."
  log_id = "logs"
  resource.type = "global"

```

### Expected Behavior

* the ingested log event in StackDriver log uses syslog message's timestamp field to denote the event time

### Actual Behavior
* the ingested log event in StackDriver log uses the system time to denote the event time

### Example Data

The log message from GCP:
```
{
 insertId: "..."  
jsonPayload: {
  appname: "..."   
  facility: "user"   
  host: "..."   
  hostname: "..."   
  message: "..."   
  severity: "notice"   
  source_ip: "..."   
  source_type: "syslog"   
  timestamp: "2020-09-06T03:55:11Z"   
 }
 logName: "..."  
 receiveTimestamp: "2020-09-06T03:57:14.598929856Z"  
 
resource: {
  
labels: {…}   
  type: "global"   
 }
 timestamp: "2020-09-06T03:57:14.598929856Z"  
}
```

`$.timestamp` should be the same as `$.jsonPayload.timestamp`.

### Additional Context

Only tested using the GCP sink.

### References

* N/A
