### ISSUE TITLE
loki sink missed labels from dropped fields

### ISSUE THREAD

**Issue by hdhoang** [timberio/vector#3731]
From #3716 description

>  It's probably worth making a pass through other sinks to see if this is an issue.

Thanks for the idea, the loki sink has this issue when copying labels from fields under `kubernetes` key together with `encoding.only_fields = ["message"]`.

I can work out a test and PR within the week.

### Vector Version

From docker image tag `nightly-2020-09-06-debian

```
vector 0.11.0 (g50f974b x86_64-unknown-linux-gnu 2020-09-06)
```

### Vector Configuration File

```toml

[sinks.dev_loki]
type = "loki"
inputs = ["filter_errors",
]

    endpoint = "http://....:3100/"

    labels.exported_namespace = "{{ kubernetes.namespace }}"
    labels.exported_app = "{{ kubernetes.labels.app }}"
    labels.exported_pod = "{{ kubernetes.pod.name }}"
    labels.exported_node = "{{ kubernetes.node.name }}"
    labels.exported_container = "{{ kubernetes.container.name }}"
    labels.vector_instance = "${HOSTNAME}"

    encoding.only_fields = ["message"] # ,"kubernetes"] # <<<--- I need the field kubernetes here, otherwise labels.exported_xyz above will not be created

```

### Expected Behavior

`exported_...` labels show up on Loki.

### Actual Behavior

Only `vector_instance` appeared on these log lines.

### Additional Context

It's in kubernetes, but should work similarly outside. I'll try to make normal a test case

### References

- #2591
- #3716
