### ISSUE TITLE
except_fields not working with gcp_cloud_storage sink

### ISSUE THREAD

**Issue by jonathanendy** [timberio/vector#3769]
### Vector Version

```
vector 0.10.0 (g1de26d2 x86_64-unknown-linux-musl 2020-07-19)
timberio/vector:nightly-2020-07-19-alpine 
```

### Vector Configuration File

```toml
[transforms.set_dates]
  # General
  type = "lua" # required
  inputs = ["coercer"] # required
  version = "2" # required

  # Hooks
  hooks.process = """
  function (event, emit)
    event.log.print_yyyy = os.date("%y", math.floor(event.log.timestamp))
    event.log.print_dd = os.date("%d", math.floor(event.log.timestamp))
    event.log.print_mm = os.date("%m", math.floor(event.log.timestamp))
    event.log.print_MM = os.date("%M", math.floor(event.log.timestamp))
    event.log.print_HH = os.date("%H", math.floor(event.log.timestamp))

    emit(event) -- Very important! Emit the processed event.
  end
  """

[sinks.gcp]
  type = "gcp_cloud_storage" # required
  inputs = ["set_dates"] # required
  credentials_path = "/etc/vector/gcs.json"
  bucket = "${BUCKET_NAME}"
  healthcheck = true

  batch.max_events = 1

  filename_append_uuid = false
  filename_extension = "json"
  filename_time_format = ""

  key_prefix="{{ id }}/{{ event }}/{{ print_yyyy }}/{{ print_mm }}/{{ print_dd }}/{{ print_HH }}/{{ print_MM }}/{{ uuid }}-{{ counter }}"

  # Encoding
  encoding.codec = "ndjson" # required
  encoding.except_fields = ["print_yyyy", "print_dd", "print_mm", "print_MM", "print_HH"]
```

### Expected Behavior

I'm using the following to create objects on gcs.
I'm parsing the dates to variables in order to use them in the file name on gcs
except_fields should eliminate the fields before writing the object

### Actual Behavior

The object is not writing at all.
It seems that fields eliminated before the key_prefix can use them

### Additional Context

It seems that without except_fields the object is writing but the print_* fields are in the content
