### ISSUE TITLE
New `rename_fields` transform

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#377]
A simple transformer that renames fields. The config should be a table of k/v pairs representing the old name and new name:

```
[transforms.<transform_id>]
  type = "rename_fields"

  [transforms.<transform_id>.fields]
    old_name = "new_name"
```

**Comment by soufiane-bouchaara** [comment]
Hi,
Is there any news about the rename transform  ?  it will be awesome if you add it asap

**Comment by a-rodin** [comment]
@soufiane-bouchaara Just in case, while `rename_fields` is not implemented yet, it is possible to use [`lua` transform](https://docs.vector.dev/usage/configuration/transforms/lua) as a temporary replacement:

```toml
[inputs.in]
type = "stdin"

[transforms.rename_message]
type = "lua"
inputs = ["in"]
source = """
    event['renamed_message'] = event['message']
    event['message'] = nil
"""

[sinks.out]
type = "console"
inputs = ["rename_message"]
encoding = "json"
```

which allows Vector to output messages like this:

```json
{"renamed_message":"hello","host":"pi","timestamp":"2019-11-17T16:26:29.370688954Z"}
```
