### ISSUE TITLE
Regex_parser not work well with multiple patterns

### ISSUE THREAD

**Issue by scarper123** [timberio/vector#3818]
### Vector Version

```
vector 0.10.0 (g0f0311a x86_64-unknown-linux-gnu 2020-07-22)
```

### Vector Configuration File

```toml
[transforms.regex_parser_simple]
  inputs = []
  type = "regex_parser"
  patterns = [
  '^(?P<openstack_timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d+) (?P<openstack_pid>\d+) (?P<openstack_loglevel>[A-Z]+) (?P<openstack_program>\S+) \[(?P<openstack_reqlist>.*)\] (?P<openstack_client>\d{2,3}\.\d{2,3}.\d{1,3}.\d{1,3}) "(?P<http_request_method>[A-Z]+) (?P<http_request_path>\S+) (?P<http_request_version>\S+)" status: (?P<http_response_status>\d+) len: (?P<http_response_len>\d+) time: (?P<http_response_time>[\d\.]+)$',
  '^(?P<openstack_timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d+) (?P<openstack_pid>\d+) (?P<openstack_loglevel>[A-Z]+) (?P<openstack_program>\S+) \[(?P<openstack_reqlist>.*)\] (?P<openstack_client>\d{2,3}\.\d{2,3}.\d{1,3}.\d{1,3}) "(?P<http_request_method>[A-Z]+) (?P<http_request_path>\S+)" status: (?P<http_response_status>\d+) len: (?P<http_response_len>\d+) microversion: (?P<http_request_version>\S+) time: (?P<http_response_time>[\d\.]+)$',
]
[[tests]]
  name = "regex_parser_simple"
  [tests.input]
    insert_at = "regex_parser_simple"
    type = "raw"
    value = "2020-09-10 06:39:43.388 11728 INFO nova.osapi_compute.wsgi.server [-] 192.168.2.38 \"OPTIONS / HTTP/1.0\" status: 200 len: 501 time: 0.0004530"
  [[tests.outputs]]
    extract_from = "regex_parser_simple"
    [[tests.outputs.conditions]]
      "openstack_timestamp.equals" = "2020-09-10 06:39:43.388"
      "openstack_loglevel.equals" = "INFO"
      "http_request_version.equals" = "HTTP/1.0"
```

### Expected Behavior

The test result should be pass, because the raw data is matched with the first pattern

### Actual Behavior

Test failure, due "http_request_version.equals" = "HTTP/1.0"

### Example Data

```
2020-09-10 06:39:43.388 11728 INFO nova.osapi_compute.wsgi.server [-] 192.168.2.38 \"OPTIONS / HTTP/1.0\" status: 200 len: 501 time: 0.0004530
```

### Additional Context

When comment the second pattern, the test will pass. So it seems the multiple patterns are impact be other patterns.

### References
- [#1477](https://github.com/timberio/vector/issues/1477)
