### ISSUE TITLE
Creating nested fields from lua transform in testing mode fails

### ISSUE THREAD

**Issue by oktal** [timberio/vector#3825]
### Vector Version

```
λ vector.exe --version
vector 0.11.0 (g653afaf x86_64-pc-windows-msvc 2020-09-11)
```

### Vector Configuration File

```toml
[sources.generator]
  type = "generator"
  lines = ["Line 1", "Line 2"]

# Structure and parse the data
[transforms.parsed_event]
  inputs = [ "generator" ]
  type = "regex_parser"
  regex = '(?m)^(?P<log_timestamp>[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]+Z)\s+([-|]\s+(?P<log_thread_id>[^\s]+)\s+[-|]\s+(?P<log_level>[^\s]+)\s+[-|]\s+(?P<log_name>.*?)\s+)?\|\|\s+(?P<log_text>.*?)'

[transforms.parse_thread_id]
  type = "lua"
  inputs = ["parsed_event"]
  version = "2"

  hooks.process = """
    function (event, emit)
      thread_id = tonumber(event.log.log_thread_id)
      if thread_id == nil then
        event.log.process.thread.name = event.log.log_thread_id
      else
        event.log.process.thread.id = thread_id
      end
      event.log.log_thread_id = nil
      emit(event)
    end
  """

[[tests]]
  name = "parse_thread_id"

  [[tests.inputs]]
    insert_at = "parsed_event"
    type = "raw"

    value = "2020-07-21 22:04:56.350158Z - 9172 - Information - MyApplication || Doing something or another..."

  [[tests.outputs]]
    extract_from = "parse_thread_id"

    [[tests.outputs.conditions]]
      type = "check_fields"
      "process.thread.id.equals" = 9172
```

### Debug Output

```
λ vector.exe test "C:\Dev\scripts\Vector\vector-test.toml"
Sep 11 18:25:48.133  INFO vector::app: Log level "info" is enabled.
Running C:\Dev\scripts\Vector\vector-test.toml tests
Sep 11 18:25:48.139  WARN vector::transforms::regex_parser: Usage of `regex` is deprecated and will be removed in a future version. Please upgrade your config to use `patterns` instead: `patterns = ['(?m)^(?P<log_timestamp>[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]+Z)\s+([-|]\s+(?P<log_thread_id>[^\s]+)\s+[-|]\s+(?P<log_level>[^\s]+)\s+[-|]\s+(?P<log_name>.*?)\s+)?\|\|\s+(?P<log_text>.*?)']`. For more info, take a look at the documentation at https://vector.dev/docs/reference/transforms/regex_parser/
Sep 11 18:25:48.141 ERROR vector::transforms::lua::v2: error=Runtime error in "hooks.process" function: runtime error: [string "?"]:6: attempt to index a nil value (field 'process')
stack traceback:
        [C]: in metamethod '__index'
        [string "?"]:6: in function <[string "?"]:1> rate_limit=30
test C:\Dev\scripts\Vector\vector-test.toml: parse_thread_id ... failed

failures:

--- C:\Dev\scripts\Vector\vector-test.toml ---

test 'parse_thread_id':

check transform 'parse_thread_id' failed, no events received.
```

### Expected Behavior

I should be allowed to create a nested "process.thread.id" field in my Lua snippet

### Actual Behavior

The Lua evaluation fails.

### Additional Context

It looks like nested fields are correctly created in normal mode, but fail in test mode.

When renaming `process.thread.id` to `process_thread_id`, the test correctly passes.
