### ISSUE TITLE
thread 'tokio-runtime-worker' panic

### ISSUE THREAD

**Issue by spencergilbert** [timberio/vector#3830]
### Vector Version

```
vector 0.11.0 (g50a9c3a x86_64-unknown-linux-musl 2020-09-10)
```

### Vector Configuration File

```toml
data_dir = "/vector-data-dir"
[log_schema]
  host_key = "host"
  message_key = "message"
  source_type_key = "source_type"
  timestamp_key = "timestamp"
[sources.internal_metrics]
  type = "internal_metrics"
[sources.kafka]
  type = "kafka"
  bootstrap_servers = "logging-kafka-bootstrap.logging-kafka:9092"
  group_id = "test-vector"
  topics = ["test-vector"]
  
[transforms.message_parser]
  type = "json_parser"
  inputs = ["kafka"]
  field = "message"
  drop_invalid = true
  
[sinks.elasticsearch]
  type = "elasticsearch"
  inputs = ["message_parser"]
  host = "http://logging-es-http.logging:9200"
  index = "logstash-vector-test"
  auth.strategy = "basic"
  auth.password = "${ELASTICSEARCH_PASSWORD}"
  auth.user = "${ELASTICSEARCH_USER}"
  # https://github.com/timberio/vector/pull/3716
  #encoding.except_fields = ["index"]
  
[sinks.prometheus]
  type = "prometheus"
  inputs = ["internal_metrics"]
  address = "0.0.0.0:9598"
  namespace = "vector"
```

### Debug Output

https://gist.github.com/spencergilbert/52f59f015769e19f4723a08da9c29f2f

### Expected Behavior

No panic!

### Actual Behavior

Panic!
