### ISSUE TITLE
Template encoding

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#3870]
### Current Vector Version

0.10.0

### Use-cases

I think it would be useful to control the rendering of structured events. Something like:

```
[sinks.console]
inputs = ["json"]
type = "console"
encoding.codec = "template"
encoding.codec.template = "{{ level }} {{ host }} {{ message }}"
```

### Attempted Solutions

This is possible by templating the `message` key via `lua` or, possibly?, the `remap` transform and then using the `text` encoding, but I think this could be simplified with the above.

### Proposal

With

```toml
[sources.stdin]
type = "stdin" # required

[transforms.json]
type = "json_parser" # required
inputs = ["stdin"] # required

[sinks.console]
inputs = ["json"]
type = "console"
encoding.codec = "template"
encoding.codec.template = "{{ method }} {{ status }} {{ request }}"
```

The log event:

```json
{"host":"189.17.105.48", "user-identifier":"feeney7313", "datetime":"14/Sep/2020:11:45:41 -0400", "method": "POST", "request": "/utilize/incentivize/turn-key", "protocol":"HTTP/1.0", "status":400, "bytes":5453, "referer": "https://www.internationaldeploy.net/b2c/productize"}
```

Would be written out as:

```text
POST 400 /utilize/incentivize/turn-key
```

### References

https://docs.fluentbit.io/manual/pipeline/outputs/file#out_file-format
https://www.elastic.co/guide/en/beats/filebeat/current/configuration-output-codec.html
https://www.elastic.co/guide/en/beats/filebeat/current/configuration-output-codec.html
