### ISSUE TITLE
invalid escape character in test conditions

### ISSUE THREAD

**Issue by spencergilbert** [timberio/vector#3873]
### Vector Version

```
vector 0.10.0 (g0f0311a x86_64-unknown-linux-gnu 2020-07-22)
```

### Vector Configuration File

```toml
[sources.kafka]
  type = "kafka"
  bootstrap_servers = "kafka-bootstrap:9092"
  group_id = "test-vector"
  topics = ["test-vector"]
  
[transforms.message_parser]
  type = "json_parser"
  inputs = ["kafka"]
  field = "message"
  drop_invalid = true
  
[sinks.elasticsearch]
  type = "elasticsearch"
  inputs = ["message_parser"]
  host = "http://logging-es-http:9200"
  index = "test-vector"
  auth.strategy = "basic"
  auth.password = "${ELASTICSEARCH_PASSWORD}"
  auth.user = "${ELASTICSEARCH_USER}"

[[tests]]
  name = "check_dot_escape"

  [[tests.inputs]]
    insert_at = "message_parser"
	type = "raw"
	value = '{"timestamp":"2020-02-14T01:22:23.223Z","application_id":1,"message":"Hello world","field.with.dot":"value","ec2":{"instance_id":"abcd1234","tags":["tag1: value1","tag2: value1"]}}'

  [[tests.outputs]]
    extract_from = "message_parser"

	[[tests.outputs.conditions]]
	  type = "check_fields"
	  "ec2.instance_id.equals" = "abcd1234"
	  "field\.with\.dots.equals" = "value"
```

### Expected Behavior

Based on the [field path notation](https://vector.dev/docs/reference/field-path-notation/#escaping) I'd expect to need to escape the fields in the conditions section the same way but it doesn't seem to be the case. Perhaps I'm misunderstanding the configuration and need to do something different?

### Actual Behavior

```sh
❯ vector test vector/test.toml
Sep 14 15:58:19.701  INFO vector: Log level "info" is enabled.
Running vector/test.toml tests
Sep 14 15:58:19.704  WARN vector::topology::config::vars: unknown env var in config: "ELASTICSEARCH_PASSWORD"
Sep 14 15:58:19.704  WARN vector::topology::config::vars: unknown env var in config: "ELASTICSEARCH_USER"
Sep 14 15:58:19.704 ERROR vector::unit_test: Failed to execute vector/test.toml tests:
invalid escape character in string: `.` at line 36
```
