### ISSUE TITLE
(docker source): use of driver "local" for a container causes deserialization failure on startup

### ISSUE THREAD

**Issue by oivindoh** [timberio/vector#4169]
### Vector Version

```
Vector 0.10.0 (g0f0311a x86_64-unknown-linux-musl 2020-07-22)
```

### Vector Configuration File

```toml
[sources.docker]
  type = "docker"
```

### Expected Behavior

The valid docker logging driver `local` should be recognized.

### Actual Behavior

Vector logs

```
stdout��ϫ�﹜�Sep 28 09:09:32.350 ERROR vector::sources::docker: Fetching container details failed error=Failed to deserialize near ...gConfig":{"Type":"local","Config":{"max-file":"3","max-s...��
stdout��ҫ�﹜�unknown variant `local`, expected one of ``, `json-file`, `syslog`, `journald`, `gelf`, `fluentd`, `awslogs`, `splunk`, `etwlogs`, `none` at line 1 column 1290�]`
```

### Example Data

docker-compose.yaml file with a service defined like this:

```yaml
version: '3'
services:
  noisy_service:
    logging:
      driver: "local"
      options:
        max-size: "10M"
        max-file: "3"
```

### Additional Context

Vector running in docker image timberio/vector@sha256:4d61e79df45c810f7ac0a5ae95a23f12dae157b98f8bc371db2cb0b39a273129
