### ISSUE TITLE
InFlightLimit::None cannot be deserialized

### ISSUE THREAD

**Issue by juchiast** [timberio/vector#4190]
This breaks `vector generate` for sinks that have `TowerRequestConfig` in there config struct. For example, sink `aws_s3`:

Generated config:
```toml
data_dir = "/var/lib/vector/"

[sinks.sink0]
healthcheck = true
inputs = ["TODO"]
bucket = ""
compression = "none"
type = "aws_s3"

[sinks.sink0.batch]

[sinks.sink0.request]
in_flight_limit = "None"

[sinks.sink0.request.auto_concurrency]
decrease_ratio = 0.9
ewma_alpha = 0.5
rtt_threshold_ratio = 0.05

[sinks.sink0.buffer]
type = "memory"
max_events = 500
when_full = "block"
```

Error:
```
unknown variant `None`, expected `auto` for key `sinks.sink0`
```
