### ISSUE TITLE
Add `auth.access_key_id` and `auth.secret_access_key` options to all AWS components

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#4199]
Currently, all AWS component's auth configuration is done through environment variables. While I like supporting env vars, they should always be fallbacks to explicit inputs. This ensures that options are discoverable and easy to override. Therefore, I'm proposing the following options for all AWS components. Ex:

```toml
[sinks.aws_s3]
auth.access_key_id = "..."
auth.secret_access_key = "..."
```

I like the `auth` namespace since it's clear and follows [precedence](https://vector.dev/docs/reference/sinks/elasticsearch/#auth) that we've already set.
