### ISSUE TITLE
Allow specifying multiple `multiline` configs per label value at the `kubernetes_logs` source

### ISSUE THREAD

**Issue by MOZGIII** [timberio/vector#4216]
## Motivation

`kubernetes_logs` source gathers the configurations from the whole cluster, and specifying just a single `multiline` config might be limiting.

Consider a cluster where Ruby and Java apps run.

If we specify a `multiline` config to work for Java stacktraces, we can't collect Ruby stacktraces, and vice versa.

## Proposal

To solve this issue, we can allow defining multiple multiline configs, for each stackstrace type. This would look something like this:

```toml
[sources.kubernetes_logs]
type = "kubernetes_logs"

[sources.kubernetes_logs.multiline.named.ruby]
start_pattern = "^[^\\s]"
mode = "continue_through"
condition_pattern = "^[\\s]+from"
timeout_ms = 1000

[sources.kubernetes_logs.multiline.named.java]
start_pattern = "^[^\\s]"
mode = "continue_through"
condition_pattern = "^[\\s]+at"
timeout_ms = 1000
```

Then, at the `Pod`, users will be able to add an `annotation`, specifying which `multiline` configuration to use.

This will look something like this:

```yaml
annotations:
  vector.dev/multiline-config/<container name>: "<multiline config name>"
```

and in practice:

```yaml
annotations:
  vector.dev/multiline-config/puma: "ruby"
```

Then, when Vector obtains the `Pod`, it'll be able to condition by this annotation and use the `ruby` configuration to automatically split the stream and apply `ruby` multiline config.

### Use (non-existing yet, #4210) `line_agg` transform and swimlanes

A quicker and more generic way of approaching the same capabilities could be via #4028.

Users can add custom labels to their `Pod`s, like so:

```yaml
labels:
  myclustername/stacktrace-format: "ruby"
```

Then, users will just add a swimlane by labels (`"kubernetes.pod_labels.myclustername/stacktrace-format".eq = "ruby"` and etc) to split the logs into multiple streams, and then apply a separate `line_agg` transform for each lane.

This approach is more generic (covers more use cases, allows for even more complicated configurations), and, at the same time, much simpler to implement.

### Use multiple `kubernetes_logs` sources and custom scopes

With #3412 and #4211 done, it would be easy to add multiple `kubenretes_logs` sources, each responsible for processing it's own selector.

As with the last alternative, users will add custom labels:

```yaml
labels:
  myclustername/stacktrace-format: "ruby"
```

And then specify multiple `kubenretes_logs` sources with different selectors:

```toml
[sources.ruby]
type = "kubernetes_logs"
label_selector = "myclustername/stacktrace-format=ruby"
[sources.ruby.multiline]
start_pattern = "^[^\\s]"
mode = "continue_through"
condition_pattern = "^[\\s]+from"
timeout_ms = 1000

[sources.java]
type = "kubernetes_logs"
label_selector = "myclustername/stacktrace-format=java"
[sources.java.multiline]
start_pattern = "^[^\\s]"
mode = "continue_through"
condition_pattern = "^[\\s]+at"
timeout_ms = 1000
```

The downside of this solution is that the overhead of consuming many streams (each with it's own selector) from the K8s API might be unwanted.

Other than that - this is probably the easiest option, as it'll be available as a workaround as soon as we implement #3412 and #4211. However, it's also very unergonomic, as a lot of duplication is required.
