### ISSUE TITLE
Hostname not supported by Humio sink

### ISSUE THREAD

**Issue by mijtrifork** [timberio/vector#4228]
### Vector Version

```
vector 0.10.0 (g0f0311a x86_64-unknown-linux-gnu 2020-07-22)
```

### Vector Configuration File

Full configuration file

```toml
[sources.in]
  type = "stdin"

[transforms.extract_timestamp]
  type = "regex_parser"
  inputs = ["in"]
  drop_field = false
  patterns = ['^(?P<timestamp>.{23}).*$']
  overwrite_target = true

[transforms.extract_timestamp.types]
  timestamp = "timestamp|%F %T%.3f"

[sinks.out]
  type = "console"
  inputs = ["extract_timestamp"]
  encoding.codec = "json"
  encoding.except_fields = ["file", "source_type"]

[sinks.humio]
  type = "humio_logs"
  inputs = ["extract_timestamp"]
  healthcheck = false
  encoding.codec = "text"
  #host = "http://localhost:5000"
  token = "TokenRedacted"
```

### Expected Behavior

I expected the message "2020-09-30 15:52:47.927 Log message here" to appear in Humio with the correct hostname from where it was ingested,

### Actual Behavior

The message did show up (and with the correctly parsed timestamp) BUT no #host tag was visible in Humio making it impossible to use in a clustered hosting environment.

### Example Data

To debug further I tried to setup a local TCP listener on port 5000 and redirect the humio_log sink to that.

This reveals the following format being sent to Humio

```
POST /services/collector/event HTTP/1.1
content-type: application/json
authorization: Splunk TokenRedacted
user-agent: Vector/0.10.0 (g0f0311a x86_64-unknown-linux-gnu 2020-07-22)
host: localhost:5000
content-length: 107

{"event":"2020-09-30 15:52:47.927 Log message here","fields":{},"sourcetype":"stdin","time":1601481167.927}
```

As can be seen from the POST body no host information is being sent though it is part of the HEC format:

https://docs.humio.com/integrations/ingest-logs-with-a-data-shipper/hec/

Would also be great if #source and #sourcetype could be supported.

### Additional Context

I tried with encoding.codec = "json" set for the Humio sink as suggested by someone from your support team. This has the effect that the whole Vector log event is stored in json format in the #rawstring field in Humio. This doesn't solve my problem as I need the #host field to be populated correctly, and I also wan't just the message part of the log event to go into Humio. I'm looking to replace FileBeat with Vector so it is important that the log format remains unchanged.
