### ISSUE TITLE
Prometheus sink doesn't bind/listen until it receives events

### ISSUE THREAD

**Issue by rrichardson** [timberio/vector#4238]
```
vector 0.11.0 (gb031ead x86_64-unknown-linux-gnu 2020-09-30) 
(Current master as of 2020-09-30) 
```

### Vector Configuration File

```toml
[sinks.prometheus]
  type = "prometheus"
  inputs = ["log_to_metric"] # required
  address = "0.0.0.0:9091" # required
  namespace = "vector" # required
```

### Expected Behavior

Vector should begin listening on port 9091 for inbound requests from prometheus. 

### Actual Behavior

Vector does not begin listening on port 9091 for inbound requests from prometheus. 

### Additional Context

Looking at the code that was refactored 3 days ago, the `start_server_if_needed()` function is now executed at the top of a while loop that is processing incoming events. 
I think it should be at the top of the 

### References

The change was made here: 

#3933
