### ISSUE TITLE
Prometheus sink should bind immediately

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#4244]
A [user in discord](https://discordapp.com/channels/742820443487993987/746070591097798688/761099486784126976) was confused that the prometheus sink didn't bind to the port immediately, but only when processioning a message.

I tend to agree, it isn't clear to me why we would want to delay binding.

Example config:

```toml
[sources.in]
  type = "stdin"

[transforms.log_to_metric]
  type = "log_to_metric"
  inputs = ["in"]

  [[transforms.log_to_metric.metrics]]
    type = "histogram"
    field = "time"
    name = "time_ms" # optional

[sinks.out]
  type = "prometheus"
  address = "0.0.0.0:9598" # required
  inputs = ["log_to_metric"]
```

If you run `vector` without sending anything to STDIN, the prometheus sink is never bound.

This code:

https://github.com/timberio/vector/blob/9fceb7ddf0504b475cc59f971d04d8905b241b23/src/sinks/prometheus.rs#L380-L381

Appears to conditionally start the server when an event is received.
