### ISSUE TITLE
http health check ignores sink status

### ISSUE THREAD

**Issue by afoninsky** [timberio/vector#4249]
### Vector Version
image: timberio/vector:nightly-2020-09-24-alpine

### Vector Configuration File
```toml
data_dir = "/var/lib/vector"
[api]
    enabled = true
    bind= "0.0.0.0:8686"
[sources.aws-alb]
    type = "http"
    address = "0.0.0.0:9090"
    encoding = "text"
[transforms.aws-alb-json]
    type = "json_parser"
    inputs = ["aws-alb"]
    drop_invalid = true
[sinks.common-kafka]
    type = "kafka"
    inputs = ["aws-alb-json"]
    bootstrap_servers = "kafka-1:9094,kafka-2:9094,kafka-3:9094"
    tls.enabled = true
    topic = "common.httprequest.metric.v1"
    encoding.codec = "json"
```

### Expected Behavior
When kafka is down - http health check should return error.

### Actual Behavior
`curl http://localhost:8686/health` returns {"ok":true}
Error in logs:
```
{"timestamp":"Oct 01 14:35:13.280","level":"ERROR","spans":[{"name":"common-kafka","type":"kafka","name":"sink"}],"span":{"name":"common-kafka","type":"kafka","name":"sink"},"target":"vector::sinks::kafka","message":"Kafka error: Message production error: NotEnoughReplicas (Broker: Not enough in-sync replicas)"}
```
