### ISSUE TITLE
New `azure_event_hubs` source

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#4261]
Ability so source data from [Azure Event Hubs](https://azure.microsoft.com/en-us/services/event-hubs/).

**Comment by joshmue** [comment]
FWIW: I can report that some testing with the kafka source using SAS authentication worked out quite nicely while kind of sticking to the information from [the Azure docs](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-for-kafka-ecosystem-overview#shared-access-signature-sas) and escaping `$`'s.

```yaml
sources:
  event_hub:
    type: kafka
    bootstrap_servers: <name>.servicebus.windows.net:9093
    group_id: '$$Default'
    topics:
    - <topic>
    sasl:
      enabled: true
      mechanism: PLAIN
      username: '$$ConnectionString'
      password: '<connection string>'
    tls:
      enabled: true
      ca_file: /etc/ssl/certs/ca-certificates.crt
      verify_certificate: true
```

So wrapping the existing kafka source for use with SAS should not be too hard, I suppose. Using AAD/OAuth2 for authentication in order to avoid any manual credential maintenance, is a more complicated issue, I'm afraid.

The authentication may be possible in a similar manner in #2434.

**Comment by mdtro** [comment]
For those that are also super excited to get vectordev to send into Azure Event Hub as a sink. I was able to get this working this morning by following @joshmue's source configuration and the Microsoft documentation as inspiration. :)

```yaml
sinks:
  event_hub:
    type: kafka
    inputs: ["kubernetes_logs"]
    bootstrap_servers: "<EVENT_HUB_NAMESPACE>.servicebus.windows.net:9093"
    group_id: '$$Default'
    topic: "<EVENT_HUB_NAME>"
    encoding:
      codec: "json"
    healthcheck:
      enabled: true
    sasl:
      enabled: true
      mechanism: PLAIN
      username: "$$ConnectionString"
      password: "<YOUR_SAS_CONNECTION_STRING>"
    librdkafka_options:
      "security.protocol": sasl_ssl
```

The key part that got it working for me are those last two lines. Make sure the _key_ is surrounding with quotes as it is expecting a string, not a map.

```yaml
    librdkafka_options:
      "security.protocol": sasl_ssl
```
