### ISSUE TITLE
New `get_schema_value` remap function

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#4477]
I keep dancing around the schema issue in Vector because it's a big problem we need to solve. Hence why I opened #3910. I've offered a number of solutions and all of them have exposed various design problems, but I think this solution might be on the mark.

I'm proposing that we add a single `get_schema_value` remap function that accepts an enumeration of common field names.

## Examples

Let's take the `datadog_logs` sink. Datadog offers a set of [reserved fields](https://docs.datadoghq.com/logs/log_collection/?tab=http#reserved-attributes) that should be set in order to have a good Datadog experience. Currently, the `datadog_logs` sink looks for these fields [based on global schema settings](https://github.com/timberio/vector/blob/50fe38019570b67362584abbe3342acc6bab0217/src/sinks/datadog/logs.rs#L88). This is flawed since events coming from different sources can have different schemas. A better solution is something like this:

```toml
[sinks.datadog_logs]
type = "datadog_logs"
schema.host = '{{ get_schema_field("host") }}' #default
schema.level = '{{ get_schema_field("level") }}' #default
# ...
```

This would automatically pull the value for the "host" field based on the event's schema. I like this because it provides the maximum amount of flexibility. The user can override this option and set the values however they want.

## Requirements

Before we start work on this, we'll need to record metadata about events as they are ingested, this metadata will be used to locate the appropriate fields. I'm leaving this open ended until we can discuss further and open an issue for this.
