### ISSUE TITLE
Add helm and k8s-related check to master workflow at CI

### ISSUE THREAD

**Issue by MOZGIII** [timberio/vector#4527]
This is needed in general, however here's a concrete snippet for post #4257 checks variant. 

```yaml
      - name: Check helm dependencies
        if: needs.changes.outputs.helm == 'true'
        run: make check-helm-dependencies
      - name: Check helm lint
        if: needs.changes.outputs.helm == 'true'
        run: make check-helm-lint
      - name: Check that generated Kubernetes YAML doesn't diverge from Helm
        if: needs.changes.outputs.helm == 'true'
        run: make check-kubernetes-yaml
      - name: Check internal events
        if: needs.changes.outputs.internal_events == 'true'
        run: make check-internal-events
```

This is more like a note to self, such that it doesn't get lost.
