### ISSUE TITLE
Replace the `reduce` transform's `ends_when` option with Remap conditionals

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#4572]
Throughout Vector we have a concept of "conditions" that let users express conditional statements through a variety of options. This is present in the `reduce` transform's `ends_when` option:

```toml
[transforms.reduce]
  type = "reduce"
  ends_when.type = "check_fields"
  ends_when."message.regex" = "\w"
```

This is not very user friendly and lacks flexibility. The Remap language supports robust conditional statements and we'd like to replace conditions with this:

```toml
[transforms.reduce]
  type = "reduce"
  ends_when = 'matches(.message, /^\w/)'
```

Users can use this syntax to represent a variety of conditions:

```toml
ends_when = '(matches(.message, /^\w/) && .level == "error") || .level != "error"'
```

**Comment by JeanMertz** [comment]
Note that #4743 solves this problem slightly different from what's described in this issue.

That is to say, we already have the plumbing to support multiple different conditional check implementations.

We currently have:

* `check_fields`
* `is_log`
* `is_metric`

After the linked PR is merged, `remap` is added to this list.

So you don't write:

```toml
[transforms.reduce]
	type = "reduce"
	ends_when = 'matches(.message, /^\w/)'
```

But instead write:

```toml
[transforms.reduce]
	type = "reduce"
	ends_when.type = "remap"
	ends_when.source = 'matches(.message, /^\w/)'
```

We can of course deprecate (or remove entirely) the `check_fields` variant, since it has become obsolete with the introduction of `remap` (note that the PR discusses naming this variant differently).
