### ISSUE TITLE
Verify that the reduce transform can handle various multi-line scenarios

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#4574]
This is a meta issue to ensure the upcoming `reduce` transform changes will solve a variety of multiline scenarios.

### 1. Ruby Exceptions

Log stream:

```text
Started GET "/" for 127.0.0.1 at 2012-03-10 14:28:14 +0100
foobar.rb:6:in `/': divided by 0 (ZeroDivisionError)
  from foobar.rb:6:in `bar'
  from foobar.rb:2:in `foo'
  from foobar.rb:9:in `<main>'
Started GET "/" for 127.0.0.1 at 2012-03-10 14:28:14 +0100
```

Lazy solution:

```toml
[transforms.reduce]
type = "reduce"
starts_with = '!match(.message, /^\w/)'
merge_strategies.default = "discard"
merge_strategies.fields.message = "concat"
```

Strict solution (checking both the start and end conditions)

```toml
[transforms.reduce]
type = "reduce"
starts_with = '!match(.message, /^[a-z]*\.rb/)'
ends_with = '!match(.message, /^\w/)'
merge_strategies.default = "discard"
merge_strategies.fields.message = "concat"
```

### 2. Line Continuations

Log stream:

```text
First-line
Second line\
more second line\
end of second line
```

Config:

```toml
[transforms.reduce]
type = "reduce"
ends_when = '!endsWith(.message, "\")'
merge_strategies.default = "discard"
merge_strategies.fields.message = "concat"
```

### 3. Line Terminations

```text
first line;
second line
more of the second line
end of second line;
third line;
```

Config:

```toml
[transforms.reduce]
type = "reduce"
ends_when = 'endsWith(.message, ";")'
merge_strategies.default = "discard"
merge_strategies.fields.message = "concat"
```

### 4. Windows Event Logs

Log stream:

```text
<12> first line 
 more of the first line
<22> second line
<17> third line
```

Config:

```toml
[transforms.reduce]
type = "reduce"
starts_with = 'match(.message, /^<\d\d> /)'
merge_strategies.default = "discard"
merge_strategies.fields.message = "concat"
```
