### ISSUE TITLE
Invalid record from journald source on Proxmox nodes

### ISSUE THREAD

**Issue by spilla-quinten** [timberio/vector#4578]
### Vector Version

```
vector 0.10.0 (g0f0311a x86_64-unknown-linux-gnu 2020-07-22)
...
```

### Vector Configuration File

```toml
data_dir = "/var/lib/vector"

[sources.journald]
  type = "journald"
[transforms.journald_filter_10]
  type = "filter"
  inputs = ["journald"]
  [transforms.journald_filter_10.condition]
    "message.not_contains" = "[status] notice: received log"
[transforms.journald_filter_15]
  type = "filter"
  inputs = ["journald_filter_10"]
  [transforms.journald_filter_15.condition]
    "message.not_contains" = "<root@pam> successful auth for user 'prometheus@pve'"
[transforms.journald_filter_20]
    type = "filter"
    inputs = ["journald_filter_15"]
    [transforms.journald_filter_20.condition]
      "message.not_contains" = "Starting Proxmox VE replication runner"
[transforms.journald_filter_25]
    type = "filter"
    inputs = ["journald_filter_20"]
    [transforms.journald_filter_25.condition]
      "message.not_contains" = "Clearing outdated entries from certificate cache"
[transforms.journald_fqdn]
  type = "add_fields"
  inputs = ["journald_filter_25"]
  overwrite = true
  fields.host = "my.fqdn.com"
[sinks.journald_datadog_logs]
  api_key = "datadog_api_key"
  inputs = ["journald_fqdn"]
  type = "datadog_logs"
  endpoint = "tcp-intake.logs.datadoghq.eu:443"
  tls.enabled = true
  encoding.codec = "json"
...
```

### Debug Output

https://gist.github.com/spilla-quinten/4031666d11325a35d1f7eeccc95eba7f

### Expected Behavior

Vector runs without reporting errors.

### Actual Behavior

Vector fills the system journal with error entries containing "Invalid record from journald", like in the example debug output.

### Additional Context

Vector is running as a systemd service in physical Proxmox nodes. The problem does not occur when vector runs in physical nodes without Proxmox, nor in virtual machines nor in LXC containers.
