### ISSUE TITLE
Investigate reported high CPU usage

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#4582]
See https://discord.com/channels/742820443487993987/746070591097798688/766308591136931870

**Comment by spencergilbert** [comment]
Not able to pin anything down :frowning: - look's like I'm consuming towards a whole core per Vector (daemonset) compared to 200m for the aggregators I'm running that are doing most of the transforms.

**Comment by binarylogic** [comment]
cc @MOZGIII since this is related to k8s.

**Comment by MOZGIII** [comment]
What message does the link point to? I can't tell which one discord opens. :(

**Comment by MOZGIII** [comment]
> Not able to pin anything down 😦 - look's like I'm consuming towards a whole core per Vector (daemonset) compared to 200m for the aggregators I'm running that are doing most of the transforms.

Can you provide more data? Ideally the configuration, and the number of agents vs aggregators, and the average load per node.

**Comment by spencergilbert** [comment]
@MOZGIII if you can excuse the "wrapping" this is the config for both charts: https://gitlab.com/-/snippets/2030000, ln15 in both is the start of the helm values.

**Comment by MOZGIII** [comment]
Load on the nodes, yes. How many events per second, etc...

**Comment by spencergilbert** [comment]
Moving back here from discord... Currently running @MOZGIII test image:

![image](https://user-images.githubusercontent.com/11903873/96323640-f8c01080-0feb-11eb-8159-372917a90cde.png)

Still seeing a _slow_ rise in memory usage. This still has `internal_metrics` routing into `blackhole`, but shouldn't matter based on the changes that were made in the test image.

This is a view of _high memory limits_ seeing a strong increase in memory usage on Oct 15 (using nightly), followed by some hilarity caused by reducing the limit drastically.

![image](https://user-images.githubusercontent.com/11903873/96323710-5c4a3e00-0fec-11eb-96cf-24719fe98e8b.png)

There doesn't appear to be a noticeable difference in used memory between `internal_metrics` -> `blackhole` vs into `prometheus`. I thought having large numbers of timeseries created from per filepath metrics might have caused the growth, but it seems like @MOZGIII 's test image has disproved that.

@Hoverbear linked https://github.com/timberio/vector/issues/2356 thinking it could be similar, but at this point I'm not sure.

**Comment by MOZGIII** [comment]
My image completely disabled internal metrics, so if no difference is observed - the issue must be somewhere else. I created #4615 to expose the cardinality of the metrics directly as a counter, so this could be used to reassure the cardinality growth is manageable.

@spencergilbert so, it's only the agents that grow in size, right?

Could you post the effective configs here, so we have a better understanding what to expect? Also, some absolute value would be nice, as if the growth is in the order of kilobytes per minute it's expected, and if it's 10s of megabytes - it's probably something odd going on.



> @MOZGIII 's test image has disproved that.

For context, this is an image built from https://github.com/timberio/vector/pull/4606 and available at `mozgiii/vector-k8s-wip:bug1`.

**Comment by spencergilbert** [comment]
Only the agents, yes. I suspect that `file` source metrics are the likely culprit...

Running config:
```toml
# Configuration for vector.
# Docs: https://vector.dev/docs/

# Data dir is location controlled at the `DaemonSet`.
data_dir = "/vector-data-dir"
[log_schema]
  host_key = "host"
  message_key = "message"
  source_type_key = "source_type"
  timestamp_key = "timestamp"
# Ingest logs from Kubernetes.
[sources.kubernetes_logs]
  type = "kubernetes_logs"
[sources.internal_metrics]
  type = "internal_metrics"
[sources.json_logs]
  type = "file"
  include = ["/var/log/kube-audit/*.json", "/var/lib/rancher/rke/log/*.log"]
  
[sources.system_logs]
  type = "file"
  include = ["/var/log/syslog*", "/var/log/auth.log*"]
  
[transforms.json_parser]
  type = "json_parser"
  inputs = ["json_logs"]
  drop_invalid = true
  
[sinks.kafka]
  type = "kafka"
  inputs = ["kubernetes_logs","json_parser","system_logs"]
  bootstrap_servers = "logging-kafka-bootstrap.logging-kafka:9092"
  topic = "test-vector"
  [sinks.kafka.buffer]
    max_size = 104900000
    type = "disk"
    when_full = "block"
  [sinks.kafka.encoding]
    codec = "json"
  
[sinks.prometheus]
  type = "prometheus"
  inputs = ["internal_metrics"]
  address = "0.0.0.0:9598"
  namespace = "vector"
```

The growth on the problematic ones are MiBs. Unfortunately I've lost the prometheus metrics I gathered overnight, so still working on getting nice graphs
