### ISSUE TITLE
Vector file input on windows not always able to write checkpoint

### ISSUE THREAD

**Issue by johnkeates** [timberio/vector#4589]
### Vector Version
```
vector 0.10.0 (g0f0311a x86_64-pc-windows-msvc 2020-07-22)
```

### Vector Configuration File

```toml
data_dir = "C:/ProgramData/Vector/var/lib/vector"

# Input data 
[sources.webserver_placeholder_w3svc1_text_logs]
  type = "file"
  include = ["C:/inetpub/logs/LogFiles/W3SVC1/*.log"]

# Output data
[sinks.webserver_placeholder_w3svc_text_logs_to_welpwlog001_port_9000]
  type = "vector"
  inputs = ["webserver_placeholder_w3svc1_text_logs"]
  address = "logserver.domain.fqdn:9000"
```
### Expected Behavior
Vector should perhaps have retried or logged more details about what went wrong as it definitely had access.

### Actual Behavior
Vector threw an error

### Example Data
I don't think the data matters, but the data in this case was 9GB of IIS logs (W3SVC).

### Additional Context
Runs on Windows 2008 R2.
