### ISSUE TITLE
Support URL Encoding and PARAMS for prometheus config

### ISSUE THREAD

**Issue by raghu999** [timberio/vector#4642]
### Current Vector Version

```
vector 0.10.0 (g0f0311a x86_64-unknown-linux-gnu 2020-07-22)
```

### Use-cases

Currently, Vector doesn't support passing params as a config parameter and users have to manually use an url encoder to pass Prometheus `match` config
```
scrape_configs:
- job_name: application_scraper
  honor_labels: true
  params:
    match[]:
    - '{__name__=~"application:aggregate:.*"}'
  scrape_interval: 1m
  scrape_timeout: 30s
  metrics_path: /federate
  scheme: http
```
The above is our prometheus configuration we want to collect data from prometheus federate endpoint and ship it to elasticsearch

### Attempted Solutions

I reached out to vector community via discord and currently we are using a manual way of encooding the url to work with vector https://discord.com/channels/742820443487993987/746070591097798688/766694036785725462

**Comment by binarylogic** [comment]
Thanks for reporting. We're on it!

**Comment by jamtur01** [comment]
@jszwedko Based on the `/metrics` et al stuff - any thoughts on an implementation for this?

**Comment by jszwedko** [comment]
I was thinking about this a bit more and I think we could generalize an approach for this by essentially allowing deconstructed urls anywhere we currently have them in our TOML configuration. That is, where one might write

```toml
endpoint = "https://localhost:8989/foo/bar?a=b&c=d"
```

could also allow:

```toml
[[endpoint]]
scheme = "https"
host = "localhost"
port = 8989
path = "/foo/bar"
query.a=b
query.c=d
```

Additionally, we could make this easier to use in the case where you just want to set query parameters by allowing configuration like:

```toml
[[endpoint]]
url = "https://localhost:8989/foo/bar"
query.a=b
query.c=d
```

Where `url` would be used as the base and then any additionally configured fields override.

This could also be written as:

```toml
endpoint.url = "https://localhost:8989/foo/bar"
endpoint.query.a=b
endpoint.query.c=d
```

I'd need to verify how we'd support that with our config deserializing, but it seems plausible.
