### ISSUE TITLE
Update `swimlanes` transform to use the Remap conditional syntax

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#4643]
Like we're doing in #4574, we want to update the `swimlanes` transform to take a Remap conditional expression instead of the crazy TOML conditions:

```toml
[transforms.swimlanes]
type = "swimlanes"
lanes.debug = '.level == "debug"'
lanes.info = '.level == "info"'
lanes.error = '.level == "error" || .level == "fatal"'
# ...
```

**Comment by JeanMertz** [comment]
This will be tackled in #4743, with a slightly different syntax then what's proposed here:

```toml
[transforms.swimlanes]
	type = "swimlanes"

	lanes.debug.type = "remap"
	lanes.debug.source = '.level == "debug"'

	lanes.info.type = "remap"
	lanes.info.source = '.level == "info"'

	lanes.error.type = "remap"
	lanes.error.source = '.level == "error" || .level == "fatal"'
```

Note that `type` can be omitted, but it defaults to `check_fields`, which is why you can write:

```
lanes.debug."level.eq" = "debug"
```

But you can't write:

```
lanes.debug.source = '.level == "debug"'
```

We could, at some point, swap the default condition check from `check_fields` to `remap`, but that's obviously a breaking change.
