### ISSUE TITLE
Blackhole does not count full event bytes

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#4704]
Mentioned in discord: https://discordapp.com/channels/742820443487993987/751109034827972709/768956157972578334

@lucperkins observed that the `blackhole` sink was reporting 0 bytes processed for log events even though events were flowing through. This turned out to be due to the fact that his logs did not contain a `message` field which is what the `blackhole` sink currently counts for logs.

```toml
[sources.logs]
type = "docker"
include_containers = ["flog"]

[sinks.out]
type = "blackhole"
inputs = ["logs"]
```
