### ISSUE TITLE
Support Elasticsearch basic auth (x-pack) security

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#472]
The primary goal of this issue is to support [x-pack](https://www.elastic.co/downloads/x-pack) security. Based on my research, this is just [basic auth](https://tools.ietf.org/html/rfc7617), requiring a username and password, but it was hard to determine from [Elastic's docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html).

That said, I propose that we offer a `basic_auth` table in the same way that we do the `http` sink:

```toml
[sinks.<sink-id>]
  type = "elasticsearch"

  [sinks.<sink-id>.basic_auth]
    user = "username"
    password = "password"
```

This simply adds a `Authorization` header using the `Basic` strategy (base64 encoding the `<user>:<password>` token).

Additionally, this could be accomplished by adding a custom `Authorization` header and supplying the base 64 encoded token yourself. See #361 for support on custom headers. I mention #361 since the change here might overlap or be shared.
