### ISSUE TITLE
Better handling of timestamp field for splunk_hec sink

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#4774]
This isn't really a bug, but confusing behavior that I think we can improve upon. Maybe as part of #3910 .

A user wanted to parse out the `time` field from their Docker logs (stored in files). This field is a RFC3339 timestamp.

I initially gave them this configuration:

```toml
data_dir = "/tmp/vector"

[sources.in]
  type = "file"
  include = ["/tmp/tmp.log"]

[transforms.json]
  type = "json_parser"
  inputs = ["in"]

[transforms.coerce]
  type = "coercer"
  inputs = ["json"]
  types.time = "timestamp"

[transforms.add_fields]
  type = "add_fields"
  inputs = ["coerce"]
  fields.timestamp = "{{ time }}"

[sinks.console]
  type = "console"
  inputs = ["add_fields"]
  encoding.codec = "json"


[sinks.splunk]
  type = "splunk_hec"
  inputs = ["add_fields"]
  host = "http://localhost:9090"
  token = "abcd1234"
  encoding.codec = "json"
```

But this silently failed to set the timestamp in Splunk to the expected timestamp as:

* The `add_fields` transform set the `timestamp` to a string value (due to the string interpolation). I think this will be improved by the upcoming `remap` transform which would allow for assigning keys directly without interpolation.
* The `splunk_hec` sink then ignored this timestamp value as it was a string rather than a timestamp, internally, and so silently set the timestamp to the current timestamp. I think at least a warning would be helpful here, but we could consider going further and attempting to coerce the timestamp.
* The `json_parser` transform still seems a bit unfortunate over setting the codec on the `file` source.

A working config looks like:

```toml
data_dir = "/tmp/vector"

[sources.in]
  type = "file"
  include = ["/tmp/tmp.log"]

[transforms.json]
  type = "json_parser"
  inputs = ["in"]

[transforms.add_fields]
  type = "add_fields"
  inputs = ["json"]
  fields.timestamp = "{{ time }}"

[transforms.coerce]
  type = "coercer"
  inputs = ["add_fields"]
  types.timestamp = "timestamp"

[sinks.console]
  type = "console"
  inputs = ["coerce"]
  encoding.codec = "json"

[sinks.splunk]
  type = "splunk_hec"
  inputs = ["coerce"]
  host = "http://localhost:9090"
  token = "abcd1234"
  encoding.codec = "json"
```
