### ISSUE TITLE
New `filter` transform

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#479]
This is a simple transform that filters events based on set conditions. This is an evolution of the current [`field_filter` transform](https://github.com/timberio/vector/blob/master/src/transforms/field_filter.rs). This allows users to build filtered pipelines, sending a subset of data to a sink, for example.

### Example

The following example filters events to those with a `"status"` of `500`:

```toml
[transforms.errors]
  type = "filter"
  
  [[transforms.errors.conditions]]
    "status.eq" = 500
```

### Requirements

- [ ] Support the `eq`, `neq`, `gt`, `gte`, `lt`, `lte` conditions.
- [ ] The condition values should support multiple types. If there is a type mismatch between the provided value and the value on the event, log a rate-limited (https://github.com/timberio/vector/issues/418) `warn` level log saying that there was a type mismatch.
- [ ] If the condition is not met, drop the event. If the condition is met, output it.
