### ISSUE TITLE
deprecate/remove `check_fields` condition variant

### ISSUE THREAD

**Issue by JeanMertz** [timberio/vector#4791]
In #4743 a new `remap` condition was introduced, allowing four different condition variants:

* `check_fields`
* `is_log`
* `is_metric`
* `remap`

Since you can write any condition you could write with `check_fields` using `remap`, and the latter is more expressive, allows more complicated checks, and doesn't involve writing sometimes awkward TOML syntax, the idea is to deprecate `check_fields`.

## Next Steps

If we want to move forward with this, there are four steps to consider:

1. Emit a warning when people use `check_fields` (since this variant is the default, it would also warn if they don't define any specific condition variant)
2. Remove mention of `check_fields` in documentation (or discourage usage through added documentation).
3. Swap the default condition variant from `check_fields` to `remap`.
4. Remove all code related to `check_fields`, making it so that people can no longer use this condition variant at all.

**Step 1** is easy to introduce, but will introduce quite some noise for many people, given the ubiquity with which this variant is used both in transforms and Vector unit tests.

**Step 2** seems fairly straightforward, although simply removing mention of it might confuse people who still use the syntax when writing Vector unit tests for example.

**Step 3** is backward-breaking (see **problem** section below), and can potentially hit many people (both for transform configurations, and Vector unit tests), but does have an easy work-around by adding an explicit `type = "check_fields"` to the conditions in the Vector config file.

**Step 4** seems like something we only want to do close to a 1.0 release, as it'll prevent people from just slapping on a `type = "check_fields"` in their config to work around the swapped default introduced in step 2.

## Problem

`check_fields` is the default condition variant if an explicit `type` isn't defined, which means that you can currently write:

```toml
[transforms.reduce]
	type = "reduce"
	ends_when."message.eq" = "done"
```

If we flipped the default, all existing configs using these conditionals would fail, since the `remap` variant expects a `source` field to exist.

It is also heavily used in unit tests that people (and we ourselves) write for their Vector configurations.

## Solution

If we want to avoid too much breakage, but still swap the default for people, we could write up some kind of way to auto-detect which default to pick:

Given these examples:

```toml
[transforms.reduce_1]
	type = "reduce"
	ends_when."message.eq" = "done"

[transforms.reduce_2]
	type = "reduce"
	ends_when.source = """
		.message == "done"
	"""
```

We could check if the condition map (in this case `ends_when`) contains a single field, and its field is named `source`. If it is, we set the type to `remap`, otherwise we keep the default `check_fields`.

Since `check_type` fields always have a predicate attached to them, there's no risk of someone writing `ends_when.source`, and expecting it to default to `check_fields`.

Of course, this assumes we really care about this being a breaking change. If we don't, we can just document this, flip the switch, and ask people to update their configs.

We could even introduce a `check_field` function in remap, to allow people to quickly copy/paste their existing checks into remap:

```js
check_field("message.eq", "done")
```

## Solution, Act 2

Even if we swap the default, there's still a question of syntax.

Right now, you would write the following:

```toml
[transforms.reduce]
	type = "reduce"
	ends_when.type = "remap"
	ends_when.source = """
		.message == "done"
	"""
```

Making `remap` the default feels a bit awkward, as you'd have to write `ends_when.source`:

```toml
[transforms.reduce]
	type = "reduce"
	ends_when.source = """
		.message == "done"
	"""
```

We _could_ make conditions either a string or a map, in which case a string would mean it's the source of the `remap` condition variant, and a map means it's either the default variant, or an explicitly enabled variant:

```toml
[transforms.reduce]
	type = "reduce"

	# string, default to `remap`, and use value as remap source
	ends_when = ".foo  == true"

	# map, default to whatever variant we've set as default (currently `check_fields`, later potentially `remap`)
	ends_when.source = ".foo == true"

	# map, with an explicit variant set
	ends_when.type = "check_fields"
	ends_when."foo.eq" = true
```

**Comment by binarylogic** [comment]
@FungusHumungus I'd like to see us follow through on this before 0.12. I think we should completely remove the `check_fields` condition type as it makes the UX very clunky. For example:

```toml
[transforms.route]
type = "route"
routes.debug.type = "remap"
routes.debug.source = '.level == "debug"'
routes.info.type = "remap"
routes.info.source = '.level == "info"'
routes.warn.type = "remap"
routes.warn.source = '.level == "warn"'
routes.error.type = "remap"
routes.error.source = '.level == "error"'
```

As you can, this is pretty verbose, and I don't foresee us support other variations of checks in the future. Therefore, it would be much easier to just do this:

```toml
[transforms.route]
type = "route"
routes.debug = '.level == "debug"'
routes.info = '.level == "info"'
routes.warn = '.level == "warn"'
routes.error = '.level == "error"'
```

Which leaves us with what to do with `is_metric` and `is_log`. We should just add Remap function equivalents that look for specific shapes.

Happy to discuss this further, but I think we should make this change before 0.12 if we want to do this.

**Comment by JeanMertz** [comment]
I agree we should just rip off the band-aid.

As for `is_metric` and `is_log`, we can still support those. We'd just swap the default to `type = "remap"`

So, given your example, you'd be able to write:

```toml
[transforms.route]
type = "route"
routes.debug = '.level == "debug"'
```

Or:

````toml
[transforms.route]
type = "route"
routes.debug.type = "remap"
routes.debug.source = '.level == "debug"'
```

Or:

````toml
[transforms.route]
type = "route"
routes.debug.type = "is_metric"
```

Or:

````toml
[transforms.route]
type = "route"
routes.debug.type = "is_log"
```
