### ISSUE TITLE
`source_ip` field contains `ip:port` when using `syslog` source in `udp` mode

### ISSUE THREAD

**Issue by khaskelberg** [timberio/vector#4792]
### Vector Version

```
vector 0.10.0 (g0f0311a x86_64-unknown-linux-gnu 2020-07-22)
```

### Vector Configuration File

```toml
[sources.listener]
    type="syslog"
    address="0.0.0.0:514"
    mode="udp"

[sinks.console]
    inputs=["listener"]
    type="console"
    encoding.codec="json"  
```

### Debug Output

https://gist.github.com/khaskelberg/8a9c2d7232486113f88639fcca8632ee

### Expected Behavior
`source_ip` field should contain only ip address `127.0.0.1`
### Actual Behavior
`source_ip` field contains `ip:port` - `127.0.0.1:58443`

### Additional Context
This behavior only happens when using `syslog` source in `udp` mode. `tcp` mode works correctly and shows only ip address `127.0.0.1`
