### ISSUE TITLE
PubSub sink issue after upgrading to 0.10.0

### ISSUE THREAD

**Issue by vlameiras** [timberio/vector#4851]
### Vector Version

```
0.10.0
```

### Vector Configuration File

```toml
    [sources.logs_app]
       address = "0.0.0.0:5514"
       mode = "tcp"
       type = "syslog"

    [sinks.my_sink_id]
      # General
      type = "console" # required
      inputs = ["logs_app"] # required
      target = "stdout"
      encoding.codec = "json"
```
