### ISSUE TITLE
Issue parsing syslog message in v0.10.0

### ISSUE THREAD

**Issue by vlameiras** [timberio/vector#4852]
### Vector Version

```
v0.10.0 and newer
```

### Vector Configuration File

```toml
    [sources.logs_app]
       address = "0.0.0.0:5514"
       mode = "tcp"
       type = "syslog"

    [sinks.my_sink_id]
      # General
      type = "console" # required
      inputs = ["logs_app"] # required
      target = "stdout"
      encoding.codec = "json"
```

### Debug Output

<https://gist.github.com/vlameiras/5dce8f87cb30d46bc1a817356f52931e>

### Expected Behavior

Vector should have parsed the message and place a single one in the console sink.

### Actual Behavior

From `v0.10.0` onwards I get my syslog message split in two messages.

### Additional Context

This was reproduced locally with the official Docker images at Dockerhub. Had an initial chat with @Hoverbear regarding this issue at Discord, thanks for the support 👍
