### ISSUE TITLE
Sending `1 <23>4` twice to the `syslog` source will cause it to go into an infinite loop

### ISSUE THREAD

**Issue by FungusHumungus** [timberio/vector#4895]
### Vector Version

master

### Vector Configuration File

```toml
[sources.remote_syslog]
  type = "syslog"
  address = "0.0.0.0:6515"
  mode = "tcp"

[sinks.stdout]
  type = "console"
  inputs = ["remote_syslog"]
  target = "stdout"
  encoding = "json"
```

### Debug Output

Send this to Vector: 

```sh
echo "1 <23>4\n1 <23>4" | nc localhost 6515 
```

The source will go into an infinite loop with this message:

```
Nov 05 23:47:06.467  WARN source{component_kind="source" component_name=remote_syslog component_type=syslog}:connection{peer_addr=127.0.0.1}: vector::sources::util::tcp: Failed to read data from TCP source. error=Unable to decode message len as number
```

repeated ad infinitum.

You have to `kill -9` Vector to stop it.

### Expected Behavior

I'm not 100% sure what should happen. The `1 ` at the start of the message is saying the syslog message is 1 byte long, which is probably a ridiculous length for a message to be. It should probably not get stuck in a loop though.
