### ISSUE TITLE
Remap driven input filters for segmenting streams

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#4923]
An idea to improve stream segmentation is introducing the concept of input modifiers. This would make it easy to operate on a segment of a stream without having to define a full `filter` or `swimlanes` transform.

## Example

```toml
[sources.file]
type = "file"
# ...

[sinks.elasticsearch]
type = "elasticsearch"
inputs = ['file.filter(.level != "debug")']

[sinks.s3]
type = "aws_s3"
inputs = ['file']
```

---

This idea needs a lot more discussion in the broader context of building pipelines. I'd also like for the Remap language to settle a little more before we proceed with this.
