### ISSUE TITLE
vector test requires unit tests to be co-located with the config

### ISSUE THREAD

**Issue by spencergilbert** [timberio/vector#4950]
### Vector Version

```
vector 0.11.0 (g68a5c43 x86_64-unknown-linux-gnu 2020-09-11)
```

### Vector Configuration File

```toml
# Configuration for vector.
# Docs: https://vector.dev/docs/

# Data dir is location controlled at the `DaemonSet`.
data_dir = "/vector-data-dir"

[log_schema]
host_key = "host"
message_key = "message"
source_type_key = "source_type"
timestamp_key = "timestamp"

[sources.internal_metrics]
type = "internal_metrics"

# Ingest logs from Kubernetes.
[sources.kubernetes_logs]
type = "kubernetes_logs"

[sources.json_logs]
type = "file"
include = ["/var/log/kube-audit/*.json", "/var/lib/rancher/rke/log/*.log"]

[sources.system_logs]
type = "file"
include = ["/var/log/syslog*", "/var/log/auth.log*"]

[transforms.json_parser]
type = "json_parser"
inputs = ["json_logs"]
drop_invalid = true

[sinks.kafka]
type = "kafka"
inputs = ["kubernetes_logs","json_parser","system_logs"]
bootstrap_servers = "logging-kafka-bootstrap.logging-kafka:9092"
topic = "vector-rc0"
# Default configuration is to block until message is committed by all ISRs
#librdkafka_options."request.required.acks" = "1"
[sinks.kafka.encoding]
codec = "json"

[sinks.prometheus]
type = "prometheus"
inputs = ["internal_metrics"]
address = "0.0.0.0:9598"
default_namespace = "agent"

[[tests]]
name = "rke_logs"
[[tests.inputs]]
insert_at = "json_parser"
type = "log"
log_fields.message = "{\"log\":\"W1108 08:48:35.665065   12995 volume_linux.go:49] Setting volume ownership for /var/lib/kubelet/pods/92e81ecf-6b15-4543-8111-5462099d498f/volumes/kubernetes.io~secret/exporter-kube-state-cluster-monitoring-token-4l94j and fsGroup set. If the volume has a lot of files then setting volume ownership could be slow, see https://github.com/kubernetes/kubernetes/issues/69699\\n\",\"stream\":\"stderr\",\"time\":\"2020-11-08T08:48:35.665242398Z\"}"
log_fields.source_type = "file"
log_fields.timestamp = "2020-11-10T03:10:56.454450647Z"
[[tests.outputs]]
extract_from = "json_parser"
[[tests.outputs.conditions]]
type = "check_fields"
"stream.exists" = true
"log.exists" = true

[[tests]]
name = "kube_audit_logs"
[[tests.inputs]]
insert_at = "json_parser"
type = "log"
log_fields.message = "{\"kind\":\"Event\",\"apiVersion\":\"audit.k8s.io/v1\",\"level\":\"Metadata\",\"auditID\":\"3ac4f198-93be-451f-8d51-1ffa65cae058\",\"stage\":\"RequestReceived\",\"requestURI\":\"/api/v1/persistentvolumes/pvc-e6069419-fea8-4678-9b2c-d935c7a92b98\",\"verb\":\"get\",\"user\":{\"username\":\"system:serviceaccount:maya-system:maya-io\",\"uid\":\"a8718c07-26d5-4301-8754-680ec975f28d\",\"groups\":[\"system:serviceaccounts\",\"system:serviceaccounts:maya-system\",\"system:authenticated\"]},\"sourceIPs\":[\"10.101.0.78\"],\"userAgent\":\"kubectl/v1.15.3 (linux/amd64) kubernetes/2d3c76f\",\"objectRef\":{\"resource\":\"persistentvolumes\",\"name\":\"pvc-e6069419-fea8-4678-9b2c-d935c7a92b98\",\"apiVersion\":\"v1\"},\"requestReceivedTimestamp\":\"2020-11-10T03:22:46.282820Z\",\"stageTimestamp\":\"2020-11-10T03:22:46.282820Z\"}"
log_fields.source_type = "file"
log_fields.timestamp = "2020-11-10T03:22:46.285462828Z"
[[tests.outputs]]
extract_from = "json_parser"
[[tests.outputs.conditions]]
type = "check_fields"
"kind.exists" = true
"user.exists" = true
```

### Expected Behavior

Runn `vector test config/*.toml` with the above config split into `config/vector.toml` and `config/test.toml`, including just the `[[test]]` sections in `test.toml`  to pass, as it does as a single file.

### Actual Behavior

The unit tests fail:
```sh
# vector test config/*.toml
Nov 10 17:37:35.113  INFO vector: Log level "info" is enabled.
Running config/test.toml tests
Nov 10 17:37:35.172 ERROR vector::unit_test: Failed to execute config/test.toml tests:
Failed to build test 'rke_logs':
  inputs[0]: unable to locate target transform 'json_parser'
Failed to build test 'kube_audit_logs':
  inputs[0]: unable to locate target transform 'json_parser'
```

As a single file:
```sh
# vector test config/*.toml
Running config/vector.toml tests
test config/vector.toml: rke_logs ... passed
test config/vector.toml: kube_audit_logs ... passed
```

If this isn't a bug, I think this would be a useful feature to enable users to have smaller more specific files that are easier to reason about.
