### ISSUE TITLE
Better support multiline JSON event ingestion

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#4952]
Requested in discord: https://discord.com/channels/742820443487993987/746070591097798688/775827674228326541

This is related to https://github.com/timberio/vector/issues/1559 (better handling of s-expressions).

Similar to s-expressions, it can be difficult to merge together the lines of a multiline JSON object, for example:

```json
{
  "event": {
    "id": "AA",
    "type": "BB"
  }
}
```
We can try to depend on specific details of the JSON like that a new object always starts with `{` as the first character of a line, but it'd be nice to handle this in a more general fashion.

https://github.com/timberio/vector/issues/1559 was closed by pointing at https://vector.dev/guides/advanced/merge-multiline-logs-with-lua/ but it still isn't clear to me how this would work with the `lua` transform. It'd be nice to provide a guide for this sort of context-free parsing if we do just want to pass it off onto the user by way of asking them to implement a `lua` transform.

**Comment by binarylogic** [comment]
@jszwedko it seems like a `json_parser` + `reduce` transform would solve this with the most revent changes?

**Comment by jszwedko** [comment]
@binarylogic I'm not sure what conditions you'd use with the `reduce` transform to handle a multiline JSON object without depending on attributes of it like that `{` will always be the first character of the line when starting a new object. What if I had a file that looked like:

```json
{
  "event":
{
    "id": "AA",
    "type": "BB"
}
}
{ "event": {
    "id": "AA",
    "type": "BB"
  }}
{"event": {
    "id": "AA",
    "type": "BB"}}
```

I'm close this saying that it is an uncommon case and that we should encourage users to have single-line JSON messages, but I figured it'd be good to report it to have somewhere to point to at least.

**Comment by binarylogic** [comment]
I see. I thought they were trying to merge full JSON documents. We actually encountered this in certain situations with Timber. The solution is to escape new line characters in the JSON strings directly. Ex:

```json
{"message": "hello\\nworld"}
```

Wouldn't the unescaped version be invalid JSON?

**Comment by jszwedko** [comment]
Ah, I see, that is a bit different. I think requiring users to escape `\n`s in the text is a reasonable assumption. It is invalid JSON otherwise.

**Comment by karsten-wagner** [comment]
I have come across the same requirement to parse pretty-printed JSON files. My solution based on the hints in this thread is to use a custom lua transformation. My scenario contains always valid JSON documents, so I did not add any error handling to avoid memory spikes for large files that do not contain valid JSON eventually.

The basic idea is to count the characters that define where a JSON document starts or ends (curly braces). Once the number of opening and closing curly braces matches, a full JSON document must be reached. This works also for documents that do not start on the first line of the file. In case you do not have top level JSON arrays, you can delete the section that counts brackets.

My test setup runs in docker.

## Limitations

- Input stream (e.g., file) has to contain valid JSON documents. If you open curly braces that are never closed on large files, this setup may run into a memory spike (and eventually crash?!).
- JSON documents need to end one per line. You cannot mix two documents in the same line as the aggregator will not split them.
- The aggregator does not consider comments in the source file, so curly braces and brackets in comments will be counted as part of a JSON document.
- The aggregator does not consider escaped character sequences, so curly braces in encoded JSON will still be counted, so your JSON values better not contain curly braces and brackets within its content.

## Vector pipeline

```TOML
[api]
enabled = true
address = "0.0.0.0:8686"

[sources.vector_logs]
type = "internal_logs"

[sinks.stderr]
type = "console"
inputs = ["vector_logs"]
target = "stderr"
encoding.codec = "text"

[sources.text]
type = "file"
include = ["/data/multiline-json-test.txt"]

[transforms.aggregator]
type = "lua"
version = "2"
inputs = ["text"]
hooks.process = "Process"
source = "require('simple-json-aggregator')"

[transforms.conversion]
type = "remap"
inputs = ["aggregator"]
source = ". = parse_json!(string!(.message))"

[sinks.stdout]
type = "console"
inputs = ["conversion"]
target = "stdout"
encoding.codec = "json"
```

## `simple-json-aggregator.lua`

```lua
-- This lua function will aggregate valid multiline JSON events, e.g., resulting from file read
function Process(event, emit)
  if MergedEvent == nil then -- a global variable containing the merged event
    MergedEvent = event -- if it is empty, set it to the current event
  else -- otherwise, concatenate the line in the stored merged event with the next line
    MergedEvent.log.message = MergedEvent.log.message .. event.log.message
  end

  -- Count brackets to handle top level JSON arrays
  local _, b1 = MergedEvent.log.message:gsub("%[","")
  local _, b2 = MergedEvent.log.message:gsub("%]","")
  if b1 > b2 then
    return -- continue to merge events until JSON document is complete
  end
  -- Count curly braces to handle JSON document
  local _, c1 = MergedEvent.log.message:gsub("{","")
  local _, c2 = MergedEvent.log.message:gsub("}","")
  if c1 > c2 then
    return -- continue to merge events until JSON document is complete
  end

  emit(MergedEvent) -- emit the resulting event
  MergedEvent = nil -- clear the merged event
end
```

## Test file `/data/multiline-json-test.txt`

- `foo03` is a document not starting at first character of the line
- `foo08` mixes a pretty-printed section with a document where all content starts on the first character of the line

```text
{"foo00":"bar00"}
{ "foo01" : "bar00" }
{ "foo02" : 
"bar00" }
   {     "foo03"  :   
        "bar00"   }
[{"foo04":"bar00"}]
[{"foo05":"bar00"},{"foo05":"bar01"}]
[
  {"foo06":"bar00"},{"foo06":"bar01"}
]
[
  {
    "foo07": "bar00"
  },
  {
    "foo07": "bar01"
  }
]
[
  {
    "foo08": {"bar00":"baz00"}
  },
{
"foo08"
:
{
"bar01"
:"baz00"
}
}
]

```

## Vector logs

You can see the documents have been aggregated from the source file and been emitted one at a time.

```text
2023-04-29 10:29:18 vector  | 2023-04-29T08:29:18.701814Z  INFO source{component_kind="source" component_id=text component_type=file component_name=text}:file_server: vector::internal_events::file::source: Found new file to watch. file=/data/multiline-json-test.txt
2023-04-29 10:29:18 vector  | Found new file to watch.
2023-04-29 10:29:18 vector  | {"foo00":"bar00"}
2023-04-29 10:29:18 vector  | {"foo01":"bar00"}
2023-04-29 10:29:18 vector  | {"foo02":"bar00"}
2023-04-29 10:29:18 vector  | {"foo03":"bar00"}
2023-04-29 10:29:18 vector  | {"foo04":"bar00"}
2023-04-29 10:29:18 vector  | {"foo05":"bar00"}
2023-04-29 10:29:18 vector  | {"foo05":"bar01"}
2023-04-29 10:29:18 vector  | {"foo06":"bar00"}
2023-04-29 10:29:18 vector  | {"foo06":"bar01"}
2023-04-29 10:29:18 vector  | {"foo07":"bar00"}
2023-04-29 10:29:18 vector  | {"foo07":"bar01"}
2023-04-29 10:29:18 vector  | {"foo08":{"bar00":"baz00"}}
2023-04-29 10:29:18 vector  | {"foo08":{"bar01":"baz00"}}
```

**Comment by JR-Otava** [comment]
Hi...
I also have this problem...

The solution, in my mind is to change the codec indicator..
```yaml
sources:
  prtg_post:
    type: http
    method: POST
    decoding:
      codec: 
        jsonl   Single line JSON
        jsonc   compact JSON alias for 'json'
        json_pretty: regular valid JSON which may include linebreaks (Entire post blob)
```
  I would also recommend deprecateing "json" in favor of a more explicit indicator of what is expected
