### ISSUE TITLE
`vector validate --deny-warnings` doesn't exit non-zero for unwired components

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#4995]
### Vector Version

```
vector 0.11.0 (g0bebc74 x86_64-unknown-linux-gnu 2020-11-11)

```

### Vector Configuration File

```toml
[sources.in]
  type = "stdin"

[sources.in2]
  type = "generator" # required
  lines = ["Line 1", "Line 2"] # required

[sinks.my_sink]
  type = "console"
  inputs = ["in"]
  encoding.codec = "json"
```

### Debug Output

```
➜  vector git:(master) vector validate -d /tmp/tmp.toml
Nov 11 20:01:22.963  WARN vector::config::compiler: Source "in2" has no consumers
√ Loaded ["/tmp/tmp.toml"]
√ Component configuration
√ Health check `my_sink`
--------------------------
                 Validated
➜  vector git:(master) echo $?
0

```

### Expected Behavior

It exits non-zero.

### Actual Behavior

It exits 0.
