### ISSUE TITLE
Elasticsearch: support basic-auth credentials in "host" URL

### ISSUE THREAD

**Issue by njam** [timberio/vector#5019]
### Current Vector Version
```
vector 0.10.0 (g0f0311a x86_64-unknown-linux-musl 2020-07-22)
```

### Use-cases

I'm trying to configure the elasticsearch sink's hostname and authentication using environment variables.

### Attempted Solutions

I can configure the sink like this:
```toml
[sinks.my_elasticsearch_sink]
type = "elasticsearch"
[...]
host = "${ES_HOST}"
auth.user = "${ES_USER}"
auth.password = "${ES_PASSWORD}"
```

### Proposal

Allow to include basic-auth credentials in the URL passed to the "host" field.
```
https://elastic:password@example.com:9200
```

So the config would be simplified to:
```toml
[sinks.my_elasticsearch_sink]
type = "elasticsearch"
[...]
host = "${ES_HOST}"
```

### References

Passing basic-auth in the "host" is supported by Logstash.  
It makes configuration a bit easier, because a single field contains all necessary information to communicate to the Elasticsearch server, so only a single field needs to be changed when changing the server.
