### ISSUE TITLE
NixOS: Configuration error: unknown variant `journald`

### ISSUE THREAD

**Issue by happysalada** [timberio/vector#5097]
In the course of providing a service for NixOS I'm running into the following error

```
Nov 13 00:35:44.887 ERROR vector: Configuration error: "/nix/store/qiw20ic94pzsklar8cbh336dpxj0va8j-vector.toml": unknown variant `journald`, expected one of `docker`, `file`, `generator`, `http`, `internal_metrics`, `kafka`, `logplex`, `prometheus`, `socket`, `splunk_hec`, `statsd`, `stdin`, `syslog`, `vector` for key `sources.input.type`
```

On NixOS vector is build with the following features enabled.

```
 "leveldb" "leveldb/leveldb-sys-2" "jemallocator" "rdkafka" "rdkafka/dynamic_linking"  "sinks" "sources" "transforms" 
```

It seems that the journald source should be included right?

I'm not sure why I'm getting the error, nor how to move forward

### Vector Version

```
10.0
```

### Vector Configuration File

```toml
[sinks]
[sinks.file]
inputs = ["level"]
path = "./logs/day-%d.log"
type = "file"

[sinks.file.encoding]
codec = "ndjson"

[sinks.loki]
endpoint = "http://localhost:3100"
inputs = ["level"]
type = "loki"

[sinks.loki.labels]
level = "{{ level }}"

[sources]
[sources.input]
type = "journald"

[transforms]
[transforms.level]
inputs = ["input"]
type = "lua"
version = "2"

[transforms.level.hooks]
process = "function (event, emit)\n  message = event.log.message\n  level = string.match(message, \"le?ve?l=(%w+)\")\n  msg = string.match(message, \"me?ss?a?ge?=(.+)\")\n  if level then\n    event.log.level = level\n    event.log.message = msg\n  end\n  -- Very important! Emit the processed event.\n  emit(event)\nend\n"

```

### Expected Behavior

no errors

### Actual Behavior

errors in the configuration

### Additional Context

this is on NixOS, using the default package. Perhaps the mistake is coming from how vector is built on NixOS. If I just have some ideas of where the problem could be coming from, I'm interested in testing myself.

### References

Here is a reference to the PR https://github.com/NixOS/nixpkgs/pull/103393

Here is a reference of how vector is build on NixOS.
https://github.com/johanot/nixpkgs/blob/a03c8a8f35613b4ca501d09c788545d1fd7376ec/pkgs/tools/misc/vector/default.nix
(the language is Nix, but hopefully things should be fairly transparent)
