### ISSUE TITLE
Global `healthchecks` option

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#5178]
Healthchecks can be disabled on a per-component basis via the `healthcheck` option, but users are not able to do this globally. We should add a global `healthcheck` option that disables healthchecks entirely.

## Example

Given the upcoming changed in #4203 I am proposing the following options.

### Default

```toml
healthchecks.enabled = true # default
healthchecks.require_healthy = false # default
```

- [ ] When `healthchecks.require_healthy` is set to `true` Vector will exit on failure. This is the same as the `--require-healthy` startup flag.
- [ ] The `--require-healthy` startup flag takes precedence.

### Disable

```toml
healthchecks.enabled = false
```

- [ ] Log that healthchecks have been disabled.
