### ISSUE TITLE
Negative throughput from `vector top`

### ISSUE THREAD

**Issue by spencergilbert** [timberio/vector#5319]
### Vector Version

```
vector 0.11.0 (gafc64e5 x86_64-unknown-linux-gnu 2020-12-01)
```

### Vector Configuration File

```toml
# Data dir is location controlled at the `DaemonSet`.
data_dir = "/vector-data-dir"

[api]
enabled = true

[log_schema]
host_key = "host"
message_key = "message"
source_type_key = "source_type"
timestamp_key = "timestamp"

[sources.internal_metrics]
type = "internal_metrics"

# Ingest logs from Kubernetes.
[sources.kubernetes_logs]
type = "kubernetes_logs"

[sources.json_logs]
type = "file"
include = ["/var/log/kube-audit/*.json", "/var/lib/rancher/rke/log/*.log"]

[sources.system_logs]
type = "file"
include = ["/var/log/syslog*", "/var/log/auth.log*"]

[transforms.json_parser]
type = "json_parser"
inputs = ["json_logs"]
drop_invalid = true

[sinks.vector]
type = "vector"
inputs = ["kubernetes_logs","json_parser","system_logs"]
address = "vector-aggregator:9000"

[sinks.prometheus]
type = "prometheus_exporter"
inputs = ["internal_metrics"]
address = "0.0.0.0:9598"
default_namespace = "agent"
```

### Expected Behavior

Greater than 0 throughput

### Actual Behavior

![image](https://user-images.githubusercontent.com/11903873/100787046-0b967500-33e1-11eb-92f7-b43fe6e65504.png)

Negative throughput reported

I'm going to try some tests and see if it happens on other sources aside from `file`
