### ISSUE TITLE
Does not convert timestamp format

### ISSUE THREAD

**Issue by 065191** [timberio/vector#5331]
### Vector Version
vector 0.10.0 (g0f0311a x86_64-unknown-linux-gnu 2020-07-22)

### Vector Configuration File

```toml
[sources.in_limit_request]
  type                          = "file"
  include                       = [ "/********/*_limit_request.log*",
                                          "/l********/*_limit_request.log"
                                  ]

[transforms.parser_limit_request]
  type     = "grok_parser"
  inputs   = ["in_limit_request"]
  pattern  = '%{DATA:[time]} \[%{LOGLEVEL:severity}\] %{POSINT:pid}#%{NUMBER}: \*%{DATA} %{DATA:error_message}\, excess: %{NUMBER:limit} by zone \"%{DATA:zone}\"\, client: %{IP:client_ip}\, server: %{IPORHOST}\, request: \"%{WORD:method} %{DATA:request} HTTP/%{NUMBER:http_version}\"\, host: \"%{IPORHOST:host}\"?(?:, referrer: \"%{URI:referrer}\")?'

[transforms.transform_limit_request]
  type = "coercer" 
  inputs = ["parser_limit_request"] # example
  types.time = "timestamp|%Y/%m/%d %H:%M:%S"

[transforms.remove_limit_request]
    inputs = [ "transform_limit_request" ]
    type   = "remove_fields"
    fields = ["data", "file", "host", "message", "timestamp", "source_type", "MONTHDAY" ,"MONTH" ,"YEAR" ,"HOUR" ,"MINUTE" ,"SECOND"]

[sinks.output_limit_request]
  inputs   = ["remove_limit_request"]
  type     = "clickhouse"
  database = "********"
  table = "********"
  host = "http://192.168.1.1:8123/"
  auth.strategy = "basic"
  auth.password = ********
  auth.user = ********
  encoding.timestamp_format = "unix"
```

### Debug Output

 
SELECT * FROM db.limit LIMIT 100
 
**1970-01-01 03:00:00**	error	32612	limiting requests
**1970-01-01 03:00:00**	error	32611	limiting requests
**1970-01-01 03:00:00**	error	32612	limiting requests

displays the default time

### Expected Behavior

I expect this output of date and time
**2020-11-11 11:11:11**	error	32612	limiting requests

### Actual Behavior

this is json's output to a file. there is no time field at all

{"client_ip":"********","error_message":"limiting requests","http_version":"2.0","limit":"********","method":"GET","pid":"18691","port":"","referrer":"","request":"**********","severity":"error","zone":"limit_zone"}

### Example Data

2020/11/11 00:14:29 [error] 10959#0: *$$$$$$ limiting requests, excess: 9999 by zone "limit_zone", client: 1.1.1.1, server: test.com, request: "GET fffffffffffff0 HTTP/2.0", host: "test.com"

2020/11/11 00:14:30 [error] 10959#0: *$$$$$$ limiting requests, excess: 9999 by zone "limit_zone", client: 1.1.1.1, server: test.com, request: "GET fffffffffffff0 HTTP/2.0", host: "test.com"
