### ISSUE TITLE
remap-lang conditionals: improve error messages

### ISSUE THREAD

**Issue by JeanMertz** [timberio/vector#5348]
You can use TRL in Vector unit tests like so:

```toml
[[tests]]
	name = "test"
	[[tests.inputs]]
		insert_at = "json_parser"
		type = "raw"
		value = '{ "message": "foo" }'
	[[tests.outputs]]
		extract_from = "json_parser"
	[[tests.outputs.conditions]]
		type = "remap"
		source = """
			exists(.nope)
		"""
```

The above would fail the test with the message:

> condition[0]: source execution resolved to false

In this context, it's fairly clear that `exists` returned false, but as soon as you add more checks in a single condition, it becomes unclear why the condition failed.

We should do some work to improve this (which also improves general errors in TRL):

* Show the line number that failed
* Print details about the specific expression that failed
