### ISSUE TITLE
docker source causing high IO read/CPU usage

### ISSUE THREAD

**Issue by jerryleooo** [timberio/vector#5404]
### Vector Version

```
vector 0.10.0 (g0f0311a x86_64-unknown-linux-gnu 2020-07-22)
```

### Vector Configuration File

```toml
data_dir = "/var/lib/vector"

# Input data. Change me to a valid input source.
[sources.docker]
  type = "docker"

[transforms.add_hostname]
  inputs = ["docker"]
  type   = "add_fields"
  overwrite = true
  fields.hostname = "${INET_IP}"

[transforms.sentry_error]
  inputs = ["add_hostname"]
  type = "filter"
  condition."message.contains" = "error-response"

[transforms.stats]
  inputs = ["add_hostname"]
  type = "filter"
  condition."message.contains" = "stats-"

[sinks.sentry_proxy]
  inputs = ["sentry_error"]
  type   = "http"
  # uri    = "http://127.0.0.1:8100/api/v1/error"
  uri    = "http://insight05.idata-server.shopee.io:10500/api/v1/error"
  encoding.codec = "json" # required

[sinks.es_klog]
  inputs = ["add_hostname"]
  type   = "elasticsearch"
  host   = "${ES_URL}"
  index  = "data-service-api-klog-v1-%Y-%m-%d"

[sinks.es_stats]
  inputs = ["stats"]
  type   = "http"
  # uri    = "http://127.0.0.1:8100/api/v1/stats"
  uri    = "http://insight05.idata-server.shopee.io:10500/api/v1/stats"
  encoding.codec = "json" # required

# Output data
[sinks.out]
  # inputs   = ["sentry_error"]
  inputs = ["docker"]
  type     = "console"
  encoding.codec = "json"
  encoding.only_fields = ["container_name", "message"]
```

### Debug Output

https://gist.github.com/jerryleooo/ec33799e1f86fdab56c792490aa13c14

### Expected Behavior

vector command should not cause high CPU usage / IO read

### Actual Behavior

I use following command to start vector
```
~/.vector/bin/vector -c ~/.vector/config/vector.toml
```

Then I found the CPU usage is high, and IO read is high. **And the situations persists even I stopped vector command**. We have 32 CPU cores, and at the beginning the `dockerd` command occupied around 1400% CPU resources, and now after sometime is drops to 800% as the 3rd pic shows.

![image](https://user-images.githubusercontent.com/3231765/101233025-92549600-36f0-11eb-96bd-8dbafc6194ec.png)
![image](https://user-images.githubusercontent.com/3231765/101233031-997ba400-36f0-11eb-89f5-27144ad92418.png)
![image](https://user-images.githubusercontent.com/3231765/101233040-ae583780-36f0-11eb-9e5c-b46db89b2763.png)

### Additional Context

```
$ docker version                                                                                                                                                  [11:52:30]
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77156
 Built:             Sat May  4 02:34:58 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 02:02:43 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

```
Linux insight04.idata-server.shopee.io 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
