### ISSUE TITLE
Kafka sink telemetry counters does not show up in Prometheus metrics

### ISSUE THREAD

**Issue by yannlambret** [timberio/vector#5476]
<!--
Hi there,

Thank you for opening an issue. Please note that we try to keep the Vector issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://chat.vector.dev.
-->

### Vector Version

```
0.11.0
```

### Vector Configuration File

```yaml
data_dir: /var/lib/vector                                                                                                                                                                                                      
                                                           
sources:                                                                                                            
  internal_metrics:                                                                                                             
    type: internal_metrics                                                        
  syslog:                                                  
    address: 127.0.0.1:12200           
    mode: udp                           
    type: syslog                                 
                                                                                                                            
transforms:                                                                                                           
  add_fields:                                                                                                
    fields:                                                                  
      severity: info                                 
    inputs:                                                                     
    - syslog     
    overwrite: true          
    type: add_fields                                                                                  
  remove_fields: 
    fields:                    
    - facility                  
    - host                             
    - source_ip                          
    - source_type                   
    inputs:                                      
    - add_fields       
    type: remove_fields                
                                                 
sinks:                                                  
  kafka:                                                                    
    bootstrap_servers: <internal_dns_record>:9094
    encoding:                                           
      codec: json                                              
    inputs:                                                                  
    - remove_fields                           
    tls:                                    
      ca_file: /tls/client/ca.crt  
      crt_file: /tls/client/user.crt
      enabled: true                   
      key_file: /tls/client/user.key        
    topic: <topic_name>
    type: kafka           
  prometheus_exporter:                   
    address: 0.0.0.0:9114                                         
    default_namespace: <service_name>
    inputs:                                                    
    - internal_metrics
```

### Expected Behavior

I was expecting to get metrics for the kafka sink.

### Actual Behavior

The 2 counters for kafka sink (```processed_events_total``` and ```processed_bytes_total```) are missing from prometheus metrics.


### Example Data

```
curl -s http://localhost:9114/metrics |grep -v '^#'
vector_internal_metrics_cardinality 8                      
vector_started_total 1                 
vector_uptime_seconds 462               
vector_requests_received_total 34                
vector_processed_events_total{component_kind="transform",component_name="remove_fields",component_type="remove_fields"} 7722
vector_processed_events_total{component_kind="source",component_name="syslog",component_type="syslog"} 7722                                                                                                                     
vector_processed_events_total{component_kind="transform",component_name="add_fields",component_type="add_fields"} 7722
vector_processed_bytes_total{component_kind="source",component_name="syslog",component_type="syslog"} 3308024
```

### Additional Context

The kafka sink behaves as expected (apart from the metric issue); messages produced by vector are stored in the right topic.

### References

<!--
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:

- #6017

-->
