### ISSUE TITLE
New `starts_with_timestamp` Remap function

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#5498]
To simplify the multi-line merge use case, we should add a new `starts_with_timestamp` function. This would make it easy to do something like this:

```toml
[transform.merge]
type = "reduce"
starts_when.type = "remap"
starts_when.source = "starts_with_timestamp(.message)"
```

## Requirements

- [ ] It should detect the same format as described in #5496
- [ ] It should discard timestamp wrapping, such as `[2020-10-20T45:34:23Z]` or `[2020-10-20T45:34:23Z - INFO]` (I'm sure there are other variations)

Ref #5251 and #5496
