### ISSUE TITLE
New `starts_with_whitespace` Remap function

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#5499]
Like #5498, a `starts_with_whitespace` would assist with multi-line merging:

```toml
[transform.merge]
type = "reduce"
starts_when.type = "remap"
starts_when.source = "!starts_with_whitespace(.message)"
```

**Comment by JeanMertz** [comment]
What's wrong with `starts_with(.message, " ")`, or `matches(.message, /^\s+/)`?

I guess the answer to my question could be "it's too complicated for non-programmers", but I worry that if we go this route (especially if we don't have any form of composability) you'll end with an ever-growing list of `starts_with_*`, `ends_with_*`, `contains_*` (etc) functions.

On some level, I feel like this is a problem that we want to tackle at a higher level in Vector itself. Specifically, if we had macro-generated transforms, one could just write (I haven't given the syntax any thought, but you get the gist):

```toml
[transform.merge]
type = "reduce"
macro = "starts_with_whitespace"
```

And vector would compile that down into a remap script that uses `matches` or whatever else makes sense.
