### ISSUE TITLE
Investigate Vector integration into bottlerocket

### ISSUE THREAD

**Issue by MOZGIII** [timberio/vector#5514]
https://github.com/bottlerocket-os/bottlerocket is a container-oriented OS. It might be interesting to work with them to integrate Vector right into their system.

**Comment by chas0amx** [comment]
The provided example demonstrates how to capture logs from the host machine in Bottlerocket using a Kubernetes Pod:
```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: eks.amazonaws.com/compute-type
            operator: NotIn
            values:
            - fargate
  containers:
  - image: public.ecr.aws/lts/ubuntu:22.04_stable
    command:
      - "/bin/bash"
      - "-c"
      - |
        apt-get update && apt-get install -y systemd-journal-remote  && sleep 604800
    imagePullPolicy: Always
    name: ubuntu
    volumeMounts:
    - mountPath: /var/log/journal-ac
      name: journal-volume
  restartPolicy: Always
  volumes:
  - name: journal-volume
    hostPath:
      path: /var/log/journal
EOF
```
Then, execute:
`kubectl exec ubuntu -- journalctl --directory=/var/log/journal-ac -f`
