### ISSUE TITLE
Division by Zero in Remap panics Vector

### ISSUE THREAD

**Issue by FungusHumungus** [timberio/vector#5523]
A division by zero within Remap will panic Vector, causing it to shutdown with the error:

```
Dec 12 12:25:58.246 ERROR transform{component_kind="transform" component_name=remap component_type=remap}: vector::topology: An error occurred that vector couldn't handle.
```

Remap should handle this and produce a stardard Remap error.

Eg.

With this transform:

```toml
[transforms.remap]
  type = "remap"
  inputs = ["stdin"]
  source = '''
   . = parse_json(.message)
   .nork = 5 // .nerk
  '''
```

Send the message: `{"nerk": 0}`.

---

Edit, this has just changed since I pushed Integer division..  It is only Integer division that panics. The standard float division will just return `infinity`.
