### ISSUE TITLE
Vector ignores static pods

### ISSUE THREAD

**Issue by enkov** [timberio/vector#5550]
### Vector Version

```
vector 0.11.0 (v0.11.0 x86_64-unknown-linux-gnu 2020-12-02)
```

### Vector Configuration File

```toml
# Configuration for vector.
# Docs: https://vector.dev/docs/

# Data dir is location controlled at the `DaemonSet`.
data_dir = "/vector-data-dir"
[log_schema]
  host_key = "host"
  message_key = "message"
  source_type_key = "source_type"
  timestamp_key = "timestamp"
# Ingest logs from Kubernetes.
[sources.kubernetes_logs]
  type = "kubernetes_logs"
[transforms.transform_json]
  type = "json_parser"
  inputs = ["kubernetes_logs"]
  drop_field = true
  drop_invalid = false
  field = "message"

[sinks.elastic]
  type = "elasticsearch"
  inputs = ["transform_json"]
  endpoint = "http://X.X.X.X:9200"
  healthcheck = true
  index = "vector-%Y-%m-%d"
```

### Expected Behavior
Vector should collect logs from static pods.

### Actual Behavior
Vector ignores statics pods

### Additional Context
It's common to deploy kubernetes control plane with static pods. For example, kubespray deploy kubernetes in such a way.
Here are kubernetes docs https://kubernetes.io/docs/tasks/configure-pod-container/static-pod/.
I think the problem here is
```
Static Pods are managed directly by the kubelet daemon on a specific node, without the API server observing them.
```
