### ISSUE TITLE
Elasticsearch sink fails with "Credential should be scoped to correct service: es" error when using assume role at AWS

### ISSUE THREAD

**Issue by MOZGIII** [timberio/vector#5554]
This happens with the latest nightly.

Error:

```text
Dec 16 13:13:27.787 ERROR sink{component_kind="sink" component_name=es component_type=elasticsearch}:request{request_id=98}: vector::sinks::util::retries: Unexpected error type; dropping the request. error=Could not generate AWS credentials: CredentialsError { message: "StsProvider get_session_token error: Unknown(BufferedHttpResponse {status: 403, body: \"{\\\"message\\\":\\\"Credential should be scoped to correct service: \\\'es\\\'. \\\"}\", headers: {\"date\": \"Wed, 16 Dec 2020 12:17:02 GMT\", \"content-type\": \"application/json\", \"content-length\": \"68\", \"connection\": \"keep-alive\", \"x-amzn-requestid\": \"4c4465b4-76be-47ba-8a2f-499ee10f75e9\", \"access-control-allow-origin\": \"*\"} })" }
Dec 16 13:13:27.787 ERROR sink{component_kind="sink" component_name=es component_type=elasticsearch}:request{request_id=98}: vector::sinks::util::sink: Request failed. error=Could not generate AWS credentials: CredentialsError { message: "StsProvider get_session_token error: Unknown(BufferedHttpResponse {status: 403, body: \"{\\\"message\\\":\\\"Credential should be scoped to correct service: \\\'es\\\'. \\\"}\", headers: {\"date\": \"Wed, 16 Dec 2020 12:17:02 GMT\", \"content-type\": \"application/json\", \"content-length\": \"68\", \"connection\": \"keep-alive\", \"x-amzn-requestid\": \"4c4465b4-76be-47ba-8a2f-499ee10f75e9\", \"access-control-allow-origin\": \"*\"} })" }
```

Config:

```toml
[sinks.es]
  type = "elasticsearch"
  inputs = ["vector"]
  endpoint = "https://search-k8s-dev-env-redacted.us-west-2.es.amazonaws.com"
  auth.assume_role = "arn:aws:iam::redacted:role/k8s-dev-env-es-access"
  auth.strategy = "aws"
```

I think it should've worked, but it doesn't apparently. I might've messed the IAM config, it's at our AWS.
