### ISSUE TITLE
Restore default `kafka` sink batch settings

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#5601]
See https://github.com/timberio/vector/pull/5010#issuecomment-748157786

**Comment by Hoverbear** [comment]
Ah, hmm, this looks to be because of https://github.com/timberio/vector/blob/deb446ab68b6de6cf3091d61b923481ed10e4237/src/sinks/kafka.rs#L52. We're overriding rdkafka with our normal defaults. I think having that an `Option<BatchConfig>` and would default it to `None` here and help this problem.

**Comment by Hoverbear** [comment]
(Pulling over my comment from #5652)

Because of this:

 https://github.com/timberio/vector/blob/507caed13f75973a435fe6b27417795c2eaee421/src/sinks/kafka.rs#L52-L53

This should have resolved to a bunch of `None`s as a struct:

https://github.com/timberio/vector/blob/507caed13f75973a435fe6b27417795c2eaee421/src/sinks/util/batch.rs#L18-L25

If that's the case, these should have never been set:

https://github.com/timberio/vector/blob/507caed13f75973a435fe6b27417795c2eaee421/src/sinks/kafka.rs#L146-L186

Which means that #5010 was not related unless the user was already setting rdkafka options and tried to migrate them to the batch options we added, and those did not work. (#5602 suggests this might be the case?)

**Comment by binarylogic** [comment]
I can clarify. Either way, it appears that batching improve performance significantly, so we should probably default to batching of some sort.

**Comment by Hoverbear** [comment]
I'm going to push a fix that adds debug logs so this is easier to diagnose to help in 0.11.2

**Comment by Hoverbear** [comment]
https://github.com/timberio/vector/pull/5652 adds some logging, but causes no behavioral changes to this, as I have not been able to determine what might be setting this for the user except the rdkafka defaults themselves.

**Comment by sergk-mambu** [comment]
Hi @Hoverbear,

I'm the user who reported this issue.
The config initially hadn't had any custom batch or buffer related options, neither vector native neither librdkafka, so it was like:
`[sinks.common-kafka]
      type = "kafka"
      inputs = ["yyyy-yyyy-yyyy"]
      bootstrap_servers = "kafka-1:9096,kafka-2:9096,kafka-3:9096"
      tls.enabled = true
      sasl.enabled = true
      sasl.mechanism = "SCRAM-SHA-512"
      sasl.username = "vector"
      sasl.password = "${PASSWORD}"
      topic = "xxxx.xxxxx.v1"
      encoding.codec = "json"`
I encountered the issue reported in #5602 only when started to play with buffer&batch parameters.

I found that something is wrong with the librdkafka batch settings when added the debug option:
`librdkafka_options."debug" = "all"`
With vector:nightly-2020-09-24 the log looked like in [nightly-2020-09-24-rdkafka-example.log](https://github.com/timberio/vector/files/5747375/nightly-2020-09-24-rdkafka-example.log), i.e first a lot of vector messages 'sending event' and then some librdkafka messages. But with vector:0.11.0 it was like in [0.11-rdkafka-example.log](https://github.com/timberio/vector/files/5747374/0.11-rdkafka-example.log), i.e. 'sending event' messages interleaved with librdkafka messages.
Also I in the logs of nightly-2020-09-24 I saw something like:
`Produce MessageSet with 224 message(s)
Produce MessageSet with 532 message(s)
Produce MessageSet with 489 message(s)`
while with 0.11.0 it was:
`Produce MessageSet with 1 message(s)
Produce MessageSet with 1 message(s)
Produce MessageSet with 2 message(s)`

I think it would be possible to reproduce this issue even without high load, just enable librdkafka debug logging and watch the MessageSet size.

**Comment by Hoverbear** [comment]
I can confirm I saw only very very rare/minor batching happening with the following config:

```toml
data_dir = "/var/lib/vector/"

[sources.source0]
  format = "apache_common"
  type = "generator"

[sinks.sink0]
  type = "kafka"
  inputs = ["source0"]
  bootstrap_servers = "localhost:9091"
  topic = "v1"
  encoding.codec = "json"
  librdkafka_options."debug" = "all"
  batch.max_events = 10
  batch.timeout_secs = 10
```

While this one showed much more regular batching:

```toml
data_dir = "/var/lib/vector/"

[sources.source0]
  format = "apache_common"
  type = "generator"

[sinks.sink0]
  type = "kafka"
  inputs = ["source0"]
  bootstrap_servers = "localhost:9091"
  topic = "v1"
  encoding.codec = "json"
  librdkafka_options."debug" = "all"
  batch.max_events = 10
  batch.timeout_secs = 10 # <---- New!!!
```

Investigating a bit more, I looked at the default rdkafka option, since when `batch.timeout_secs` is not present it'll fall to that. Looking at https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md you can see `queue.buffering.max.ms` defaults to 5 ms.

Is it possible that your messages are only sometimes arriving less than 5 ms apart? Does changing the timeout help?
