### ISSUE TITLE
remap-lang: improve support (or guardrails) when used in conditions

### ISSUE THREAD

**Issue by JeanMertz** [timberio/vector#5614]
In Vector component conditions, the boolean result of a TRL program determines if the configured condition passes.

Take this example:

```toml
[transforms.critical_logs]
    type = "filter"
    condition.type = "check_fields"
    condition."level.eq" = "critical"
    condition."status.code.eq" = 500
```

Here's the same condition using TRL:

```toml
[transforms.critical_logs]
    type = "filter"
    condition.type = "remap"
    condition.source = """
    	.level == "critical"
		.status.code == 500
    """
```

Right? Nope.

The provided program is this:

```rust
.level == "critical"
.status.code == 500
```

But only the _last_ expression is used as the result of the outcome of the condition. And so in this case, the `level` field value is ignored in the result.

The solution is to write the transform like this:

```toml
[transforms.critical_logs]
    type = "filter"
    condition.type = "remap"
    condition.source = """
    	.level == "critical" && .status.code == 500
    """
```

I've seen already three different people make this mistake in the short time since we support TRL for conditions, so I suspect this will become a major headache for operators configuring their Vector configuration.

I don't know what the best solution is right now, there are multiple routes we can take, but each one requires a bit of work, so I wanted to log this issue, so that we can (1) write down the possible solutions to this later, and (2) keep track of this until it's fixed.
