### ISSUE TITLE
Invalid record from journald errors on NetworkManager events

### ISSUE THREAD

**Issue by yaleman** [timberio/vector#5617]
### Vector Version

```
vector 0.11.0 (v0.11.0 aarch64-unknown-linux-musl 2020-12-02)
```

### Vector Configuration File
```yaml
---
sources:
  local_journald:
    type: journald
    current_boot_only: true
    exclude_units: []
    include_units: []
transforms:
  journald_coercer:
    type: coercer
    inputs:
    - journald_remove_fields
    types:
      SYSLOG_FACILITY: bytes
```

### Debug Output

https://gist.github.com/yaleman/29da2505adbd00df97f695d96e9767f9

### Expected Behavior

Logs to be processed successfully, I'm happy for the coercer to handle them...

### Actual Behavior

Errors in the logs stating `vector::internal_events::journald: Invalid record from journald, discarding. error=Error("invalid type: sequence, expected a string", line: 0, column: 0)`

### Example Data

error logs: https://gist.github.com/yaleman/3f727b1eb133f907ec1c3c268c629f2d

### Additional Context

Only NetworkManger events have a SYSLOG_FACILITY that's an array:

`"SYSLOG_FACILITY": ["DHCP4", "DHCP6"],`
