### ISSUE TITLE
influxdb_logs sink does not send an HTTP body in 0.11.1

### ISSUE THREAD

**Issue by zackangelo** [timberio/vector#5632]
### Vector Version
```
0.11.1
```

### Vector Configuration File
```toml
data_dir = "/var/run/vector"

[sources.in]
  type = "file" # required
  include = ["/var/run/thermopolis/*.log"] #must match data_dir in thermopolis

#[sources.vector-log]
#  type = "file" # required
#  include = ["/var/log/vector.log"]

#[sources.thermopolis-log]
#  type = "file" # required
#  include = ["/Users/eight/thermopolis/logs/thermopolis.log"]

# lifts and parses the JSON payload out of the message field
# and makes them top level fields
[transforms.json_transform]
  type = "json_parser"
  inputs = ["in"]
  drop_field = true
  drop_invalid = true
  field = "message"

# InfluxDB
[sinks.influxdb]
 inputs = ["json_transform"]
 type = "influxdb_logs"
 endpoint = "https://us-central1-1.gcp.cloud2.influxdata.com"
 namespace = "plc"
 bucket = "plc_mask_counts"
 org = "<REDACTED>"
 token = "<REDACTED>"
 encoding.only_fields = ["timestamp", "machine", "mask_count_track_1", "mask_count_track_2", "employee_badge_id"]
 tags = ["machine", "employee_badge_id"]
```

### Expected Behavior

Vector successfully sends data to InfluxDB. 

### Actual Behavior

Works fine in 0.10.0. After upgrading to 0.11.1, I started receiving the error "points required" from the InfluxDB server in the logs. After turning on debug logging, it appears that Vector was not writing an HTTP body in its request. Reverting back to 0.10.0 fixed the problem.  

### Example Data

```
{"employee_badge_id":null,"file":"/var/run/thermopolis/juliette.log","host":"thermopolis","machine":"juliette","source_type":"file","timestamp":"2020-12-19T22:30:20.622743278Z","track_1_pusher":472550,"track_2_pusher":628112}
```
