### ISSUE TITLE
Add doc support for specifying k8s configuration

### ISSUE THREAD

**Issue by engineater** [timberio/vector#5715]
Hi there,

I have tried install vector on **Kubernetes** with **source type kubernetes_logs** and **sinks clickhouse**.

Version's pod container image is **timberio/vector:0.11.1-debian**
But my pods are in status Crashloopbackoff and  logs look like this:
```
Dec 25 09:31:57.154 INFO vector::app: Log level is enabled. level="vector=info,codec=info,file_source=info,tower_limit=trace,rdkafka=info"
--
Fri, Dec 25 2020 3:31:57 pm | Dec 25 09:31:57.154 INFO vector::app: Loading configs. path=[("/etc/vector/managed.toml", None)]
Fri, Dec 25 2020 3:31:57 pm | Dec 25 09:31:57.155 ERROR vector::cli: Configuration error. error=missing field `endpoint` for key `sinks.my_sink_id` at line 16 column 1
```

I've installed vector with this commands
```
$ helm repo add timberio https://packages.timber.io/helm/latest
$ helm install --namespace vector --create-namespace vector timberio/vector-agent --values clickhouse_values.yaml
```

My file clickhouse_values.yaml look like this:
```
sources:
  my_source_id:
    type: kubernetes_logs
sinks:
  my_sink_id:
    type: clickhouse
    inputs:
      - my_source_id
    compression: gzip
    database: default
    endpoint: "http://clickhouse-service-http.default:8123"
    table: mytable
    healthcheck:
      enabled: true
```

My clickhouser service 06-clickhouse-endpoint-service.yaml is Endpoint service(because a clickhouse is outside of k8s claster) and placed in default namespace:
```
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-service
spec:
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000

---
apiVersion: v1
kind: Endpoints
metadata:
  name: clickhouse-service
subsets:
  - addresses:
      - ip: 192.168.1.109
    ports:
      - port: 9000

---
# clickhouse service http
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-service-http
spec:
  ports:
    - protocol: TCP
      port: 8123
      targetPort: 8123

---
apiVersion: v1
kind: Endpoints
metadata:
  name: clickhouse-service-http
subsets:
  - addresses:
      - ip: 192.168.1.109
    ports:
      - port: 8123
```
 
Could you bug fixing that error?
```
Fri, Dec 25 2020 3:31:57 pm | Dec 25 09:31:57.155 ERROR vector::cli: Configuration error. error=missing field `endpoint` for key `sinks.my_sink_id` at line 16 column 1
```

**Comment by jamtur01** [comment]
@MOZGIII Just concerned this is a YAML-config bug. Adding you as an FYI.

**Comment by MOZGIII** [comment]
The configuration params for the compoennts besides `inputs` and `type` have to be specified via `rawConfig` like so:

```yaml
sinks:
  my_sink_id:
    type: clickhouse
    inputs:
      - my_source_id
    rawConfig: |
      compression = "gzip"
      database = "default"
      endpoint = "http://clickhouse-service-http.default:8123"
      ...
```
