### ISSUE TITLE
Missing label from docker_job source

### ISSUE THREAD

**Issue by nivekuil** [timberio/vector#5716]
### Vector Version
0.11

### Vector Configuration File

```toml
[sources.docker]
  type = "docker_logs"

[sinks.loki]
  encoding = "text"
  endpoint = "http://loki:3100"
  inputs = ["docker"]
  type = "loki"

  labels.instance = "{{ label.com.docker.swarm.task.id }}"
  labels.node = "{{ label.com.docker.swarm.node.id }}"
  labels.job = "{{ label.com.docker.swarm.service.name }}"
```

### Expected Behavior

All Loki log lines have `label.com.docker.swarm.task.id` as the `instance` label
### Actual Behavior

All Loki log lines for some task/instances only have the `node` and `job` labels
### Additional Context
Vector is running as a Docker Swarm 20.10 service, along with the docker_logs sources being monitored. Most tasks seem to have the instance/task label set properly, but on the ones I was interested in looking at (short lived, errored shortly after starting) only the job and node labels were there. Inspecting the task does show it as having the proper labels applied, so Vector is not picking it up or Loki is dropping it somehow.
