### ISSUE TITLE
Require the `type` option for conditions

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#5724]
The `filter`, `swimlanes`, `reduce`, etc take conditions as options. In order to migrate users to the new remap version we should require the `type` option:

```toml
[transforms.filter]
type = "filter"
condition.type = "remap" # REQUIRED
# ...
```
