### ISSUE TITLE
remove_field transform fails to remove "file" field from File source

### ISSUE THREAD

**Issue by danthegoodman1** [timberio/vector#5729]
### Vector Version

```
vector 0.11.1 (v0.11.1 x86_64-unknown-linux-gnu 2020-12-17)
```

### Vector Configuration File

```toml
[sources.my_source_id]
  type = "file" # required
  ignore_older = 600 # optional, no default, seconds
  include = ["/var/log/*.log"] # required

[transforms.my_transform_id]
  # General
  type = "add_fields" # required
  inputs = ["my_source_id"] # required
  overwrite = true # optional, default

  # Fields
  fields.string_field = "string value" # exampl

[transforms.my_transform_id_n]
  type = "json_parser" # required
  inputs = ["my_transform_id"] # required
  drop_field = true # optional, default
  drop_invalid = true # required
  field = "message" # optional, default

[transforms.my_transform_id_b]
  type = "remove_fields" # required
  inputs = ["my_transform_id_n"] # required
  fields = ["source_type", "host", "file"] # required

[sinks.my_sink_id]
  # General
  type = "loki" # required
  inputs = ["my_transform_id_b"] # required
  endpoint = "http://10.116.16.3:3100" # required

  # Encoding
  encoding.codec = "json" # required
  labels.forwarder = "vector" # example
  labels.file = "{{ file }}"
```

### Debug Output

https://gist.github.com/danthegoodman1/7f13eead80a9109e6486e556874c2ff9

### Expected Behavior

Logs are received in Loki

### Actual Behavior

No logs are received by Loki

### Additional Context

I am trying to send logs to loki, and remove the `file` field from the log message, and set it as a label instead. It keeps appearing in the message though. The problem is when ever I add the `file` field to the `remove_fields` transforms, logs fail to send. If I remove it, logs start flowing again. In the image below, you can see it appears in the `Parsed Fields` and the `Log Labels`

![image](https://user-images.githubusercontent.com/17806508/103157050-39bb6a80-477d-11eb-842e-0cb60ffab405.png)
