### ISSUE TITLE
Prometheus sink: Out of bounds metrics

### ISSUE THREAD

**Issue by spencergilbert** [timberio/vector#5744]
### Vector Version

```
Dec 27 21:43:30.726 INFO vector: Vector has started. version="0.12.0" git_version="v0.11.0-197-gbbb5fb6" released="Sun, 27 Dec 2020 04:54:32 +0000" arch="x86_64"
Sun, Dec 27 2020 4:43:30 pm
```

### Vector Configuration File

```toml
# ------------------------------------------------------------------------------
# Metric events
# ------------------------------------------------------------------------------

[sources.internal_metrics]
type = "internal_metrics"

[sinks.prometheus]
type = "prometheus_exporter"
inputs = ["internal_metrics"]
address = "0.0.0.0:9090"
```

I recently noticed "all" of my vector metrics were not being recorded by prometheus, though the scrapes were marked as successful (there are very brief periods when metrics are present, seems like right around vector startup). When moving prometheus's log level to debug I see the following messages:

```
level=debug ts=2020-12-28T17:21:15.093Z caller=scrape.go:1255 component="scrape manager" scrape_pool=vector/vector-agent/0 target=http://10.42.2.152:9090/metrics msg="Out of bounds metric" series="node_cpu_seconds_total{collector=\"cpu\",cpu=\"23\",host=\"vector-agent-f97wn\",mode=\"nice\"}"
```
(Similar messages for all other varieties of vector's metrics, all with the same `msg`)

I haven't run into this with prometheus before, so I'm not entirely sure where to start, but I can help narrow down when this started happening by deploying specific releases until it's resolved.
