### ISSUE TITLE
Enhance Remap variables to not use a conflicted identifier character

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#5842]
As pointed out by @JeanMertz, remap variables must start with `$`, and our configuration syntax uses `$` for environment variables, this means that users must escape this character in order to use Remap variables in Vector configuration files:

```toml
[transforms.remap]
type = "remap"
source = '''
$$my_variable = "value"
'''
```

We should fix this before launching 0.12. To keep things simple, I'd be in favor plain old variables without a special leading character:

```toml
[transforms.remap]
type = "remap"
source = '''
my_variable = "value"
'''
```
