### ISSUE TITLE
can't merge a non object mapping [kubernetes.pod_labels.istio] with an object mapping

### ISSUE THREAD

**Issue by uthng** [timberio/vector#5881]
### Vector Version

```
0.11.1
```

### Vector Configuration File

```toml
# Configuration for vector.
# Docs: https://vector.dev/docs/

# Data dir is location controlled at the `DaemonSet`.
data_dir = "/vector-data-dir"
[log_schema]
  host_key = "host"
  message_key = "message"
  source_type_key = "source_type"
  timestamp_key = "timestamp"
# Ingest logs from Kubernetes.
[sources.kubernetes_logs]
  type = "kubernetes_logs"
[sinks.es-mgtnpe]
  type = "elasticsearch"
  inputs = ["kubernetes_logs"]
  compression = "none"
  endpoint = "https://es.logging.svc.cluster.local:9200"
  healthcheck = true
  index = "vector-mgtnpe-%F"

  # Auth
  auth.user = "${ELASTICSEARCH_USER}"
  auth.password = "${ELASTICSEARCH_PASSWORD}"
  auth.strategy = "basic"

  # TLS
  tls.ca_file = "/etc/vector/ca.crt"
```

### Debug Output

```
Jan 06 14:16:15.070 DEBUG http: hyper::client::pool: pooling idle connection for ("https", es.logging.svc.cluster.local:9200)
Jan 06 14:16:15.071 DEBUG http: vector::internal_events::http_client: HTTP response. status=200 OK version=HTTP/1.1 headers={"warning": "299 Elasticsearch-7.10.1-1c34507e66d7db1211f66f3513706fdf548736aa \"[types removal] Specifying types in bulk requests is deprecated.\"", "content-type": "application/json; charset=UTF-8", "content-length": "6123"} body=[6123 bytes]
Jan 06 14:16:15.071 ERROR sink{component_kind="sink" component_name=es-mgtnpe component_type=elasticsearch}:request{request_id=24}: vector::sinks::util::retries: Not retriable; dropping the request. reason="error type: illegal_argument_exception, reason: can\'t merge a non object mapping [kubernetes.pod_labels.istio] with an object mapping"
```

### Expected Behavior

No error occurred and get logs of istio's pods in Elasticsearch

### Actual Behavior

No istio pods' logs are sent to Elasticsearch

**Comment by uthng** [comment]
Well, I found it. It was because there are all sorts of labels in pods. Among them, there were: `istio=xxx` and `istio.io/rev=xxx`. This created 2 fields `istio` with different types in the mapping of Elasticsearch. The solution is to remove the field `kubernetes.pod_labels.istio` with `remove_fields` transformer.

You might have the similar error with `kubernetes.pod_labels.app` which is a common label.

Thank you anyway.

**Comment by Abhinav9512** [comment]
@uthng I removed the <filter kubernetes.**> field still facing the error. Any clue?

**Comment by Abhinav9512** [comment]
@uthng can you explain a little more, I am facing kubernetes.labels.app error in fluentd logs. How to resolve this?

**Comment by nettnikl** [comment]
Hey!
Having the same problem right now(`can't merge a non object mapping [label.com.docker.compose.project] with an object mapping`), but to be fair, the way you shared is a workaround, not a solution. So, please kindly reopen the issue, so we can find another solution that works for other use cases as well.

I want to **keep both** of this key value pairs of my docker_logs-type source.
_I know this to be possible, because i have seen it in another instance_ (which i did however not administrate).

```
    "com.docker.compose.project": "gitea",
    "com.docker.compose.project.working_dir": "/srv/gitea",
```

For reference, my logs:
```
vector  | 2023-08-30T22:34:58.818738Z ERROR sink{component_kind="sink" component_id=opensearch-docker component_type=elasticsearch component_name=opensearch-docker}:request{request_id=1}: vector::sinks::util::retries: Not retriable; dropping the request. reason="error type: illegal_argument_exception, reason: can't merge a non object mapping [label.com.docker.compose.project] with an object mapping" internal_log_rate_limit=true
vector  | 2023-08-30T22:34:58.818950Z ERROR sink{component_kind="sink" component_id=opensearch-docker component_type=elasticsearch component_name=opensearch-docker}:request{request_id=1}: vector_common::internal_event::service: Service call failed. No retries or retries exhausted. error=None request_id=1 error_type="request_failed" stage="sending" internal_log_rate_limit=true
vector  | 2023-08-30T22:34:58.819026Z ERROR sink{component_kind="sink" component_id=opensearch-docker component_type=elasticsearch component_name=opensearch-docker}:request{request_id=1}: vector_common::internal_event::component_events_dropped: Events dropped intentional=false count=6 reason="Service call failed. No retries or retries exhausted." internal_log_rate_limit=true
```

**Comment by Abhinav9512** [comment]
@nettnikl if you want to keep both, is it possible for you to rename `com.docker.compose.project` to lets say `com.docker.compose.project.name`, it will solve your issue. It's a workaround tho. Major fix needs to be implemented in elasticsearch.

**Comment by nettnikl** [comment]
Thanks for your suggestion.
Let me check. I'm quite sure i've seen this work with elastic - though it might be v8, not OS which is v7 based afaik.

To be clear, I want:
[some][thing.deep]
[some][thing]

So, the label names are including a dot, but are not meant to be parsed as an object.

**Comment by joejoe-am** [comment]
@jszwedko Hi, still have this issue on 0.33.0 version. this is my configuration.

```toml
[sources]
    [sources.docker_logs]
        type = "docker_logs"
        include_images = ["shop"]
        exclude_containers = ["vector"]

[sinks]
    [sinks.console]
        type = "console"
        encoding.codec = "json"
        inputs = ["docker_logs"]

    [sinks.elasticsearch]
        type = "elasticsearch"
        inputs = ["docker_logs"]
        endpoints = ["http://elastic:9200"]
```
### this is the error:
```
reason: can't merge a non object mapping [label.com.docker.compose.project] with an object mapping" internal_log_rate_limit=true
```
i tried to use remap transforms to remove the label but it didn't effect and label still shows in console. 
any lead to fix this issue ? thanks
