### ISSUE TITLE
Better default configuration for Vector

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#5888]
The [default configuration](https://github.com/timberio/vector/blob/master/config/vector.toml) is not ideal. By default, it doesn't do anything since STDIN is not used for most deployments. This configuration was created at a time when we didn't have the API, `generator`, `host_metrics`, or `remap` features. A better default is one that demonstrates Vector working, so I propose the following:

```toml
# Vector's API for introspection
[api]
enabled = true
address = "127.0.0.1:8686"

# Dummy Apache formatted logs
[sources.dummy_logs]
type = "generator"
format = "apache_common"
interval = 1

# Parse Apache formatted logs
[transforms.parse_logs]
type = "remap"
source = '''
. = parse_apache_common(.message)
'''

# Host-level metrics (cpu, memory, disk, etc)
[sources.host_metrics]
type = "host_metrics"

# Vector's own internal metrics
[sources.internal_metrics]
type = "internal_metrics"

# Print it all out for inspection
[sinks.print]
type = "console"
inptus = ["parse_logs", "host_metrics", "internal_metrics"]
```
