### ISSUE TITLE
Allow templating in the gcp_stackdriver_logs sink "resource.*" fields

### ISSUE THREAD

**Issue by mwoodson** [timberio/vector#5931]
I am attempting to use the gcp_stackdriver_logs sink to populate the "resources" as represented in GCP stackdriver (now GCP operations, it was renamed).

I'm new to both vector and stackdriver, so I think this is valid.  In doing so, I believe that the "resources" are additional json fields that are added to the log entry.  These additional resource tags can then be used to filter messages, both by queries and sending them to new sinks.  This feature is built into GCP console.

The resources are documented here:

https://cloud.google.com/monitoring/api/resources

I am attempting to send kubernetes container and audit logs to stackdriver.  I would like to fill out the resources.* for the log entry using the kubernetes tags.  I got this to work with cloudwatch in aws, but with stackdriver, I just got the non-templated string.

Here is my sink config:

```
    [sinks.gcp_cloud_operations_container]
      type = "gcp_stackdriver_logs"
      inputs = ["swimlanes.kubernetes_logs"]
      credentials_path = "/credentials/service_account.json" # optional, no default
      log_id = "my-clustername-container" # required
      project_id = "my-projectid" # required
      resource.type = "k8s_container"
      resource.project_id = "my-projectid"
      resource.location = "us-east1"   # not sure what location is used for, stuck in region!?
      resource.cluster_name = "my-clustername"
      resource.namespace_name = "{{ kubernetes.pod_namespace }}"
      resource.pod_name = "{{ kubernetes.pod_name }}"
      resource.container_name = "{{ kubernetes.container_name }}"
      healthcheck.enabled = true # optional, default

```

Looking at the logs in GCP Logging, I see this:

```
...
  "resource": {
    "type": "k8s_container",
    "labels": {
      "container_name": "{{ kubernetes.container_name }}",
      "cluster_name": "my-clustername",
      "pod_name": "{{ kubernetes.pod_name }}",
      "location": "us-east1",
      "namespace_name": "{{ kubernetes.pod_namespace }}",
      "project_id": "my-projectid"
    }
...

```
The kubernetes tags are not being resolved.  Again, I was able to use templates like this in cloudwatch, so I believe its a GCP stackdriver sink issue?

If there is a better way to do this, I'd be interested.

### Current Vector Version

```
version="0.12.0" git_version="v0.11.0-265-g5b5222c"
```

**Comment by callicles** [comment]
Just ran into the same issue

**Comment by dfredell** [comment]
Thank you for posting this config. It helped me get kick started populating the metadata in google stackdriver. Even better if this was wired up by default. 
To answer your question, it seems the resource.location is only used for the Log Fields on the left filter section. I also configured vector to pull the location from the kubernetes node_labels.


```yaml
    sinks:
      gcp_stackdriver_logs:
        type: gcp_stackdriver_logs
        log_id: rsna-dev
        inputs:
          - kubernetes
        project_id: flywheel-log
        resource:
          type: k8s_container
          location: '{{ kubernetes.node_labels."topology.kubernetes.io/zone" }}'
          namespace_name: "{{ kubernetes.pod_namespace }}"
          pod_name: "{{ kubernetes.pod_name }}"
          container_name: "{{ kubernetes.container_name }}"

```
