### ISSUE TITLE
TLS Support in TCP sink

### ISSUE THREAD

**Issue by mdfranz** [timberio/vector#598]
Goal is to allow TCP source/sink to be used on public internet with mutual TLS authentication for on premise to cloud environments where direct connectivity to AWS services or publicly exposed ElasticSearch, Kafka (or other Sinks) would violate security policy.  

Example Implementations
https://www.rsyslog.com/doc/v8-stable/tutorials/tls_cert_summary.html
https://www.rsyslog.com/doc/v8-stable/tutorials/tls.html
https://www.linux.com/blog/tls-encryption-and-mutual-authentication-using-syslog-ng-open-source-edition

A workaround would be to use stunnel as a wrapper per https://www.stunnel.org/howto.html or https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/security_guide/sec-configuring_stunnel_wrapper

**Comment by binarylogic** [comment]
Adding requirements so we can begin work:

## Requirements

We'll need to support the following `tls` table as shown here:

```toml
[sinks.tcp]
  type = "tcp"

  [sinks.tcp.tls]
    enabled = false # default
    verify = true # default
    ca_file = "/path/to/ca.crt" # no default, required if verify = true
    crt_file = "/path/to/cert.crt" # no default, required if verify = true
    key_file = "/path/to/private.key" # no default, required if verify = true
    key_phrase = "my_phrase" # optional
```

Options:

- [ ] `enabled` - boolean - defaults to `false`
- [ ] `verify` - boolean - defaults to `true` - If `true` Vector will force certificate validation.
- [ ] `ca_file` - string - no default - Absolute path to CA certificate file.
- [ ] `crt_file` - string - no default - Absolute path to certificate file.
- [ ] `key_file` - string - no default - Absolute path to private Key file.
- [ ] `key_phrase` - string - no default - Optional phrase for `key_file`.

Behavior:

There isn't anything special here. Currently, the `tcp` sink should log connection error and continue to retry connecting. TLS errors should just be another error in that same process. The `tls` options just raise the potential for other kind of errors, such as handshake errors, etc.

I'd also ask that you please think through the failure cases here and make sure my above comment is correct. I, unfortunately, am not an expert in this domain so it's possible I'm missing edge cases.
