### ISSUE TITLE
vector_processed_events_total metric missing from HTTP sink

### ISSUE THREAD

**Issue by hreidar** [timberio/vector#6069]
### Vector Version

```
vector:0.11.1-debian
```

### Vector Configuration File

```toml
# metrics
[sources.p2-metrics]
type = "internal_metrics"

### I have several file sources and add_fields transforms here which I have omitted from this example  ###

## sinks
[sinks.to_dedup]
  type = "http"
#  inputs = ["sampler"]
  inputs = ["back01-oss-fields",
            "cnr01-ipv6-fields",
            "cnr02-ipv6-fields",
            "cnr01-ipv4-fields",
            "cnr02-ipv4-fields",
            "cnr01-autod-fields",
            "cnr02-autod-fields"
           ]
  uri = "http://127.0.0.1:9001"
  encoding.codec = "json"
  healthcheck = false
  buffer.type = "disk"
  buffer.max_size = 104900000
  request.concurrency = "adaptive"

[sinks.p2-to-prometheus]
  type = "prometheus_exporter"
  inputs = ["p2-metrics"]
  address = "0.0.0.0:9501"
  default_namespace = "p2-ingress1"
  buckets = [0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0]
  quantiles = [0.5, 0.75, 0.9, 0.95, 0.99]
```

### Debug Output

Debug output: [https://gist.github.com/hreidar/dcb9506c8a0a0501110991d9827df32a](url)
Metrics output: [https://gist.github.com/hreidar/29889bca10c9aa2516038a191e32ba5f](url)

### Expected Behavior

I should have vector_processed_events_total for the HTTP sink.
### Actual Behavior

vector_processed_events_total for HTTP sink not in my metrics output.
### Additional Context

The example I have here is from a Vector container running on a VM. It is controlled by docker-compose. I also have a similar container that is running in a pod on Kubernetes. I see the same behavior there, no vector_processed_events_total for HTTP sink.
