### ISSUE TITLE
Setting healthcheck.enabled configuration fails

### ISSUE THREAD

**Issue by jamtur01** [timberio/vector#6101]
Take this config:

```toml
[sources.my_source_id]
  type = "socket" # required
  mode = "unix" # required
  path = "/tmp/temp.sock" # required, required when mode = `unix`

[sinks.my_sink_id]
  # General
  type = "loki" # required
  inputs = ["my_source_id"] # required
  endpoint = "http://localhost:3100" # required

  # Encoding
  encoding.codec = "json" # required

  # Healthcheck
  healthcheck.enabled = true # optional, default

  # Labels
  labels.forwarder = "vector" # example
  labels.event = "{{ event_field }}" # example
  labels.key = "value" # example
```

Running vector from head gets:

```
❯ vector -c ./target/release/vector.toml
Jan 16 12:40:05.807  INFO vector::app: Log level is enabled. level="vector=info,codec=info,file_source=info,tower_limit=trace,rdkafka=info"
Jan 16 12:40:05.807  INFO vector::app: Loading configs. path=[("target/release/vector.toml", None)]
Jan 16 12:40:05.810 ERROR vector::cli: Configuration error. error=invalid type: map, expected a boolean for key `sinks.my_sink_id.healthcheck` at line 16 column 25
```

Perhaps a `serde` error somewhere in config from https://github.com/timberio/vector/commit/6e517e50608ec29a75185385ac866db0cf2a33d1?

**Comment by gangtao** [comment]
I got the same error

**Comment by ktff** [comment]
@jamtur01 @gangtao are you both sure you are running this on master? 

#5564 landed after `v0.11.1`, and I don't see the error on the current master.

**Comment by jamtur01** [comment]
Hmmm. I just rebuilt and don't see the error now. Weird. @gangtao Can you share your version string? (`vector --version`) to confirm before I close.

**Comment by rcdailey** [comment]
I'm getting this as well using  YAML config format. Logs I get:

```
vector_1     | Feb 01 13:00:02.865  INFO vector::app: Log level is enabled. level="vector=info,codec=info,file_source=info,tower_limit=trace,rdkafka=info"
vector_1     | Feb 01 13:00:02.865  INFO vector::app: Loading configs. path=[("/etc/vector/vector.yml", None)]
vector_1     | Feb 01 13:00:02.867 ERROR vector::cli: Configuration error. error=sources.syslog: missing field `mode` at line 3 column 9
vector_1     | Feb 01 13:00:28.265  INFO vector::app: Log level is enabled. level="vector=info,codec=info,file_source=info,tower_limit=trace,rdkafka=info"
vector_1     | Feb 01 13:00:28.265  INFO vector::app: Loading configs. path=[("/etc/vector/vector.yml", None)]
vector_1     | Feb 01 13:00:28.266 ERROR vector::cli: Configuration error. error=sinks.loki.healthcheck: invalid type: map, expected a boolean at line 16 column 14
```

Config is:

```yml
sources:
  syslog:
    type: syslog
    address: 0.0.0.0:1514
    mode: tcp

sinks:
  loki:
    type: loki
    inputs:
      - syslog
    endpoint: http://loki:3100/loki/api/v1/push
    encoding:
      codec: json
    healthcheck:
      enabled: true
    labels:
      forwarder: vector
      source: nami varlogs
```

Result of `vector --version` (using it in Docker):

```
vector 0.11.1 (v0.11.1 x86_64-unknown-linux-musl 2020-12-17)
```

**Comment by jszwedko** [comment]
@rcdailey 0.11.1 actually still has the old config style so you'll want to use:

```yaml
sources:
  syslog:
    type: syslog
    address: 0.0.0.0:1514
    mode: tcp

sinks:
  loki:
    type: loki
    inputs:
      - syslog
    endpoint: http://loki:3100/loki/api/v1/push
    encoding:
      codec: json
    healthcheck: true
    labels:
      forwarder: vector
      source: nami varlogs
```

The next release will allow for using:

```
healthcheck:
  enabled: true
```
