### ISSUE TITLE
Mismatched type for extra_field_selector option

### ISSUE THREAD

**Issue by Alexx-G** [timberio/vector#6130]
### Vector Version

```
0.11.1
```

### Vector Configuration File

```yaml
kubernetesLogsSource:
  enabled: true
  sourceId: kubernetes_logs
  rawConfig: |
    extra_field_selector = "metadata.namespace=ingress-nginx"
```

### Expected Behavior

According to documentation it's should be possible to specify multiple field selectors, possible use cases:
- include/exclude logs only from specific namespace(s);
- exclude pods with a specific name

The first use case (including only specific namespaces or excluding other namespaces) and #5846 are the only issues (detected so far) that block us from upgrading from 0.8 :tada: 

### Actual Behavior

Setting this option to array results in vector rejecting the config.
IIRC the `extra_label_selector` option has the same problem.
