### ISSUE TITLE
Ability to disable individual sink health checks

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#621]
This came from https://github.com/timberio/vector/issues/620.

We need a way to disable healthchecks for select sinks. This should be a global / default option for all sinks. Ex:

```toml
[sinks.my_sink]
  healthcheck = false # defaults to true
```

Open to better naming here. I'd prefer that it start with `healthcheck` though so we can keep the healthcheck options together.
