### ISSUE TITLE
Enable Vector to "integration test" live data

### ISSUE THREAD

**Issue by lucperkins** [timberio/vector#6221]
Unit testing static data is one of Vector's less-sung but nonetheless most powerful features, especially now that condition checking supports VRL. A feature that may allow users to have *even more confidence* in how Vector will behave in production environments would be "integration testing," and by that I mean the ability to turn Vector on, have it process events from live sources and send events to live sinks, and return granular success/failure results. How many events? That would be configurable, potentially on a per-component basis with global defaults.

## Success/failure

In terms of determining success vs. failure, VRL could still be used, but users would have the option of specifying less restrictive conditions. Here's an example comparison:

```ruby
# Unit test
type = "remap"
source = '''
.foo == "bar" && .bar == [1, 2, 3] && .code >= 200 && .code < 300 && .some_boolean_condition

# Integration test
type = "remap"
source = '''
exists(.foo) && exists(.bar) && !exists(.baz)
'''
'''
```

For even less restrictive checks, you could specify that you're only trying to ascertain that no errors arise. In that case, you could set `type = "error_check"`, which is a special type of condition that yields either nothing (good) or a list of errors (bad).

## Concrete example

To make this a bit more concrete, imagine that you have two sources, Kafka and Syslog, some VRL transforms in the middle, and two sinks, S3 and Clickhouse. You could create a test environment with staging versions of all of those sources/sinks and configure Vector along these lines:

```toml
# The following is pseudocode
[[tests.integration.sources.my_kafka_source]]
num_events = 50
type = "error_check" # Make sure no errors emerge

[[tests.integration.sources.my_syslog_source]]
num_events = 25
type = "remap"
source = '''
_, err = parse_syslog!(.message)
err == null
'''

[[tests.integration.sinks.my_s3_sink]]
num_events = 100
type = "error_check"

# and so on
```
