### ISSUE TITLE
Cloudwatch logs sink assumes it can list all log groups

### ISSUE THREAD

**Issue by bittrance** [timberio/vector#624]
I consider the following to be a sensible IAM Cloudwatch logs policy for instances:
```
Statement:
  - Action:
      - logs:PutLogEvents
      - logs:CreateLogStream
    Effect: Allow
    Resource:
      - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/application/*:log-stream:*'}
```
The current Cloudwatch logs health check assumes it can do [describe_log_groups](https://github.com/timberio/vector/blob/d8a8e961a35d2eb7dadf183a69f214a4637a47b0/src/sinks/aws_cloudwatch_logs.rs#L435) which as far as I can tell translates into listing all log groups (i.e. requires permisions on `arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*:log-stream:*`) which I don't think is reasonable, particularly where multiple customers or environments share the same account. 

I'm not sure what is the best health check strategy: personally, I would prefer actually inserting a log event, but I imagine a lot of people would object to that. Can we at least change the health check to use `describe_log_stream` which is anyway required for [normal operation](https://github.com/timberio/vector/blob/d8a8e961a35d2eb7dadf183a69f214a4637a47b0/src/sinks/aws_cloudwatch_logs.rs#L307) ?

(I'll be happy to provide a PR if you think this is a reasonable change.)
