### ISSUE TITLE
Invalid gzip compression when using s3 as sink

### ISSUE THREAD

**Issue by inian** [timberio/vector#6241]
### Vector Version

```
vector 0.11.1 (v0.11.1 aarch64-unknown-linux-musl 2020-12-17)
```

### Vector Configuration File

```toml
..my sources..

[sinks.s3_sink]
    type = "aws_s3"
    inputs = ["source_id"]
    bucket = "bucket_name"
    region = "us-west-1"
    encoding.codec = "ndjson"
    key_prefix = "{{ project }}/%F/"
    batch.timeout_secs = 300
```

### Debug Output
No errors or warnings were found in the vector log

### Expected Behavior
The gzip uploaded to s3 are valid GZIP

### Actual Behavior
Gzip uploaded to s3 aren't valid GZIP. I can't decompress them. 

### References

Might be related - https://github.com/timberio/vector/issues/5918
