### ISSUE TITLE
Remove strftime specifiers from the templating syntax

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#6254]
The current support for strftime specifiers in the templating syntax was a quick hack to allow for date-based partitioning:

```toml
[sinks.backup]
  type = "aws_s3"
  bucket = "all_application_logs"
  key_prefix = "application_id={{ application_id }}/date=%F/"
```

The obvious limitation of this is the assumption that the `timestamp` field should be used to derive their formatted dates. What if a user wants to use another field?

Given that we decided against supporting the Remap syntax in #3836, we should do 1 of 2 things:

1. Remove support for the strftime specifiers and require users to format dates in a `remap` transform.
2. Reopen the discussion of supporting Remap functions in the templating syntax.

I lean towards 1 until we see more reasons to do 2.
