### ISSUE TITLE
Document how to configure and install Vector on Kubernetes in Oracle Cloud

### ISSUE THREAD

**Issue by Foosvald** [timberio/vector#6277]
### Current Vector Version

```
timberio/vector:0.11.1-debian
```

### Use-cases

I want to collect logs from Kubernetes running in Oracle Cloud (https://www.oracle.com/cloud-native/container-engine-kubernetes/). I simply followed the guide in https://vector.dev/docs/setup/installation/platforms/kubernetes/ and installed Vector using Helm, but the Vector pods didn't manage to collect any logs from Kubernetes. They also didn't log any errors...

### Attempted Solutions

By changing the values.yaml file to mount /u01/data/docker/containers/ I managed to get it working, since this is where Kubernetes in Oracle is saving the logs. This is the working values.yaml file:

```
# The Vector Kubernetes integration automatically defines a
# kubernetes_logs source that is made available to you.
# You do not need to define a log source.
extraVolumes:       
- name: u01data
  hostPath:
    path: /u01/data/docker/containers/

extraVolumeMounts:
- name: u01data
  mountPath: /u01/data/docker/containers/
  readOnly: true

sinks:
  # Adjust as necessary. By default we use the console sink
  # to print all data. This allows you to see Vector working.
  # https://vector.dev/docs/reference/sinks/
  stdout:
    type: console
    inputs: ["kubernetes_logs"]
    rawConfig: |
      target = "stdout"
      encoding = "json"

```
(Installed with `helm install --namespace vector --create-namespace vector timberio/vector-agent --values values.yaml`)

### Proposal

Maybe it would be good to add documentation describing what needs to be configured for different managed Kubernetes environments?
