### ISSUE TITLE
Unit tests with Remap conditions should display the source of a failed test

### ISSUE THREAD

**Issue by StephenWakely** [timberio/vector#6321]
Say you have a unit test with multiple Remap conditions:

```toml
 [[tests.outputs]]
    extract_from = "remap_nested"
    conditions = [
      '.a.b == 123',
      '.x.y == 4563'
    ]
```

If one of the conditions fails, the failing test is displayed:

```
check transform 'remap_nested' failed conditions:
  condition[1]: source execution resolved to false
```

It would be useful if it could also print the source of the failing condition as well as the index.
