### ISSUE TITLE
Allow `time` field to be set on `splunk_hec` source

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#6368]
Requested by user: https://github.com/timberio/vector/issues/6185#issuecomment-773566173

The user would like to be able to specify the `time` Splunk metadata field in the same way as other metadata fields like `source` and `sourcetype` can be specified.

For example:

```toml
[sinks.splunk_hec]
type = "splunk_hec"
inputs = [...]

time = "{{ alert_timestamp }}"
```

Currently the `splunk_hec` source only uses the `timestamp` key.

Notably, I think this will require some extra parsing since templates return strings, but we need to convert the timestamp to a unix timestamp in that sink. I think optimistically parsing the timestamps with the default timestamp formats supported by the `coercer` transform could be an approach.
