### ISSUE TITLE
Config timestamp field interpolation

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#638]
### Description

#519 introduced support for interpolating event attributes in config values. For example:

```toml
[sinks.my_cw_sink]
  type = "aws_cloudwatch_logs"
  group_name = "{{file}}"
  stream_name = "{{host}}"
```

While this works for primitive types this gets a little tricky with timestamps.
I'd like to allow `strftime` specifiers on timestamp fields. This should be
reuired. For example:

```toml
[sinks.my_cw_sink]
  type = "aws_cloudwatch_logs"
  group_name = "{{file}}"
  stream_name = "{{timestamp | strftime %Y/%m/%d}}"
```

I'm open to other syntaxes, but my thought process is that we'll probably want
to allow other modifiers in the future, such as `downcase`. This syntax is
very similar to liquid. I do not want to support a full liquid syntax, just
simple modifiers.

### Old timestamp interpolation

Once this is done I'd like drop the old naked timestamp interpolation. Ex: `%F`.

### Requirements

- [ ] If a `timestamp` type is used the default should be ISO8601
- [ ] Log a rate limited error if the formatting fails.
