### ISSUE TITLE
docker_logs not using the host key defined in the configuration

### ISSUE THREAD

**Issue by drunkirishcoder** [timberio/vector#6394]
### Vector Version

0.11.1

### Vector Configuration File

```toml
[log_schema]
  host_key = "host.hostname"
  timestamp_key = "@timestamp"

[sources.docker]
  type = "docker_logs"

[sinks.console]
  type = "console"
  inputs = ["docker"]
  encoding = "json"
```

### Debug Output

```json
{
  "@timestamp": "2021-02-08T16:38:35.639689800Z",
  "container_created_at": "2021-02-08T16:38:35.206171600Z",
  "container_id": "3f108cb61775cb261491e8ba47d49b9c9dcd455448bfa624250ad61ae1e80f66",
  "container_name": "goofy_mayer",
  "host": "HQSML-1719880",
  "image": "timberio/vector:nightly-debian",
  "message": "Feb 08 16:38:35.639  INFO vector::app: Log level is enabled. level=\"vector=info,codec=info,file_source=info,tower_limit=trace,rdkafka=info\"",
  "source_type": "docker",
  "stream": "stdout"
}
```

### Expected Behavior

The hostname should be inserted as `host.hostname`.

### Actual Behavior

The hostname is inserted with the global default key `host`, not the override key name in the configuration.
