### ISSUE TITLE
HTTP proxy support

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#6401]
Requested by user in discord: https://discord.com/channels/742820443487993987/746070591097798688/808697724547104815

I think we can take a general approach, similar to other HTTP configuration, to allow for the use of an HTTP proxy with any component that makes HTTP requests. We could allow specification of the proxy both at the global and component level.

Suggested config:

Global:

```toml
[proxy]
http = "http://myproxy:3128"
https = "http://myproxy:3128"
no_proxy = ["localhost", "192.168.1.1"]
```

Component:

```toml
[sinks.http]
type = "http"
proxy.http = "http://myproxy:3128"
proxy.https = "http://myproxy:3128"
proxy.no_proxy = ["localhost", "192.168.1.1"]
```

Additionally we should read from the following env vars:

```
HTTP_PROXY
HTTPS_PROXY
NO_PROXY
http_proxy
https_proxy
no_proxy
```

These are commonly supported env vars for this purpose (for example `curl` respects them). `no_proxy` should accept a comma delimited list.

Ref: https://github.com/timberio/vector/issues/4534
