### ISSUE TITLE
'remap' doesn't make sense when I just want to check a field

### ISSUE THREAD

**Issue by FHIR360** [timberio/vector#6419]
"remap' doesn't make sense to me. I prefer check for field "x" and if it contains "y". please make a check_fields feature.

**Comment by binarylogic** [comment]
Hi, could you give us more context? Are you referring to the `type` option?

**Comment by FHIR360** [comment]
Hello @binarylogic, I am jumping in on a project and it seems lots of syntax has changed since I looked at the documentation last. Previously, we were using a "check_fields" type in swimlanes and it seemed straightforward. The "new" (to me) way seems a bit more convoluted. Maybe I am missing something.

**Comment by JeanMertz** [comment]
@FHIR360 thanks for that context.

Do you have an example snippet of config of the before situation and the after situation?

After the 0.12 release drops (today, hopefully), it _should_ suffice to change this:

```toml
[transforms.routing]
type = "swimlane"
inputs = ["..."]
lanes.errors."level.contains" = "error"
```

To this:

```toml
[transforms.routing]
type = "route"
inputs = ["..."]
lanes.errors = 'contains(.level, "error")'
```

Which looks straightforward to me. However, I understand this is somewhat subjective, so maybe it doesn't look as straightforward to you?

To give a bit more context: the reason we made this change is that VRL (Vector Remap Language) will become a core part of most Vector configs through the new `remap` transform, and so having it be consistently used in other locations where we can use it makes sense to us, as it removes the need to know when you can, and when you can't use VRL.

Also, I should point out that the 0.12 release will include an entire section on the website to explain VRL and how to use it, so hopefully that makes it easier to migrate.
