### ISSUE TITLE
Loki sink: Labels with "/" in them seemingly ignored.

### ISSUE THREAD

**Issue by DanTulovsky** [timberio/vector#6431]
### Vector Version

```
Vector has started. version="0.12.0" git_version="v0.11.0-508-g0793e59" released="Thu, 11 Feb 2021 04:44:24 +0000" arch="x86_64"
```

### Vector Configuration File

```toml
# Configuration for vector.
# Docs: https://vector.dev/docs/

data_dir = "/vector-data-dir"

[api]
  enabled = false
  address = "0.0.0.0:8686"
  playground = true

[log_schema]
  host_key = "host"
  message_key = "message"
  source_type_key = "source_type"
  timestamp_key = "timestamp"

# Ingest logs from Kubernetes.
[sources.kubernetes_logs]
  type = "kubernetes_logs"

# Capture the metrics from the host.
[sources.host_metrics]
  type = "host_metrics"


# Emit internal Vector metrics.
[sources.internal_metrics]
  type = "internal_metrics"

# Expose metrics for scraping in the Prometheus format.
[sinks.prometheus_sink]
  address = "0.0.0.0:9090"
  inputs = ["internal_metrics", "host_metrics"]
  type = "prometheus"


[sinks.kafka0]
  inputs = ["kubernetes_logs"]
  type = "kafka"
  # General
  bootstrap_servers = "kafka0-headless.kafka:9092"
  compression = "gzip" # optional, default
  key_field = "pod" # required
  topic = "kube-logs" # required
  encoding.codec = "json"
  

[sinks.loki]
  inputs = ["kubernetes_logs"]
  type = "loki"
  endpoint = "http://loki.monitoring:3100"
  remove_timestamp = true
  encoding.codec = "json"
  labels.forwarder = "vector"
  labels.file = "{{ file }}"
  labels.stream = "{{ stream }}"
  labels.source_type = "{{ source_type }}"
  labels.k8s_pod_namespace = "{{ kubernetes.pod_namespace }}"
  labels.k8s_pod_name = "{{ kubernetes.pod_name }}"
  labels.k8s_pod_uid = "{{ kubernetes.pod_uid }}"
  labels.k8s_pod_ip = "{{ kubernetes.pod_ip }}"
  labels.k8s_pod_ips = "{{ kubernetes.pod_ips }}"
  labels.k8s_pod_node_name = "{{ kubernetes.pod_node_name }}"
  labels.k8s_app = "{{ kubernetes.pod_labels.app }}"
  labels.k8s_kubernetes_io_instance = "{{ kubernetes.pod_labels.app.kubernetes.io/instance }}"
  labels.k8s_kubernetes_io_component = "{{ kubernetes.pod_labels.app.kubernetes.io/component }}"
  labels.k8s_kubernetes_io_name = "{{ kubernetes.pod_labels.app.kubernetes.io/name }}"
  labels.source_type = "{{ source_type }}"
  labels.k8s_container_name = "{{ kubernetes.container_name }}"
  labels.k8s_container_image = "{{ kubernetes.container_image }}"
  request.in_flight_limit = 1

```

### Expected Behavior

It looks like labels with "/" in them are ignored by the loki sink.  e.g.

```
labels.k8s_kubernetes_io_instance = "{{ kubernetes.pod_labels.app.kubernetes.io/instance }}"
```

does not create the `k8s_kubernetes_io_instance` label.

### Actual Behavior

`k8s_kubernetes_io_instance ` is missing.

### Example Data

![FireShot Capture 025 - Grafana - grafana wetsnow com](https://user-images.githubusercontent.com/509887/107788109-05484180-6d1e-11eb-86d1-f499cc6f51d8.png)

Note the missing `k8s_kubernetes_io_instance` label in the Log Labels section.
