### ISSUE TITLE
How read from structured json logs?

### ISSUE THREAD

**Issue by mamcx** [timberio/vector#6457]
Is not clear to me how read from file/stdin when the log is already structured. I use tracing in Rust and get:

```json
{"timestamp":"Feb 16 12:05:10.439","level":"DEBUG","fields":{"message":"ExeSql","sql":"\" SELECT 1 FROM information_schema.schemata WHERE schema_name=\\'public\\'\"","params":"None","company":"\"public\""},"target":"corelib::db::pg"}
{"timestamp":"Feb 16 12:05:10.470","level":"DEBUG","fields":{"message":"ExeSql","sql":"\"SELECT libs.set_schema(\\'public\\')\"","params":"None","company":"\"public\""},"target":"corelib::db::pg"}
{"timestamp":"Feb 16 12:05:10.484","level":"DEBUG","fields":{"message":"SELECT","sql":"\" SELECT     * FROM     Company     \"","params":"None","company":"\"public\""},"target":"corelib::db::pg"}
```

So I assume I need to do:

```toml
# General
data_dir = "/tmp/" 

[sources.apps]
  type         = "file"
  include      = ["path/sync/*.log"]
  host_key     = "dev"

[transforms.parse]
  inputs = ["apps"]
  type = "json_parser"

[sinks.print]
  type = "console"
  inputs = ["parse"]
  target = "stdout"
  encoding = "json"
```

However, I see the whole file is set to the message instead of parse per object/line.
