### ISSUE TITLE
File input wildcard glob maybe not working

### ISSUE THREAD

**Issue by fogg4444** [timberio/vector#6460]
### Vector Version

```
vector 0.11.1 (v0.11.1 x86_64-unknown-linux-gnu 2020-12-17)
```

### Vector Configuration File

```toml
[sources.my_logs]
  type = "file"
  start_at_beginning = true
  include = ["/dir/dir/dir/dir/**/dir/dir/my_logs.stdout.0"]
```

### Behavior
I have a system which creates directories on the fly and I want to capture logs from many directories. This wildcard with two asterisks does not appear to work. If I hardcode one of the directories, it's working fine.

Docs say it works here: https://vector.dev/docs/reference/sources/file/
