### ISSUE TITLE
Memory usage keeps increasing with Prometheus sink

### ISSUE THREAD

**Issue by svend** [timberio/vector#6461]
### Vector Version

```
vector 0.11.1 (v0.11.1 x86_64-unknown-linux-gnu 2020-12-17)

Using Docker image:
    Image:         timberio/vector:0.11.1-debian
    Image ID:      docker.io/timberio/vector@sha256:3d21e43161d77abc56675a7f163e6962d5180538a68a7285b7b9334a4fa88f42
```

### Vector Configuration File

```toml


# Create syslog source
[sources.syslog]
type = "syslog"
address = "0.0.0.0:9000"
mode = "udp"

# Vector system metrics
[sources.internal]
type = "internal_metrics"

# Parse request event logs
[transforms.json_parser]
type = "json_parser"
inputs = ["syslog"]
drop_invalid = true # required

# Transform the parsed event into a metric
[transforms.log_to_metric]
inputs = ["json_parser"]
type = "log_to_metric"

[[transforms.log_to_metric.metrics]]
namespace = "http"
type = "histogram"
field = "request_duration"
name = "request_duration_seconds"
tags.http_status = "{{http_status}}" # Cardinality: 12
tags.endpoint = "{{endpoint}}"       # Cardinality: (N/A) (client mapped to same endpoint)
tags.client = "{{client}}"           # Cardinality: 1000

# Set up Promtheus metrics sink

[sinks.prometheus]
inputs = ["internal", "log_to_metric"]
type = "prometheus_exporter"
address = "0.0.0.0:9090"
# Cardinality: 36 (35 + "Inf")
buckets = [0.001, 0.002, 0.003, 0.004, 0.005, 0.006, 0.007, 0.008, 0.009, 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 2, 3, 4, 5, 6, 7, 8, 9]
```

### Expected Behavior

Memory usage should stabilize once metric cardinality has stabilized.

### Actual Behavior

Memory usage continues to grow.

### Example Data

Memory usage:

![image](https://user-images.githubusercontent.com/306190/108115442-fbd91500-704e-11eb-9a11-e92f6e87dcdf.png)

Samples scraped:

![image](https://user-images.githubusercontent.com/306190/108115593-3642b200-704f-11eb-9bc8-c136e8c1dfd4.png)

Metric cardinality:

![image](https://user-images.githubusercontent.com/306190/108121245-570f0580-7057-11eb-883b-225828918e46.png)

### Additional Context

I am testing vector for exposing high cardinality metrics.

Records are sent to vector at a rate of 400 per second. The number of metrics exposed grows for about five minutes, until it reaches the maximum value of 468008. The number of metrics never goes higher than this.

After the first five minutes, the memory initially varies between 27 MiB and 150 MiB. (The memory goes up during a scrape, which happens every 30 seconds.) The memory usage continues to grow, and after about 18 hours it hits a Kubernetes container memory limit of 512 MiB, and the process is OOM-killed.
