### ISSUE TITLE
Misbehaving multiline behavior

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#6486]
Reported by user in discord: https://discord.com/channels/742820443487993987/746070591097798688/811980747853266954

Vector seems to be exhibiting odd multiline merging behavior where it starts incorrectly identifying start or end conditions after some number of identical lines.

### Vector Version

```
vector 0.11.1 (v0.11.1 x86_64-apple-darwin 2020-12-17)
```

### Vector Configuration File

```toml
data_dir = "/tmp/vector"
[sources.fwd_gw]
    type = "file"
    include = ["/tmp/tmp.log"]
    start_at_beginning = true
    ignore_older = 86400

    [sources.fwd_gw.multiline]
        start_pattern = '^\[\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}\]'
        mode = "halt_before"
        condition_pattern = '^\[\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}\]'
        timeout_ms = 1000

[transforms.timestamp_parse]
    type = "regex_parser"
    inputs = ["fwd_gw"]
    field = "message"
    patterns = ['^\[(?P<dt_event>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3})\]\s(?P<message_text>(.|\n)*$)']
    types.dt_event = "timestamp|%Y-%m-%d %H:%M:%S,%3f"

[transforms.message_parse]
    type = "regex_parser"
    inputs = ["timestamp_parse"]
    field = "message_text"
    drop_field = false
    patterns = ['^(?P<level>\w+)']

[sinks.console]
type = "console"
inputs = ["message_parse"]
encoding.codec = "json"
```

### Debug Output

[output.txt.gz](https://github.com/timberio/vector/files/6005236/output.txt.gz)

### Expected Behavior

Vector should have processed all lines correctly.

### Actual Behavior

It starts misidentifying lines (search for "failed to match").

### Example Data

Input file (compressed): 
[tmp.log.gz](https://github.com/timberio/vector/files/6005237/tmp.log.gz)
