### ISSUE TITLE
VRL string pattern crashes Vector

### ISSUE THREAD

**Issue by lucperkins** [timberio/vector#6571]
On a whim, I tried out this string inside a VRL program:

```
"foo\/bar"
```

This immediately crashed the VRL REPL:

```
thread 'main' panicked at 'not implemented: invalid escape', lib/vrl/parser/src/lex.rs:1110:18
```

I also tried it out in a real configuration, with the same result:

```toml
[sources.in]
type = "generator"
format = "json"
interval = 1

[transforms.modify]
type = "remap"
inputs = ["in"]
source = '''
.field = "foo\/bar"
'''

[sinks.out]
type = "console"
inputs = ["modify"]
encoding.codec = "json"
```

The offending code is [here](https://github.com/timberio/vector/blob/master/lib/vrl/parser/src/lex.rs#L1100-L1120).
