### ISSUE TITLE
Allow config reloading that changes global options

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#6598]
@ktff noted in https://github.com/timberio/vector/pull/6581#discussion_r585865848 that changes to global vector configuration will not be picked up by config reloads. This includes:

```toml
# General
data_dir = "/var/lib/vector/" # optional, default

# Log Schema
log_schema.host_key = "host" # optional, default
log_schema.message_key = "message" # optional, default
log_schema.source_type_key = "source_type" # optional, default
log_schema.timestamp_key = "timestamp" # optional, default
```

Ideally these config options would be modifiable between config reloads as well for consistency, but it was noted this will require rebuilding components even when their configuration remains the same between reloads.
