### ISSUE TITLE
issue with disk buffer - data_dir filling up with ldb files and data even though data is making it upstream

### ISSUE THREAD

**Issue by ryn9** [timberio/vector#6602]
I am having an issue with disk buffer in an http sink.
The data_dir filling up with ldb files and data even though data is making it upstream.

### Vector Version
From timberio/vector:0.11.1-alpine
```
vector 0.11.1 (v0.11.1 x86_64-unknown-linux-musl 2020-12-17)
```

### Vector Configuration File

Numerous input and transforms, but everything end up going out the one sink...
```
sinks:
  logs_out:
    type: http
    inputs:
      - logs_remove_fields
    compression: gzip
    uri: https://url.domain.name:10010/logs
    tls:
      ca_file: /etc/vector/ssl_auth/ca-certificates.crt
      crt_file: /etc/vector/ssl_auth/client.crt
      key_file: /etc/vector/ssl_auth/client.key
      verify_hostname: true
    encoding:
      codec: ndjson
      timestamp_format: rfc3339
    buffer:
      max_size: 10737418240
      type: disk
      when_full: block
```

### Debug Output
Not performed

### Expected Behavior

The data_dir should have buffered data only that has not been flushed.

### Actual Behavior

The data_dir filling up with ldb files and data even though data is making it upstream.

### Example Data

N/A

### Additional Context

N/A

### References

N/A

### Additional Notes
I started asking about this on this Discord Timber server, in the support channel.
Please feel free to reach out via that method as well if more information is needed.
