### ISSUE TITLE
VRL doesn't allow uppercase characters in unquoted path fields

### ISSUE THREAD

**Issue by FungusHumungus** [timberio/vector#6625]
Spotted on [Discord](https://discord.com/channels/742820443487993987/764187584452493323/817079342626111518).

According to our [docs](https://master.vector.dev/docs/reference/vrl/expressions/#path_segments) path fields can be `_ (a-zA-Z0-9_)`. 

However VRL only accepts lowercase characters, as per [here](https://github.com/timberio/vector/blob/master/lib/vrl/parser/src/lex.rs#L1076).

Also, VRL does not allow underscores `_` at the first character position. 

These are allowed in our Toml config:

```toml
[transforms.rename]
type = "rename_fields"
inputs = ["json"]
fields._OLD_CHILD_NAME = "_NEW_CHILD_NAME" # example
```

So these should be allowed in VRL too.
