### ISSUE TITLE
Memory leak while using kubernetes_logs source

### ISSUE THREAD

**Issue by karlmartink** [timberio/vector#6673]
### Vector Version

```
0.11.1-alpine

```

running on Kubernetes
```
v1.19.3
```
### Vector Configuration File

```toml

    [sources.kube_logs_1]
      type = "kubernetes_logs"
      exclude_paths_glob_patterns = ["**/calico-node/**"]
      annotation_fields.container_name = "container_name"
      annotation_fields.container_image = "container_image"
      annotation_fields.pod_ip = "pod_ip"
      annotation_fields.pod_name = "pod_name"
      annotation_fields.pod_namespace = "namespace_name"
      annotation_fields.pod_node_name = "pod_node_name"
      annotation_fields.pod_uid = "pod_uid"

    [transforms.kube_logs_remapped]
      type = "remap"
      inputs = ["kube_logs_1"]
      source = '''
      .full_message = .message
      .message = "pod_stderr_stdout"
      .source = .pod_node_name
      del(.file)
      del(.pod_node_name)
      del(.kubernetes)
      '''
    [transforms.add_region_fields_to_logs]
      type = "add_fields"
      inputs = ["vector_1", "kube_logs_remapped"]
      fields.env = "<%= @environment %>"
      fields.region = "<%= @region %>"
      fields.region_domain = "<%= @region_domain %>"

    [sinks.graylog_gelf]
      type = "http"
      inputs = ["add_region_fields_to_logs"]
      uri = xxx
      encoding.codec = "ndjson"
      compression = "none"
      batch.max_bytes = 4096
      #batch.timeout_secs = 1
      #buffer.max_events = 1
      #buffer.type = "memory"
      tls.verify_hostname = false
```

### Debug Output

https://gist.github.com/karlmartink/095979bec3dea7d91430c91a842d3927

### Expected Behavior

Stable memory usage or slight increase until some maximum level is increased.

### Actual Behavior

Containers memory + cpu usage is slowly growing overtime until maximum limits are reached and service is killed while processed events remain the same.

### Example Data

POD CPU and Memory usage
<img width="1594" alt="Screenshot 2021-03-09 at 15 14 19" src="https://user-images.githubusercontent.com/39082269/110476526-befebc00-80ea-11eb-9792-2a28c3e348fe.png">

Processed events
<img width="744" alt="Screenshot 2021-03-09 at 15 14 28" src="https://user-images.githubusercontent.com/39082269/110476544-c3c37000-80ea-11eb-9132-e64c042717f7.png">

### Additional Context

I am using vector to mostly collect Kubernetes logs and manipulate them with some transforms. After that they get forwarded to graylog via HTTP to GELF input.
