### ISSUE TITLE
Aws_cloudwatch_logs doesn't work with no error or warning produced

### ISSUE THREAD

**Issue by droslean** [timberio/vector#6682]
Version: `0.11.1`

Here is my configuration

```toml
    data_dir = "/var/lib/vector"

    [sources.kubernetes]
      type = "kubernetes_logs"

    [transforms.ci-services]
      type = "filter"
      inputs = ["kubernetes"]
      condition.type = "check_fields"
      condition."pod_namespace.eq" = "my-namespace"
      condition."container_name.neq" = "vector"

    [transforms.json_parsed]
      type = "json_parser"
      inputs = ["ci-services"]
      drop_invalid = true


    [sinks.aws_cloudwatch_logs]
      type = "aws_cloudwatch_logs"
      inputs = ["json_parsed"]
      group_name = "app-ci-pod-logs-test"
      region = "us-east-1"
      stream_name = "{{ host }}"
      encoding = "json"
      batch.max_size = 1000000
```

In vector pod, there are tons of logs like 
`Found new file to watch` `Resuming to watch file` `Currently ignoring file` but there is no ERROR anywhere.

While running the pods with `LOG=debug` env var, I noticed that it does some successful calls to AWS.

**Comment by jszwedko** [comment]
Discussed this with the user in discord: https://discord.com/channels/742820443487993987/753400475545501836/819212586003464193

The issue ended up being that their `filter` transform needed to be:

```toml
    [transforms.ci-services]
      type = "filter"
      inputs = ["kubernetes"]
      condition.type = "check_fields"
      condition."kubernetes.pod_namespace.eq" = "my-namespace"
      condition."kubernetes.container_name.neq" = "vector"
```

Also `stream_name = "{{ host }}"` was changed to `stream_name = "{{ kubernetes.pod_node_name }}"`given that `host` isn't defined on events coming from the `kubernetes_logs` source.
