### ISSUE TITLE
sinks.aws_cloudwatch_logs wrong validation on configuration 

### ISSUE THREAD

**Issue by droslean** [timberio/vector#6684]
Version `0.11.1`

Error
```console
 ERROR vector::cli: Configuration error. error=invalid type: map, expected a boolean for key `sinks.aws_cloudwatch_logs.healthcheck`
```
Configuration:
```toml
    [sinks.aws_cloudwatch_logs]
      type = "aws_cloudwatch_logs"
      inputs = ["json_parsed"]
      compression = "none"
      create_missing_group = true
      create_missing_stream = true
      group_name = "app-ci-pod-logs-test"
      region = "us-east-1" 
      stream_name = "{{ host }}"
      encoding.codec = "json"
      healthcheck.enabled = true
```
