### ISSUE TITLE
`promotheus_exporter` publishes metrics with stale timestamps which breaks scraping

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#6725]
Reported by user in discord:

https://discord.com/channels/742820443487993987/746070591097798688/819569444073897998

It looks like the `prometheus_exporter` sink can expose metrics that have the same timestamp but different values (that is, the timestamp is stale). This breaks scraping by prometheus as it complains that it already ingested a metric with that timestamp with a different value.

I had the user run `curl` twice to verify. They got:

```
# HELP nginx_http_response_count_total http_response_count_total
# TYPE nginx_http_response_count_total counter
nginx_http_response_count_total{host="docker-vagrant",remote_user="ATG",request_uri="/loyalty-engine/rest/sp145/v1",status="200"} 4535 1615480381223
nginx_http_response_count_total{host="docker-vagrant",remote_user="FOBO",request_uri="/fiscalization/rest/create-check",status="200"} 4571 1615480381223
nginx_http_response_count_total{host="docker-vagrant",remote_user="other",request_uri="/eldo-transfer/rest/order/block",status="200"} 4651 1615480381223
nginx_http_response_count_total{host="docker-vagrant",remote_user="other",request_uri="/mlmLoyalty/rest/v1/external/process",status="200"} 4456 1615480381223
nginx_http_response_count_total{host="docker-vagrant",remote_user="CRM",request_uri="/acquiring/rest/banking/payment/info/extended",status="200"} 4604 161548038122
```

and then

```
# HELP nginx_http_response_count_total http_response_count_total
# TYPE nginx_http_response_count_total counter
nginx_http_response_count_total{host="docker-vagrant",remote_user="other",request_uri="/mlmLoyalty/rest/v1/external/process",status="200"} 4458 1615480381223
nginx_http_response_count_total{host="docker-vagrant",remote_user="ATG",request_uri="/loyalty-engine/rest/sp145/v1",status="200"} 4536 1615480381223
nginx_http_response_count_total{host="docker-vagrant",remote_user="FOBO",request_uri="/fiscalization/rest/create-check",status="200"} 4572 1615480381223
nginx_http_response_count_total{host="docker-vagrant",remote_user="other",request_uri="/eldo-transfer/rest/order/block",status="200"} 4655 1615480381223
nginx_http_response_count_total{host="docker-vagrant",remote_user="CRM",request_uri="/acquiring/rest/banking/payment/info/extended",status="200"} 4605 161548038122
```

As we can see here, the counter values changed but the timestamp is the same. The timestamp should be updated whenever the metric value changes.

This is a regression from 0.11.1 to 0.12.0 given 0.11.1 didn't publish timestamps in the `prometheus_exporter` sink.

Partial config:

```toml
[transforms.nginx_http_metrics]
  type = "log_to_metric"
  inputs = ["nginx_parse_coercer"]

  [[transforms.nginx_http_metrics.metrics]]
     type = "counter"
     field = "status"
     name = "http_response_count_total"
     namespace = "nginx"

     tags.host = "docker-vagrant"
     tags.remote_user = "{{ remote_user }}"
     tags.request_uri = "{{ request_uri }}"
     tags.status = "{{ status }}"

[sinks.nginx_output_prometheus]
 address = "0.0.0.0:9598"
 inputs = ["nginx_http_metrics"]
 type = "prometheus"
 default_namespace = "vector"
```
