### ISSUE TITLE
vector segfaults on compiling a filter

### ISSUE THREAD

**Issue by jeromekleinen** [timberio/vector#6726]
Hello,

I seem to have ran into an issue when trying to build a filter.

Version: 0.12.0 stable, running on RHEL8, installed from rpm package.

This is the config I am using:

```
# listen on tcp socket
[sources.socket]
  type = "socket"
  address = "0.0.0.0:9000"
  max_length = 102400
  mode = "tcp"

# filter netconn
[transforms.filter]
  type = "filter"
  inputs = ["socket"]
  condition = '''
  !(
    (.a == 1 && .b == 53 && incudes(["a", "b"], .c)) ||
    (starts_with(.d, "a") && starts_with(.e, "b")) ||
    (.f == "abc") ||
    (.g == "def" && includes([1, 2, 3], .a) && .f == "def") ||
    (starts_with(.f, "jik"))
   )
  '''

[sinks.stdout]
  type = "console"
  inputs = ["filter"]
  target = "stdout"
  
  encoding.codec = "json"
```

which leads to
```
Mar 11 17:39:34.561  INFO vector::app: Loading configs. path=[("segfault.toml", None)]
Segmentation fault
```

I'm available in Discord if you have any questions.

Jerome

**Comment by binarylogic** [comment]
Thanks @jeromekleinen, @FungusHumungus @JeanMertz that seems like it's related to the new remap conditional support.

**Comment by jeromekleinen** [comment]
In some other attempts for this configuration I stumbled upon the following error:

```
thread 'main' panicked at 'a Display implementation returned an error unexpectedly: Error', /rust/lib/rustlib/src/rust/library/alloc/src/string.rs:2204:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Perhaps this can help in pinpointing the issue.

**Comment by jeromekleinen** [comment]
Periodically, the config from the first post doesn't segfault but instead gives the following memory allocation error:

```
memory allocation of 140735845393665 bytes failed
Aborted
```

**Comment by jszwedko** [comment]
Another example config that causes this, using `reduce`:

```toml
[sources.in]
type = "stdin"

[transforms.reduce]
type = "reduce"
inputs = ["in"]
starts_when = """
  matches(.message, r'\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}.\\d{3}')
"""
merge_strategies.message = "concat_newline"

[sinks.out]
type = "console"
inputs = ["reduce"]
encoding.codec = "json"
```
