### ISSUE TITLE
File source has suboptimial performance degredation as line sizes increase

### ISSUE THREAD

**Issue by blt** [timberio/vector#6730]
### Vector Version

Custom build of 0327d46a9d213b5390e11d86b920224bdf91ed38. Build string:

```
RUSTFLAGS="-g" cargo build --no-default-features --features "sources-file,sources-internal_metrics,sinks-prometheus,sinks-blackhole" --release 
```

### Vector Configuration File

```toml
data_dir = "data"

[sources.internal]
type = "internal_metrics"

[sources.file]
type = "file"
max_line_bytes = 102400
fingerprint.strategy = "device_and_inode"
include = ["logs/*.log"]

[sinks.prometheus]
type = "prometheus_exporter"
inputs = ["internal"]
address = "0.0.0.0:9001"

[sinks.blackhole]
type = "blackhole"
inputs = ["file"]
```

### Expected Behavior

The file source as of the above commit demonstrates a sub-optimal throughput drop-off when line sizes go beyond 100Kb. Before this point the source is capable of processing at least 25Mb/s -- see https://github.com/timberio/vector-test-harness/pull/74 for details -- but after this performance drops off significantly all the way to 900Kb/s. 

### Actual Behavior

https://github.com/timberio/vector-test-harness/pull/74#discussion_r591917337

### Example Data

See referenced issue. 

### Additional Context

See referenced issue. 

### References

* https://github.com/timberio/vector-test-harness/pull/74
