### ISSUE TITLE
K8s log source sets `default_glob_minimum_cooldown_ms` too high, does not document its existence 

### ISSUE THREAD

**Issue by blt** [timberio/vector#6771]
### Vector Version

```
0.12.1
```

### Expected Behavior

When reading Kubernetes logs via the k8s logs source Vector will not lose log lines. 

### Actual Behavior

Kubernetes log source implicitly sets `default_glob_minimum_cooldown_ms` to 60,000 milliseconds, or one minute. In environments where there is a high degree of log rotation vector will miss logs. We should adjust the default down to the file source's -- 1,000 milliseconds -- and document the existence of `default_glob_minimum_cooldown_ms`.

**Comment by CasparChou** [comment]
as fluentbit defualt config is 5000ms
https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/configuration-file

and also `max_read_bytes` not mention in document, we set it to 2MB, default is 2KB

here is our config 

```
# The "built-in" kubernetes logs source. Will be added by default, unless
# explicitly disabled.
kubernetesLogsSource:
  # Disable to omit the kubernetes logs source from being added.
  enabled: true
  # The name to use for the "built-in" kubernetes logs source.
  sourceId: kubernetes_logs
  # Raw TOML config to embed at the kubernetes logs source.
  rawConfig: |
    max_read_bytes = 2048000
    glob_minimum_cooldown_ms = 5000
 ```
