### ISSUE TITLE
`prometheus_remote_write` writes metrics with a timestamp of 0 if the metrics source has no timestamp

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#6814]
I'm unsure if this is a bug with the `prometheus_scrape` source or the `prometheus_remote_write` sink, but a user discovered that Grafana Cloud was rejecting their metrics because the timestamp was out-of-bounds: https://discord.com/channels/742820443487993987/746070591097798688/822181386924457984

I ran a test and it seems like, if `prometheus_scrape` scrapes a prometheus exporter that doesn't publish timestamps, piping this into the `prometheus_remote_write` sink results in vector sending the metrics with a unix timestamp of `0`.

To test I used:

* The [`node_exporter`](https://github.com/prometheus/node_exporter) as the source of the metrics
* An example [test server](https://github.com/prometheus/prometheus/tree/main/documentation/examples/remote_storage/example_write_adapter) to receive the `remote_write` messages and log them out

```toml
[sources.localhost]
type = "prometheus_scrape"
endpoints = ["http://localhost:9100/metrics"]
scrape_interval_secs = 2

[sinks.grafana_cloud]
inputs              = ["localhost"]
type                = "prometheus_remote_write"
endpoint            = "http://localhost:1234/receive"
healthcheck.enabled = false
```

Sample output from the test server:

```
node_network_up{device="eth0"}
  1.000000 0
node_network_iface_link_mode{device="lo"}
  0.000000 0
node_network_device_id{device="veth963a53c"}
  0.000000 0
node_softnet_processed_total{cpu="1"}
  3723029.000000 0
node_xfs_read_calls_total{device="nvme0n1p1"}
  31224930.000000 0
node_schedstat_running_seconds_total{cpu="6"}
  13115.416296 0
node_softnet_processed_total{cpu="7"}
  3904592.000000 0
node_network_transmit_fifo_total{device="docker0"}
  0.000000 0
node_scrape_collector_success{collector="zfs"}
  1.000000 0
node_cpu_guest_seconds_total{cpu="6", mode="user"}
  0.000000 0
node_network_carrier_changes_total{device="docker0"}
  118.000000 0
go_memstats_gc_sys_bytes
  3582216.000000 0
go_threads
  13.000000 0
node_network_transmit_fifo_total{device="br-7926c8e16fd6"}
  0.000000 0
node_cpu_seconds_total{cpu="6", mode="steal"}
  1601.590000 0
node_softnet_processed_total{cpu="4"}
  3627108.000000 0
```

We may want to do a quick audit of other handling of metric timestamps as it seems like we've had a few issues with them recently:

* https://github.com/timberio/vector/issues/6725
* https://github.com/timberio/vector/issues/5916
