### ISSUE TITLE
Vector crashes when reloading configs that have a route transform

### ISSUE THREAD

**Issue by steveberryman** [timberio/vector#6821]
### Vector Version

```
vector 0.12.1 (v0.12.1 x86_64-unknown-linux-musl 2021-03-12)
```

### Vector Configuration File

```toml
[sources.journald_input]
  type = "journald"

[transforms.journald_units]
  type = "route"
  inputs = ["journald_input"]
  route.therest = '.systemd.transport != "kernel"'

[sinks.print]
  type = "console"
  inputs = ["journald_units.therest"]
  encoding.codec = "json"
```

### Debug Output

https://gist.github.com/steveberryman/50e454635b8dec1e38906cdbe454450f

### Expected Behavior

When changing a config file, and running vector with `-w` vector should reload the config and continue processing logs

### Actual Behavior

Vector crashes with the trace in the gist above

### Additional Context

I have narrowed this down to I _think_ the route transform. It may happen in other cases but the example above seems to reproduce it pretty consistently. Even adding a bit of whitespace to a config file and saving it will crash vector.
