### ISSUE TITLE
New source: "loki"

### ISSUE THREAD

**Issue by afoninsky** [timberio/vector#6873]
For now, Vector has "loki" sink which is responsible for delivery logs to Loki.
Loki also has functionality to consume live logs so its possible to create a source: https://grafana.com/docs/loki/latest/api/ -> `/loki/api/v1/tail`
Theoretically, it will allow to execute queries with live tailing and create much more flexible processing pipelines.

**Comment by marcbachmann** [comment]
In case somebody wants to work on that, here's some example code how to merge multiple loki streams into one array of logs: https://github.com/livingdocsIO/loki-log-export/blob/3488c019d5f0c2525cdc844e02c3a1a8a7d3e8d2/merge-logs.js#L3-L13

**Comment by joemiller** [comment]
Vector could also implement a `loki source` listening on the `/loki/api/v1/push` API endpoint.  Basically acting like the loki receiver in a typical `promtail -> loki` setup.

One thing that this would allow for is a path to incrementally move from a promtail/loki setup to a full vector pipeline. For example, in a `promtail -> loki` setup one could introduce vector aggregator into this pipeline easily: `promtail -> vector-aggregator -> loki`. Once the aggregator is in place it becomes straightforward to add additional outputs to your log pipeline: gcs, s3, bigquery, etc. Over time promtail should be replaced with vector agent. By introducing vector incrementally it gives the org time to convert their promtail config (filters, relabels, etc) and test safely before swapping promtail for vector agent.

**Comment by kbudde** [comment]
Good morning,

From what I can see there are two interesting use cases here.

(1) Described in this issue (initially), Loki is used as a source to retrieve the data as they are stored. Vector actively reads the data from the system.
Most comparable to the [prometheus_scrape source](https://vector.dev/docs/reference/configuration/sources/prometheus_scrape/) .

Use cases:
- Export of data from Loki for further processing with Vector and/or transport to other systems
- Federation of multiple Loki instances

This was also implemented by @zamazan4ik in #15405. Unfortunately closed.
Behavior when Vector is not running: A gap is created in the downstream systems. The data can be viewed in Loki.

(2) The second [suggestion ](https://github.com/vectordotdev/vector/issues/6873#issuecomment-1240017185) in this issue makes Vector part of the processing chain. The logs are pushed to Vector.
Most comparable to [source prometheus_remote_write](https://vector.dev/docs/reference/configuration/sources/prometheus_remote_write/) where it mimics a receiver endpoint.

Use cases:

- Ingest buffer: As an intermediate instance, Vector can accept and buffer the messages and thus take the load off the target
- Duplicate incoming logs to multiple systems. The feature is missing in the Grafana agent/Promtail/Loki stack
- Normalize the data before ingest. As described, it also makes sense for a step-by-step replacement of Loki.

Behavior when Vector is not running: Logs cannot be sent. Load on the clients to buffer the logs.

In my view, both approaches make sense and something similiar has already been implement for promtheus.
Which makes sense as a [loki is like prometheus, but for logs](https://grafana.com/go/webinar/intro-to-loki-like-prometheus-but-for-logs/).

Overview:
```
Grafana agent
or Promtail ---> Vector (2) ----> Loki <-- (pull)-- Vector(1) --> Sink
```

@jszwedko what is required to bring these improvements to vector?
I can create RFCs for both or create a second issue describing option 2. 
I'm not sure if I can support with implementation (never did something in rust) but maybe preparing the road will unblock motivated people like @zamazan4ik .

**Comment by jszwedko** [comment]
Hi @kbudde !

Just FYI that there is another contributor working on a `websocket` source over here: https://github.com/vectordotdev/vector/pull/17856

That seems likely to go in soon, after which I think a specialized `loki` pull source could be layered on top that pulls logs from Loki via its live tail API.

It additionally also seems sensible to have a `loki` API source that exposes the same API as Loki for clients like `promtail` to push to (your option 2). I think we would be amenable to that too. It seems like it could be a fairly light wrapper around the `http_server` source.

**Comment by bryanyork** [comment]
I would love an integration for Promtail instances to send data to Vector.

**Comment by GreyTeardrop** [comment]
I would love for Vector to have a Loki API source. My use case: there's a tool ([Unpoller](https://unpoller.com/)) that supports sending log events to [Loki only](https://unpoller.com/docs/dependencies/loki). Would be great to use Vector with it instead to be able to forward logs to other systems.

**Comment by labmir** [comment]
We have many docker containers in production that are configured to to stream to loki server.  I want to put Vector instead of loki server so that in followup I can redirect logs to both: elasticsearch(our coders for debugging) and Grafana/Loki (our support engineers).
So yes, +1 for the Loki as source.

**Comment by zamazan4ik** [comment]
@labmir if I understand your use case correctly, you need to use already existing Loki [sink](https://vector.dev/docs/reference/configuration/sinks/loki/).

**Comment by labmir** [comment]
@zamazan4ik Thank you, but I must've not explained it well. The reason we want Loki as source is because our docker daemon is configured to log to Loki and changing log driver for docker requires to restart docker service and rebuild docker compose which is a down time I want to avoid on the production. So we want to stop our Loki server and launch Vector on the same IP:PORT where Loki used to listen and tell Vector to redirect logs to both Loki (launched on a different IP:PORT) and Elastic

**Comment by pgassmann** [comment]
there are two types of loki sources discussed here:
- vector acting as loki server. (for receiving logs from promtail)
- vector reading logs from loki server (tail api).

**vector acting as loki server** would be useful for us for two reasons:
- send logs from promtail to multiple servers (e.g. loki and [victorialogs](https://docs.victoriametrics.com/victorialogs/data-ingestion/vector/))
- use promtail to read docker logs instead of vectors own docker_logs source, to not lose logs #7358

**Comment by LinTechSo** [comment]
Hi, 
same requirement.
any updates?

**Comment by Taverius** [comment]
In the meantime, there's a 2 options that I've identified:

1. Use `grafana/alloy` to convert loki log streams into otlp log streams. Note the OTLP side of this is entirely backed by in-memory buffers, unlike the alloy loki writer that has a disk-based WAL backing it.
  So if you care about not losing data, you have to disable the write queue and buffers, and then if you target vector instance goes down it'll pass the backpressure to your sources, which might react badly.
  So it becomes a 2-stage solution with

    * Alloy instance 1 ingests loki and pushes them via loki to Alloy instance 2. Anything else that outputs loki points to here.
    * Alloy instance 2 is a stateless loki-otlp converter that ingests from instance 1 and outputs to Vector.

2. Use `open-telemetry/opentelemetry-collector-contrib` as a WAL-backed converter from loki to otlp logs. Upside is you do it in one stop. Downside is that multiple of the components you want - loki input, the storage backing to the queue - are marked alpha/beta/unmaintained. Although they're widely used in deployments, make your own evaluations of how much that matters to you.

If I were deploying in prod, I would look into alloy myself - all the code is stable and it has robust built-in clustering features for HA. Its a bit of a bear on memory though, depending on throughput.

If you want to use the otlp-collector route, something like this works:

```yaml
# Refs:
# Loki Receiver: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/lokireceiver/README.md
# Basic Auth Extension: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/extension/basicauthextension/README.md
# File Storage Extension: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/extension/storage/filestorage/README.md
# OTLP gRPC Exporter: https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/otlpexporter/README.md
# OTLP/HTTP Exporter: https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/otlphttpexporter/README.md
# General Exporter: https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/README.md
# Exporter Helper (Queue setup): https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/exporterhelper/README.md
extensions:
  file_storage/vector:
    directory: /storage/bolt
    create_directory: true
    timeout: 1s
    fsync: true
    compaction:
      directory: /storage/tmp
      on_start: true
      on_rebound: true
      rebound_needed_threshold_mib: 1000 # Adjust these and based on your data rate
      rebound_trigger_threshold_mib: 200 # and expected timeout durations
  basicauth/loki:
    htpasswd:
      inline: user:supersecretpassword

receivers:
  loki/proxy:
    protocols:
      http:
        endpoint: "0.0.0.0:3100"
        auth:
          authenticator: basicauth/loki
    use_incoming_timestamp: true

exporters:
  otlphttp/vector:
    logs_endpoint: http://vector:4318/v1/logs
    write_buffer_size: 0
    tls:
      insecure: true
    retry_on_failure:
      enabled: true
      multiplier: 1.2
      max_elapsed_time: 0 # Max time to try resending. 0 means keep trying forever.
    sending_queue:
      enabled: true
      storage: file_storage/vector

service:
  extensions:
    - file_storage/vector
    - basicauth/loki
  telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: 0.0.0.0
                port: 8888
    logs:
      encoding: json
  pipelines:
    logs/proxy:
      receivers: [loki/proxy]
      exporters: [otlphttp/vector]
```

This example is intended to be deployed alongside a vector instance, with a dedicated `opentelemetry` source for it in a secure network, and the loki input open to the public. Adjust auth as needed.
* You can use the `otlp` exporter instead if you'd rather stream via gRPC. For high volumes, this may be advisable.
* The default queue size (1000 batches) is apparently good for about ~4GB of data, adjust as needed.
* The compaction thresholds should be adjusted to your datarate and expected outage for rebound compaction to be effective. Values like `20/5` might be a starting point for homelab. Storage has to go above `needed` and then fall below `trigger` for live compaction to occur.
* If you run this in docker like I am, be aware OTLP-Collector runs as user 10001:10001 by default. Either prepare your storage volume for that or adjust the container's user.
* The BoltDB-based file storage is considered beta but stable and reliable. There's also a Redis storage and a SQLite/Postgres storage, in alpha.

**Comment by rucciva** [comment]
+1

my current workaround for this is to use http server with protobuf decoding. i used [buf](https://buf.build/) to genereate the needed descriptor file

-- buf.yaml
```
version: v2
modules:
  - path: proto/loki
  - path: proto/loki/vendor/github.com/gogo/protobuf
  - path: proto/loki/vendor
    excludes:
      - proto/loki/vendor/github.com/gogo/protobuf
```

-- build.sh
```
#!/bin/bash
set -euo pipefail

# download
curl https://github.com/grafana/loki/archive/f078e0e3f9b650d7d083b548f8be0700003d7032.zip -L -o loki.zip
unzip loki.zip '*.proto' -d loki

# extract
rm -rf proto/loki/
mkdir -p proto/loki/
mv -f loki/*/* proto/loki/

# build
rm -f logproto.binpb
buf build --path ./proto/loki/pkg/logproto -o logproto.binpb

# cleanup
rm -rf loki loki.zip
```

-- vector.yaml
```
sources:
  loki:
    type: http_server
    address: 0.0.0.0:3100
    path: /loki/api/v1/push
    decoding:
      codec: protobuf
      protobuf:
        desc_file: /<path>/<to>/logproto.binpb
        message_type: logproto.PushRequest
    framing:
      method: bytes
```

but the client needs to pass `content-encoding: snappy`, such as the following with alloy

```
loki.write "vector" {
  endpoint {
    url = "http://localhost:3100/loki/api/v1/push"
    headers = {
      "Content-Encoding" = "snappy",
    }
  }
}
```
