### ISSUE TITLE
host_metrics filesystem filtering by device patterns is not working

### ISSUE THREAD

**Issue by mmerickel** [timberio/vector#6920]
### Vector Version

```
vector 0.12.1 (v0.12.1 x86_64-unknown-linux-gnu 2021-03-12)
```

### Vector Configuration File

```toml
[sources.host_metrics_raw]
type = "host_metrics"
collectors = [
    "filesystem",
]
namespace = "Vector/EC2"
scrape_interval_secs = 15

[sources.host_metrics_raw.filesystem.devices]
includes = [
    "/dev/root",
]

[sinks.metrics_out]
type = "console"
inputs = ["host_metrics_raw"]
encoding.codec = "json"
```

### Expected Behavior

Expected to get metrics for only `/dev/root`.

### Actual Behavior

No metrics for any filesystem.

### Additional Context

I've tried several permutations of the includes filtering. By default, vector includes tons and tons of devices that I do not want. I only want the physical block devices.

For example, my desired setting is: `includes = ["/dev/root", "/dev/hd*", "/dev/sd*", "/dev/nvme*", "/dev/xvd*"]` .

When executing vector without any filtering (`includes = ["*"]`) then I get tons of stuff including cgroups, overlay filesystems, tmpfs, shm, etc. This is great but I want to filter it. Notably, one of the records I want shows up below:

```
{"name":"filesystem_free_bytes","namespace":"Vector/EC2","tags":{"collector":"filesystem","device":"/dev/root","filesystem":"ext4","host":"DUMMY_INSTANCE","mountpoint":"/"},"timestamp":"2021-03-29T17:08:53.463635035Z","kind":"absolute","gauge":{"value":126504243200.0}}
```

With an output like `"device":"/dev/root"` I cannot understand why the filter is not working and even at trace level there is no output on what devices match what patterns.

I also tried filtering by filesystem, such as `filesystem.filesystems.includes = ["ext4"]` and this did result in the desired output so it appears specific to the devices filtering.

A couple other things worth noting:

I also tried without the `/dev/` prefix to no avail.

`/dev/root` is not a symlink, and it is apparently what is picked up when running vector on an ubuntu:20.04 AMI on EC2 for the root filesystem by vector, not `/dev/nvme*`. It is the same as the value from `cat /proc/cmdline`.
