### ISSUE TITLE
Elasticsearch sink: Failed to make HTTP(S) request: error trying to connect: the handshake failed

### ISSUE THREAD

**Issue by rawbertp** [timberio/vector#6952]
### Vector Version

```
0.12.2
```

### Vector Configuration File

```toml
    [sinks.es_out]
      # General
      type = "elasticsearch" # required
      inputs = ["temperature_transformer"] # required
      compression = "none" # optional, default
      endpoint = "https://elasticsearch-master:9200" # required
      index = "sensordata-%Y.%m" # optional, default
      #pipeline = "pipeline-name" # optional, no default
      auth.user = "${ELASTICSEARCH_USERNAME}"
      auth.password = "${ELASTICSEARCH_PASSWORD}"
      auth.strategy = "basic"
      tls.crt_file = "/usr/share/certs/elastic-certificates.p12"
      tls.key_file = "/usr/share/certs/elastic-certificates.p12"
      tls.ca_file = "/usr/share/certs/elastic-ca.crt"
      tls.verify_hostname = false
      # Healthcheck
      #healthcheck.enabled = true # optional, default
```

### Error

```
Mar 31 15:46:05.284 ERROR vector::topology::builder: msg="Healthcheck: Failed Reason." error=Failed to make HTTP(S) request: error trying to connect: the handshake failed: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1913:: self signed certificate in certificate chain component_kind="sink" component_type="elasticsearch" component_name="es_out"
```

### Expected Behavior

I have set up ES x-pack security with self-signed certificates. A few days ago this just worked fine. I had to set up the cluster from scratch, using the same approach and certificates. And suddenly it doesn't work anymore?!

### Actual Behavior

The above mentioned error is thrown and communication with ES fails (not only the health check but subsequent calls also).

### Example Data

N/A

### Additional Context

N/A

### References

N/A
