### ISSUE TITLE
Vector should reread AWS_SHARED_CREDENTIALS_FILE on SIGHUP

### ISSUE THREAD

**Issue by mcgfenwick** [timberio/vector#7013]
### Vector Version

```
vector 0.12.1 (v0.12.1 x86_64-unknown-linux-gnu 2021-03-12)
```

### Vector Configuration File

```toml
[sinks.aws_bar_aws_s3]
  type = "aws_s3"
  bucket = "our_bucket"
  compression = "gzip"
  healthcheck = true
  region = "us-west-2"
  batch.max_size = 1049000000
  batch.timeout_secs = 60
  buffer.type = "memory"
  encoding.codec = "ndjson"
  filename_append_uuid = false
  filename_time_format =""
  key_prefix = "bar_foo/%Y/%m/%d/%H/%M/${HOSTNAME}"
  filename_extension = "0.json.gz"
  inputs = ["bar_aws_s3_source"]

Environment="AWS_SHARED_CREDENTIALS_FILE=/etc/vector/creds2"

# cat /etc/vector/creds2
[default]
AWS_SECRET_ACCESS_KEY=ZZZZZZZZZZZZZ
AWS_SESSION_TOKEN=REALLYLONGSESSIONKEYSTRING
AWS_ACCESS_KEY_ID=XXXXXXXXXXXXX
AWS_CREDENTIAL_EXPIRATION=2021-04-04T03:19:21.000Z

```
