### ISSUE TITLE
clickhouse sink incorrectly encodes arrays

### ISSUE THREAD

**Issue by Peter-Sh** [timberio/vector#7048]
### Vector Version

0.12.2
0.13 nightly

### Vector Configuration File
```toml
[sources.stdin]
  type = "stdin"

[transforms.remap]
  type = "remap"
  inputs = ["stdin"]
  source = '''
    .array_field = ["val1", "val2"]
  '''

[sinks.clickhouse]
  inputs = ["remap"]
  type = "clickhouse"
  compression = "none"
  endpoint = "${CLICKHOUSE_URL}"
  table = "tbl"

  encoding.only_fields = ["array_field"]

  auth.user = "user"
  auth.strategy = "basic"
  auth.password = "pass"
```

### Expected Behavior

Running fake http server
```
while true ; do  echo -e "HTTP/1.1 200 OK\n\n $(date)" | nc -l 8877; done
```

Running vector:
```
echo 123 | docker run -e CLICKHOUSE_URL=http://HOST_IP:8877 -i --rm --name vector  -v `pwd`/issue.toml:/etc/vector/vector.toml timberio/vector:nightly-debian
```

Expected request body:
```
{"array_field":["val1", "val2"]}
```

### Actual Behavior

```
{"array_field[0]":"val1","array_field[1]":"val2"}
```

### Why

Using arrays in clickhouse is essential for filling [nested](https://clickhouse.tech/docs/en/sql-reference/data-types/nested-data-structures/nested/) structures.

### Workaround

http sink with ndjson encoding can be used to send data to clickhouse
