### ISSUE TITLE
aws_s3 input doesn't handle files properly

### ISSUE THREAD

**Issue by afoninsky** [timberio/vector#7061]
Seems like s3 doesn't handle big files. I'm trying to send 17M archive with logs generated by AWS ALB:

```sh
# re-emit real logs to test bucket
aws s3 cp s3://mambu-prod-alb-logs-us-east-1/***/sand/AWSLogs/***/elasticloadbalancing/us-east-1/2021/03/15/***_elasticloadbalancing_us-east-1_app.awseb-AWSEB-1MVD8OW91UMOH.a32a5508b8fdaa6b_20210315T2115Z_10.219.6.78_1h057jj9.log.gz test.log.gz
aws s3 cp test.log.gz s3://mambu-staging-alb-logs-us-east-2/`date +%s | sha256sum | base64 | head -c 32`.log.gz

# ensure that logs are in valid format
gunzip test.log.gz
wc -l test.log
272228
```

### Vector Version
```
brew install vector
vector --version
vector 0.12.1 (v0.12.1 x86_64-apple-darwin 2021-03-12)
```

### Vector Configuration File

```yaml
sources:
  logs-us-east-1:
    type: aws_s3
    region: us-east-2
    compression: gzip
    sqs:
      delete_message: true
      queue_url: https://sqs.us-east-2.amazonaws.com/***/alb-logs-us-east-2-sqs-kourier
      visibility_timeout_secs: 30

sinks:
  console:
    type: console
    inputs: ["logs-*"]
    target: stdout
    encoding:
      codec: text
```

### Debug Output
RUST_BACKTRACE=full vector -vvv  -c vector.yaml
https://gist.github.com/afoninsky/f2929e608b8fadbc94792b6426b7dda1

### Expected Behavior
- SQS message is removed from the queue
- all (270k+) log entities are displayed in the console

### Actual Behavior
- SQS message is removed from the queue
- only 2 entities are displayed (see debug output)

### Additional Context
1. was able to repeat such behaviour on local machine and using alpine docker image with the latest version
2. when I gzipped file with 1M repeatable lines (resulting archive size was about 5M) everything was fine -> issue could be connected to the archive size not amount of lines

**Comment by afoninsky** [comment]
Seems like the issue in the way how Vector processes gzipped files - was able to repeat the same with http input:

```sh
# file uploaded from aws using "aws s3 cp ..."
curl -X POST --data-binary @./test.log.gz -H "Content-encoding: gzip" http://localhost:8080
... bug exists, two lines are displayed
# repack it and resend again
gzip -d test.log.gz
gzip test.log
curl -X POST --data-binary @./test.log.gz -H "Content-encoding: gzip" http://localhost:8080
... everything is fine
```

```yaml
sources:
  logs-http:
    type: http
    address: 0.0.0.0:8080
    encoding: text

sinks:
  console:
    type: console
    inputs: ["logs-*"]
    target: stdout
    encoding:
      codec: text
```

Please inform if you can't repeat and need to have bugged archive.
