### ISSUE TITLE
php-fpm metrics source

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#7083]
Requested by user in discord: https://discord.com/channels/742820443487993987/759154784309215252/830879932510371861

php-fpm seems to be able to expose a status page similar to Apache's `mod_status`: https://www.tecmint.com/enable-monitor-php-fpm-status-in-nginx/ . We could add a source component similar to our `apache_metrics` and `nginix_metrics` sources to pull this information.

**Comment by yakimov** [comment]
+++
This is a very useful metric for sites that uses PHP. 
DevOps will be able to control important parameters and will tune them if it's needed. 
I would say it's more important data than data from Nginx or Apache metrics.

**Comment by neilmcguigan** [comment]
for now, you can do the following (creates logs...use log_to_metric to transform to metrics):

```
phpfpm_status:
  type: http_client
  endpoint: "http://127.0.0.1/status?json&full"
  decoding:
    codec: json
```
