### ISSUE TITLE
Normalize metric values and units

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#711]
As noted in https://github.com/timberio/vector/pull/675#issuecomment-518734568, we need to think about normalizing units before aggregating them into Prometheus histogram types.

### Problem

Given this internal metric:

```js
{
  "histogram": {
    "name": "duration_ms",
    "val": 1000.0
  }
}
```

And these default buckets (in seconds):

```rust
[0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0]
```

The above metric would fall into the `10.0` bucket, which is wrong when it should fall into the `1.0` bucket.

### Solutions

1. Do nothing. We could just make it clear in the docs that the default buckets are in seconds and the user should redefine them if their values are not in seconds.
  1. As a follow up to this, we could have a unit converter transform?
2. Defer until a later date. We can wait to see if users complain or ask for this.
3. Add a `unit` concept to our internal histogram data type. This could be optionally specified during metric creation, or derived from the name suffix (ex: `duration_ms` = `milliseconds`).

### Prior Art

- https://hexdocs.pm/prometheus_ex/time.html#content - Notice how they detect time units

**Comment by binarylogic** [comment]
@loony-bean I've assigned this to you. Before we begin work I'd love to hear what you think we should do, if anything.

**Comment by binarylogic** [comment]
@lukesteensen do you mind reviewing this so we can get your take before beginning work?

**Comment by lukesteensen** [comment]
It seems like the immediate problem is that the default bucketing for histograms is the first place where we need to make some assumptions about units. It'd be nice to just pass values through without worrying about units, but I don't see a good way around it in this case. 

The simplest "solution" would probably be to assume that histograms will be aggregated from statsd timers, which seem to have a default unit of milliseconds, and align the default buckets with that. Since a lot of log-derived timing metrics seem to use milliseconds as well (in my experience), this seems like it would be a relatively safe bet.

A slightly more involved solution would be to provide unit-based "preset" bucketings that users could specify as the default for histograms (e.g. `timing_ms` vs `timing_secs`). Since we don't have a way of really knowing what units will be used ahead of time, I think configuration is really the only full solution here.

I'm a little hesitant to start assigning units to metrics in the data model just because there will always be cases where we don't know, which means it'd be hard to rely on for this kind of functionality anyway. I do like the idea of using the name heuristics as a hint, I'm just not sure it's worth it for a partial solution at this point.

**Comment by binarylogic** [comment]
> The simplest "solution" would probably be to assume that histograms will be aggregated from statsd timers, which seem to have a default unit of milliseconds, and align the default buckets with that. Since a lot of log-derived timing metrics seem to use milliseconds as well (in my experience), this seems like it would be a relatively safe bet.

Hm, this is not a bad idea. Do you think it's worth documenting that Vector assumes the `val` field in the `histogram` struct is in milliseconds? Then, later, we could provide levers to convert units at the source or transform level?

Alternatively, #710 can provide defaults based on the metric naming. Ex:

```toml
[sinks.prometheus]
  type = "prometheus"

  # Global default buckets for histograms
  [[sinks.prometheus.metrics]]
    match_type = "histogram"
    buckets = [5.0, 10.0, 25.0, 50.0, 100.0, 250.0, 500.0, 1000.0, 2500.0, 5000.0, 10000.0] # assumes milliseconds

  # Default seconds override
  [[sinks.prometheus.metrics]]
    match_name = ".*_seconds" # regex pattern
    buckets = [0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0] # optional

  # ... potentially other units
```

These would be default/fallback rules, any rules the user provided would take precedence. What do you think?

> A slightly more involved solution would be to provide unit-based "preset" bucketings that users could specify as the default for histograms (e.g. timing_ms vs timing_secs). Since we don't have a way of really knowing what units will be used ahead of time, I think configuration is really the only full solution here.

Is what I described above basically what you're describing here?

> I'm a little hesitant to start assigning units to metrics in the data model just because there will always be cases where we don't know, which means it'd be hard to rely on for this kind of functionality anyway. I do like the idea of using the name heuristics as a hint, I'm just not sure it's worth it for a partial solution at this point.

👍
