### ISSUE TITLE
File source stops gathering events from several log files at once

### ISSUE THREAD

**Issue by hreidar** [timberio/vector#7192]
### Vector Version

```
0.12.2-debian
```

### Vector Configuration File

# ingress1
```toml
## sources
# metrics
[sources.p2-metrics]
  type = "internal_metrics"

# API
[api]
  enabled = true
  address = "0.0.0.0:8681"

[sources.back01-oss]
  include = ["/nfsmount/back01/i-OSS."]
  type = "file"
  data_dir = "/tmp/checkpoints/"
  glob_minimum_cooldown_ms = 600000
  multiline.start_pattern = '(?m)^(\d{4}-\d{2}-\d{2})'
  multiline.mode = "continue_through"
  multiline.condition_pattern = '(?m)^(\()'
  multiline.timeout_ms = 1000

[sources.cnr01-ipv6]
  include = ["/nfsmount/cnr01/ipv6_leased.log"]
  type = "file"
  data_dir = "/tmp/checkpoints/"
  glob_minimum_cooldown_ms = 600000
  multiline.start_pattern = '(?m)^(?:[a-zA-Z0-9]{2}:){8,}[a-zA-Z0-9]{2}'
  multiline.mode = "continue_through"
  multiline.condition_pattern = '(?m)^[[:space:]]'
  multiline.timeout_ms = 1000

[sources.cnr01-ipv4]
  include = ["/nfsmount/cnr01/ip_leased.log"]
  type = "file"
  data_dir = "/tmp/checkpoints/"
  glob_minimum_cooldown_ms = 600000

[sources.cnr02-ipv4]
  include = ["/nfsmount/cnr02/ip_leased.log"]
  type = "file"
  data_dir = "/tmp/checkpoints/"
  glob_minimum_cooldown_ms = 600000

[sources.cnr01-autod]
  include = ["/nfsmount/cnr01-auto/AUTODISCOVERYFE.log"]
  type = "file"
  data_dir = "/tmp/checkpoints/"
  glob_minimum_cooldown_ms = 600000

[sources.cnr02-autod]
  include = ["/nfsmount/cnr02-auto/AUTODISCOVERYFE.log"]
  type = "file"
  data_dir = "/tmp/checkpoints/"
  glob_minimum_cooldown_ms = 600000

## transforms
[transforms.back01-oss-fields]
  type = "add_fields"
  inputs = ["back01-oss"]
  fields.type = "oss"
  fields.origin = "back01"
  fields.harvester = "ingress1"

[transforms.cnr01-ipv6-fields]
  type = "add_fields"
  inputs = ["cnr01-ipv6"]
  fields.type = "ipv6_lease_log"
  fields.origin = "cnr01"
  fields.harvester = "ingress1"

[transforms.cnr01-ipv4-fields]
  type = "add_fields"
  inputs = ["cnr01-ipv4"]
  fields.type = "ipv4_lease_log"
  fields.origin = "cnr01"
  fields.harvester = "ingress1"

[transforms.cnr02-ipv4-fields]
  type = "add_fields"
  inputs = ["cnr02-ipv4"]
  fields.type = "ipv4_lease_log"
  fields.origin = "cnr02"
  fields.harvester = "ingress1"

[transforms.cnr01-autod-fields]
  type = "add_fields"
  inputs = ["cnr01-autod"]
  fields.type = "autoDiscovery_log"
  fields.origin = "cnr01"
  fields.harvester = "ingress1"

[transforms.cnr02-autod-fields]
  type = "add_fields"
  inputs = ["cnr02-autod"]
  fields.type = "autoDiscovery_log"
  fields.origin = "cnr02"
  fields.harvester = "ingress1"

[transforms.cnr01-autod-filter]
  type = "filter"
  inputs = ["cnr01-autod-fields"]
  condition = '!contains!(.message, "Duplicate", case_sensitive: true)'

[transforms.cnr02-autod-filter]
  type = "filter"
  inputs = ["cnr02-autod-fields"]
  condition = '!contains!(.message, "Duplicate", case_sensitive: true)'

## sinks
[sinks.ingress1_to_dedup]
  type = "http"
  inputs = ["back01-oss-fields",
            "cnr01-ipv6-fields",
            "cnr01-ipv4-fields",
            "cnr02-ipv4-fields",
            "cnr01-autod-filter",
            "cnr02-autod-filter"
           ]
  uri = "http://127.0.0.1:9001"
  encoding.codec = "json"
  healthcheck = false
  buffer.type = "disk"
  buffer.max_size = 10490000000
  request.concurrency = "adaptive"

[sinks.p2-to-prometheus]
  type = "prometheus_exporter"
  inputs = ["p2-metrics"]
  address = "0.0.0.0:9501"
  default_namespace = "p2-ingress1"
  buckets = [0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0]
  quantiles = [0.5, 0.75, 0.9, 0.95, 0.99]
```
ingress2
```toml
## sources
# metrics
[sources.p2-metrics]
  type = "internal_metrics"

# API
[api]
  enabled = true
  address = "0.0.0.0:8682"

[sources.back01-oss]
  include = ["/nfsmount/back01/i-OSS."]
  type = "file"
  data_dir = "/tmp/checkpoints/"
  glob_minimum_cooldown_ms = 600000
  multiline.start_pattern = '(?m)^(\d{4}-\d{2}-\d{2})'
  multiline.mode = "continue_through"
  multiline.condition_pattern = '(?m)^(\()'
  multiline.timeout_ms = 1000

[sources.cnr01-ipv6]
  include = ["/nfsmount/cnr01/ipv6_leased.log"]
  type = "file"
  data_dir = "/tmp/checkpoints/"
  glob_minimum_cooldown_ms = 600000
  multiline.start_pattern = '(?m)^(?:[a-zA-Z0-9]{2}:){8,}[a-zA-Z0-9]{2}'
  multiline.mode = "continue_through"
  multiline.condition_pattern = '(?m)^[[:space:]]'
  multiline.timeout_ms = 1000

[sources.cnr01-ipv4]
  include = ["/nfsmount/cnr01/ip_leased.log"]
  type = "file"
  data_dir = "/tmp/checkpoints/"
  glob_minimum_cooldown_ms = 600000

[sources.cnr02-ipv4]
  include = ["/nfsmount/cnr02/ip_leased.log"]
  type = "file"
  data_dir = "/tmp/checkpoints/"
  glob_minimum_cooldown_ms = 600000

[sources.cnr01-autod]
  include = ["/nfsmount/cnr01-auto/AUTODISCOVERYFE.log"]
  type = "file"
  data_dir = "/tmp/checkpoints/"
  glob_minimum_cooldown_ms = 600000

[sources.cnr02-autod]
  include = ["/nfsmount/cnr02-auto/AUTODISCOVERYFE.log"]
  type = "file"
  data_dir = "/tmp/checkpoints/"
  glob_minimum_cooldown_ms = 600000

## transforms
[transforms.back01-oss-fields]
  type = "add_fields"
  inputs = ["back01-oss"]
  fields.type = "oss"
  fields.origin = "back01"
  fields.harvester = "ingress2"

[transforms.cnr01-ipv6-fields]
  type = "add_fields"
  inputs = ["cnr01-ipv6"]
  fields.type = "ipv6_lease_log"
  fields.origin = "cnr01"
  fields.harvester = "ingress2"

[transforms.cnr01-ipv4-fields]
  type = "add_fields"
  inputs = ["cnr01-ipv4"]
  fields.type = "ipv4_lease_log"
  fields.origin = "cnr01"
  fields.harvester = "ingress2"

[transforms.cnr02-ipv4-fields]
  type = "add_fields"
  inputs = ["cnr02-ipv4"]
  fields.type = "ipv4_lease_log"
  fields.origin = "cnr02"
  fields.harvester = "ingress2"

[transforms.cnr01-autod-fields]
  type = "add_fields"
  inputs = ["cnr01-autod"]
  fields.type = "autoDiscovery_log"
  fields.origin = "cnr01"
  fields.harvester = "ingress2"

[transforms.cnr02-autod-fields]
  type = "add_fields"
  inputs = ["cnr02-autod"]
  fields.type = "autoDiscovery_log"
  fields.origin = "cnr02"
  fields.harvester = "ingress2"

[transforms.cnr01-autod-filter]
  type = "filter"
  inputs = ["cnr01-autod-fields"]
  condition = '!contains!(.message, "Duplicate", case_sensitive: true)'

[transforms.cnr02-autod-filter]
  type = "filter"
  inputs = ["cnr02-autod-fields"]
  condition = '!contains!(.message, "Duplicate", case_sensitive: true)'


## sinks
[sinks.ingress2_to_dedup]
  type = "http"
  inputs = ["back01-oss-fields",
            "cnr01-ipv6-fields",
            "cnr01-ipv4-fields",
            "cnr02-ipv4-fields",
            "cnr01-autod-filter",
            "cnr02-autod-filter"
           ]
  uri = "http://127.0.0.1:9002"
  encoding.codec = "json"
  buffer.type = "disk"
  buffer.max_size = 10490000000
  request.concurrency = "adaptive"

[sinks.p2-to-prometheus]
  type = "prometheus_exporter"
  inputs = ["p2-metrics"]
  address = "0.0.0.0:9502"
  default_namespace = "p2-ingress2"
  buckets = [0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0]
  quantiles = [0.5, 0.75, 0.9, 0.95, 0.99]
```

output
```toml
## sources
# metrics
[sources.p2-metrics]
  type = "internal_metrics"

# API
[api]
  enabled = true
  address = "0.0.0.0:8680"

[sources.from_ingress1]
  type = "http"
  address = "127.0.0.1:9001"
  encoding = "json"

[sources.from_ingress2]
  type = "http"
  address = "127.0.0.1:9002"
  encoding = "json"

## transports
[transforms.dedupe_events]
  type = "dedupe"
  inputs = ["from_ingress1","from_ingress2"]
  cache.num_events = 1000
  fields.match = ["message"]

## sinks
[sinks.dedup_to_kafka]
  type = "kafka"
  inputs = ["dedupe_events"]
  bootstrap_servers = "k8s-c4-m1:30656,k8s-c4-m2:30656,k8s-c4-m3:30656"
  topic = "P2_OSS_AND_IP.R"
  encoding.codec = "json"
  librdkafka_options."acks" = "all"
  librdkafka_options."retries" = "10000000"
  librdkafka_options."delivery.timeout.ms" = "2147483647"
  librdkafka_options."max.in.flight.requests.per.connection" = "5"
  #librdkafka_options."enable.idempotence" = "true"
  #librdkafka_options."client.id" = "vector-ingress"

[sinks.p2-to-prometheus]
  type = "prometheus_exporter"
  inputs = ["p2-metrics"]
  address = "0.0.0.0:9500"
  default_namespace = "p2-ingress-output"
  buckets = [0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0]
  quantiles = [0.5, 0.75, 0.9, 0.95, 0.99]
```

### Debug Output

https://gist.github.com/hreidar/16f43e77643bbde4a025acba91bb3819

### Expected Behavior
Events from log files should keep on going through my data pipeline.

### Actual Behavior
Data stops coming from the ingress containers as it seems randomly. Sometimes they keep on going for several minutes/hours some times longer. Restarting the container gets them back on the job.

### Additional Context
This stack is running on the same virtual machine, controlled by one docker-compose stack.

There are two, almost identical, ingress containers posting data to the third one which does deduplication of events before publishing them to Kafka.

This setup was created to prevent the occasional event loss when using only one container doing both the file tailing and data publishing.

In the ingress2 trace log you can see the last data transfer to the output/dedup container at 14:13:38.

This is happening several times a day.  There are some settings in the provided configuration that I have been tweaking to try to figure out a way to stop this problem like buffer.max_size and glob_minimum_cooldown_ms. These settings were at their default values when I started seeing this problem.
