### ISSUE TITLE
Same kube config file working fine for kubectl but vector gets certificate issue error

### ISSUE THREAD

**Issue by shuza** [timberio/vector#7193]
### Vector Version

```
vector 0.12.2 (v0.12.2 x86_64-apple-darwin 2021-03-30)
```

### Vector Configuration File

```toml
data_dir = "/var/lib/vector"

[sources.my_source_id]
  type = "kubernetes_logs"
  auto_partial_merge = true
  extra_label_selector = "app=api"
  self_node_name = "docker-desktop"
  kube_config_file = "KUBE_CONFIG_FILE_PATH"

[sinks.print]
  type = "console"
  inputs = ["my_source_id"]
  encoding.codec = "json"

[api]
  enabled = true
  address = "127.0.0.1:8686"
```

### Debug Output

Debug output at [here](https://gist.github.com/shuza/92329191d735a5996436ff14ea8f5d14)

### Expected Behavior

As the kube config file is working fine for kubectl. So according to `vector.toml` it should print pods stdout logs in vector stdout console.
### Actual Behavior

vector can't access kubernetes logs. It was unable to get local issuer certificate which turn into certificate verify failed error.
