### ISSUE TITLE
bug - dropping data with http sink in .13.0

### ISSUE THREAD

**Issue by ryn9** [timberio/vector#7219]
### Vector Version

```
vector 0.13.0 (v0.13.0 x86_64-unknown-linux-gnu 2021-04-21)
```

#previous version was 0.12.2 and worked fine

### Vector Configuration File

#sanitized sink config

```
sinks:
  out:
    type: http
    inputs:
      - filter_out
    compression: gzip
    uri: http://1.1.1.1:8080/
    encoding:
      codec: ndjson
      timestamp_format: rfc3339
    buffer:
      type: memory
      when_full: block
    request:
      concurrency: 1
```

### Debug Output

N/A

### Expected Behavior

All data should make it to the data sink endpoint

### Actual Behavior

Consistently dropping the same data to the endpoint.
In our test data - consistently getting only 210043 of 1598789 records to the target - 87% data loss.

### Example Data

N/A

### Additional Context

As I have seen issues with buffers before - I tried testing with different memory and disk buffers

### References

N/A
