### ISSUE TITLE
VRL `strip_ansi_escape_codes` does not appear to actually strip the codes

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#7239]
Reported by user in discord: https://discord.com/channels/742820443487993987/746070591097798688/835256781122961442

Example config:

```toml
[sources.in]
type = "stdin"

[transforms.parse_logs]
type = "remap"
inputs = ["in"]
source = '''
strip_ansi_escape_codes!(.message)
'''

[sinks.print]
type = "console"
inputs = ["parse_logs"]
encoding.codec = "json"
```

Running:

```
cho "2021-04-23 06:32:21.115 \u001b[32mDEBUG\u001b[m \u001b[35m1\u001b[m [           main] \u001b[36ml.l.c.Slf4jLogger                       \u001b[m : Searching for: is assignable to Pok in package: uibase/logging" | vector --config /tmp/vector.toml
```

I see:

```json
{"host":"COMP-C02DV25MML87","message":"2021-04-23 06:32:21.115 \u001b[32mDEBUG\u001b[m \u001b[35m1\u001b[m [           main] \u001b[36ml.l.c.Slf4jLogger                       \u001b[m : Searching for: is assignable to Pok in package: uibase/logging","source_type":"stdin","timestamp":"2021-04-23T21:07:24.946411Z"}
```

Whereas the deprecated `ansi_stripper` transform does seem to work:

```toml
[sources.in]
type = "stdin"

[transforms.parse_logs]
  type = "ansi_stripper" # required
  inputs = ["in"] # required
  field = "message" # optional, default

[sinks.print]
type = "console"
inputs = ["parse_logs"]
encoding.codec = "json"
```

Outputs:

```json
{"host":"COMP-C02DV25MML87","message":"2021-04-23 06:32:21.115 DEBUG 1 [           main] l.l.c.Slf4jLogger                        : Searching for: is assignable to Pok in package: uibase/logging","source_type":"stdin","timestamp":"2021-04-23T21:09:47.750790Z"}
```
