### ISSUE TITLE
VRL `strip_ansi_escape_codes` does not work if a following regex fails parsing `.message`

### ISSUE THREAD

**Issue by TomGudman** [timberio/vector#7255]
`parse_regex` after stripping the ansi codes will either return successfully the parsed message or the `.message` **prior** the ansi code stripping.

### Vector Version
```
vector 0.13.0 (v0.13.0 x86_64-unknown-linux-gnu 2021-04-21)  (Ubuntu 20.04)
```

### Vector Configuration File
```toml
[sources.in]
type = "stdin"

[transforms.parse_logs]
type = "remap"
inputs = ["in"]
source = '''
.message = strip_ansi_escape_codes!(.message)
# This regexp WORKS (be sure to comment the following parse_regex)
. |= parse_regex!(.message, r'^(?P<timestamp>\d+-\d+-\d+ \d+:\d+:\d+.\d+)\s+(?P<severity>\w+)\s+(?P<pid>\d+)\s+\[\s*(?P<thread>\w+)\]\s+(?P<class>[\w\.]+)\s*:\s*(?P<message>.*)$')
# This regexp does NOT work (be sure to comment the above regex)
#. |= parse_regex!(.message, r'^(?P<timestamp>\d+-\d+-\d+ \d+:\d+:\d+.\d+)  (?P<severity>\w+)\s+(?P<pid>\d+)\s+\[\s*(?P<thread>\w+)\]\s+(?P<class>[\w\.]+)\s*:\s*(?P<message>.*)$')
'''

[sinks.print]
type = "console"
inputs = ["parse_logs"]
encoding.codec = "json"
```

### Expected Behavior
If the regexp fails then the full `.message` should be returned WITHOUT the ansi codes.

### Actual Behavior
The original` .message` is returned with all the ANSI codes

### Example Data
Run with `cat mockmini | vector --config=mockdemo.toml`  See [example.zip](https://github.com/timberio/vector/files/6382457/example.zip) for data sample and configuration. Run once with the working regexp and then run it with the non working regexp you will see the ANSI codes coming back.

### References

The original discussion about this issue started on discourse and an attempt to report this issue was #7239
