### ISSUE TITLE
`kafka` source has runaway memory usage 

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#7258]
Regression in 0.13.0 noted by a couple of discord users:

* https://discord.com/channels/742820443487993987/746070591097798688/836678143594070046
* https://discord.com/channels/742820443487993987/746070591097798688/836588506641596446

I'm able to reproduce and am `git bisect`ing now. The behavior is that it very rapidly consumes memory (GBs per minute).

Reproduction config:

```toml
log_schema.timestamp_key = "@timestamp"

#[api]
  #enabled = true

#[sinks.monitoring_exporter]

  #type = "prometheus_exporter"
  #inputs = ["internal_metrics_app"]
  #address = "0.0.0.0:9598"

#[sources.internal_metrics_app]
  #type = "internal_metrics"

#[sources.kafka_source]
  #type = "stdin"

[sources.kafka_source]
  type = "kafka"
  bootstrap_servers = "127.0.0.1:9092"
  group_id = "ch-test-10-consumer-group"
  topics = ["new_topic"]
  auto_offset_reset = "beginning"

[transforms.copy_original_message]
  type = "remap"
  inputs = ["kafka_source"]
  source = '''
  .original_message, err = to_string(.message)
  '''

[transforms.json_parser_app]
  type = "json_parser"
  inputs = ["copy_original_message"]
  drop_field = true
  drop_invalid = true
  field = "message"

[transforms.to_downcase_app]
  type = "remap"
  inputs = ["json_parser_app"]
  source = '''
  .component_type, err = downcase(.component_type)
  .log_type, err = downcase(.log_type)
  '''

[transforms.regex_component]
  type = "regex_parser"
  inputs = ["to_downcase_app"]
  drop_failed = true
  drop_field = false
  field = "component_type"
  patterns = ['^[\w]{3,}$']

[transforms.regex_log_type]
  type = "regex_parser"
  inputs = ["regex_component"]
  drop_failed = true
  drop_field = false
  field = "log_type"
  patterns = ['^[\w]{3,}$']

[transforms.clickhouse_event_preparation]
  type = "remap"
  inputs = ["regex_log_type"]
  source = '''
  .timestamp = format_timestamp!(now(), format: "%s")
  .timestamp_unix = format_timestamp!(now(), format: "%s")
  .log_source = .type
  if (!exists(.log_level)){
    if (exists(.level)){
      .log_level = .level
    } else {
      .log_level = "undefined"
    }
  }
  del(.tags)
  del(.headers)
  flatten(.)
  '''

#[sinks.output_clickhouse]
  #inputs = ["clickhouse_event_preparation"]
  #type = "blackhole"
  #encoding.codec = "json"

[sinks.output_clickhouse]
  inputs = ["clickhouse_event_preparation"]
  type = "clickhouse"
  compression = "gzip"
  database = "elk_logs"
  endpoint = "http://localhost:8123" # required
  table = "unified_logs"

  batch.max_bytes = 1049000
  batch.timeout_secs = 5

  #buffer.max_events = 5000000 # optional, default, events, relevant when type = "memory"
  #buffer.max_size = 104900000000 # required, bytes, required when type = "disk"
  #buffer.type = "memory"
  #buffer.when_full = "block"

  encoding.only_fields = ["timestamp", "timestamp_unix", "component_type", "log_type", "log_level", "log_source", "original_message"]
  encoding.timestamp_format = "rfc3339" # optional, default | "unix" as an alternative

  healthcheck.enabled = true
```

I'm running Kafka and Clickhouse locally. I tried to narrow down the reproduction config but found that swapping `clickhouse` for `blackhole` or `kafka` for `stdin` caused the issue to not manifest so I just left most components for now. I'm assuming the `git bisect` will make the issue more clear. If it doesn't, I'll try to trim down the config more.

Producing messages to kafka:

```
yes '{"app_name":"qwoidqw-qwoqwpo-qskdmq","component_type":"XXX","duration_ms":7,"env_name":"QWPOE-QWLQW-11","env_unit":"12","host":"127.0.0.1","hostname":"localhost.ringcentral.com","level":"DEBUG","level_value":10000,"location":"DWNJF","log_format":"json","log_type":"main","logger_name":"ldfdl.woeim.1oi2eowqmi.qweqe","marathonappid":"eqmwpewqqep-12378kmd-ubdwijnkdklwed1","message":"RESULT kdlmqkldkl.qwie12oe.12qwe(qlwekmqwkle=weiodwdweokl) => {\"qwlekwqqwelwqepo\":0,\"qweqpwep123\":0,\"qwleqweop12\":0,\"qowieunqjwkmlemqw\":0,\"qweojiqweop\":0,\"ehio12newnklq\":0} took 7 ms.","request_id":"qweinqklweqlek12839ioqklmeqwoihnklmds","request_token":"910uj2eopwqd;l:oiwejoqwje12309joid","source_type":"socket","thread_name":"14685 - GET /qoiwe/jqwieoejwqi1/v1.0/account/asdlaskdskm1/mlqwlq","timestamp":"2020-06-02T09:51:14.217+00:00","version":"1"}' | ./kafkacat -b localhost:9092 -t new_topic -P
```

Creating Clickhouse resources:

```
create database elk_logs;
create table elk_logs.unified_logs(timestamp DateTime, timestamp_unix UInt64, component_type String, log_type String, log_level String, log_source String, original_message String) ENGINE = Log;
```

**Comment by jszwedko** [comment]
Good news: I narrowed it down. Bad news: it's the tokio 1.0 upgrade commit: 45da52c2c658893ba28044a807ecbaee1884d918 😢 I'll see if anything jumps out there.

**Comment by jszwedko** [comment]
I haven't tracked this down yet, but have a smaller reproducible case:

```toml
[sources.kafka]
  type = "kafka"
  bootstrap_servers = "127.0.0.1:9092"
  group_id = "ch-test-41-consumer-group" # increment to start topic from beginning
  topics = ["new_topic"]
  auto_offset_reset = "beginning"

# growth only _seems_ to occur when transform is introduced
[transforms.json_parser]
  type = "json_parser"
  inputs = ["kafka"]
  drop_field = true
  drop_invalid = true
  field = "message"

[sinks.blackhole]
  inputs = ["json_parser"]
  type = "blackhole"
```

To populate Kafka:

I used this docker-compose.yml to start it:

```yml
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/jesse/kafka:/var/lib/kafka/data
```

I ended up not using that `test` topic, but instead creating a new one (`new_topic`) when publishing via:

```
yes '{"app_name":"qwoidqw-qwoqwpo-qskdmq","component_type":"XXX","duration_ms":7,"env_name":"QWPOE-QWLQW-11","env_unit":"12","host":"127.0.0.1","hostname":"localhost.ringcentral.com","level":"DEBUG","level_value":10000,"location":"DWNJF","log_format":"json","log_type":"main","logger_name":"ldfdl.woeim.1oi2eowqmi.qweqe","marathonappid":"eqmwpewqqep-12378kmd-ubdwijnkdklwed1","message":"RESULT kdlmqkldkl.qwie12oe.12qwe(qlwekmqwkle=weiodwdweokl) => {\"qwlekwqqwelwqepo\":0,\"qweqpwep123\":0,\"qwleqweop12\":0,\"qowieunqjwkmlemqw\":0,\"qweojiqweop\":0,\"ehio12newnklq\":0} took 7 ms.","request_id":"qweinqklweqlek12839ioqklmeqwoihnklmds","request_token":"910uj2eopwqd;l:oiwejoqwje12309joid","source_type":"socket","thread_name":"14685 - GET /qoiwe/jqwieoejwqi1/v1.0/account/asdlaskdskm1/mlqwlq","timestamp":"2020-06-02T09:51:14.217+00:00","version":"1"}' | kafkacat -b localhost:9092 -t new_topic -P
```

Kafkacat: https://github.com/edenhill/kafkacat

I let that run a few minutes to populate ~10-20 GB of messages in the topic.

I then built vector at commit 45da52c:

```
cargo build --release --no-default-features --features 'sources-kafka,transforms-json_parser,sinks-blackhole'
```

Letting this run, I opened `htop`. The memory use quickly starts to grow multiple gigabytes a minute.

Other notes:

* Replacing `kafka` source with `stdin` does not show the same issue
* massif seems to indicate we are stacking up a bunch of futures and events (linearly over time) (ran with `valgrind --tool=massif` after enabling debug symbols for release build). Note with massif I saw the memory not runaway, but just grow to a certain point (roughly 3 GB).

[massif.out.10746.gz](https://github.com/timberio/vector/files/6388114/massif.out.10746.gz)
![Screenshot from 2021-04-27 14-32-41](https://user-images.githubusercontent.com/316880/116322807-cd806000-a78a-11eb-9ed4-4bcac35d3392.png)
