### ISSUE TITLE
http input doesn't work for dotnet clients with gzip

### ISSUE THREAD

**Issue by AntonSmolkov** [timberio/vector#7375]
### Vector Version

```
v0.13.1
```

### Vector Configuration File

```toml
[sources.http_source]
  type = "http"
  address = "0.0.0.0:8041"
  encoding = "json"

[sinks.out]
  inputs = ["http_source"]
  type = "console"
  encoding.codec = "json"
```

### Debug Output

> Failed decompressing payload. encoding=gzip error=corrupt deflate stream internal_log_rate_secs=10

https://gist.github.com/AntonSmolkov/a7ff872080ecba0860b8d124f6e7d97e

### Expected Behavior
Vector accepts gzip-compressed http messages from dotnet applications

### Actual Behavior
It does not. Only works with uncompressed messages

### Example Data
Sample dotnet gzip http post app: https://gist.github.com/AntonSmolkov/76d22bedc40a3741060fcbf7f5b94ee7
Works fine with Logstash http input, does not work with vector. Also request content is shown fine in Fiddler.

### Additional Context

At the same time vector accepts gzip-compressed http posts from [Python Requests](https://gist.github.com/AntonSmolkov/110fe7ae6b3ed337842a5be1a79db0c8)  And [Curl](https://gist.github.com/AntonSmolkov/73c02ac5f2c9336607758b0ea4a0ccb4) with no errors.

**Summary:**
dotnet => vector http input ✅ 
dotnet => vector http input Gzip ❌

dotnet => logstash http input ✅ 
dotnet => logstash http input Gzip ✅ 

python => vector http input Gzip ✅
curl => vector http input Gzip ✅
