### ISSUE TITLE
`aws_s3` source does not pick up files with specials characters in the key name

### ISSUE THREAD

**Issue by samdphillips** [timberio/vector#7437]
### Vector Version

```
vector 0.13.1 (v0.13.1 x86_64-unknown-linux-gnu 2021-04-29)
```

### Vector Configuration File

```toml

data_dir = "/tmp/vector_data"

[sources.s3_input]
  type = "aws_s3"
  region = "us-west-2"

  sqs.delete_message = false
  sqs.queue_url = "https://sqs.us-west-2.amazonaws.com/<my-account-number>/<my-queue-name>"

[sinks.stdout]
  type = "console"
  inputs = ["s3_input"]
  encoding.codec = "json"
```

### Expected Behavior

The S3 source should decode the url encoded location from the SQS and load the data.

### Actual Behavior

Vector doesn't load the data and I get a `WARN`.  In this case the file it should be reading has the bucket+key `s3://s3-bucket-name/job/subjob/2021-05-12T19:26:00+00:00/1.log`.
```
May 12 20:41:01.351  WARN source{component_kind="source" component_name=input_s3 component_type=aws_s3}: vector::internal_events::aws_s3::source: Failed to process SQS. self.message_id=3c03881b-b8d8-4afc-94c9-d848633468ff self.error=Failed to fetch s3://s3-bucket-name/job/subjob/2021-05-12T19%3A26%3A00%2B00%3A00/1.log: The specified key does not exist.
```

According to [AWS](https://docs.aws.amazon.com/AmazonS3/latest/userguide/notification-content-structure.html):
> The s3 key provides information about the bucket and object involved in the event. The object key name value is URL encoded.
