### ISSUE TITLE
How can I get all the `internal_metrics` metrics

### ISSUE THREAD

**Issue by ADiiana** [timberio/vector#7441]
I'm a newbie and I'm using `internal_metrics` to collect vector metrics, but I can only see some metrics.
Would like to have more metrics to monitor the operation of the vector.

### Vector Version

```
vector 0.13.0
```

### Vector Configuration File

```toml
data_dir = "."
[sources.metrics]
type="internal_metrics"

[sinks.prometheus]
type = "prometheus_exporter" # required
inputs = ["metrics"] # required
address = "0.0.0.0:8889" # required
```

### Expected Behavior

For example, when the source is kafka, I can't get the `consumer_offset_updates_failed_total`, `events_failed_total metrics`.
I can only get the `events_in_total`, `processed_bytes_total`, `events_out_total`, `processed_events_total metrics`.

For example, when sink is http, I can't get `events_discarded_total`, `http_bad_requests_total` metrics, but only `processed_bytes_total`, `events_in_total`, `processed_events_total`, `events_out_total` metrics.

I would like some error metrics, which are more useful for me.

### References

https://vector.dev/docs/reference/configuration/sinks/http/#telemetry
