### ISSUE TITLE
Helm TOML conversion coverts int to float

### ISSUE THREAD

**Issue by trexx** [timberio/vector#7453]
### Vector Version

```
0.13.1
```

### Helm Values File

```yaml
  sinks:
    elasticsearch:
      batch:
        max_events: 3000
```

### Debug Output

```
ERROR vector::cli: Configuration error. error=invalid type: floating point `3000`, expected usize for key `sinks.elasticsearch` at line 61 column 3
ERROR vector: Failed to load config files, reload aborted.
```

### Expected Behavior

```toml
      [sinks.elasticsearch.batch]
        max_events = 3000
```

### Actual Behavior

```toml
      [sinks.elasticsearch.batch]
        max_events = 3000.0
```

### Additional Context

Helm version: v3.5.4

Installing Vector via helm, when attempting to set batch.max_events, the value gets converted to a float as the TOML configuration gets rendered.

It seems I can't mix and match rawConfig with other settings defined as yaml since the key is duplicated. So the whole sink needs to be writen under rawConfig.

### References

None that I can see
