### ISSUE TITLE
the link of regex troubleshooting hint doesn't work correctly

### ISSUE THREAD

**Issue by moznion** [timberio/vector#7481]
Hello team,

### Vector Version

```
$ vector --version
vector 0.13.1 (v0.13.1 x86_64-unknown-linux-gnu 2021-04-29)
```

### Vector Configuration File

```toml
[sources.foo_source]
  type = "file"
  ignore_older_secs = 600
  include = ["/var/log/foo.log"]
  read_from = "beginning"

[transforms.foo_regex]
  type = "remap"
  inputs = ["foo_source"]

  source = '''
  . = parse_regex!(.message, r'[0-9\/]')
  '''

[sinks.foo_out]
  inputs = ["foo_regex"]
  type = "console"
  encoding.codec = "json"
```

### Debug Output

```
error[E101]: invalid regular expression
  ┌─ :1:30
  │
1 │   . = parse_regex!(.message, r'[0-9\/]')
  │                              ^^^^^^^^^^ regex parse error: unrecognized escape sequence: ^^: [0-9\/]
  │
  = see documentation about regular expressions at https://vrl.dev/expressions/#regular-expression
  = learn more about error code 101 at https://errors.vrl.dev/101
  = see language documentation at https://vrl.dev
```

### Expected Behavior

https://vrl.dev/expressions/#regular-expression

The above link returns an error with the 522 status code. Does the redirector have something complications?

### Actual Behavior

I've expected it should redirect to the legit location (e.g. https://vector.dev/docs/reference/vrl/expressions/#regular-expression)
