### ISSUE TITLE
Since 0.13.0, Docker source with Loki sink is not applying labels correctly

### ISSUE THREAD

**Issue by hhromic** [timberio/vector#7543]
### Vector Version

```
May 21 15:51:40.101  INFO vector: Vector has started. version="0.13.1" git_version="v0.13.1" released="Thu, 29 Apr 2021 14:26:57 +0000" arch="x86_64"
```

First BROKEN version:
```
0.13.0
```

Last WORKING version:
```
0.12.2
```

### Vector Configuration File

```yaml
sources:
  docker:
    type: docker
    include_labels:
      - logging

sinks:
  loki:
    type: loki
    inputs:
      - docker
    endpoint: http://loki:3100

    encoding:
      codec: json

    labels:
      node_id: '{{ label.com.docker.swarm.node.id }}'
      stack_namespace: '{{ label.com.docker.stack.namespace }}'
      service_name: '{{ label.com.docker.swarm.service.name }}'

    remove_label_fields: true

```

### Expected Behavior

Until Vector `0.12.2`, querying Loki gives the expected labels:
```
$ curl -s http://localhost:3100/loki/api/v1/labels | jq
{
  "status": "success",
  "data": [
    "__name__",
    "node_id",
    "service_name",
    "stack_namespace"
  ]
}
```

### Actual Behavior

Since Vector `0.13.0`, querying Loki gives no labels except for the default `agent` one:
```
$ curl -s http://localhost:3100/loki/api/v1/labels | jq
{
  "status": "success",
  "data": [
    "__name__",
    "agent"
  ]
}
```

Here is an example event in Loki, it can be seen that the label fields are also not dropped as expected:
```
$ curl -s 'http://localhost:3100/loki/api/v1/query_range?limit=1&query=%7Bagent%3D%22vector%22%7D' | jq -r '.data.result[].values[][1]' | jq
{
  "container_created_at": "2021-05-21T15:09:55.301486700Z",
  "container_id": "9ef4b5cf9a59892e1c4c62e74882eccd00203d74c9a5a4c92cefee8a3230bd45",
  "container_name": "test_dummy.1.pg6s22287dp6731rtq0614u1r",
  "host": "7b3e85e5b8bc",
  "image": "alpine:latest@sha256:69e70a79f2d41ab5d637de98c1e0b055206ba40a8145e7bddb55ccc04e13cf8f",
  "label.com.docker.stack.namespace": "test",
  "label.com.docker.swarm.node.id": "is1q916pjfsu91mg5fqtkjfr9",
  "label.com.docker.swarm.service.id": "eumo6cn87ernc5nwqym51bonh",
  "label.com.docker.swarm.service.name": "test_dummy",
  "label.com.docker.swarm.task": "",
  "label.com.docker.swarm.task.id": "pg6s22287dp6731rtq0614u1r",
  "label.com.docker.swarm.task.name": "test_dummy.1.pg6s22287dp6731rtq0614u1r",
  "label.com.hpe.gcs.logging": "true",
  "message": "Random 10713",
  "source_type": "docker",
  "stream": "stdout",
}
```

### Example Data

I made the following Docker Swarm stack files for testing:

**Stack file: `test.yaml`**
```yaml
version: '3.8'

services:
  dummy:
    image: alpine:latest
    command: sh -c 'while true; do echo Random $$RANDOM; sleep 1; done'
    labels:
      logging: 'true'    
```

**Stack file: `logging.yaml`**
```yaml
version: '3.8'

services:
  loki:
    image: grafana/loki:2.2.1
    ports:
      - 3100:3100
    volumes:
      - loki_data:/loki
    deploy:
      mode: replicated
      replicas: 1
  vector:
    image: timberio/vector:0.13.1-alpine
    command: -c /etc/vector/vector.yaml
    configs:
      - source: vector.yaml
        target: /etc/vector/vector.yaml
    volumes:
      - vector_data:/var/lib/vector
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global

configs:
  vector.yaml:
    external: true
    name: vector-yml

volumes:
  loki_data:
  vector_data:
```

**Comment by jszwedko** [comment]
Hi @hhromic . I think you are hitting behavior that changed in 0.13.0. Prior to that, labels with a `.` in them coming from `docker_logs` were incorrectly inserted as nested objects in the event. This changed with #7152 to ensure that labels are added as-is as inserting them nested was causing issues with labels being dropped (https://github.com/timberio/vector/issues/5716).

I think what you want to do is escape the label name like: `label.com\.docker\.stack\.namespace`

**Comment by hhromic** [comment]
Oh, really? I was thinking it could be behaviour changing and I scouted all the relevant release notes, mostly for the keyword `Loki`. Didn't think it could be something from the Docker source. I'll test your suggestion right now!

**Comment by hhromic** [comment]
That worked!  Thank you so much!  Probably this should be documented better somewhere then.

I also noticed that the `only_fields` configuration in the sink's `encoding` configuration is not working properly.

Take this example:
```yaml
    encoding:
      codec: json
      only_fields:
        - label.com.docker.swarm.node.id
        - label.com.docker.stack.namespace
        - label.com.docker.swarm.service.name
        - message
        - stream
```

The event sent to Loki contains:

```json
{
  "label.com.docker.swarm.service.id": "jqobtvbo1bw2ch55yn5po7h1s",
  "label.com.docker.swarm.task": "",
  "label.com.docker.swarm.task.id": "4co594t2mr5s2etl415po2ud4",
  "label.com.docker.swarm.task.name": "grafana_grafana.1.4co594t2mr5s2etl415po2ud4",
  "label.logging": "true",
  "message": "t=2021-05-21T16:39:24+0000 lvl=info msg=\"Request Completed\" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=10.0.0.4 time_ms=0 size=29 referer=",
  "stream": "stdout",
}
```

Which is all the labels from the Docker source minus the labels processed and dropped by `remove_label_fields: true`.

I tried escaping the dots too there but same effect still happens.
Thank you in advance for the great help you and your team provide.

**Comment by hhromic** [comment]
I am doing more debugging now. Using the `console` sink has the same problem:

```yaml
sources:
  docker:
    type: docker
    include_labels:
      - logging

sinks:
  console:
    type: console
    inputs:
      - docker
    encoding:
      codec: json
      only_fields:
        - message
        - stream
```

Which yields these JSON messages:
```json
{
  "label": {
    "com.docker.stack.namespace": "test",
    "com.docker.swarm.node.id": "is1q916pjfsu91mg5fqtkjfr9",
    "com.docker.swarm.service.id": "kxikjh60yjr5ausn5nlhv42ar",
    "com.docker.swarm.service.name": "test_dummy",
    "com.docker.swarm.task": "",
    "com.docker.swarm.task.id": "6c7oiz35ocgf4w0smuf8n0tc3",
    "com.docker.swarm.task.name": "test_dummy.1.6c7oiz35ocgf4w0smuf8n0tc3"
  },
  "message": "Random 19832",
  "stream": "stdout"
}
```

Looks like `encoding.only_fields` is not filtering out the `label` field/object. Maybe in general?
