### ISSUE TITLE
Kubernetes tests should clean up their data directories when they finish

### ISSUE THREAD

**Issue by StephenWakely** [timberio/vector#7544]
The tests should clean up their data directories when they finish. Currently they don't and this could cause issues if we are intending on testing on a long running cluster.

@spencergilbert has provided this yaml that should do the trick:

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: data-dir-cleaner
spec:
  selector:
    matchLabels:
      name: data-dir-cleaner
  template:
    metadata:
      labels:
        name: data-dir-cleaner
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
        - name: cleaner
          image: alpine:latest
          command: ["rm"]
          args: ["-rf", "/var/lib/vector/*"]
          volumeMounts:
            - name: data-dir
              mountPath: /var/lib/vector
      volumes:
        - name: data-dir
          hostPath:
            path: /var/lib/vector
```
