### ISSUE TITLE
The `only_fields` option in `encoding` is ignoring `label` field from Docker source

### ISSUE THREAD

**Issue by hhromic** [timberio/vector#7546]
This is a follow-up from https://github.com/timberio/vector/issues/7543#issuecomment-846145894

Consider the following Vector configuration:

```yaml
sources:
  docker:
    type: docker

sinks:
  console:
    type: console
    inputs:
      - docker
    encoding:
      codec: json
      only_fields:
        - message
        - stream
```

Which yields the following JSON messages to the console:
```json
{
  "label": {
    "com.docker.stack.namespace": "test",
    "com.docker.swarm.node.id": "is1q916pjfsu91mg5fqtkjfr9",
    "com.docker.swarm.service.id": "kxikjh60yjr5ausn5nlhv42ar",
    "com.docker.swarm.service.name": "test_dummy",
    "com.docker.swarm.task": "",
    "com.docker.swarm.task.id": "6c7oiz35ocgf4w0smuf8n0tc3",
    "com.docker.swarm.task.name": "test_dummy.1.6c7oiz35ocgf4w0smuf8n0tc3"
  },
  "message": "Random 19832",
  "stream": "stdout"
}
```

Note how `encoding.only_fields` is not filtering out the `label` field/object.

The complementary option `encoding.except_fields` is working as expected:
```yaml
sources:
  docker:
    type: docker

sinks:
  console:
    type: console
    inputs:
      - docker
    encoding:
      codec: json
      except_fields:
        - label
```
```json
{
  "container_created_at": "2021-05-21T17:49:48.308759300Z",
  "container_id": "673fcda6c76965a495698264d884870f5ffcc1c3d462634a5b972d90921599c6",
  "container_name": "test_dummy.1.6c7oiz35ocgf4w0smuf8n0tc3",
  "host": "BIDGZJYP3N",
  "image": "alpine:latest@sha256:69e70a79f2d41ab5d637de98c1e0b055206ba40a8145e7bddb55ccc04e13cf8f",
  "message": "Random 28238",
  "source_type": "docker",
  "stream": "stdout",
  "timestamp": "2021-05-21T18:15:13.158351900Z"
}
```

Lastly, combining `except_fields` with `only_fields` gives the expected result in the original configuration:
```yaml
sources:
  docker:
    type: docker

sinks:
  console:
    type: console
    inputs:
      - docker
    encoding:
      codec: json
      except_fields:
        - label
      only_fields:
        - message
        - stream
```
```json
{
  "message": "Random 2892",
  "stream": "stdout"
}
```
