### ISSUE TITLE
Ability to change the default templating syntax

### ISSUE THREAD

**Issue by atibdialpad** [timberio/vector#7586]
It should be possible to change vector template variables to use something other than curly brackets {{ var }}. For example, in jinja2 we can do something like `#jinja2: variable_start_string: '[%', variable_end_string: '%]'` .Something in global config to change the default behaviour probably. Would help in cases  for example  when ansible is used to copy vector configs and ansible tries to resolve {{ foo }} but this was not a ansible variable, rather it was supposed to be a vector variable. 

JFYI:
@jszwedko

**Comment by Jerrimikkihvatai** [comment]
Whoever stucked on configuring vector via ansible, I solved this issue via this stuff:
```yaml
...
transforms:
    throttle_journald:
      type: throttle
      inputs:
        - src_kernel
        - src_units
      key_field: "{{ '{{ \"{{ SYSLOG_IDENTIFIER \"}} }}' }}"
      threshold: 200
      window_secs: 200
...
```
to become 
```yaml
...
transforms:
    throttle_journald:
      type: throttle
      inputs:
        - my_src
      key_field: '{{ SYSLOG_IDENTIFIER }}'
      threshold: 200
      window_secs: 200
...
```
