### ISSUE TITLE
(sink) aws_cloudwatch_logs: healthcheck errors if log group doesn't exist

### ISSUE THREAD

**Issue by spencergilbert** [timberio/vector#7592]
### Vector Version

```
vector 0.13.1 (v0.13.1 x86_64-unknown-linux-gnu 2021-04-29)
```

### Vector Configuration File

```toml
[sources.journald]
type = "journald"

[transforms.filter_journald]
  type = "filter"
  inputs = ["journald"]
  condition = """
  (to_int(.PRIORITY) ?? 0) < 4
  """

[transforms.remap_journald]
  type = "remap"
  inputs = ["journald"]
  source = """
  if !contains(.message,"boot") {
  abort
  }
  """

[sinks.out1]
type = "aws_cloudwatch_logs"
inputs = [ "filter_journald" ]
group_name = "journald_server_logs"
region = "eu-central-1"
stream_name = "aws1_journald"
encoding.codec = "json"

[sinks.out2]
type = "aws_cloudwatch_logs"
inputs = [ "remap_journald" ]
group_name = "boot_server_logs"
region = "eu-central-1"
stream_name = "aws1_boot"
encoding.codec = "json"
```

### Debug Output

```
ERROR vector::topology::builder: msg="Healthcheck: Failed Reason." error=No log group found component_kind="sink" component_type="aws_cloudwatch_logs" component_name="out2" 
```

### Expected Behavior

Healthcheck passes, vector will create any missing log group by default.

### Actual Behavior

`aws_cloudwatch_logs` has a healthcheck that checks if the `log_group` is going to be dynamically generated from the log (using templating) [ref](https://github.com/timberio/vector/blob/master/src/sinks/aws_cloudwatch_logs/mod.rs#L499-L501). However, if a user is expecting Vector to use the default behavior of creating log group and log streams but with _hard coded_ `log_group`, like the example above with two separate sinks, the healthcheck will fail since it only looks for dynamism.

It seems to me that the conditional should rather check that the `create_missing_group` config is true, which is already more important than the group being dynamic. A dynamic group with `create_missing_group = false` _should_ fail by my understanding.
