### ISSUE TITLE
Dedupe is ratelimited due to warnings

### ISSUE THREAD

**Issue by ybinnenwegin2ip** [timberio/vector#7809]
### Vector Version

```
vector 0.14.0 (x86_64-unknown-linux-gnu 5f3a319 2021-06-03)
```

### Vector Configuration File

```toml
[sources.samba_audit_syslog]
  type = "syslog" # required
  address = "127.0.0.1:9000" # required, required when mode = `tcp` or `udp`
  max_length = 102400 # optional, default, bytes
  mode = "udp" # required

[transforms.samba_audit_dedupe]
  # General
  type = "dedupe" # required
  inputs = ["samba_audit_syslog"] # required

  # Fields
  fields.match = ["timestamp", "host", "message"] # optional, default

  # Cache
  cache.num_events = 15000

[transforms.samba_audit_transformed]
  inputs = [ "samba_audit_dedupe"]
  type = "remap"
  source = '''
    ts, err = to_string(.timestamp)
    . = join!([ts, .message], separator: " ")
  '''

# Print parsed logs to stdout
[sinks.print]
  type = "console"
  inputs = ["samba_audit_transformed"]
  encoding.codec = "text"

[sinks.samba_audit_dedupe_file]
  # General
  type = "file" # required
  inputs = ["samba_audit_transformed"] # required
  compression = "none" # optional, default
  path = "/var/log/samba/audit_dedupe-%Y-%m-%d.log" # required

  # Encoding
  encoding.codec = "text" # required
  encoding.only_fields = ["timestamp","message"]

  # Healthcheck
  healthcheck.enabled = true # optional, default
```

### Debug Output

https://gist.github.com/ybinnenwegin2ip/c5e2a22ecbd337c6bbfbde890ef8d758

### Expected Behavior

I would expect the dedupe transformation not to log a line for every deduplication (?) it does.

### Actual Behavior

The dedupe transformation seems to log a line for every event it deduplicates and then gets rate limited by vector.

### Example Data

```
{ datadog_api_key: None, finalizers: EventFinalizers([]) } })
Jun 09 16:34:45.070  WARN transform{component_kind="transform" component_name=samba_audit_dedupe component_type=dedupe}: vector::internal_events::dedupe: Internal log [Encountered duplicate event; discarding.] has been rate limited 3335 times.
Jun 09 16:34:45.070  WARN transform{component_kind="transform" component_name=samba_audit_dedupe component_type=dedupe}: vector::internal_events::dedupe: Encountered duplicate event; discarding. internal_log_rate_secs=30
```

### Additional Context

I'm feeding Vector the output data of Samba's full_audit VFS, which is rather verbose. Vector is used to deduplicate the amount of lines to a managable amount before writing to disk.

### References

None AFAIK
