### ISSUE TITLE
Loki sync flattens nested object type event fields

### ISSUE THREAD

**Issue by airhorns** [timberio/vector#7815]
I would like to keep my log entries containing nested object or array fields like `{ "example": { "foo": "bar" }, values": ["foo", "bar"] }` submitted as such to the `loki` sync, but when querying loki I instead see `{ "example.foo": "bar", "values[0]": "foo", "values[1]": "bar" }`. After talking with @jszwedko on Discord, it looks like https://github.com/timberio/vector/blob/master/src/sinks/loki.rs#L229 may be to blame, they mentioned that `all_fields()` may have this behavior. 

I am also sending the same events to a `humio` sync and they appear untouched and properly nested there, so I am pretty confident my events are indeed nested and the issue lies somewhere after my transform stages . There might be something happening loki side, but I was able to get Loki to accept events with nested JSON (really just JSON strings) via promtail when I was using it.

### Vector Version

```
vector 0.14.0 (x86_64-unknown-linux-musl 5f3a319 2021-06-03)
```

### Vector Configuration File

From a helm `values.yaml` for the vector chart:

```yaml
# Sinks to add to the generated `vector` config.
sinks:
  # sink_name:
  #   type: "sink_type"
  #   inputs: ["input1", "input2"]
  #   option: "value"
  #   rawConfig: |
  #     option = "value"
  app-loki:
    type: "loki"
    inputs: ["tagged-sandbox-logs"]
    endpoint: http://loki-app.loki-app.svc:3100
    tenant_id: "{{ application_id }}"
    encoding:
      codec: "json"
    labels:
      application_id: "{{ application_id }}"
      host: "{{ host }}"
      app_logs_service: "{{ app_logs_service }}"
```
### Expected Behavior

Log events with nested structure (usually parsed from JSON) have that structure preserved when submitted to Loki

### Actual Behavior

Log events with nested structure are flattened to only have top level keys when submitted to Loki

### Additional Context

vector is running in kubernetes, there is a `remap` transform which is changing the JSON logs from the `kubernetes-logs` source, but I am pretty sure it isn't doing this flattening behaviour because the events appear untouched in another sink
