### ISSUE TITLE
Unit test regression in 0.14.0

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#7854]
The following test config fails `vector test` on 0.14.0 with:

```
Jun 14 10:33:35.373 ERROR remap{vrl_position=57}: vrl_stdlib::log: "Unable to parse json message: function call error for \"parse_json\" at (11:31): unable to parse json: expected value at line 1 column 1" internal_log_rate_secs=1
test filter_invalid_json_message ... failed

failures:

test filter_invalid_json_message:

check transform 'filter_json_message' failed: expected no outputs.
payloads (events encoded as JSON):
   input: {"message":null}
  output: {"message":null}
```

But passes on 0.13.1.

Config:

```toml
[transforms.parse_json_message]
  type   = "remap"
  inputs = ["syslog"]
  source = '''
  ., err = parse_json(.message)
  if err != null {
      log("Unable to parse json message: " + err, level: "error")
      .error = true
  }
  '''

[transforms.filter_json_message]
  type      = "filter"
  inputs    = ["parse_json_message"]
  condition = '.error != true'

[[tests]]
    name = "filter_invalid_json_message"
    no_outputs_from = ["filter_json_message"]
    [[tests.inputs]]
        insert_at = "parse_json_message"
        type = "log"
        log_fields.message = "invalidJSON"
```
