### ISSUE TITLE
Duplicate Metrics

### ISSUE THREAD

**Issue by cholcombe973** [timberio/vector#7923]
### Current Vector Version

```
latest via install script
```

### Use-cases
I'd like to be able to take a metric (or a log) and duplicate it so it can be split between 2 sinks. I've been looking at the documentation and I'm not sure that's possible currently. I'm filing this to see if someone knows more. 

### Attempted Solutions
I tried looking at the current transforms. Nothing sticks out that can accomplish this. Maybe VRL can do it. I wasn't sure. 

### Proposal
If it's not possible with the current plugins I'd like to propose building this functionality myself and PR'ing it.

**Comment by jszwedko** [comment]
Hi @cholcombe973 ,

Vector is capable of "fanning out" to have one component serve as the input to two components like:

```toml
[sources.metrics]
type = "host_metrics"

[sinks.console]
type = "console"
inputs = ["metrics"]
encoding.codec = "json"

[sinks.prometheus]
type = "prometheus_exporter"
address = "0.0.0.0:8787"
```

Is that something along the lines of what you were thinking?
