### ISSUE TITLE
Parses for Java logs

### ISSUE THREAD

**Issue by alpi-ua** [timberio/vector#7941]
Hello

It would be great if vector gain more simple management of Java logs.
It might be needed in multi line support as well as VRL function similar to "parse_nginx_log" etc.

**Multiline**
I'm using expression like this to combine strings from all cases I faced in my app. Finally it looks complete and no strings left out. Timeout is so huge because when it lesser logs got splitted.
     ```toml
     start_pattern = '^[^\s]'
     mode = "continue_through"
     condition_pattern = '(?m)^[\s].*$|(?m)^Caused.+$|(?m)^\}.*$'
     timeout_ms = 1000000000
     ```
**Parsing**
To get a timestamp, level, message etc. It could be few scenarious

1.  from Java log output - I build the pattern like this which covering most my cases.
 ```
. |= parse_regex!(.message,r'^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3}) (?P<level>\w+) (?P<message>.*[\s]*.*$)')
.timestamp = parse_timestamp(.timestamp,"%Y-%m-%d %H:%M:%S.%3f") ?? now()
```
Nevertheless, I can't grab a full message with this one - only first few strings, and struggle to solve it properly.

2. from Java app stdin / stdout. The difference is that stdout producing only %H:%M:%S timestamp. 
. |= parse_regex!(.message,r'^(?P<time>\d{2}:\d{2}:\d{2},\d{3}) \|-(?P<level>\w+) (?P<message>.*[\s]*.*$)')
And It look a bit over complicated to set a proper timestamp on this stage. 

Appreciate any help improving this, as I'm not very professional in regexp writing, and looking forward to see if the function covering all diverse in future.
