### ISSUE TITLE
Commented environment variables are still attempted to be interpolated

### ISSUE THREAD

**Issue by a-rodin** [timberio/vector#797]
When Vector is launched with this config

```toml
[sources.stdin]
  type = "stdin"
  # commented = "${UNDEFINED_VARIABLE}"

[sinks.console]
  type = "console"
  inputs = ["stdin"]
```

then, assuming that `UNDEFINED_VARIABLE` is not defined, there is a warning

```
Aug 25 13:48:36.037  WARN vector::topology::config::vars: unknown env var in config: "UNDEFINED_VARIABLE"
```

**Comment by binarylogic** [comment]
Thanks @a-rodin. I'm wondering how we can streamline this. Currently, we interpolate env vars before passing the config through the TOML parser. I can't think of a better way to solve this than to move env var interpolation to post TOML parsing. This means we'd have to walk all string values.

**Comment by a-rodin** [comment]
I think there's nothing bad in walking over string values, it shouldn't be slower that deserialization itself. Maybe it can be implemented by deserializing TOML not directly to `vector::topology::Config` type, but first to `toml::Value`, recursively traversing the resulting `toml::Value` to do interpolations in all strings, and then using `toml::Value::try_into<'_, vector::topology::Config>` to convert the updated `toml::Value` to `vector::topology::Config`.

**Comment by a-rodin** [comment]
Although with that approach it would not be possible to use interpolations for non-string values, such as integers and booleans. So probably stripping comments and doing the interpolation after that before parsing would still be necessary to use vars for non-string values.

**Comment by jszwedko** [comment]
We also have users using the environment variable interpolation to interpolate full blocks of configuration like:

```toml
[sources.stdin]
  type = "stdin"
  ${STIDN_CONFIG}
```

Which, if we did the interpolation later, would prohibit this use-case. This might be OK (maybe it isn't something we want to support), but just noting it for consideration.
