### ISSUE TITLE
cannot log raw message

### ISSUE THREAD

**Issue by lichuan6** [timberio/vector#7975]
```toml
[sources.nginx_logs]
type = "file" # required
include = ["/var/log/nginx/*.log"] # required
read_from = "beginning" # optional, default
ignore_checkpoints = true

[transforms.parse_logs]
type = "remap"
inputs = ["nginx_logs"]
source = '''
  structured, err = parse_regex(.message, r'^(-|(?P<remote_addr>\S+)) - (-|(?P<user>\S+)) \[(?P<timestamp>.+)\] "(?P<req
uest>(?P<method>\w+) (?P<path>\S+) (?P<protocol>\S+))" (?P<status>\d+) (?P<size>\d+) "(-|(?P<referer>.+))" "(-|(?P<agent
>.+))" "(-|(?P<http_x_forwarded_for>.+))" "(-|(?P<host>.+))" "(-|(?P<cookie_username>.+))" "(-|(?P<request_time>\d+\.\d+
))" "user\[(-|(?P<http_uid>.+))\]"$')
  if err != null {
    log("Unable to parse_regex RAW:" + message, level: "error")
  } else {
    . = merge(., structured)
    .status = to_int!(.status)
    .size = to_int!(.size)
    .request_time = to_float!(.request_time)
    .@timestamp = parse_timestamp!(.timestamp, "%d/%b/%Y:%H:%M:%S %z")
  }
 '''
```

Hi, I'm using vector to parse nginx log, but how to log raw original nginx log when error occurs during the transform process(using parse_regex)? `message` is empty in vector's console log.

```
Jun 22 15:42:23.829 ERROR transform{component_kind="transform" component_name=parse_logs component_type=remap}:remap{vrl_position=421}: vrl_stdlib::log: "Unable to parse_regex RAW:" internal_log_rate_secs=1
```

**Comment by spencergilbert** [comment]
Hey! You have an error in your `log` , you're missing the `.` preceding message which is having VRL look for a variable rather than a path (field).

Also, rather than using regex have you tried them built-in parse function we have? https://vector.dev/docs/reference/vrl/functions/#parse_nginx_log

**Comment by Georgekonsec** [comment]
Hey Spencer! Actually I have the same problem like lichuan6. I am using parse_regex function. 
Could you show how it looks like the correct code in the lichuan6 code? 

From vector docs it seems what lichuan6 tried, was correct:
```
structured, err = parse_json("not json")
if err != null {
  log("Unable to parse JSON: " + err, level: "error")
} else {
  . = merge(., structured)
}
```

**Comment by spencergilbert** [comment]
Definitely! So the _slight_ difference there is the snippet you shared is assigning a successful result to `structured` and failed result to `err`, both are variable internal to the VRL script.

The `log()` in the snippet is passing in the variable `err` which contains the error message from the parse function, the example @lichuan6 shared is attempting to log the _raw text_ that failed parsing which is contained in `.message` (in the example `message` is an undefined variable - note the missing `.`)

**Comment by Georgekonsec** [comment]
This is exactly what I tried, but it seems that is not working as expected.
You can see the below block:
```
  if err != null {
    log("Unable to parse_regex RAW:" + .message, level: "error")
  } else {
    . = merge(., structured)
```

Another failed block without merging:
```
., err = parse_regex(.message, r^(-|(?P<remote_addr>\S+)) - (-|(?P<user>\S+)) \[(?P<timestamp>.+)\] "(?P<req
uest>(?P<method>\w+) (?P<path>\S+) (?P<protocol>\S+))" (?P<status>\d+) (?P<size>\d+) "(-|(?P<referer>.+))" "(-|(?P<agent
>.+))" "(-|(?P<http_x_forwarded_for>.+))" "(-|(?P<host>.+))" "(-|(?P<cookie_username>.+))" "(-|(?P<request_time>\d+\.\d+
))" "user\[(-|(?P<http_uid>.+))\]"$')
if err != null {
  log("Unable to parse_regex RAW:" + .message, level: "error")
 } else {
  .status = to_int!(.status)
  .size = to_int!(.size)
  .request_time = to_float!(.request_time)
  .@timestamp = parse_timestamp!(.timestamp, "%d/%b/%Y:%H:%M:%S %z")
  }
```
Still, no output from vector. Am I missing something?

**Comment by spencergilbert** [comment]
Can you share an example log that should be parsed by this setup?

**Comment by spencergilbert** [comment]
This is likely what you want to be using as config:

```toml
[transforms.remap]
  type = "remap"
  inputs = ["in"]
  source = '''
    structured, err = parse_regex(.message, r'^(-|(?P<remote_addr>\S+)) - (-|(?P<user>\S+)) \[(?P<timestamp>.+)\] "(?P<request>(?P<method>\w+) (?P<path>\S+) (?P<protocol>\S+))" (?P<status>\d+) (?P<size>\d+) "(-|(?P<referer>.+))" "(-|(?P<agent>.+))" "(-|(?P<http_x_forwarded_for>.+))" "(-|(?P<host>.+))" "(-|(?P<cookie_username>.+))" "(-|(?P<request_time>\d+\.\d+))" "user\[(-|(?P<http_uid>.+))\]"$')
    if err != null {
      log("Unable to parse_regex RAW:" + string!(.message), level: "error")
    } else {
      . = merge(., structured)
      .status = to_int!(.status)
      .size = to_int!(.size)
      .request_time = to_float!(.request_time)
      .@timestamp = parse_timestamp!(.timestamp, "%d/%b/%Y:%H:%M:%S %z")
    }
  '''
```
