### ISSUE TITLE
support json encoding for file sink

### ISSUE THREAD

**Issue by lichuan6** [timberio/vector#7976]
Hi,

Is it possible to support json encoding in file sink, just like console sink?

**Comment by jszwedko** [comment]
Hi @lichuan6 ,

The `file` sink actually already supports writing JSON logs with `content.encoding = "ndjson"`. We use `ndjson` there given that it is new-line delimited JSON (as opposed to, for example, a JSON array like the `http` sink). Is this what you are after?

**Comment by lichuan6** [comment]
Hi @jszwedko ,

Thanks for your reply. I tried with `encoding = "ndjson"`, but the fields(`agent`, `host`, etc) are not parsed in output file, which I expected the json in file sink to be like in elasticsearch sink(the `_source` field):


```json
{
  "took": 0,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 3,
      "relation": "eq"
    },
    "max_score": 1,
    "hits": [
      {
        "_index": "vector-nginx-2021-06-23",
        "_type": "_doc",
        "_id": "upsAN3oBvArNzQQHD5NL",
        "_score": 1,
        "_source": {
          "@timestamp": "2021-06-20T16:00:00Z",
          "agent": "okhttp/3.12.0",
          "cookie_username": null,
          "file": "1.log",
          "host": "example.example.com",
          "http_uid": null,
          "http_x_forwarded_for": "222.222.222.222",
          "message": "10.222.222.222 - - [21/Jun/2021:00:00:00 +0800] \"GET /test/oooo HTTP/1.1\" 200 170 \"-\" \"okhttp/3.12.0\" \"222.222.222.222\" \"example.example.com\" \"-\" \"0.006\" \"user[-]\"",
          "method": "GET",
          "path": "/test/oooo",
          "protocol": "HTTP/1.1",
          "referer": null,
          "remote_addr": "10.222.222.222",
          "request": "GET /test/oooo HTTP/1.1",
          "request_time": 0.006,
          "size": 170,
          "source_type": "file",
          "status": 200,
          "timestamp": "21/Jun/2021:00:00:00 +0800",
          "user": null
        }
      },
      {
        "_index": "vector-nginx-2021-06-23",
        "_type": "_doc",
        "_id": "u5sAN3oBvArNzQQHD5NL",
        "_score": 1,
        "_source": {
          "file": "1.log",
          "host": "bogon",
          "message": "10.128.4.225 - - [21/Jun/2021:00:00:00 +0800]",
          "source_type": "file",
          "timestamp": "2021-06-23T03:53:06.757890Z"
        }
      },
      {
        "_index": "vector-nginx-2021-06-23",
        "_type": "_doc",
        "_id": "vJsAN3oBvArNzQQHD5NL",
        "_score": 1,
        "_source": {
          "file": "1.log",
          "host": "bogon",
          "message": "10.128.4.22[21/Jun/2021:00:00:00 +0800]",
          "source_type": "file",
          "timestamp": "2021-06-23T03:53:06.757900Z"
        }
      }
    ]
  }
}
```

Here is my config file:

```toml
data_dir = "/tmp/var/lib/vector"

[sources.nginx_logs]
type = "file" # required
include = ["1.log"] # required
read_from = "beginning" # optional, default
ignore_checkpoints = true

[transforms.parse_logs]
type = "remap"
inputs = ["nginx_logs"]

source = '''
  structured, err = parse_regex(.message, r'^(-|(?P<remote_addr>\S+)) - (-|(?P<user>\S+)) \[(?P<timestamp>.+)\] "(?P<request>(?P<method>\w+) (?P<path>\S+) (?P<protocol>\S+))" (?P<status>\d+) (?P<size>\d+) "(-|(?P<referer>.+))" "(-|(?P<agent>.+))" "(-|(?P<http_x_forwarded_for>.+))" "(-|(?P<host>.+))" "(-|(?P<cookie_username>.+))" "(-|(?P<request_time>\d+\.\d+))" "user\[(-|(?P<http_uid>.+))\]"$')
  if err != null {
    log("Unable to parse_regex RAW" + string!(.message), level: "error")
  } else {
    . = merge(., structured)
    .status = to_int!(.status)
    .size = to_int!(.size)
    .request_time = to_float!(.request_time)
    .@timestamp = parse_timestamp!(.timestamp, "%d/%b/%Y:%H:%M:%S %z")
  }
 '''

[sinks.write_to_parsed_ok_file]
type = "file" # must be: "file"
inputs = ["nginx_logs"]
path = "vector-%Y-%m-%d.log" # example
# Tried this, but failed
# content.encoding = "ndjson"
encoding = "ndjson"

# [sinks.write_to_console]
# # General
# type = "console" # required
# inputs = ["nginx_logs"]
# target = "stdout" # optional, default
# # Encoding
# encoding.codec = "json" # required

```

Here is my source file `1.log`:

```
10.222.222.222 - - [21/Jun/2021:00:00:00 +0800] "GET /test/oooo HTTP/1.1" 200 170 "-" "okhttp/3.12.0" "222.222.222.222" "example.example.com" "-" "0.006" "user[-]"
10.128.4.225 - - [21/Jun/2021:00:00:00 +0800]
10.128.4.22[21/Jun/2021:00:00:00 +0800]
```

Here is the file content in file sink:

```
{"file":"1.log","host":"bogon","message":"10.222.222.222 - - [21/Jun/2021:00:00:00 +0800] \"GET /test/oooo HTTP/1.1\" 20
0 170 \"-\" \"okhttp/3.12.0\" \"222.222.222.222\" \"example.example.com\" \"-\" \"0.006\" \"user[-]\"","source_type":"fi
le","timestamp":"2021-06-23T03:46:35.801615Z"}
{"file":"1.log","host":"bogon","message":"10.128.4.225 - - [21/Jun/2021:00:00:00 +0800]","source_type":"file","timestamp
":"2021-06-23T03:46:35.801934Z"}
{"file":"1.log","host":"bogon","message":"10.128.4.22[21/Jun/2021:00:00:00 +0800]","source_type":"file","timestamp":"202
1-06-23T03:46:35.801944Z"}

```

**Comment by jszwedko** [comment]
Hi @lichuan6 ,

I think the reason that the extra fields you expected are not in the output is because the regex you have does not match the input files. Are you seeing `Unable to parse_regex RAW` in the Vector output?

You can use https://rustexp.lpil.uk/ to test your regular expressions. That site uses the same regex engine as Vector.

**Comment by jszwedko** [comment]
Actually, I'm sorry, it does match the first input line you have, just not the others.

I think you mean to have:

```toml
[sinks.write_to_parsed_ok_file]
type = "file" # must be: "file"
inputs = ["parse_logs"]
path = "vector-%Y-%m-%d.log" # example
# Tried this, but failed
# content.encoding = "ndjson"
encoding = "ndjson"
```

Though. Note that I changed the input to the output of the remap transform. Previously it was consuming directly from the `nginx_logs` component.
