### ISSUE TITLE
Extend tokenizer transform to support arbitrary split separator

### ISSUE THREAD

**Issue by mre** [timberio/vector#799]
## Status Quo

As of now, the tokenizer transform splits the input on ~a single whitespace character~ whitespace.
To support more use-cases, the tokenizer could allow for arbitrary separators however.
This would be quite helpful when migrating from Logstash, which [supports that feature](https://www.elastic.co/guide/en/logstash/current/plugins-filters-mutate.html#plugins-filters-mutate-split).

## Proposal

To make this backward-compatible, we could add an optional `separator` config option to the tokenizer that would default to whitespace.

## Alternative approaches

* Using the existing `regex_parser` and `grok_parser` transforms could work, but writing a regular expression for this might be repetitive and could be avoided for this simple use-case.
* Writing a `lua` script is another option, but requires programming experience and might cause some overhead due to crossing the language barrier.
* Create a new split transform and leave the tokenizer transform untouched. In this case we have to clearly communicate the different use-cases of both transforms and there will probably be some code duplication.

**Comment by mre** [comment]
I agree that if I defined `,` as a separator, it would come as a surprise to me if the input was also split by other separators like quotes. The current choice of separators of `tokenizer` is a bit odd to me because I could think of a related separators that are currently not taken into account - like single quotes, parentheses, or angular brackets.

For instance if the input is

```
[2016-08-15 12:32:11] "my server"
```

then the parsed value is 

```
["2016-08-15 12:32:11", "my server"]
```

but if the input is

```
(2016-08-15 12:32:11) 'my server'
```

then the tokens are

```
["(2016-08-15", "12:32:11)", "\'my", "server\'"]
```

The configuration options for `split` would be almost identical to `tokenizer` (minus the type coercion maybe).

```toml
[transforms.my_split_transform]
  # REQUIRED - General
  type = "split" # must be: split
  inputs = ["my-source-id"]
  field_names = ["timestamp", "level", "message"]

  # OPTIONAL - General
  drop_field = true # default
  field = "message" # default
  # Default separator would be whitespace.
  separator = "," # Or separators = [",", ";"] if we want to support multiple separators.
```

On a more general note, maybe the `tokenizer` transform is not generic enough after all. Adding more built-in separators to the nom parser might cause an increase of edge-cases. There's also the concern that having both `tokenizer` and `split` might confuse newcomers as those terms are defined quite loosely in other projects.

So maybe we can start with a standalone `split` transform for now and reserve the option to merge both transforms again in a future iteration?
