### ISSUE TITLE
can't use auth.token with source prometheus remote writer

### ISSUE THREAD

**Issue by ocrlgv** [timberio/vector#8000]
Using vector on a host to relay a local prometheus node_exporter data using the sink::prometheus_remote_writer to send the data to a remote source::prometheus_remote_writer has some differences in configuration.

I had by accident "access_keys" as the token on the remote side source vector prom remote writer thinking it was the token but it simply ignored it with no errors thought the sink of prometheus remote writer actually supports a token.

As per Spencer on discord (can't copy link in discord, damn safari)
1: Source should support bearer auth tokens
2: If that caused the errors, that's a separate issue

### Vector Version
```
vector 0.14.0 (x86_64-unknown-linux-gnu 5f3a319 2021-06-03)
```

### Vector Configuration File
local side which works but prometheus remote writer source doesn't
```toml
[sinks.sink_ingest]
  type                          = "prometheus_remote_write"
  inputs                        = ["prometheus_tagged"]
  default_namespace             = "node"
  endpoint                      = "https://ingest.domain.com:5623/"
  auth.strategy                 = "bearer"
  auth.token                     = "mytoken"
```
