### ISSUE TITLE
salt stack with syslog source

### ISSUE THREAD

**Issue by antonyc** [timberio/vector#8017]
Hi guys! I know this is not a totally vector issue.
I have a (beautiful) vector configured to accept syslog messages from salt-minion. Python is known to have problems [1] logging and there is not so much to configure [2] in salt stack, so I end up with single option: `log_file: tcp://vector-aggregator:514` in salt conf file.
In my elastic search I get unparsed messages, both multiple joined into one:
```
<15>2021-06-24 08:32:57,564 [salt.loader      :770 ][DEBUG   ][1306977] Grains refresh requested. Refreshing grains.<15>2021-06-24 08:32:57,564 [salt.config      :2111][DEBUG   ][1306977] Reading configuration from /etc/salt/minion<15>2021-06-24 08:32:57,565 [salt.config      :2255][DEBUG   ][1306977] Including configuration from '/etc/salt/minion.d/_schedule.conf'<15>2021-06-24 08:32:57,565 [salt.config      :2111][DEBUG   ][1306977]
```
and one message split into multiple ones in elastic in some random places:
part number | result
-------------|-------
1 | ```[salt.utils.lazy  :104 ][DEBUG   ][1280075] LazyLoaded jinja.render<15>20```
2 | ```[salt.minion      :```

I think this might be a problem with the Python, but I am not sure. 

Using `logger` to send log lines directly from the same host `logger --stderr --tcp --port 514 --server vector-aggregator "hello"` gives me the result I expect - each line is correctly parsed. So this is not a problem with syslog itself.

I haven't tried switching to UDP yet, this may help, because each message will be sent independently but I don't believe it to be a good long term solution.
I also don't want to have a log-file parsing agent on my host - I would like to save resources at any cost.
I also saw [parsing section](https://vector.dev/docs/reference/configuration/sources/syslog/#parsing) of syslog source, it recommends using socket with regex parser, which is something I will consider. 
I cannot easily switch logs to JSON, though they say salt can send to logstash json over UDP form [3], this may be an option (a strange one, but why not).

So could you please share your thoughts of what option seems the best to you? 

[1] https://bugs.python.org/issue28404
[2] https://docs.saltproject.io/en/latest/ref/configuration/logging/index.html
[3] https://docs.saltproject.io/en/latest/ref/configuration/logging/handlers/salt.log.handlers.logstash_mod.html#module-salt.log.handlers.logstash_mod

**Comment by jszwedko** [comment]
Hi @antonyc!

Are you able to share the vector config you are using?

**Comment by antonyc** [comment]
```
transforms:
  dataplane_syslog_tosink:
    type: remap
    inputs:
      - dataplane
    source: |
      .msg = .message
      del(.message)
      .level = .severity
      del(.severity)
  presink_hook:
    type: remap
    inputs:
      - dataplane_syslog_tosink
    source: |
      .context.region = "${controlplane_region}"
sources:
  dataplane:
    type: syslog
    address: "0.0.0.0:${port:-514}"
    #    max_length: 102400
    mode: tcp
sinks:
  elastic:
    type: elasticsearch  # https://vector.dev/docs/reference/configuration/sinks/elasticsearch/
    inputs:
      - presink_hook
    compression: gzip
    endpoint: "${elastic_endpoint}"
    index: log-dataplane-${controlplane_region}-%Y-%m-%d
    healthcheck: # --require-healthy if need to stop
      enabled: true
    #    batch:
    #      max_bytes: 10490000  # 10 MiB
    #      timeout_secs: 1
    buffer:
      type: memory
      #      max_events: 500
      when_full: drop_newest
    bulk_action: index  # TODO: change to create and use data stream https://www.elastic.co/guide/en/elasticsearch/reference/current/data-streams.html
    auth:
      password: "${elasticuser_password}"
      user: "${elasticuser_name}"
      strategy: basic
    request:
      concurrency: adaptive  # https://vector.dev/docs/reference/configuration/sinks/elasticsearch/#adaptive-request-concurrency-arc
    #      retry_initial_backoff_secs: 1
    #      timeout_secs: 60
```
