### ISSUE TITLE
host_metrics source emits logs when not configured

### ISSUE THREAD

**Issue by spencergilbert** [timberio/vector#8045]
### Vector Version

```
Jun 26 00:14:10.587  INFO vector: Vector has started. debug="false" version="0.15.0" arch="x86_64" build_id="d4503f8 2021-06-25"
```

### Vector Configuration File

```toml
# Configuration for vector.
# Docs: https://vector.dev/docs/

data_dir = "/vector-data-dir"

[api]
  enabled = false
  address = "0.0.0.0:8686"
  playground = true

[log_schema]
  host_key = "host"
  message_key = "message"
  source_type_key = "source_type"
  timestamp_key = "timestamp"

[sources.gen_logs]
  format = "syslog"
  interval = 1.5
  type = "generator"

[sinks.stdout]
  inputs = ["*_logs"]
  type = "console"
  [sinks.stdout.encoding]
    codec = "json"
```

### Expected Behavior

Components not configured should not emit any log output.

### Actual Behavior

```
Jun 25 22:54:59.422  INFO vector::sources::host_metrics: PROCFS_ROOT is unset. Using default '/proc' for procfs root.
Jun 25 22:54:59.422  INFO vector::sources::host_metrics: SYSFS_ROOT is unset. Using default '/sys' for sysfs root.
```
