### ISSUE TITLE
[kubernetes_logs] Logs are not forwarded if pod has "app" label configured 

### ISSUE THREAD

**Issue by Nicarim** [timberio/vector#8058]
I'm getting an error when my pod has label called "app". I've found about it when I tried to run https://github.com/opsgenie/kubernetes-event-exporter/blob/master/deploy/02-deployment.yaml this deployment. I think it should be pretty easy to replicate given that.

I've fixed it by changing the `app` label to `app_name` label. 

### Vector Version
```
vector 0.14.0 (x86_64-unknown-linux-gnu 5f3a319 2021-06-03)
```

### Vector Configuration File
I'm using helm setup with following values

```yaml
sinks:
  elasticsearch:
    type: elasticsearch
    inputs:
      - kubernetes_logs
    index: "index-%F"
    endpoint: "removed"
    auth:
      user: "${ELASTICSEARCH_USERNAME}"
      password: "${ELASTICSEARCH_PASSWORD}"
      strategy: basic
```

### Debug Output

I'm not quite sure how to configure the debug output using helm chart, but can provide if it will be really necessary

### Expected Behavior

Logs should be forwarded to elasticsearch

### Actual Behavior

Logs were dropping, with error in stdout 

```
│ Jun 28 14:14:35.021 ERROR sink{component_kind="sink" component_name=elasticsearch component_type=elasticsearch}:request{request_id=304}: vector::sinks::util::retries: Not retriable; dropping the request. reaso │
│ n="error type: mapper_parsing_exception, reason: object mapping for [kubernetes.pod_labels.app] tried to parse field [app] as object, but found a concrete value"
```

### Example Data
https://github.com/opsgenie/kubernetes-event-exporter/blob/master/deploy/02-deployment.yaml
Deploy this kubernetes cluster alongside vector, configure elasticsearch sink and the logs are not there.
