### ISSUE TITLE
The replace command does not capture groups inside a transform

### ISSUE THREAD

**Issue by ismoil-nosr** [timberio/vector#8067]
### Vector Version

```
vector 0.14.0 (x86_64-pc-windows-msvc 5f3a319 2021-06-03)
```

### Vector Configuration File

```toml
[transforms.replace_pan]
    type = "remap"
    inputs = ["logs"]
    source = '''
        .pan = replace("4455111122223333", r'(\d{6})(\d+)(\d{4})', "$1******$3")
    }
    '''
```

### Expected Behavior

```json
{
   "pan": "445511******3333" 
}
```

### Actual Behavior

```json
{
   "pan": "******" 
}
```

But interesting part when I run `replace` command from `vector-cli` I'm getting right output:
```console
$ replace("4455111122223333", r'(\d{6})(\d+)(\d{4})', "$1******$3")
"445511******3333"
```
