### ISSUE TITLE
GCP authentication in Helm v0.14.0

### ISSUE THREAD

**Issue by c0rv4x** [timberio/vector#8107]
### Vector Version

`v0.14.0` - specifically I am using **Helm** version in my Kube cluster in Scaleway

### Vector Configuration File

Since I am using helm, posting also the helmchart values I am using

```yaml
sources:
  dummy_logs:
    type: generator
    format: syslog
    interval: 1

transforms:
  parse_logs:
    type: remap
    inputs:
      - dummy_logs
    source: ". = parse_syslog!(string!(.message))"
  
sinks:
  google:
    type: gcp_stackdriver_logs
    inputs:
      - parse_logs
    credentials_path: "/secrets/gcp-logging-key.json"
    log_id: PROJECT_NAME
    project_id: PROJECT_NAME
    healthcheck:
      enabled: true
    resource:
      type: global
      projectId: PROJECT_NAME
      zone: us-central1-a

extraVolumeMounts:
  - name: google-logging-secret
    mountPath: "/secrets"
    readOnly: true

extraVolumes:
  - name: google-logging-secret
    secret:
      secretName: google-logging-secret

env:
  - name: RUST_BACKTRACE
    value: full
  - name: LOG
    value: debug
```

As you can see, I am using kube secrets to mount the service account into the pod. Here is how you can create one 
```bash
kubectl create secret generic google-logging-secret --from-file=gcp-logging-key.json --namespace vector
```

Here is the **toml** I have taken from the pod

https://gist.github.com/c0rv4x/c5f0649cb7c270693f3fc2a79a778fba

### Debug Output

https://gist.github.com/c0rv4x/51415b39f7a6d06d6c533448ab80cf04

### Expected Behavior

Vector successfully authenticates to google

### Actual Behavior

The problem is that for some reason Vector fails to get oauth token. I have tried the same setup locally (no helm, just the generated toml) and it works fine. For reference and future searches here is the error: `Configuration error. error=Sink "google": Failed to get OAuth token`

### References

Tagging @spencergilbert upon talking on Discord
