### ISSUE TITLE
File checkpoints are incompatible between 0.13.1 and 0.14.0

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#8182]
### Vector Version

```
vector 0.13.1 (v0.13.1 x86_64-unknown-linux-gnu 2021-04-29)
vector 0.14.0 (x86_64-unknown-linux-gnu 5f3a319 2021-06-03)
```

### Vector Configuration File

```toml
data_dir = "/tmp/vector-file-test/"

[sources.source0]
exclude = []
file_key = "file"
glob_minimum_cooldown_ms = 1000
ignore_not_found = false
include = ["/tmp/logs/*"]
line_delimiter = "\n"
max_line_bytes = 102400
max_read_bytes = 2048
multi_line_timeout = 1000
oldest_first = false
type = "file"

[sources.source0.fingerprint]
ignored_header_bytes = 0
strategy = "checksum"

[sinks.sink0]
inputs = ["source0"]
target = "stdout"
type = "console"

[sinks.sink0.encoding]
codec = "json"

[sinks.sink0.healthcheck]
enabled = true

[sinks.sink0.buffer]
type = "memory"
max_events = 500
when_full = "block"
```

### Expected Behavior

Vector should correctly re-use the file checkpoints written by 0.13.1.

### Actual Behavior

Vector does not match up the checkpoints and re-ingests the existing files.

### Additional Context

To reproduce:

* Start Vector 0.13.1
* `echo hello > /tmp/logs/foo.log`
* Observe Vector picking up the file and outputting the line
* Stop Vector 0.13.1
* Start Vector 0.14.0
* Observe that it thinks `foo.log` is new and outputs the same line
