### ISSUE TITLE
input net bandwidth > output net bandwidth causes vector OOM

### ISSUE THREAD

**Issue by AntonSmolkov** [timberio/vector#8238]
### Vector Version

```
vector 0.15.0 (x86_64-unknown-linux-gnu b2992c9 2021-06-30)
(Nightly)
```

### Vector Configuration File

```toml
data_dir = "/var/vector/data"


[sources.fluent_source]
  type = "fluent"
  address = "0.0.0.0:24224"


[sinks.elasticsearch-fluent]
  # General
  type = "elasticsearch" 
  inputs = ["fluent_source"] 
  compression = "none" # optional,
  endpoint = "http://10.1.0.9:9200/" 
  index = "{{ viaq_index_name }}-%Y-%m-%d"
  healthcheck.enabled = true 
```

### Debug Output

https://gist.github.com/AntonSmolkov/10a10cb1749d16418f71419f31cc6209
### Expected Behavior
Fluent source does not cause OOM

### Actual Behavior
Fluent source causes OOM. Vector eats all machines memory (8GiB in my case)

```
[Mon Jul 12 13:10:23 2021] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/system.slice/vector.service,task=vector,pid=1082674,uid=1001
[Mon Jul 12 13:10:23 2021] Out of memory: Killed process 1082674 (vector) total-vm:7494848kB, anon-rss:6939664kB, file-rss:0kB, shmem-rss:0kB, UID:1001 pgtables:14032kB oom_score_adj:0
[Mon Jul 12 13:10:23 2021] oom_reaper: reaped process 1082674 (vector), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```
### Additional Context
~200 logs/per sec from OpenShift.  

Vector is located on Azure - Standard_D2_v3 instance with 1GiB/sec outbound traffic limit. Inbound traffic is unlimited and effectevely is 40GiB/sec(link speed)

Fluentd under the same circumstances works fine and consumes only 1.5 GiB of RAM.

**Comment by StephenWakely** [comment]
I'm struggling to reproduce this one.

I have fluent configured to send to Vector with:

```
<match *>
  @type forward
  <server>
        name  local
        host  127.0.0.1
        port 7474
  </server>
  compress gzip
</match>
```

Vector:

```toml
[api]
    enabled = true

[sources.fluent]
    type = "fluent"
    address = "0.0.0.0:7474"

[sinks.elastic]
    inputs = ["fluent"]
    type = "elasticsearch" 
    compression = "none" # optional,
    endpoint = "http://localhost:9200/" 
    index = "zork-%Y-%m-%d"
    healthcheck.enabled = true 

[sinks.out]
    inputs = ["fluent"]
    type = "console"
    encoding = "text"
```

Then sending data to fluent using `flog`:

```
flog -l | xargs -I % curl -X POST -d 'json={"message":"%"}' http://localhost:8888/nork 
```

Memory usage stays consistently low:

```
$ ps -p $(pgrep vector) -o %cpu,%mem,cmd
%CPU %MEM CMD
 0.5  0.1 ./bin/vector -c fluent.toml
```

Running `vector 0.15.0 (x86_64-unknown-linux-gnu 23b6c9e 2021-07-13)`

@AntonSmolkov do you have any other info that might be useful to help track this down? What fluent settings are you using to send to Vector? What is the shape of the data being sent? What is ` viaq_index_name`?

**Comment by AntonSmolkov** [comment]
Hi, @StephenWakely  
Shape of the data - [OpenShift logs](https://docs.openshift.com/container-platform/4.6/logging/cluster-logging-external.html#cluster-logging-collector-log-forward-fluentd_cluster-logging-external) (very similar to k8s logs). viaq_index_name - is the kind of the logs (infrastructure/application/audit). 

I have it 100% reproducible, so can make gcore dump if it helps or even configure log forwarding to you instance, if you give me public endpoint.

**Comment by jszwedko** [comment]
@AntonSmolkov we're still trying to reproduce this locally, but we may take you up on the offer to forward logs. Just to confirm, how long does it take you to see the runaway memory growth?

**Comment by AntonSmolkov** [comment]
@jszwedko not fast, ~10-15 minutes

**Comment by jszwedko** [comment]
@AntonSmolkov thanks for the info! Could you provide some more details that might help us reproduce:

* OpenShift version
* fluentd version
* Elasticsearch version

Could you also try running `vector` with debug logs enabled (`-vv`) and paste those here? Are events still processed by Vector while this is happening? Or do they halt?

**Comment by jszwedko** [comment]
Ah, nvm on the logs, I see you included some already.

**Comment by AntonSmolkov** [comment]
- Elasticsearch version: 7.1.12
- OpenShift Version: OKD 4.6.0-0.okd-2021-02-14-205305, 3 masters, 3 workers
- Fluentd version: OpenShift Logging Operator 4.6 (fluentd 1.7.4 on nodes)

All nodes are: Azure Standard D4s v3 (4 vcpus, 16 GiB memory)

BUT, it became flaky at my side too. Could only reproduce it once yesterday =(

**Comment by StephenWakely** [comment]
@AntonSmolkov I'll look into setting up a public endpoint for you to send the logs to if that is ok with you. I just need to prepare an instance of Vector with extra logging so we can hopefully see what the difference is between the data you are sending that is causing the memory issues.  Hopefully that will help track it down.

I'll liase with you using the email you have on your profile once it is set up.

**Comment by AntonSmolkov** [comment]
@StephenWakely ok, will be waiting for the e-mail.

BTW. Another weird stuff i noticed that might be related - many of CLOSE_WAIT connections to 24224 port. Even had to increase `ulimit -n`

**Comment by AntonSmolkov** [comment]
Ok. It is easilly to catch again.
![image](https://user-images.githubusercontent.com/5318028/125934902-fdfd82e8-12a6-484a-ada5-fe83dfb4fe52.png)
Red squares - OpenShift nodes public IPs (6 nodes)
10.1.0.8 - Vector machine (current machie on screenshot )
10.1.0.9 - LoadBalanced in front of the ElasticSearch nodes
10.1.0.5-7 - Elasticsearch nodes without LB (probably found by sniffing).

I think log flow must be big enought to cause the issue. 
On the screenshot we can see ~200-300Mib/sec inbound flow and only 70Mb/sec outbound flow.
(The cause of the big amount of log is receiving side(vector) being disabled since yesterday)

**Comment by StephenWakely** [comment]
Yes, I can confirm that I can reproduce the OOM by throttling the network connection between Vector and Elasticsearch. What is the reason for the difference in throughput? Is there a way you can increase the bandwidth to Elasticsearch?

**Comment by AntonSmolkov** [comment]
Oh, this is how MS Azure works. All VM types have bandwith limit, but this limit applies only for outbound traffic. 
> The network bandwidth allocated to each virtual machine **is metered on egress (outbound)** traffic from the virtual machine. All network traffic leaving the virtual machine is counted toward the allocated limit, regardless of destination. For example, if a virtual machine has a 1,000 Mbps limit, that limit applies whether the outbound traffic is destined for another virtual machine in the same virtual network, or outside of Azure.

>**Ingress is not metered or limited directly.** However, there are other factors, such as CPU and storage limits, which can impact a virtual machine’s ability to process incoming data.

[source](https://docs.microsoft.com/en-us/azure/virtual-network/virtual-machine-network-throughput)
For vector i have Standard_D2_v3 instance with 1GiB/sec outbound traffic limit. Inbound traffic is unlimited and effectevely is 40GiB/sec(link speed)

**Comment by AntonSmolkov** [comment]
This is, probably, not fluent-source specific issue. Should i rename the header?

**Comment by StephenWakely** [comment]
> Should i rename the header?

Good idea. Thanks.

**Comment by StephenWakely** [comment]
Testing this with a socket source also shows the same problem.

**Comment by StephenWakely** [comment]
Related #6961

**Comment by AntonSmolkov** [comment]
FYI - Buffer enabling on ElasticSearch sink doesn't help at   :(
```
  buffer.type = "disk"
  buffer.max_size = 2000000000
```

**Comment by AntonSmolkov** [comment]
I limeted both sides of connections manually (with wondershaper) to 1 Gib/sec and still have the issue.
Are you sure that asymmetric bandwidth is the reason?
![image](https://user-images.githubusercontent.com/5318028/126488429-a3c55d22-3c27-43a8-981d-8e7bce749540.png)
FluentD under exact same circumstances works fine and consumes only ~ 1.3 GiB of memory.

Just in case, DamonSet which gives me ability to reproduce the issue easily:
<details>
  <summary>Click to expand!</summary>

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: log-flooder
spec:
  selector:
    matchLabels:
      name: log-flooder
  template:
    metadata:
      labels:
        name: log-flooder
    spec:
      tolerations:
      # this toleration is to have the daemonset runnable on master nodes
      # remove it if your masters can't run pods
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: log-flooder
        image: bash
        args:
          - "-c"
          - 'while true; do echo \"looooong log looooong log looooong log looooong log looooong log looooong log looooong log looooong log looooong log looooong log looooong log looooong log looooong log looooong log looooong log looooong log looooong log looooong log looooong log looooong log looooong log looooong log looooong log looooong log looooong log\" ; done'
        resources:
          limits:
            memory: 200Mi
            cpu: 100m
          requests:
            cpu: 100m
            memory: 200Mi
```

</details>
(Assuming that stdout is being collected by fluentd/fluentbit on k8s nodes and sent to the Vector)

**Comment by AntonSmolkov** [comment]
Another more interseting observation - If i chain Fluentd with Vector the issue is not reproducing.
So:
6 hosts => Vector => ElasticSearch  --  **OOM.**
6 hosts => Fluentd => Vector => ElasticSearch   --  **Everything is FINE.** 

I guess, the pinpoint of the issue in the number of incoming hosts, and this might be somehow related to big number of CLOSE_WAIT connections mentioned above.

@StephenWakely Have a look please

**Comment by jszwedko** [comment]
I believe I reproduced this with a simplified config:

```toml
[sources.source0]
address = "0.0.0.0:24224"
type = "fluent"

[sinks.sink0]
inputs = ["source0"]
print_amount = 1000
type = "blackhole"
rate = 1000
```

This artificially restricts throughput at the sink to 1000 events/s by setting `rate = 1000`.

I then used fluentd 1.7.4 with:

```
<source>
  @type exec
  command flog -f json -l

  <parse>
    @type json
  </parse>

  tag json
</source>

<match *>
  @type forward
  send_timeout 60s
  recover_wait 10s
  hard_timeout 60s

  <server>
    name myserver1
    host localhost
    port 24224
    weight 60
  </server>
</match>
```

This has fluentd run https://github.com/mingrammer/flog to generate logs and push them to Vector.

With this setup, I observed memory use in Vector pretty quickly rising which seems to point to the back-pressure not propagating correctly. I'm looking more now.

**Comment by jszwedko** [comment]
The issue seems to me to be that `fluentd` is opening new connections frequently to send events rather than using a single TCP connection. Vector will accept new TCP connections, even in the presence of back pressure, and read events off of the stream, but block internally when it attempts to push them to the next component; holding the connection open.

After letting this setup run for a minute I saw

```
lsof -p 3561919 | grep CLOSE_WAIT | wc -l
111
```

111 pending connections in `CLOSE_WAIT`. Vector reported that it had accepted 435 connections over its lifetime.

The solution to this issue of not propagating back-pressure to senders seems similar to the lack of effective back-pressure to HTTP-based sources, #7186, where, at some point, we'd like to stop accepting new connections if we cannot send quickly enough. I opened https://github.com/timberio/vector/issues/8596 to track this.

I think this situation would only be exacerbated by higher numbers of senders (6 as mentioned here).

Does this make sense to you @AntonSmolkov ? Essentially Vector couldn't process the data fast enough, but Fluentd kept opening new TCP connections to send it more.

You could likely achieve higher throughput through the `elasticsearch` sink with the following settings:

```
request.concurrency = "adaptive"
request.rate_limit_num = "100000" # some very high number
```

This will cause Vector to use its adaptive concurrency algorithm to configure the number of in-flight requests to Elasticsearch.

> Another more interseting observation - If i chain Fluentd with Vector the issue is not reproducing.

I'm guessing this ended up limiting the number of open connections to Vector.

**Comment by jszwedko** [comment]
This is also somewhat exacerbated for the `fluent` source specifically as decoding of each frame happens all at once. For the `CompressedForward` fluent frame, this can result in a lot of memory use since it is read all-at-once. In my testing, each one of those frames would include ~30000 events, each ~300 bytes, which would be ~10 MB being read at once.

We could improve that situation for `PackedForward` and `CompressedForward` fluent frames by only reading one event at a time and attempting to push that before reading the next. This would result in less memory use per-connection in the presence of back-pressure. This would require a bit of a re-architecture of the source to hold onto more state. I opened https://github.com/timberio/vector/issues/8597 to track this.

**Comment by StephenWakely** [comment]
Noting down the steps needed to repro this.

Running `vector 0.16.0 (x86_64-unknown-linux-gnu 49785af 2021-08-05)`. 

The issue seems to only occur on Linux and not on Mac.

1. Run ElasticSearch on a separate machine on the local network. It might be relevant that the machine I am running ES on is pretty low powered, 4gb memory.
2. Run Vector with this config:

```toml
[api]
    enabled = true

[sources.fluent]
    type = "fluent"
    address = "0.0.0.0:24224"

[sinks.elastic]
   inputs = ["fluent"]
   type = "elasticsearch"
   compression = "none"
   endpoint = "http://192.168.0.3:9200/"
   index = "nong-%Y-%m-%d"
   healthcheck.enabled = true
```

3. Run flog in Docker using the fluentd logging driver with:

```
docker run --log-driver=fluentd --rm mingrammer/flog -l -f json
```

4. Throttle the network. I used [this](https://www.sitespeed.io/documentation/throttle/), with the command `throttle --profile 2g`.
5. Observe the memory increase.

Running Vector under valgrind with `valgrind --tool=massif --trace-children=yes ./bin/vector -c fluent.toml` produced the following trace:

[massif.zip](https://github.com/timberio/vector/files/6945018/massif.zip)

![index](https://user-images.githubusercontent.com/192679/128499812-2bc4c53d-ef9d-46ec-b822-89972f1b847a.png)
![index](https://user-images.githubusercontent.com/192679/128499866-b1332867-f89f-419c-8358-4f8e09b9376f.png)
