### ISSUE TITLE
`host_metrics` source

### ISSUE THREAD

**Issue by spencergilbert** [timberio/vector#8282]
Today in our Helm chart we pass a _complex_ set of options to the `host_metrics` source:

```toml
    [sources.host_metrics]
      type = "host_metrics"
      [sources.host_metrics.filesystem]
        [sources.host_metrics.filesystem.devices]
          excludes = ["binfmt_misc"]
        [sources.host_metrics.filesystem.filesystems]
          excludes = ["binfmt_misc"]
        [sources.host_metrics.filesystem.mountpoints]
          excludes = ["*/proc/sys/fs/binfmt_misc"]
```

After speaking with @binarylogic we believe the source should be able to handle this internally without user configuration. This reduces configuration bloat and improves the overall resilience of the source itself.
