### ISSUE TITLE
Ability to include multiple Vector configuration files

### ISSUE THREAD

**Issue by karlseguin** [timberio/vector#832]
Don't think this is currently supported, but is there any appetite for an `include` directive to include other config files? Helps organize things a little better (distinct sources -> transform -> sink flows can be in their own file).

**Comment by Jeffail** [comment]
I think we can go in one (or both) of two significantly different directions here:

## Import fields

The syntax could be very simple. Something like an array field `imports` at the root of a config file:

```toml
imports = [
    "./path/to/foo.toml",
    "./path/to/bar.toml",
    "./path/to/${ENV}.toml",
]
```

However, this syntax limits us in the future if we wanted to allow more specialized imports. If we wish to leave that door open we can instead support import tables:

```toml
[[imports]]
  path = "./path/to/foo.toml"
```

Which is a little more to write, but allows us to expand the spec later on for higher levels of import customization:

```toml
[[imports]]
  path = "./path/to/bar.toml"
  components = [
      "sinks.send_logs_to_kafka",
  ]
```

## N path args in config flag

Another possibility is to allow multiple values for the `--config` flag. Paths could also be directories, and potentially support ellipsis syntax for instructing vector to walk a directory for any `.toml` files:

```sh
vector -c "./foo.toml" -c "./and_also/${ENV}" -c "./and_also_these/..."
```

This is much more limited than using configuration parameters but is probably easier for users to pick up. It also ties nicely in with https://github.com/timberio/vector/issues/98#issuecomment-542660074 as it would complement `vector --dry-run -c ./config/examples/...`.

However, this is also very easy to go wrong for users. Allowing Vector to walk a directory for `.toml` files also sets it up nicely to gobble up all kinds of unrelated configs unbeknownst to our user.

**Comment by Jeffail** [comment]
One interesting use case I would quite like to solve would be to import config snippets multiple times with different insertion points. For example, if we have a pretty complex set of transforms for doing something that is common to us we might break it out into a snippet, e.g. `./snippets/quack_to_woof.toml`:

```toml
[transform.foo]
  type = "foo"
  inputs = ["source_quack"]

[transform.bar]
  type = "bar"
  inputs = ["foo"]

[transform.resulting_woof]
  type = "baz"
  inputs = ["bar"]
```

However, we can only import that snippet once into a root config as it has a static source `source_quack` and a static sink `resulting_woof`. What if we want to use this snippet in multiple places? Without a solution we would have to copy/paste that snippet, and if it evolves over time we would need to duplicate our effort (both writing and unit testing) across all copies of it.

Solutions to this wouldn't necessarily need to be complicated. A very simple approach would be to use environment variables within the snippet:

```toml
[transform.foo]
  type = "foo"
  inputs = ["${QUACK_SOURCE}"]

[transform.bar]
  type = "bar"
  inputs = ["foo"]

[transform.${WOOF_SINK}]
  type = "baz"
  inputs = ["bar"]
```

And if we implement the table based import syntax we can add the ability to set custom environment variables for each import:

```toml
[sources.foo_source]
  type = "file"
  include = ["/var/log/nginx/*.log"]

[[import]]
  path = "./snippets/quack_to_woof.toml"
  [import.environment]
    QUACK_SOURCE = "foo_source"
    WOOF_SINK = "woofs"
    
[sinks.bar_sink]
  type = "console"
  inputs = ["woofs"]
  target = "stdout"
```
