### ISSUE TITLE
Add a field mapping transformer

### ISSUE THREAD

**Issue by xcaptain** [timberio/vector#851]
A raw log may contain many fields but at last we may only care some of them and want them to have a different name, For example, a transformer produces log like

```json
{
    "a": 1,
    "c": "some non-sence data"
}
```

we may want to rename field `a` to `b` and remove field `c` and get a result like

```json
{
    "b": 1
}
```

currently the `add_fields` and `remove_fields` transformer can not achieve this goal.

**Comment by lukesteensen** [comment]
Thanks for opening this @xcaptain! You're right that there is a gap in those transforms around renaming fields.

This is a good example of a situation where I'd recommend using the lua transform. Here's the equivalent of your example config:

```toml
[transforms.map_fields]
  type = "lua"
  inputs = ["transform_timestamp"]
  source = """
event["http_status"] = event["status"]
"""

[sinks.my_sink1]
  type = "console"
  inputs = ["map_fields"]
  target = "stdout"
  encoding = "json"

[sinks.my_sink2]
  type = "console"
  inputs = ["transform_timestamp"]
  target = "stdout"
  encoding = "json"
```

If you want to remove the old `status` field, you can add `event["status"] = nil`.

We are also in the process of planning a more general transform that will consolidate adding, removing, renaming, coercing, etc into a single more powerful transform (see #750).
