### ISSUE TITLE
[vector-aggregator] Helm configs for AWS auth should be stored in k8s secret

### ISSUE THREAD

**Issue by namm2** [timberio/vector#8522]
### Current Vector Version

```
0.15.1
```

### Use-cases

Install vector-aggregator Helm chart on k8s cluster with AWS S3 configs (https://vector.dev/docs/reference/configuration/sources/aws_s3/)

Helm values:
```
customConfig:
  datadir: "/var/lib/vector"
  sources:
    s3-logs:
      type: aws_s3
      auth:
        access_key_id: ABCXYZEXAMPLE
        secret_access_key: xyzabcexample
      strategy: sqs
      compression: auto
...
```

Helm template results:
```
---
# Source: vector-aggregator/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-alb-vector-aggregator
  labels:
    helm.sh/chart: vector-aggregator-0.0.0
    app.kubernetes.io/name: vector-aggregator
    app.kubernetes.io/instance: vector-alb
    app.kubernetes.io/version: "0.0.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: vector-aggregator
data:
  vector.yaml: |
    datadir: /var/lib/vector
    sinks:
      logbackend:
        encoding: null
        endpoint: elk-client.elasticsearch.svc:9200
        index: vector-%F
        inputs:
        - s3-alb-logs
        mode: normal
        pipeline: es
        type: elasticsearch
    sources:
      s3-alb-logs:
        auth:
          access_key_id: ABCXYZEXAMPLE
          secret_access_key: xyzabcexample
        compression: auto

```

This is because vector include all `customConfig` block into a configmap, but it'll leak plaintext credentials if one uses AWS  IAM secret key.

### Proposal

Create k8s secret for AWS credentials and reference to it

**Comment by spencergilbert** [comment]
We can definitely look at allowing users to create secret resources as part of the `helm install` (which does begin to entertain gotchas if users are relying on GitOps workflows...).

You can securely configure that source today with the `env` key like so (and remove the options from `customConfig` block):

```yaml
env:
  - name: AWS_ACCESS_KEY_ID
     valueFrom:
       secretKeyRef:
         name: existing-secret
         key: access_key_id
  - name: AWS_SECRET_ACCESS_KEY
     valueFrom:
       secretKeyRef:
         name: existing-secret
         key: secret_access_key
```

**Comment by namm2** [comment]
Thanks for the response, I think an opt-in to create secret in helm won't hurt anybody though (for instance, we encrypt sensitive values before every git commit), and I'd like to avoid manually create resources outside of helm install/upgrade pipeline.

**Comment by spencergilbert** [comment]
Agreed! Having the option is definitely a nice to have 😄

**Comment by spencergilbert** [comment]
Hey @namm2 would something like this satisfy your needs?

```yaml
{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "libvector.fullname" . }}
  labels:
    {{- include "libvector.labels" . | nindent 4 }}
type: Opaque
data:
  awsAccessKeyId: {{ default "MISSING" .Values.secrets.aws.accessKeyId | b64enc | quote }}
  awsAccessKeyId: {{ default "MISSING" .Values.secrets.aws.secretAccessKey | b64enc | quote }}
{{- end }}
```
```yaml
secrets:
  aws:
    accessKeyId: ""
    secretAccessKey: ""
```
