### ISSUE TITLE
High memory use when starting Vector with a large disk buffer

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#8532]
Reported by user in Slack.

They are running `vector 0.14.0 (x86_64-unknown-linux-gnu 5f3a319 2021-06-03)`. I tested with that and `vector 0.15.1 (x86_64-unknown-linux-gnu c5e4732 2021-07-27)` and the appear to have the same behavior. The massif profile below was with 0.15.1.

I was able to reproduce via the following.

Run:

```
$ log -l -f json | vector --config /tmp/tmp.toml
```

With the following config:

```toml
data_dir = "/tmp/vector"

[sources.source0]
max_length = 102400
type = "stdin"

[transforms.remap]
type = "remap"
inputs = ["source0"]
source = """
. |= object!(parse_json!(.message))
"""

[sinks.sink0]
inputs = ["remap"]
type = "http"
uri = "https://10.22.212.22:9000/endpoint"
buffer.max_events = 1000000
# 11Gb
buffer.max_size = 11000000000
buffer.type = "disk"

[sinks.sink0.encoding]
codec = "ndjson"
```

This will cause Vector to buffer up data since the endpoint is unreachable. I ran it like this until it buffered ~9 GB (checking via `du -h -d /tmp/vector/sink0_buffer`.

I then stopped Vector, and rerean it with a working config:

```toml
data_dir = "/tmp/vector"

[sources.source0]
max_length = 102400
type = "stdin"

[transforms.remap]
type = "remap"
inputs = ["source0"]
source = """
. |= object!(parse_json!(.message))
"""

[sinks.sink0]
inputs = ["remap"]
type = "aws_s3"
bucket = "timberio-jesse-test"
region = "us-east-1"
key_prefix = "klarna/{{ host }}"
filename_append_uuid = false
batch.max_bytes = 10000000
batch.max_events = 1000000
buffer.max_events = 1000000
# 11Gb
buffer.max_size = 11000000000
buffer.type = "disk"

[sinks.sink0.encoding]
codec = "ndjson"
```

This swaps the bad `http` sink for a functioning `aws_s3` sink.

I observed Vector seemed to read the entire disk buffer into memory, peaking at around 11 GB of memory use, before it actually started sending data to the sink.

Notably the same behavior seems to occur even just rerunning with the broken HTTP sink so it doesn't _seem_ sink specific.

This is the massif profile from the run using the `aws_s3` sink (txt extension to allow me to upload it to Github): 
[massif.out.3006388.txt](https://github.com/timberio/vector/files/6909816/massif.out.3006388.txt)

Graphed:

![Screenshot from 2021-07-30 12-47-00](https://user-images.githubusercontent.com/316880/127706712-0034d6c4-c8dc-423a-915c-0eef5e56b739.png)

I did verify that this isn't leveldb mmapping files (which shouldn't show up in massif anyway; or at least it didn't when we were analyzing that behavior before). It, as expected, only had 10 files mmap'd at a time.
