### ISSUE TITLE
Problem with connecting prometheus in v0.3

### ISSUE THREAD

**Issue by romvarac** [timberio/vector#855]
Hi Team, I try to connect sinks prometheus in document v.03 but not work. May be in v.03 not using sinks promethes ???
1. vector.toml in https://docs.vector.dev/v/v0.3/usage/configuration/sinks/prometheus. 
```
[sinks.out]
      inputs = [<source-id>]
      type = "prometheus"
      address = "0.0.0.0:9090"

      [sinks.<source-id>.buffer]
        type = "disk"
        max_size = 100000000
```
Error: vector::topology: Configuration error: missing field `when_full` for key `sinks.out.buffer`
2. Changed config 
```
[sinks.out]
      inputs = [<source-id>]
      type = "prometheus"
      address = "0.0.0.0:9090"

      [sinks.<source-id>.buffer]
        type = "disk"
        max_size = 100000000

       when_full = "block"
       num_items = 500
```
ERROR vector::topology: Configuration error: Sink "out": Must set data_dir to use on-disk buffering.
ERROR vector::topology: Configuration error: Data type mismatch between in (Log) and out (Metric)

I try to by pass, but empty log_to_metric in doc (https://docs.vector.dev/v/v0.3/usage/configuration/transforms/log_to_metric).

**Comment by loony-bean** [comment]
Oh, got it. I missed the fact you are using 0.3. Yes, these modules received many updates recently, and I'd recommend using nightly or waiting for 0.4.

**Comment by binarylogic** [comment]
I'm assigning this to myself since it is related to the release process I'm working on.

**Comment by romvarac** [comment]
Hi @loony-bean, I try to deploy the new version release (0.4.0)
1. vector.toml
```
[sources.in]
    type = "stdin"

[sinks.out]
    inputs = ["in"]
    type = "console
```
2. docker-compose.yml
```
version: "3.7"

services:
  vector:
    image: timberio/vector:0.4.0-alpine
    volumes: 
      - ${PWD}/vector.toml:/vector/config/vector.toml:ro
    command: 
      - --config=/vector/config/vector.toml
```
Error
```
- ERROR log: Configuration error: unknown variant `stdin`, there are no variants for key `sources.in.type`  log.target="vector" log.module_path="vector" log.file="src/main.rs" log.line=299
- ERROR vector: Configuration error: unknown variant `stdin`, there are no variants for key `sources.in.type`
```
3. Using 0.4.0-debian
- docker-compose.yml in the above
```
ERROR: for vector_vector_1  Cannot start service vector: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"--config=/vector/config/vector.toml\": stat --config=/vector/config/vector.toml: no such file or directory": unknown

ERROR: for vector  Cannot start service vector: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"--config=/vector/config/vector.toml\": stat --config=/vector/config/vector.toml: no such file or directory": unknown
ERROR: Encountered errors while bringing up the project.
```
- comment out command in docker-compose.ym
```
version: "3.7"

services:
  vector:
    image: timberio/vector:0.4.0-debian
    volumes: 
      - ${PWD}/vector.toml:/vector/config/vector.toml:ro
    # command: 
    #   - --config=/vector/config/vector.toml
```
Check log don't show any thing. So, how I can run new version release (0.4.0). Thanks
