### ISSUE TITLE
AWS IRSA enabled for aws_s3 source?

### ISSUE THREAD

**Issue by namm2** [timberio/vector#8566]
### Current Vector Version

```
0.15.1
```

### Use-cases

Hi I'd like to use AWS IAM role for kubernetes service account (https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) instead of generating IAM secrets, but couldn't find it anywhere in the docs yet. Is it possible to use it with vector-aggregator? 

For example, on vector-generator Helm chart I can set annotation to the IAM role ARN like this:
```
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::111111111111:role/NAME"
```

I found there's a similar config here: https://github.com/timberio/vector/issues/8019#issuecomment-868640346 but when I actually  try it, vector results in errors related to permissions:

```vector::internal_events::aws_s3::source: Failed to fetch SQS events. error=Request ID: Some("527ccabc-e8d9-5509-b42f-933e1a3989c8") Body: <?xml version="1.0"?><ErrorResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/"><Error><Type>Sender</Type><Code>AccessDenied</Code><Message>Access to the resource https://sqs.eu-central-1.amazonaws.com/ is denied.</Message><Detail/></Error><RequestId>527ccabc-e8d9-5509-b42f-933e1a3989c8</RequestId></ErrorResponse>```

### Proposal

Have vector's kubernetes service account to use AWS IRSA with aws_s3 source.

**Comment by spencergilbert** [comment]
Have you gone through the three steps described in your first link? Once the infrastructure on the AWS side is configured there shouldn't be anything aside from the `annotation` on the ServiceAccount

**Comment by namm2** [comment]
Yes, of course this is not the first time I setup IRSA. I asked because checking the IAM role it shows

> **Last activity** Not accessed in the tracking period

That means the role wasn't assumed even once.

**Comment by spencergilbert** [comment]
Mind sharing a more complete example of the setup+config you're using, happy to dig into it to try and see what the issue may be.

**Comment by namm2** [comment]
This is the TF configs for IAM role

```hcl
data "aws_iam_policy_document" "vector" {
  statement {
    actions = [
      "s3:GetObject",
    ]
    resources = [
      "arn:aws:s3:::${var.s3_bucket_name}/*"
    ]
  }

  statement {
    actions = [
      "sqs:ReceiveMessage",
      "sqs:DeleteMessage",
    ]
    resources = [
      "arn:aws:sqs:*:${var.aws_account_id}:${var.queue_name}"
    ]
  }
}

data "aws_iam_policy_document" "vector_trust_relationship" {
  statement {
    actions = ["sts:AssumeRole"]

    principals {
      type        = "Service"
      identifiers = ["ec2.amazonaws.com"]
    }
  }

  statement {
    principals {
      type        = "Federated"
      identifiers = [var.openid_connect_provider_arn]
    }
    actions = [
      "sts:AssumeRoleWithWebIdentity"
    ]
    condition {
      test     = "StringEquals"
      variable = "${var.openid_connect_provider_url}:sub"
      values   = ["system:serviceaccount:${var.kubernetes_namespace}:${var.kubernetes_serviceaccount}"]
    }
  }
}

resource "aws_iam_role" "vector" {
  name               = "VectorRole"
  assume_role_policy = data.aws_iam_policy_document.vector_trust_relationship.json
}

resource "aws_iam_user_policy" "vector" {
  name   = "vector-user-policy"
  user   = aws_iam_user.vector.name
  policy = data.aws_iam_policy_document.vector.json
}
```

Vector Helm values
```yaml
# vector-aggregator:
image:
  version: "0.15.1"

tolerations: []

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::111111111111:role/VectorRole"

customConfig:
  sources:
    s3-alb-logs:
      type: aws_s3
      strategy: sqs
      compression: auto
      region: eu-central-1
      sqs:
        delete_message: true
        queue_url: https://sqs.eu-central-1.amazonaws.com/111111111111/s3_queue
```

**Comment by spencergilbert** [comment]
Thanks! I'll find some time today to try and figure out what's happening

**Comment by spencergilbert** [comment]
🤔 still trying to figure out if I've messed up my infra setup or if it's the same thing...

I wonder if adjusting `4.` [here](https://vector.dev/docs/reference/configuration/sources/aws_s3/#aws-authentication) may help?

**Comment by namm2** [comment]
I think those ENV Vars are useful for appliction to directly access AWS IAM authentication. I'm not a Rust user, so I can only find this part in rusoto module: https://github.com/timberio/vector/blob/master/src/rusoto/mod.rs#L54-L72

**Comment by spencergilbert** [comment]
So Vector was able to access my S3 bucket and SQS queue with the following annotation/config using `eksctl` to create the cluster (with oidc provider), and role - so it seems like there's an issue with the infra/tf side of things in the environment. 

```yaml
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<...>:role/eksctl-<cluster-name>-addon-ia-....
customConfig:
  sources:
    s3_logs:
      type: aws_s3
      region: us-east-2
      sqs:
        poll_secs: 15
        visibility_timeout_secs: 300
        delete_message: false
        queue_url: https://sqs.us-east-2.amazonaws.com/.../<queue>
  sinks:
    stdout:
      type: console
      inputs: [s3_logs]
      encoding: json
```
