### ISSUE TITLE
How do I add fixed attributes to the expanded array?

### ISSUE THREAD

**Issue by PanHywel** [timberio/vector#8642]
How do I add fixed attributes to the expanded array

### Vector Version

vector 0.15.0

```toml
[sources.httpSources]
type = "http"
address = "172.16.1.41:7001"
path = "/client-lua"
encoding = "json"
headers = ["x-forwarded-for"]


[transforms.parse_logs]
type = "remap"
inputs = ["httpSources"]
source = '''
. = .msg
.clientIp = .x-forwarded-for
'''


[sinks.print]
 type = "console"
 inputs = ["parse_logs"]
 encoding.codec = "json"
```

```json
{
   "x-forwarded-for":"192.168.1.1",
   "msg":[
     {
       "name":"tom"
     },
     {
       "name":"mimi"
     }
  ]
}

```
I hope to get：
```json
{
  "clientIp":"192.168.1.1",
  "name":"tom"
},
{
  "clientIp":"192.168.1.1",
  "name":"mimi"
}

```
