### ISSUE TITLE
Disk buffer fails to flush correctly

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#8650]
I seem to have managed to create a situation where the Vector fails to properly ack the disk buffer. This appears to be due an overflow error when subtracting. In release builds, this seems to result in Vector simply not deleting the processed events from the disk buffer due to silently overflowing, but when I ran a debug build, I was able to see the invalid subtraction:

```
thread 'vector-worker' panicked at 'attempt to subtract with overflow', /Users/jesse.szwedko/workspace/vector/lib/vector-core/buffers/src/disk/leveldb_buffer/reader.rs:172:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

However when I tried again, I'm now seeing:

```
thread 'vector-worker' panicked at 'Tried to ack beyond read offset', /Users/jesse.szwedko/workspace/vector/lib/vector-core/buffers/src/disk/leveldb_buffer/reader.rs:194:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I'm imagining these might be related.

The config:

```toml
data_dir = "/tmp/vector2/"

[sources.stdin]
type = "stdin"

[transforms.remap]
type = "remap"
inputs = ["stdin"]
source = """
. = object!(parse_json!(.message))
"""

[sinks.blackhole]
type = "console"
inputs = ["remap"]
encoding.codec = "json"
buffer.type = "disk"
buffer.max_size = 50000
buffer.when_full = "block"
```

The data directory: 
[vector2.tar.gz](https://github.com/timberio/vector/files/6964911/vector2.tar.gz)

I was building off of ab94fd61b.
