### ISSUE TITLE
I compile executable files locally,start error

### ISSUE THREAD

**Issue by fujianan** [timberio/vector#869]
![image](https://user-images.githubusercontent.com/22000011/64948086-e1729900-d8a8-11e9-8771-7514d293666f.png)

![image](https://user-images.githubusercontent.com/22000011/64947893-82ad1f80-d8a8-11e9-87e7-c38b128fb1c9.png)
this is my vector.toml configuration:
```
data_dir = "/var/lib/vector"
[sources.apache_logs]
  type         = "file"
  include      = ["/var/log/apache2/*.log"]
[sources.kafka_source]
  type = "kafka"
  bootstrap_servers = "10.14.22.123:9092,10.14.23.332:9092"
  group_id = "consumer-group-name"
  topics = ["topic-1", "topic-2", "topic-3"]
  auto_offset_reset = "largest"
  key_field = "user_id"
  session_timeout_ms = 5000
[transforms.apache_parser]
  inputs       = ["apache_logs"]
  type         = "regex_parser"
  regex        = '^(?P<host>[w.]+) - (?P<user>[w]+) (?P<bytes_in>[d]+) [(?P<timestamp>.*)] "(?P<method>[w]+) (?P<path>.*)" (?P<status>[d]+) (?P<bytes_out>[d]+)$'
[sinks.print]
  type         = "console"
```

**Comment by binarylogic** [comment]
Hi @fujianan you need to add an `inputs` field for your `[sinks.print]` sink. Ex:

```toml
[transforms.apache_parser]
  inputs       = ["apache_logs"]
  type         = "regex_parser"
  regex        = '^(?P<host>[w.]+) - (?P<user>[w]+) (?P<bytes_in>[d]+) [(?P<timestamp>.*)] "(?P<method>[w]+) (?P<path>.*)" (?P<status>[d]+) (?P<bytes_out>[d]+)$'
[sinks.print]
  inputs      = ["apache_parser"]
  type         = "console"
```

That should resolve your issue. Let us know if you encounter anything else.
