### ISSUE TITLE
loki sink does not work for Grafana Cloud when endpoint does not have /loki/...

### ISSUE THREAD

**Issue by tesharp** [timberio/vector#8702]
### Vector Version

```
0.15.2 (and nightly)
```

### Vector Configuration File

```toml
[sinks.loki]
type = "loki"
inputs = ["varlogs"]
encoding.codec = "json"
endpoint = "https://logs-prod-eu-west-0.grafana.net"
auth.strategy = "basic"
auth.user = "****"
auth.password = "****"
healthcheck.enabled = false

  [sinks.loki.labels]
  "*" = "vector"
```

### Expected Behavior

Logs to be uploaded to Grafana Cloud Loki instance. Used the nightly build to support http proxy.

### Actual Behavior

Getting error:

```
Response failed. response=Response { status: 400, version: HTTP/1.1, headers: {"content-type": "text/plain; charset=utf-8", "x-content-type-options": "nosniff", "date": "Fri, 13 Aug 2021 11:07:12 GMT", "content-length": "58", "via": "1.1 google", "alt-svc": "clear"}, body: b"1:2: parse error: unexpected character inside braces: '*'\n" }
```

### Additional Context

When looking at endpoint Grafana Cloud expect loki to receive logs at it is `https://logs-prod-eu-west-0.grafana.net/api/prom/push`, and not `https://logs-prod-eu-west-0.grafana.net/loki/api/prom/push`. Seems like the code is appending `/loki/api/prom/push` to the endpoint url, which does not work in this case.

Maybe need a way to either override the url segment it is adding (/loki/...) or be able to set full url.
