### ISSUE TITLE
`file` source does not report `events_in_total` without `file` tag

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#8713]
It appears that the `file` source is only reporting `events_in_total` with the `file` tag but not an overall count:

```
vector 0.15.0 (x86_64-apple-darwin 994d812 2021-07-16)
```

```toml
data_dir = "/tmp/vector/"

[sources.file]
type = "file"
include = ["/tmp/logs/*.log"]

[sinks.console]
inputs = ["file"]
target = "stdout"
type = "console"
encoding.codec = "json"

[sources.internal_metrics]
scrape_interval_secs = 2
type = "internal_metrics"

[sinks.sink0]
type = "prometheus_exporter"
inputs = ["internal_metrics"]
address = "0.0.0.0:9598"
```

I then created a file with 10 lines:

```
log | head -n 10  > /tmp/logs/9.log
```

And curl'd the metrics:

```
➜  vector git:(master) curl -s localhost:9598/metrics | grep events_in_total
# HELP vector_events_in_total events_in_total
# TYPE vector_events_in_total counter
vector_events_in_total{component_kind="sink",component_name="console",component_type="console",host="COMP-C02DV25MML87"} 10 1628878196694
vector_events_in_total{component_kind="source",component_name="internal_metrics",component_type="internal_metrics",host="COMP-C02DV25MML87"} 0 1628878196694
vector_events_in_total{component_kind="source",component_name="file",component_type="file",host="COMP-C02DV25MML87"} 0 1628878196694
vector_events_in_total{component_kind="source",component_name="file",component_type="file",file="/tmp/logs/9.log",host="COMP-C02DV25MML87"} 10 1628878196694
vector_events_in_total{component_kind="sink",component_name="sink0",component_type="prometheus_exporter",host="COMP-C02DV25MML87"} 3472 1628878196694
```

Here we can see that `vector_events_in_total` with the `file` tag has the correct 10 events, but the `vector_events_in_total` without any `file` key is 0.
