### ISSUE TITLE
Segfault in Kafka source (rd_kafka_toppar_set_fetch_state)

### ISSUE THREAD

**Issue by fpytloun** [timberio/vector#8750]
### Vector Version

```
0.15.1-debian Docker image
```

### Vector Configuration File

```toml
    [sources.in_kafka_access]
      type = "kafka"
      bootstrap_servers = "kafka-0:9093"
      group_id = "vector_access"
      topics = ["^fluentd.(log)_.*$"]
      librdkafka_options."client.id" = "${HOSTNAME}.region1"
      librdkafka_options."client.rack" = "region1"
      librdkafka_options."group.instance.id" = "${HOSTNAME}.region1"
      # Prefer roundrobin balancing to spread load more evenly
      librdkafka_options."partition.assignment.strategy" = "roundrobin,range"
      topic_key = "_topic"
      partition_key = "_partition"
      offset_key = "_offset"

      tls.enabled = true
      tls.ca_file = "/secrets/identity/server_ca.crt"
      tls.crt_file = "/secrets/identity/client.crt"
      tls.key_file = "/secrets/identity/client.key"
```

Kafka is deployed in two regions (3 nodes per region). there's 120+ topics total (400+ partitions). Nothing useful in Kafka logs, just information that consumer failed and was removed from group.

### Debug Output

```
*** /cargo/registry/src/github.com-1ecc6299db9ec823/rdkafka-sys-4.0.0+1.6.1/librdkafka/src/rdkafka_partition.c:346:rd_kafka_toppar_set_fetch_state: assert: thrd_is_current(rktp->rktp_rkt->rkt_rk->rk_thread) ***
```

Debug output nor RUST_BACKTRACE gives no additional info :-(

### Actual Behavior

```
*** /cargo/registry/src/github.com-1ecc6299db9ec823/rdkafka-sys-4.0.0+1.6.1/librdkafka/src/rdkafka_partition.c:346:rd_kafka_toppar_set_fetch_state: assert: thrd_is_current(rktp->rktp_rkt->rkt_rk->rk_thread) ***
```
