### ISSUE TITLE
replace function is documented as infallible, but the compiler considers it faillible.

### ISSUE THREAD

**Issue by anas-aso** [timberio/vector#8772]
### Vector Version

```
vector 0.15.1 (x86_64-unknown-linux-gnu c5e4732 2021-07-27)
```

### Vector Configuration File

```yaml
transforms:
  number_duration:
      type: remap
      inputs:
        - nowhere
      source: |-
         .duration = replace(.latency, "s", "")
```

### Debug Output
I didn't run the debug command since the issue is clear
```rust
error[E103]: unhandled fallible assignment
   ┌─ :16:15
   │
16 │   .duration = replace(.latency, "s", "")
   │   ----------- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   │   │           │
   │   │           this expression is fallible
   │   │           update the expression to be infallible
   │   or change this to an infallible assignment:
   │   .duration, err = replace(.latency, "s", "")
   │
   = see documentation about error handling at https://errors.vrl.dev/#handling
   = learn more about error code 103 at https://errors.vrl.dev/103
   = see language documentation at https://vrl.dev
```

### Expected Behavior
No errors. Since the function is [documented as infallible](https://vector.dev/docs/reference/vrl/functions/#replace).
