### ISSUE TITLE
Static metadata for sources

### ISSUE THREAD

**Issue by apollo13** [timberio/vector#8809]
### Current Vector Version

```
vector 0.15.1 (x86_64-unknown-linux-gnu c5e4732 2021-07-27)
```

### Use-cases

It would be useful to be able to attach static key value pairs to sources. For instance add `logtype=auditlog` to a few file sources and `logtype=applog` to others.

### Attempted Solutions

Not much, I have no idea where to even start -- looked through all docs I could find :) Technically it would be possible to add a transform to every source and add the wanted keys there, but that seems to be quite a bit of overhead for something rather simple.

### Proposal

Could look like this:
```
---
sources:
  my_source_id:
    type: datadog_logs
    ...
    metadata:
       tag: applog
  my_source_id_2:
    type: datadog_logs
    ...
    metadata:
       tag: filelog
       
```
