### ISSUE TITLE
Global `proxy` settings appear not to apply

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#8864]
Noticed by user here: https://github.com/timberio/vector/issues/6401#issuecomment-904341117

I was able to reproduce with this config (on 7c1d91dd9):

```toml
# these do not work
[proxy]
enabled = true
http = "http://localhost:3168"
https = "http://localhost:3168"

[sources.source0]
format = "json"
type = "generator"

[sinks.sink0]
inputs = ["source0"]
type = "http"
uri = "http://localhost:8080"
encoding.codec = "json"

# these work
#proxy.enabled = true
#proxy.http = "http://localhost:3168"
#proxy.https = "http://localhost:3168"
```

Running `vector` with the above config did not use the proxy. Uncommenting the sink configuration, did use the configured proxy.

I dug into it a bit and it seems like the global proxy configuration is not being deserialized, but I couldn't see why.

We may also want to consider adding `#[serde(deny_unknown_fields)]` to the `ProxyConfig` struct. My initial attempt to reproduce was a red herring since I was using `proxy.http_proxy` instead of `proxy.http` which was silently ignored.
