### ISSUE TITLE
Can not use add_fields transform

### ISSUE THREAD

**Issue by thinhnd8752** [timberio/vector#895]
Hi all,
**add_fields** transform not work with my configuration
------------------------------------------

```
data_dir = "/var/lib/vector"

[sources.logs]
  type = "file"
  include      = ["/var/log/apps/*.log"]
  ignore_older = 86400 # 1 day

[transforms.json]
  inputs       = ["logs"]
  type   = "json_parser"
  field  = "message"

[transforms.add_host]
  inputs       = ["json"]
  type         = "add_fields"

  [transforms.add_host.fields]
    host = "${HOSTNAME}"
    
[sinks.kafka]
  type = "kafka"
  inputs = ["logs"]
  bootstrap_servers = ["10.56.239.125:9092"]
  topic = "mba-api.vector.agent"

```
------------------------------------------

But the error come:

ERROR vector::topology: Configuration error: unknown variant `add_fields`, expected one of `augmenter`, `field_filter`, `grok_parser`, `json_parser`, `log_to_metric`, `lua`, `regex_parser`, `remove_fields`, `sampler`, `tokenizer` for key `transforms.add_host`

**Comment by loony-bean** [comment]
Hi @thinhnd8752! Try using it by 'augmenter' name.

@LucioFranco Seems like we need to update the name [here](https://github.com/timberio/vector/blob/master/src/transforms/add_fields.rs#L22)? I can see in the commit history that there was intention to rename the transform, but the tag was not updated.

**Comment by LucioFranco** [comment]
@loony-bean yup looks like an oversight!

**Comment by genki** [comment]
Now this issue is happening again at v0.31.0

```
 > [3/3] RUN vector validate -d:                                                
#0 0.381 Failed to load ["/etc/vector/vector.toml"]                             
#0 0.381 ------------------------------------------                             
#0 0.381 x unknown variant `add_fields`, expected one of `aggregate`, `aws_ec2_metadata`, `dedupe`, `filter`, `log_to_metric`, `lua`, `metric_to_log`, `reduce`, `remap`, `route`, `sample`, `tag_cardinality_limit`, `throttle`
#0 0.381 in `transforms.add_host`
```

Here is the `vector.toml`

```toml
[sources.host_metrics]
  type = "host_metrics"
  collectors = [
    "cpu", "disk", "load", "memory", "network", "cgroups", "filesystem", "host"
  ]

[transforms.add_host]
  type = "add_fields"
  inputs = ["host_metrics"]
  [transforms.add_host.fields]
    host = "${HOSTNAME}"

[sinks.prometheus]
  type = "prometheus_exporter"
  inputs = ["add_host"]
  address = "0.0.0.0:9598"
```
