### ISSUE TITLE
Vector silently fails to load invalid YAML files

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#8996]
```
vector 0.16.1 (x86_64-apple-darwin 739e878 2021-08-26)
```

Config:

```yaml
sources:
  splunk:
    type: splunk_hec

sinks:
  console:
    type: console
                encoding:
                        codec: json
    inputs:
      - splunk
```

Note that the `encoding` and `codec: json` are preceded by tabs instead of spaces like the rest of the file.

```
➜  vector git:(master) ✗ vector --config /tmp/vector.yaml
➜  vector git:(master) ✗ echo $?
78
```

Vector silently exits.
