### ISSUE TITLE
docs: YAML example shows incorrect null value

### ISSUE THREAD

**Issue by lukesteensen** [timberio/vector#9075]
The [example](https://vector.dev/docs/reference/configuration/sinks/console/#example-configurations) YAML configuration for the `console` sink shows the following:

```yaml
---
sinks:
  my_sink_id:
    type: console
    inputs:
      - my-source-or-transform-id
    target: stdout
    encoding: null
```

The `encoding: null` there is incorrect, and doesn't show up in either the TOML or JSON example configs.
