### ISSUE TITLE
Loki sink is panicking with  'Batch is empty'

### ISSUE THREAD

**Issue by stanvit** [timberio/vector#9124]
### Vector Version
```
vector 0.16.1 (x86_64-unknown-linux-musl 739e878 2021-08-26)
```

### Vector Configuration File

The config is a reduced/minimal version of our full configureation. We're running Vector on Kubernetes. For this bugreport
it was launched with these settings only plus internal telemetry and API settings that shouldn't be relevant at all.

```toml
data_dir = "/data"
healthchecks.enabled = false

[sources.firehose]
type = "aws_kinesis_firehose"
address = "0.0.0.0:8080"
access_key = "REDACTED"

[transforms.firehose_message]
type = "remap"
inputs = ["firehose"]
source = '''

# Parse account ID and regions of Kinesis stream ARN
parsed_arn, err = parse_regex(.source_arn, r'arn:aws:firehose:(?P<stream_region>[^:]+):(?P<stream_account_id>[0-9]+):deliverystream/(?P<stream_name>.+)$')
if err == null {
  . |= parsed_arn
}
# Remove not needed Kinesis attributes
del(.source_arn)
del(.request_id)
del(.timestamp)

# Parse .message field expecting JSON, reject otherwise
_message = del(.message)
., err |= object(parse_json!(_message))
if err != null {
  log("Message field is not in JSON/Object format, dropping: " + encode_json(_message), level:"error", rate_limit_secs:10)
  abort
}

# Map Firehose stream account ID to the account name if .account field is not set
# TODO: rewrite this as {tf_generated_object}.get(stream_account_id) when dynamic paths are supported in Vector
if !exists(.account) && exists(.stream_account_id) {
  if .stream_account_id == "1234567890123" {
    .account = "account1"
  }
  if .stream_account_id == "9876543210987" {
    .account = "account2"
  }

}
'''

# Message type/source router
[transforms.type]
type = "route"
inputs = ["firehose_message"]
route.kubernetes = '.src_type == "kubernetes"'

[transforms.kubernetes]
type = "remap"
inputs = ["type.kubernetes"]
source = '''

# Parse Docker timestamp
.timestamp = parse_timestamp(.time, "%FT%X%.fZ") ?? now()

# Read Kubernetes message attributes
.pod_name = .kubernetes.pod_name
.container_name = .kubernetes.container_name
.namespace = .kubernetes.namespace_name
.host = .kubernetes.host
.image = .kubernetes.container_image
.app_name = .kubernetes.labels."app.kubernetes.io/name" || .kubernetes.labels."k8s-app" || "UNDEFINED"
.app_instance = .kubernetes.labels."app.kubernetes.io/instance" || .app_name

# Parse message, extract JSON log from it and try to detect log type:
log_parsed, err = parse_json(.log)
if is_null(err) && is_object(log_parsed) {
  .log_type = log_parsed.log_type
}
if is_null(.log_type) {
  .log_type = .stream || "other"
}

# Detect app version
.app_version = .kubernetes.labels."app.kubernetes.io/version" || split(.kubernetes.container_image, ":", 2)[1] ?? null
if is_null(.app_version) || .app_version == "latest" {
  del(.app_version)
}

# Delete the whole .kubernetes part of the log
del(.kubernetes)
'''

[sinks.loki_grafana_cloud]
type = "loki"
inputs = ["kubernetes"]
endpoint = "https://logs-prod-us-central1.grafana.net"
auth.strategy = "basic"
auth.user = "REDACTED"
auth.password = "REDACTED"
remove_timestamp = false
remove_label_fields = true
out_of_order_action = "drop"

encoding.codec = "json"
encoding.timestamp_format = "rfc3339"

labels.log_type = "{{ log_type }}"
labels.src_type = "{{ src_type }}"
#labels.account = "{{ account }}"
#labels.project = "{{ project }}"
#labels.container_name = "{{ container_name }}"
#labels.container_id = "{{ container_id }}"
#labels.frontend_name = "{{ frontend_name }}"
#labels.backend_name = "{{ backend_name }}"
#labels.instance_id = "{{ instance-id }}"
#labels.pod_name = "{{ pod_name }}"
#labels.namespace = "{{ namespace }}"
```

### Debug Output

Please see the Gist [here](https://gist.githubusercontent.com/stanvit/73704d3d31cf6a75334a888febf2d3d5/raw/025e0934beafbc30d321b6e0e2ceec26435c78fd/vector-loki-trace-20210913.log)

### Expected Behavior

We were expecting Vector to post data to Loki

### Actual Behavior

Vector is panicking and dying instead.

### Example Data

- `type.kubernetes` transform output:
```json
{
  "account": "account1",
  "kubernetes": {
    "annotations": {
      "cluster-autoscaler.kubernetes.io/safe-to-evict": "false",
      "kubernetes.io/psp": "eks.privileged",
      "prometheus.io/path": "metrics",
      "prometheus.io/port": "8085",
      "prometheus.io/scrape": "true"
    },
    "container_hash": "k8s.gcr.io/autoscaling/cluster-autoscaler@sha256:7a8123595b4878dff6eeef2b8f47d1903f6adcd930a420006ea1af95c98c62f4",
    "container_image": "k8s.gcr.io/autoscaling/cluster-autoscaler:v1.21.0",
    "container_name": "aws-cluster-autoscaler",
    "docker_id": "b1cd4420e5e206118a35e939d146a967ef90e3101f2e4b5de9f345f7e03fd6f2",
    "host": "ip-1-2-3-4.ec2.internal",
    "labels": {
      "app.kubernetes.io/instance": "aws-cluster-autoscaler",
      "app.kubernetes.io/name": "aws-cluster-autoscaler",
      "pod-template-hash": "7cf545d867"
    },
    "namespace_name": "kube-system",
    "pod_id": "0b0b26b5-6a49-42d5-ab0d-c605a362fa63",
    "pod_name": "aws-cluster-autoscaler-7cf545d867-xzk69"
  },
  "log": "I0913 11:08:24.106055       1 static_autoscaler.go:228] Starting main loop\n",
  "src_type": "kubernetes",
  "stream": "stderr",
  "stream_account_id": "1234567890123",
  "stream_name": "logs",
  "stream_region": "us-east-1",
  "time": "2021-09-13T11:08:24.106290101Z"
}
```

- `kubernetes` transform output (this data is passed to the loki sink):
```json
{
  "account": "staging-fe",
  "app_instance": "aws-cluster-autoscaler",
  "app_name": "aws-cluster-autoscaler",
  "app_version": "v1.21.0",
  "container_name": "aws-cluster-autoscaler",
  "host": "ip-1-2-3-4.ec2.internal",
  "image": "k8s.gcr.io/autoscaling/cluster-autoscaler:v1.21.0",
  "log": "I0913 11:08:24.106055       1 static_autoscaler.go:228] Starting main loop\n",
  "log_type": "stderr",
  "namespace": "kube-system",
  "pod_name": "aws-cluster-autoscaler-7cf545d867-xzk69",
  "src_type": "kubernetes",
  "stream": "stderr",
  "stream_account_id": "1234567890123",
  "stream_name": "logs",
  "stream_region": "us-east-1",
  "time": "2021-09-13T11:08:24.106290101Z",
  "timestamp": "2021-09-13T11:08:24.106290101Z"
}
```

### Additional Context

This behaviour is reproducible quite reliably only when record rate limit is relatively high - about 30 messages per second or more.

The listed config is not out normal configuration, there are more log types, parsers and Loki labels. We tried to upgrade our Vector to 0.16.1 from 0.15.2 and started getting "lockups" when data won't flow past the `firehose` source - that was visible both in Prometheus and `vector top`.

We experienced these or similar lokups in older versions, but only with `disk` buffer type. I [reported the issue on Discord](https://discord.com/channels/742820443487993987/746070591097798688/877732870632927243) about a month ago and was told that the (mis)behaviour was known and worked on.

With 0.16.1 the `firehose` data source was "locking up" almost immediately, passing maybe 700-900 evends down the pipeline and stopping forever afterwards. I started reducing our config trying to find the problematic part and eventually managed to cause the panic, which is hopefully related to the lockup issue.

Please advise if I should open another issue for the lockup. I'm happy to assist with further investigation.
