### ISSUE TITLE
systemd.socket as source

### ISSUE THREAD

**Issue by gumieri** [timberio/vector#950]
Would be interesting to have a [`systemd.socket`](https://www.freedesktop.org/software/systemd/man/systemd.socket.html) as source to the vector.

The advantage of using it instead of listening directly a port is to it "queue" requests if the `vector.service` is being restarted in case of errors, updating the binary or updating the configurations.

**Comment by binarylogic** [comment]
@bruceg do you mind reviewing this? Is this something we should do, and does it overlap with the `journald` source? I don't have enough context on this source to know. Thanks.

**Comment by gumieri** [comment]
To be fair, it is possible to take advantages of the `systemd.socket` by configuring a [systemd-socket-proxyd](https://www.freedesktop.org/software/systemd/man/systemd-socket-proxyd.html), but the option to use the socket more "natively" (a quick search [for rust](https://github.com/mitsuhiko/rust-listenfd)) instead of configuring a proxy sounds great.

It does not overlap `journald` because it is more like a tcp/udp source integrated with the system for having more resilience decoupling the "listen" responsibility from the service to the systemd, letting the service only with the "serve" responsibility instead of "listen and serve".

**Comment by bruceg** [comment]
I agree with @gumieri, this does not have any interaction with the `journald` source. This would be an enhancement to the `tcp` source (and maybe `udp` or `vector`?) to accept a file descriptor passed to it by systemd or systemfd instead of listening for connections directly.

It would be a useful addition for people running systemd. It could allow for restarting Vector without dropping connections.

**Comment by binarylogic** [comment]
Sounds good, let's proceed then.

**Comment by bruceg** [comment]
How do we want to handle configuring the listening socket address? When started from systemd, the `address` setting is overridden by the already created listening socket and so is redundant, but otherwise it is required.

**Comment by gumieri** [comment]
I think if the systemd.socket would be considered a new sink, the configuration would be just a type (like `stdin`):

```toml
[sources.my_source_id]
  type = "systemd.socket" # must be: "systemd.socket"
```
But it would be not able to receive metrics from that, only if a `statsd` transform was also created.

The other strategy would be considering UNIX/IPC socket and systemd.socket as a different kind of `address`. But, I see it conflicting with `tcp` and `udp` source. In that way, would not exist these sources but a `raw` source and at `address` to inform if it is a socket or a IP.
TCP Example:
```toml
[sources.my_source_id]
  type = "raw"
  address = "0.0.0.0:9000" # as default
```
UDP example:
```toml
[sources.my_source_id]
  type = "raw"
  address = "0.0.0.0:9000/udp"
```
UNIX Socket example:
```toml
[sources.my_source_id]
  type = "raw"
  address = "/tmp/sample.sock"
```
Systemd Socket example:
```toml
[sources.my_source_id]
  type = "raw"
  address = "systemd.socket"
```
I'm sorry if I am being too intrusive.
