### ISSUE TITLE
New `test`/`fake` source

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#980]
## Overview

This came about after discussing https://github.com/timberio/vector/issues/975.

I think a `test`/`fake` source can be a useful source for fiddling with Vector. For example:

```toml
[sources.in]
  type = "test"
  interval_seconds = 30
  data = [
    "Welcome to Vector!",
    "This is example data to demonstrate Vector.",
    "You can change how this works in /etc/vector/vector.toml",
    "See https://docs.vector.dev/configuration for configuration docs"
  ]

[sinks.out]
  inputs = ["in"]
  type = "console"
```

### Onboarding

It's important, as part of onboarding, to demonstrate a working example of Vector as soon as possible. An example that is not obtrusive and allows the users to "fiddle" with the input. This would be a good solution.

### Testing transformation/parsing

This is an easy way to test input/output, to ensure output data is correct.

## Ideas

1. It would also be neat to provide "templates" for certain types of random data. Ex: apache2, nginx, postgres, rails, etc.
