### ISSUE TITLE
New `cmd` or `exec` source

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#992]
After talking with @lukesteensen he had an interesting idea of using a command as data input. This command would be executed on an interval, the output would be ingested as either log or metrics events. This is an interesting approach to "plugins" in that users could write simple scripts that interface with any data source.

Before we begin work, we should outline scenarios this would support and how the incoming data should be structured, if at all. And would this support metrics?

**Comment by a-rodin** [comment]
I really like this idea.

Actually, there is a way to do this right now without a special source using a combination of a shell script, `netcat`, and `tcp` source:

`script.sh`:
```bash
#!/bin/bash
set -ex

(while true; do "my-command"; sleep 1; done) |
  nc 127.0.0.1 55555
```
`vector.toml`:
```toml
[sources.service]
  type = "tcp"
  address = "127.0.0.1:55555"
```

However, it is not very ergonomic and it is better to have it built in.

> This command would be executed on an interval, the output would be ingested ...

I think we could avoid forcing users to generate only one event per invocation (and thus each time necessarily create new process). The command could generate a stream of newline-delimited events until it exits. To improve reliability and flexibility we can add two additional parameter `exit_restart_interval` and which would specify the interval since the end of the previous invocation after which the command will be launched again. With these two parameters, the `command` itself and `restart_interval`, it would be possible to support both one-off commands and long-running stream generators.

Examples:

* Report size of a directory:
    ```toml
    [sources.dir_size_watcher]
    command = "du -h | cut -f1"
    restart_interval = 10 # seconds
    ```
    The command would be executed each 10 seconds.
* Make a stateful counter:
    ```toml
    [sources.stateful_counter]
    command = "./counter.sh"
    ```
    and the `counter.sh` would be
    ```sh
    #!/bin/sh
    for ((i = 0;; i++)); do
        echo $i
        sleep 1
    fi
    ```
* It should be possible to generate structured events this way too:
    ```toml
    [sources.structured_counter]
    command = "node ./structured_counter.js"
    encoding = "json"
    ```
    with `structured_counter.js` being a Node.js script:
    ```javascript
    for (let i = 0;; i++) {
        const event = {
            message: i.toString(),
            timestamp: new Date().toISOString()
        }
        console.log(JSON.stringify(event))
    }
    ```

The source could also be written in a high-performant language, such as Rust or C. 

Actually, before `kafka` source was implemented, I was trying to use [kafkacat](https://github.com/edenhill/kafkacat) combined with `stdin` source to do this. However, I encountered two issues:

1. `kafkacat` sometimes exited with an error, but nothing restarted it automatically
2. graceful shutdown was not possible because termination of Vector and `kafkacat` was not synchronized

Both of the problems mentioned above could have been solved if there were `cmd` sink from my examples above.

Also, the same approach can be used to create `cmd` transform and sink (need to be put into separate issues). Combined, `cmd` sources/transforms/sinks might even be a viable alternative to scripting from #1041, as they could provide the same benefits and not force the users to learn a specific programming language.
